WITH APOSENTADORIA_INVALIDEZ AS (
    SELECT DISTINCT
        'FUNPREV' AS ORGAO,
        FO.ANO,
        NVL(FF.ID_PESSOA_DEPENDENTE, FF.ID_PESSOA_FUNCIONARIO) AS ID_PESSOA_APOSENTADO,
        FLOOR(
            MONTHS_BETWEEN(
                TO_DATE(FO.ANO || '1231', 'RRRRMMDD'),
                P.DATA_NASCIMENTO
            ) / 12
        ) AS IDADE
    FROM 
        SW_FUNPREV.FOLHA FO 
        JOIN SW_FUNPREV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_PESSOA = NVL(FF.ID_PESSOA_DEPENDENTE, FF.ID_PESSOA_FUNCIONARIO)
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = NVL(FF.ID_PESSOA_DEPENDENTE, FF.ID_PESSOA_FUNCIONARIO)
        JOIN SW_FUNPREV.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        FA.DATA_APOSENTADORIA IS NOT NULL
        AND R.COD_RUBRICA = 620000
        AND P.DATA_OBITO IS NULL
        AND FA.DATA_APOSENTADORIA <= TO_DATE(FO.ANO || '1231', 'RRRRMMDD')
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 1 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50) -- NOT IN = VÁLIDOS | IN = INVÁLIDOS
),
ORGAOS AS (
    SELECT DISTINCT ORGAO FROM APOSENTADORIA_INVALIDEZ
),
IDADES AS (
    SELECT LEVEL - 1 AS IDADE
    FROM DUAL
    CONNECT BY LEVEL <= 106
)
SELECT
    ORG.ORGAO,
    I.IDADE,
    COUNT(CASE WHEN AI.ANO = 2025 THEN 1 END) AS "2025",
    COUNT(CASE WHEN AI.ANO = 2024 THEN 1 END) AS "2024",
    COUNT(CASE WHEN AI.ANO = 2023 THEN 1 END) AS "2023",
    COUNT(CASE WHEN AI.ANO = 2022 THEN 1 END) AS "2022",
    COUNT(CASE WHEN AI.ANO = 2021 THEN 1 END) AS "2021",
    COUNT(CASE WHEN AI.ANO = 2020 THEN 1 END) AS "2020"
FROM
    ORGAOS ORG
    CROSS JOIN IDADES I
    LEFT JOIN APOSENTADORIA_INVALIDEZ AI ON AI.ORGAO = ORG.ORGAO AND AI.IDADE = I.IDADE
GROUP BY
    ORG.ORGAO, I.IDADE
ORDER BY
    ORG.ORGAO, I.IDADE;