WITH APOSENTADORIA_INVALIDEZ AS (
    SELECT DISTINCT
        'ADAPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_ADAPI.FOLHA FO
        JOIN SW_ADAPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_ADAPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_ADAPI.FUNC_APOSENTADORIA FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        FI.ID_REGIME = 2
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2014 AND 2025
        AND FS.ID_SEXO = 1
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)
),
ORGAOS AS (
    SELECT DISTINCT ORGAO FROM APOSENTADORIA_INVALIDEZ
),
IDADES AS (
    SELECT LEVEL - 1 AS IDADE
    FROM DUAL
    CONNECT BY LEVEL <= 106
)
SELECT
    ORG.ORGAO,
    I.IDADE,
    COUNT(CASE WHEN AI.ANO = 2025 THEN 1 END) AS "2025",
    COUNT(CASE WHEN AI.ANO = 2024 THEN 1 END) AS "2024",
    COUNT(CASE WHEN AI.ANO = 2023 THEN 1 END) AS "2023",
    COUNT(CASE WHEN AI.ANO = 2022 THEN 1 END) AS "2022",
    COUNT(CASE WHEN AI.ANO = 2021 THEN 1 END) AS "2021",
    COUNT(CASE WHEN AI.ANO = 2020 THEN 1 END) AS "2020",
    COUNT(CASE WHEN AI.ANO = 2019 THEN 1 END) AS "2019",
    COUNT(CASE WHEN AI.ANO = 2018 THEN 1 END) AS "2018",
    COUNT(CASE WHEN AI.ANO = 2017 THEN 1 END) AS "2017",
    COUNT(CASE WHEN AI.ANO = 2016 THEN 1 END) AS "2016",
    COUNT(CASE WHEN AI.ANO = 2015 THEN 1 END) AS "2015",
    COUNT(CASE WHEN AI.ANO = 2014 THEN 1 END) AS "2014"
FROM
    ORGAOS ORG
    CROSS JOIN IDADES I
    LEFT JOIN APOSENTADORIA_INVALIDEZ AI ON AI.ORGAO = ORG.ORGAO AND AI.IDADE = I.IDADE
GROUP BY
    ORG.ORGAO, I.IDADE
ORDER BY
    ORG.ORGAO, I.IDADE;