WITH APOSENTADORIA_INVALIDEZ AS (
    SELECT DISTINCT
        'FUNPREV' AS ORGAO,
        FO.ANO,
        NVL(FF.ID_PESSOA_DEPENDENTE, FF.ID_PESSOA_FUNCIONARIO) AS ID_PESSOA_APOSENTADO,
        FLOOR(
            MONTHS_BETWEEN(
                P.DATA_OBITO,
                P.DATA_NASCIMENTO
            ) / 12
        ) AS IDADE
    FROM 
        SW_FUNPREV.FOLHA FO 
        JOIN SW_FUNPREV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_PESSOA = NVL(FF.ID_PESSOA_DEPENDENTE, FF.ID_PESSOA_FUNCIONARIO)
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = NVL(FF.ID_PESSOA_DEPENDENTE, FF.ID_PESSOA_FUNCIONARIO)
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        FA.DATA_APOSENTADORIA IS NOT NULL
        AND P.DATA_OBITO IS NOT NULL
        AND FA.DATA_APOSENTADORIA <= P.DATA_OBITO
        AND EXTRACT(YEAR FROM P.DATA_OBITO) = FO.ANO
        AND FO.ANO BETWEEN 2014 AND 2025
        AND FS.ID_SEXO = 2
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50) -- NOT IN = VÁLIDOS | IN = INVÁLIDOS
),
ORGAOS AS (
    SELECT DISTINCT ORGAO FROM APOSENTADORIA_INVALIDEZ
),
IDADES AS (
    SELECT LEVEL - 1 AS IDADE
    FROM DUAL
    CONNECT BY LEVEL <= 106
)
SELECT
    ORG.ORGAO,
    I.IDADE,
    COUNT(CASE WHEN AI.ANO = 2025 THEN 1 END) AS "2025",
    COUNT(CASE WHEN AI.ANO = 2024 THEN 1 END) AS "2024",
    COUNT(CASE WHEN AI.ANO = 2023 THEN 1 END) AS "2023",
    COUNT(CASE WHEN AI.ANO = 2022 THEN 1 END) AS "2022",
    COUNT(CASE WHEN AI.ANO = 2021 THEN 1 END) AS "2021",
    COUNT(CASE WHEN AI.ANO = 2020 THEN 1 END) AS "2020",
    COUNT(CASE WHEN AI.ANO = 2019 THEN 1 END) AS "2019",
    COUNT(CASE WHEN AI.ANO = 2018 THEN 1 END) AS "2018",
    COUNT(CASE WHEN AI.ANO = 2017 THEN 1 END) AS "2017",
    COUNT(CASE WHEN AI.ANO = 2016 THEN 1 END) AS "2016",
    COUNT(CASE WHEN AI.ANO = 2015 THEN 1 END) AS "2015",
    COUNT(CASE WHEN AI.ANO = 2014 THEN 1 END) AS "2014"
FROM
    ORGAOS ORG
    CROSS JOIN IDADES I
    LEFT JOIN APOSENTADORIA_INVALIDEZ AI ON AI.ORGAO = ORG.ORGAO AND AI.IDADE = I.IDADE
GROUP BY
    ORG.ORGAO, I.IDADE
ORDER BY
    ORG.ORGAO, I.IDADE;