WITH VALORES AS (
    SELECT '000637-8' MATRICULA FROM DUAL UNION ALL
SELECT '001428-1' MATRICULA FROM DUAL UNION ALL
SELECT '007620-1' MATRICULA FROM DUAL UNION ALL
SELECT '007778-0' MATRICULA FROM DUAL UNION ALL
SELECT '008834-0' MATRICULA FROM DUAL UNION ALL
SELECT '009229-X' MATRICULA FROM DUAL UNION ALL
SELECT '009919-8' MATRICULA FROM DUAL UNION ALL
SELECT '009925-2' MATRICULA FROM DUAL UNION ALL
SELECT '021553-8' MATRICULA FROM DUAL UNION ALL
SELECT '039911-6' MATRICULA FROM DUAL UNION ALL
SELECT '047213-1' MATRICULA FROM DUAL UNION ALL
SELECT '062150-1' MATRICULA FROM DUAL UNION ALL
SELECT '097813-2' MATRICULA FROM DUAL UNION ALL
SELECT '113034-0' MATRICULA FROM DUAL UNION ALL
SELECT '130144-6' MATRICULA FROM DUAL UNION ALL
SELECT '130175-6' MATRICULA FROM DUAL UNION ALL
SELECT '130176-4' MATRICULA FROM DUAL UNION ALL
SELECT '165632-5' MATRICULA FROM DUAL UNION ALL
SELECT '176169-2' MATRICULA FROM DUAL UNION ALL
SELECT '204775-6' MATRICULA FROM DUAL UNION ALL
SELECT '204949-0' MATRICULA FROM DUAL UNION ALL
SELECT '204960-X' MATRICULA FROM DUAL UNION ALL
SELECT '205035-8' MATRICULA FROM DUAL UNION ALL
SELECT '205036-6' MATRICULA FROM DUAL UNION ALL
SELECT '205089-7' MATRICULA FROM DUAL UNION ALL
SELECT '205129-0' MATRICULA FROM DUAL UNION ALL
SELECT '205211-3' MATRICULA FROM DUAL UNION ALL
SELECT '205472-8' MATRICULA FROM DUAL UNION ALL
SELECT '205546-5' MATRICULA FROM DUAL UNION ALL
SELECT '205628-3' MATRICULA FROM DUAL UNION ALL
SELECT '205843-0' MATRICULA FROM DUAL UNION ALL
SELECT '205892-8' MATRICULA FROM DUAL UNION ALL
SELECT '205893-6' MATRICULA FROM DUAL UNION ALL
SELECT '208928-9' MATRICULA FROM DUAL UNION ALL
SELECT '209705-2' MATRICULA FROM DUAL UNION ALL
SELECT '209888-1' MATRICULA FROM DUAL UNION ALL
SELECT '221594-2' MATRICULA FROM DUAL UNION ALL
SELECT '227134-6' MATRICULA FROM DUAL UNION ALL
SELECT '230528-3' MATRICULA FROM DUAL UNION ALL
SELECT '230991-2' MATRICULA FROM DUAL UNION ALL
SELECT '231011-2' MATRICULA FROM DUAL UNION ALL
SELECT '233092-0' MATRICULA FROM DUAL UNION ALL
SELECT '258571-5' MATRICULA FROM DUAL UNION ALL
SELECT '259641-5' MATRICULA FROM DUAL UNION ALL
SELECT '266867-0' MATRICULA FROM DUAL UNION ALL
SELECT '269495-6' MATRICULA FROM DUAL UNION ALL
SELECT '280129-9' MATRICULA FROM DUAL UNION ALL
SELECT '282241-5' MATRICULA FROM DUAL UNION ALL
SELECT '283057-4' MATRICULA FROM DUAL UNION ALL
SELECT '287038-0' MATRICULA FROM DUAL UNION ALL
SELECT '289287-1' MATRICULA FROM DUAL UNION ALL
SELECT '293664-0' MATRICULA FROM DUAL UNION ALL
SELECT '330853-7' MATRICULA FROM DUAL UNION ALL
SELECT '331104-0' MATRICULA FROM DUAL UNION ALL
SELECT '331915-6' MATRICULA FROM DUAL UNION ALL
SELECT '332227-X' MATRICULA FROM DUAL UNION ALL
SELECT '369261-2' MATRICULA FROM DUAL UNION ALL
SELECT '372157-4' MATRICULA FROM DUAL UNION ALL
SELECT '372319-4' MATRICULA FROM DUAL UNION ALL
SELECT '372674-6' MATRICULA FROM DUAL UNION ALL
SELECT '372808-X' MATRICULA FROM DUAL UNION ALL
SELECT '373084-X' MATRICULA FROM DUAL UNION ALL
SELECT '373086-7' MATRICULA FROM DUAL UNION ALL
SELECT '373340-8' MATRICULA FROM DUAL UNION ALL
SELECT '373477-3' MATRICULA FROM DUAL UNION ALL
SELECT '373526-5' MATRICULA FROM DUAL UNION ALL
SELECT '373545-1' MATRICULA FROM DUAL UNION ALL
SELECT '373552-4' MATRICULA FROM DUAL UNION ALL
SELECT '373948-1' MATRICULA FROM DUAL UNION ALL
SELECT '373961-9' MATRICULA FROM DUAL UNION ALL
SELECT '373965-1' MATRICULA FROM DUAL UNION ALL
SELECT '374131-1' MATRICULA FROM DUAL UNION ALL
SELECT '374135-4' MATRICULA FROM DUAL UNION ALL
SELECT '374136-2' MATRICULA FROM DUAL UNION ALL
SELECT '374137-X' MATRICULA FROM DUAL UNION ALL
SELECT '374142-7' MATRICULA FROM DUAL UNION ALL
SELECT '374177-0' MATRICULA FROM DUAL UNION ALL
SELECT '374185-X' MATRICULA FROM DUAL UNION ALL
SELECT '374197-4' MATRICULA FROM DUAL UNION ALL
SELECT '374198-2' MATRICULA FROM DUAL UNION ALL
SELECT '374238-5' MATRICULA FROM DUAL UNION ALL
SELECT '374280-6' MATRICULA FROM DUAL UNION ALL
SELECT '374341-1' MATRICULA FROM DUAL UNION ALL
SELECT '374367-5' MATRICULA FROM DUAL UNION ALL
SELECT '376222-0' MATRICULA FROM DUAL UNION ALL
SELECT '376258-X' MATRICULA FROM DUAL UNION ALL
SELECT '376260-2' MATRICULA FROM DUAL UNION ALL
SELECT '376262-9' MATRICULA FROM DUAL UNION ALL
SELECT '376264-5' MATRICULA FROM DUAL UNION ALL
SELECT '376266-1' MATRICULA FROM DUAL UNION ALL
SELECT '376267-0' MATRICULA FROM DUAL UNION ALL
SELECT '376270-0' MATRICULA FROM DUAL UNION ALL
SELECT '376273-4' MATRICULA FROM DUAL UNION ALL
SELECT '376274-2' MATRICULA FROM DUAL UNION ALL
SELECT '376279-3' MATRICULA FROM DUAL UNION ALL
SELECT '376311-X' MATRICULA FROM DUAL UNION ALL
SELECT '376319-6' MATRICULA FROM DUAL UNION ALL
SELECT '377338-8' MATRICULA FROM DUAL UNION ALL
SELECT '377340-0' MATRICULA FROM DUAL UNION ALL
SELECT '377901-7' MATRICULA FROM DUAL UNION ALL
SELECT '377926-2' MATRICULA FROM DUAL UNION ALL
SELECT '377927-X' MATRICULA FROM DUAL UNION ALL
SELECT '377929-7' MATRICULA FROM DUAL UNION ALL
SELECT '377935-1' MATRICULA FROM DUAL UNION ALL
SELECT '377941-6' MATRICULA FROM DUAL UNION ALL
SELECT '377943-2' MATRICULA FROM DUAL UNION ALL
SELECT '378064-3' MATRICULA FROM DUAL UNION ALL
SELECT '378065-1' MATRICULA FROM DUAL UNION ALL
SELECT '378258-1' MATRICULA FROM DUAL UNION ALL
SELECT '378263-8' MATRICULA FROM DUAL UNION ALL
SELECT '378321-9' MATRICULA FROM DUAL UNION ALL
SELECT '378325-1' MATRICULA FROM DUAL UNION ALL
SELECT '378379-X' MATRICULA FROM DUAL UNION ALL
SELECT '378447-9' MATRICULA FROM DUAL UNION ALL
SELECT '380905-6' MATRICULA FROM DUAL UNION ALL
SELECT '380906-4' MATRICULA FROM DUAL UNION ALL
SELECT '380916-1' MATRICULA FROM DUAL UNION ALL
SELECT '380930-7' MATRICULA FROM DUAL UNION ALL
SELECT '380937-4' MATRICULA FROM DUAL UNION ALL
SELECT '381180-8' MATRICULA FROM DUAL UNION ALL
SELECT '381225-1' MATRICULA FROM DUAL UNION ALL
SELECT '382866-2' MATRICULA FROM DUAL UNION ALL
SELECT '382875-1' MATRICULA FROM DUAL UNION ALL
SELECT '385645-3' MATRICULA FROM DUAL UNION ALL
SELECT '385662-3' MATRICULA FROM DUAL UNION ALL
SELECT '385767-X' MATRICULA FROM DUAL UNION ALL
SELECT '385777-8' MATRICULA FROM DUAL UNION ALL
SELECT '386341-7' MATRICULA FROM DUAL UNION ALL
SELECT '392122-X' MATRICULA FROM DUAL UNION ALL
SELECT '398984-4' MATRICULA FROM DUAL UNION ALL
SELECT '398989-5' MATRICULA FROM DUAL UNION ALL
SELECT '399038-9' MATRICULA FROM DUAL UNION ALL
SELECT '401273-9' MATRICULA FROM DUAL UNION ALL
SELECT '402316-1' MATRICULA FROM DUAL UNION ALL
SELECT '402506-7' MATRICULA FROM DUAL UNION ALL
SELECT '402933-0' MATRICULA FROM DUAL UNION ALL
SELECT '403046-0' MATRICULA FROM DUAL UNION ALL
SELECT '405302-8' MATRICULA FROM DUAL UNION ALL
SELECT '409081-X' MATRICULA FROM DUAL UNION ALL
SELECT '410685-7' MATRICULA FROM DUAL UNION ALL
SELECT '418051-8' MATRICULA FROM DUAL UNION ALL
SELECT '423362-0' MATRICULA FROM DUAL UNION ALL
SELECT '427005-3' MATRICULA FROM DUAL UNION ALL
SELECT '427296-0' MATRICULA FROM DUAL UNION ALL
SELECT '427423-7' MATRICULA FROM DUAL UNION ALL
SELECT '431370-4' MATRICULA FROM DUAL UNION ALL
SELECT '433872-3' MATRICULA FROM DUAL UNION ALL
SELECT '435049-9' MATRICULA FROM DUAL UNION ALL
SELECT '437103-8' MATRICULA FROM DUAL UNION ALL
SELECT '438293-5' MATRICULA FROM DUAL UNION ALL
SELECT '438301-0' MATRICULA FROM DUAL UNION ALL
SELECT '441228-1' MATRICULA FROM DUAL UNION ALL
SELECT '441780-1' MATRICULA FROM DUAL UNION ALL
SELECT '442804-8' MATRICULA FROM DUAL UNION ALL
SELECT '014625-X' MATRICULA FROM DUAL UNION ALL
SELECT '082780-X' MATRICULA FROM DUAL UNION ALL
SELECT '084287-7' MATRICULA FROM DUAL UNION ALL
SELECT '092354-X' MATRICULA FROM DUAL UNION ALL
SELECT '206544-4' MATRICULA FROM DUAL UNION ALL
SELECT '206903-2' MATRICULA FROM DUAL UNION ALL
SELECT '289049-6' MATRICULA FROM DUAL UNION ALL
SELECT '310149-5' MATRICULA FROM DUAL UNION ALL
SELECT '332401-0' MATRICULA FROM DUAL UNION ALL
SELECT '332452-4' MATRICULA FROM DUAL UNION ALL
SELECT '382595-7' MATRICULA FROM DUAL UNION ALL
SELECT '431704-1' MATRICULA FROM DUAL UNION ALL
SELECT '431831-5' MATRICULA FROM DUAL UNION ALL
SELECT '001871-6' MATRICULA FROM DUAL UNION ALL
SELECT '001872-4' MATRICULA FROM DUAL UNION ALL
SELECT '001874-X' MATRICULA FROM DUAL UNION ALL
SELECT '001876-7' MATRICULA FROM DUAL UNION ALL
SELECT '001934-8' MATRICULA FROM DUAL UNION ALL
SELECT '002628-0' MATRICULA FROM DUAL UNION ALL
SELECT '002660-3' MATRICULA FROM DUAL UNION ALL
SELECT '002664-6' MATRICULA FROM DUAL UNION ALL
SELECT '008830-7' MATRICULA FROM DUAL UNION ALL
SELECT '008839-X' MATRICULA FROM DUAL UNION ALL
SELECT '008848-0' MATRICULA FROM DUAL UNION ALL
SELECT '008855-2' MATRICULA FROM DUAL UNION ALL
SELECT '008870-6' MATRICULA FROM DUAL UNION ALL
SELECT '008910-9' MATRICULA FROM DUAL UNION ALL
SELECT '008946-0' MATRICULA FROM DUAL UNION ALL
SELECT '009108-1' MATRICULA FROM DUAL UNION ALL
SELECT '009115-4' MATRICULA FROM DUAL UNION ALL
SELECT '009243-6' MATRICULA FROM DUAL UNION ALL
SELECT '009347-5' MATRICULA FROM DUAL UNION ALL
SELECT '009392-X' MATRICULA FROM DUAL UNION ALL
SELECT '009776-4' MATRICULA FROM DUAL UNION ALL
SELECT '009782-9' MATRICULA FROM DUAL UNION ALL
SELECT '009791-8' MATRICULA FROM DUAL UNION ALL
SELECT '009806-0' MATRICULA FROM DUAL UNION ALL
SELECT '010024-2' MATRICULA FROM DUAL UNION ALL
SELECT '024900-9' MATRICULA FROM DUAL UNION ALL
SELECT '037428-8' MATRICULA FROM DUAL UNION ALL
SELECT '037434-2' MATRICULA FROM DUAL UNION ALL
SELECT '037437-7' MATRICULA FROM DUAL UNION ALL
SELECT '037503-9' MATRICULA FROM DUAL UNION ALL
SELECT '037576-4' MATRICULA FROM DUAL UNION ALL
SELECT '037620-5' MATRICULA FROM DUAL UNION ALL
SELECT '039456-4' MATRICULA FROM DUAL UNION ALL
SELECT '043126-5' MATRICULA FROM DUAL UNION ALL
SELECT '043127-3' MATRICULA FROM DUAL UNION ALL
SELECT '043421-3' MATRICULA FROM DUAL UNION ALL
SELECT '047216-6' MATRICULA FROM DUAL UNION ALL
SELECT '056473-7' MATRICULA FROM DUAL UNION ALL
SELECT '066278-0' MATRICULA FROM DUAL UNION ALL
SELECT '090963-7' MATRICULA FROM DUAL UNION ALL
SELECT '137059-6' MATRICULA FROM DUAL UNION ALL
SELECT '137333-1' MATRICULA FROM DUAL UNION ALL
SELECT '137401-0' MATRICULA FROM DUAL UNION ALL
SELECT '137855-4' MATRICULA FROM DUAL UNION ALL
SELECT '138024-9' MATRICULA FROM DUAL UNION ALL
SELECT '138177-6' MATRICULA FROM DUAL UNION ALL
SELECT '138208-0' MATRICULA FROM DUAL UNION ALL
SELECT '138230-6' MATRICULA FROM DUAL UNION ALL
SELECT '138233-X' MATRICULA FROM DUAL UNION ALL
SELECT '138245-4' MATRICULA FROM DUAL UNION ALL
SELECT '138246-2' MATRICULA FROM DUAL UNION ALL
SELECT '138247-X' MATRICULA FROM DUAL UNION ALL
SELECT '138262-4' MATRICULA FROM DUAL UNION ALL
SELECT '138278-X' MATRICULA FROM DUAL UNION ALL
SELECT '138287-0' MATRICULA FROM DUAL UNION ALL
SELECT '138299-3' MATRICULA FROM DUAL UNION ALL
SELECT '138305-1' MATRICULA FROM DUAL UNION ALL
SELECT '138330-2' MATRICULA FROM DUAL UNION ALL
SELECT '138335-3' MATRICULA FROM DUAL UNION ALL
SELECT '138382-5' MATRICULA FROM DUAL UNION ALL
SELECT '138427-9' MATRICULA FROM DUAL UNION ALL
SELECT '138460-X' MATRICULA FROM DUAL UNION ALL
SELECT '138463-5' MATRICULA FROM DUAL UNION ALL
SELECT '138464-3' MATRICULA FROM DUAL UNION ALL
SELECT '138491-X' MATRICULA FROM DUAL UNION ALL
SELECT '138499-6' MATRICULA FROM DUAL UNION ALL
SELECT '138517-8' MATRICULA FROM DUAL UNION ALL
SELECT '138535-6' MATRICULA FROM DUAL UNION ALL
SELECT '138554-2' MATRICULA FROM DUAL UNION ALL
SELECT '138555-X' MATRICULA FROM DUAL UNION ALL
SELECT '138569-X' MATRICULA FROM DUAL UNION ALL
SELECT '138611-5' MATRICULA FROM DUAL UNION ALL
SELECT '138624-7' MATRICULA FROM DUAL UNION ALL
SELECT '138661-1' MATRICULA FROM DUAL UNION ALL
SELECT '138714-6' MATRICULA FROM DUAL UNION ALL
SELECT '138715-4' MATRICULA FROM DUAL UNION ALL
SELECT '138717-X' MATRICULA FROM DUAL UNION ALL
SELECT '138729-4' MATRICULA FROM DUAL UNION ALL
SELECT '138731-6' MATRICULA FROM DUAL UNION ALL
SELECT '138732-4' MATRICULA FROM DUAL UNION ALL
SELECT '138736-7' MATRICULA FROM DUAL UNION ALL
SELECT '138741-3' MATRICULA FROM DUAL UNION ALL
SELECT '138742-1' MATRICULA FROM DUAL UNION ALL
SELECT '138763-4' MATRICULA FROM DUAL UNION ALL
SELECT '138773-1' MATRICULA FROM DUAL UNION ALL
SELECT '138799-5' MATRICULA FROM DUAL UNION ALL
SELECT '138832-X' MATRICULA FROM DUAL UNION ALL
SELECT '138839-8' MATRICULA FROM DUAL UNION ALL
SELECT '138843-6' MATRICULA FROM DUAL UNION ALL
SELECT '138858-4' MATRICULA FROM DUAL UNION ALL
SELECT '138863-X' MATRICULA FROM DUAL UNION ALL
SELECT '138877-X' MATRICULA FROM DUAL UNION ALL
SELECT '138879-7' MATRICULA FROM DUAL UNION ALL
SELECT '138905-0' MATRICULA FROM DUAL UNION ALL
SELECT '138906-8' MATRICULA FROM DUAL UNION ALL
SELECT '138915-7' MATRICULA FROM DUAL UNION ALL
SELECT '138946-7' MATRICULA FROM DUAL UNION ALL
SELECT '138964-5' MATRICULA FROM DUAL UNION ALL
SELECT '138989-X' MATRICULA FROM DUAL UNION ALL
SELECT '138994-7' MATRICULA FROM DUAL UNION ALL
SELECT '139002-3' MATRICULA FROM DUAL UNION ALL
SELECT '139017-1' MATRICULA FROM DUAL UNION ALL
SELECT '139037-6' MATRICULA FROM DUAL UNION ALL
SELECT '139039-2' MATRICULA FROM DUAL UNION ALL
SELECT '139069-4' MATRICULA FROM DUAL UNION ALL
SELECT '139106-2' MATRICULA FROM DUAL UNION ALL
SELECT '139108-9' MATRICULA FROM DUAL UNION ALL
SELECT '139133-0' MATRICULA FROM DUAL UNION ALL
SELECT '139134-8' MATRICULA FROM DUAL UNION ALL
SELECT '139135-6' MATRICULA FROM DUAL UNION ALL
SELECT '139146-1' MATRICULA FROM DUAL UNION ALL
SELECT '139178-0' MATRICULA FROM DUAL UNION ALL
SELECT '139200-0' MATRICULA FROM DUAL UNION ALL
SELECT '139209-3' MATRICULA FROM DUAL UNION ALL
SELECT '139227-1' MATRICULA FROM DUAL UNION ALL
SELECT '139228-0' MATRICULA FROM DUAL UNION ALL
SELECT '139245-0' MATRICULA FROM DUAL UNION ALL
SELECT '139291-3' MATRICULA FROM DUAL UNION ALL
SELECT '139301-4' MATRICULA FROM DUAL UNION ALL
SELECT '139316-2' MATRICULA FROM DUAL UNION ALL
SELECT '139322-7' MATRICULA FROM DUAL UNION ALL
SELECT '139332-4' MATRICULA FROM DUAL UNION ALL
SELECT '139341-3' MATRICULA FROM DUAL UNION ALL
SELECT '139345-6' MATRICULA FROM DUAL UNION ALL
SELECT '139347-2' MATRICULA FROM DUAL UNION ALL
SELECT '139357-0' MATRICULA FROM DUAL UNION ALL
SELECT '139358-8' MATRICULA FROM DUAL UNION ALL
SELECT '139361-8' MATRICULA FROM DUAL UNION ALL
SELECT '139370-7' MATRICULA FROM DUAL UNION ALL
SELECT '139372-3' MATRICULA FROM DUAL UNION ALL
SELECT '139391-0' MATRICULA FROM DUAL UNION ALL
SELECT '139407-0' MATRICULA FROM DUAL UNION ALL
SELECT '139408-8' MATRICULA FROM DUAL UNION ALL
SELECT '139412-6' MATRICULA FROM DUAL UNION ALL
SELECT '139418-5' MATRICULA FROM DUAL UNION ALL
SELECT '139442-8' MATRICULA FROM DUAL UNION ALL
SELECT '139443-6' MATRICULA FROM DUAL UNION ALL
SELECT '139448-7' MATRICULA FROM DUAL UNION ALL
SELECT '139467-3' MATRICULA FROM DUAL UNION ALL
SELECT '139468-1' MATRICULA FROM DUAL UNION ALL
SELECT '139481-9' MATRICULA FROM DUAL UNION ALL
SELECT '139489-4' MATRICULA FROM DUAL UNION ALL
SELECT '139496-7' MATRICULA FROM DUAL UNION ALL
SELECT '139512-2' MATRICULA FROM DUAL UNION ALL
SELECT '139514-9' MATRICULA FROM DUAL UNION ALL
SELECT '139518-1' MATRICULA FROM DUAL UNION ALL
SELECT '139522-0' MATRICULA FROM DUAL UNION ALL
SELECT '139524-6' MATRICULA FROM DUAL UNION ALL
SELECT '139528-9' MATRICULA FROM DUAL UNION ALL
SELECT '139537-8' MATRICULA FROM DUAL UNION ALL
SELECT '139550-5' MATRICULA FROM DUAL UNION ALL
SELECT '139555-6' MATRICULA FROM DUAL UNION ALL
SELECT '139556-4' MATRICULA FROM DUAL UNION ALL
SELECT '139561-X' MATRICULA FROM DUAL UNION ALL
SELECT '139571-8' MATRICULA FROM DUAL UNION ALL
SELECT '139572-6' MATRICULA FROM DUAL UNION ALL
SELECT '139576-9' MATRICULA FROM DUAL UNION ALL
SELECT '139587-4' MATRICULA FROM DUAL UNION ALL
SELECT '139599-8' MATRICULA FROM DUAL UNION ALL
SELECT '139620-0' MATRICULA FROM DUAL UNION ALL
SELECT '139640-4' MATRICULA FROM DUAL UNION ALL
SELECT '139652-8' MATRICULA FROM DUAL UNION ALL
SELECT '139653-6' MATRICULA FROM DUAL UNION ALL
SELECT '139661-7' MATRICULA FROM DUAL UNION ALL
SELECT '139666-8' MATRICULA FROM DUAL UNION ALL
SELECT '139680-3' MATRICULA FROM DUAL UNION ALL
SELECT '139694-3' MATRICULA FROM DUAL UNION ALL
SELECT '139719-2' MATRICULA FROM DUAL UNION ALL
SELECT '139730-3' MATRICULA FROM DUAL UNION ALL
SELECT '139737-X' MATRICULA FROM DUAL UNION ALL
SELECT '139742-7' MATRICULA FROM DUAL UNION ALL
SELECT '139757-5' MATRICULA FROM DUAL UNION ALL
SELECT '139758-3' MATRICULA FROM DUAL UNION ALL
SELECT '139776-1' MATRICULA FROM DUAL UNION ALL
SELECT '139779-6' MATRICULA FROM DUAL UNION ALL
SELECT '139783-4' MATRICULA FROM DUAL UNION ALL
SELECT '139789-3' MATRICULA FROM DUAL UNION ALL
SELECT '139795-8' MATRICULA FROM DUAL UNION ALL
SELECT '139829-6' MATRICULA FROM DUAL UNION ALL
SELECT '139838-5' MATRICULA FROM DUAL UNION ALL
SELECT '139841-5' MATRICULA FROM DUAL UNION ALL
SELECT '139845-8' MATRICULA FROM DUAL UNION ALL
SELECT '139852-X' MATRICULA FROM DUAL UNION ALL
SELECT '139875-0' MATRICULA FROM DUAL UNION ALL
SELECT '139876-8' MATRICULA FROM DUAL UNION ALL
SELECT '139881-4' MATRICULA FROM DUAL UNION ALL
SELECT '139882-2' MATRICULA FROM DUAL UNION ALL
SELECT '139889-0' MATRICULA FROM DUAL UNION ALL
SELECT '139890-3' MATRICULA FROM DUAL UNION ALL
SELECT '139927-6' MATRICULA FROM DUAL UNION ALL
SELECT '139930-6' MATRICULA FROM DUAL UNION ALL
SELECT '139934-9' MATRICULA FROM DUAL UNION ALL
SELECT '139935-7' MATRICULA FROM DUAL UNION ALL
SELECT '139936-5' MATRICULA FROM DUAL UNION ALL
SELECT '139940-3' MATRICULA FROM DUAL UNION ALL
SELECT '139951-9' MATRICULA FROM DUAL UNION ALL
SELECT '139962-4' MATRICULA FROM DUAL UNION ALL
SELECT '139970-5' MATRICULA FROM DUAL UNION ALL
SELECT '139991-8' MATRICULA FROM DUAL UNION ALL
SELECT '140027-4' MATRICULA FROM DUAL UNION ALL
SELECT '140098-3' MATRICULA FROM DUAL UNION ALL
SELECT '140104-1' MATRICULA FROM DUAL UNION ALL
SELECT '140127-X' MATRICULA FROM DUAL UNION ALL
SELECT '140150-5' MATRICULA FROM DUAL UNION ALL
SELECT '140156-4' MATRICULA FROM DUAL UNION ALL
SELECT '140228-5' MATRICULA FROM DUAL UNION ALL
SELECT '140230-7' MATRICULA FROM DUAL UNION ALL
SELECT '140240-4' MATRICULA FROM DUAL UNION ALL
SELECT '140257-9' MATRICULA FROM DUAL UNION ALL
SELECT '140270-6' MATRICULA FROM DUAL UNION ALL
SELECT '140297-8' MATRICULA FROM DUAL UNION ALL
SELECT '140307-9' MATRICULA FROM DUAL UNION ALL
SELECT '140391-5' MATRICULA FROM DUAL UNION ALL
SELECT '140474-1' MATRICULA FROM DUAL UNION ALL
SELECT '140503-9' MATRICULA FROM DUAL UNION ALL
SELECT '140504-7' MATRICULA FROM DUAL UNION ALL
SELECT '140520-9' MATRICULA FROM DUAL UNION ALL
SELECT '140521-7' MATRICULA FROM DUAL UNION ALL
SELECT '140527-6' MATRICULA FROM DUAL UNION ALL
SELECT '140530-6' MATRICULA FROM DUAL UNION ALL
SELECT '140536-5' MATRICULA FROM DUAL UNION ALL
SELECT '140551-9' MATRICULA FROM DUAL UNION ALL
SELECT '140555-1' MATRICULA FROM DUAL UNION ALL
SELECT '140556-0' MATRICULA FROM DUAL UNION ALL
SELECT '140560-8' MATRICULA FROM DUAL UNION ALL
SELECT '140565-9' MATRICULA FROM DUAL UNION ALL
SELECT '140567-5' MATRICULA FROM DUAL UNION ALL
SELECT '140569-1' MATRICULA FROM DUAL UNION ALL
SELECT '140574-8' MATRICULA FROM DUAL UNION ALL
SELECT '140578-X' MATRICULA FROM DUAL UNION ALL
SELECT '140581-X' MATRICULA FROM DUAL UNION ALL
SELECT '140584-5' MATRICULA FROM DUAL UNION ALL
SELECT '140586-1' MATRICULA FROM DUAL UNION ALL
SELECT '140596-9' MATRICULA FROM DUAL UNION ALL
SELECT '140598-5' MATRICULA FROM DUAL UNION ALL
SELECT '140599-3' MATRICULA FROM DUAL UNION ALL
SELECT '140621-3' MATRICULA FROM DUAL UNION ALL
SELECT '140630-2' MATRICULA FROM DUAL UNION ALL
SELECT '140639-6' MATRICULA FROM DUAL UNION ALL
SELECT '140641-8' MATRICULA FROM DUAL UNION ALL
SELECT '140649-3' MATRICULA FROM DUAL UNION ALL
SELECT '140658-2' MATRICULA FROM DUAL UNION ALL
SELECT '140668-0' MATRICULA FROM DUAL UNION ALL
SELECT '140674-4' MATRICULA FROM DUAL UNION ALL
SELECT '140685-0' MATRICULA FROM DUAL UNION ALL
SELECT '140696-5' MATRICULA FROM DUAL UNION ALL
SELECT '140724-4' MATRICULA FROM DUAL UNION ALL
SELECT '140725-2' MATRICULA FROM DUAL UNION ALL
SELECT '140729-5' MATRICULA FROM DUAL UNION ALL
SELECT '140744-9' MATRICULA FROM DUAL UNION ALL
SELECT '140787-2' MATRICULA FROM DUAL UNION ALL
SELECT '140789-9' MATRICULA FROM DUAL UNION ALL
SELECT '140795-3' MATRICULA FROM DUAL UNION ALL
SELECT '140796-1' MATRICULA FROM DUAL UNION ALL
SELECT '140801-1' MATRICULA FROM DUAL UNION ALL
SELECT '140802-0' MATRICULA FROM DUAL UNION ALL
SELECT '140803-8' MATRICULA FROM DUAL UNION ALL
SELECT '140806-2' MATRICULA FROM DUAL UNION ALL
SELECT '140815-1' MATRICULA FROM DUAL UNION ALL
SELECT '140819-4' MATRICULA FROM DUAL UNION ALL
SELECT '140820-8' MATRICULA FROM DUAL UNION ALL
SELECT '140822-4' MATRICULA FROM DUAL UNION ALL
SELECT '140825-9' MATRICULA FROM DUAL UNION ALL
SELECT '140826-7' MATRICULA FROM DUAL UNION ALL
SELECT '140830-5' MATRICULA FROM DUAL UNION ALL
SELECT '140834-8' MATRICULA FROM DUAL UNION ALL
SELECT '140838-X' MATRICULA FROM DUAL UNION ALL
SELECT '141991-9' MATRICULA FROM DUAL UNION ALL
SELECT '142160-3' MATRICULA FROM DUAL UNION ALL
SELECT '142606-X' MATRICULA FROM DUAL UNION ALL
SELECT '142794-6' MATRICULA FROM DUAL UNION ALL
SELECT '142974-4' MATRICULA FROM DUAL UNION ALL
SELECT '143007-6' MATRICULA FROM DUAL UNION ALL
SELECT '143342-3' MATRICULA FROM DUAL UNION ALL
SELECT '143563-9' MATRICULA FROM DUAL UNION ALL
SELECT '143683-0' MATRICULA FROM DUAL UNION ALL
SELECT '145138-3' MATRICULA FROM DUAL UNION ALL
SELECT '145139-1' MATRICULA FROM DUAL UNION ALL
SELECT '145666-X' MATRICULA FROM DUAL UNION ALL
SELECT '145668-7' MATRICULA FROM DUAL UNION ALL
SELECT '146079-0' MATRICULA FROM DUAL UNION ALL
SELECT '147554-1' MATRICULA FROM DUAL UNION ALL
SELECT '147557-6' MATRICULA FROM DUAL UNION ALL
SELECT '147889-3' MATRICULA FROM DUAL UNION ALL
SELECT '158420-X' MATRICULA FROM DUAL UNION ALL
SELECT '158423-5' MATRICULA FROM DUAL UNION ALL
SELECT '159822-8' MATRICULA FROM DUAL UNION ALL
SELECT '160034-6' MATRICULA FROM DUAL UNION ALL
SELECT '160047-8' MATRICULA FROM DUAL UNION ALL
SELECT '160065-6' MATRICULA FROM DUAL UNION ALL
SELECT '160662-0' MATRICULA FROM DUAL UNION ALL
SELECT '160670-X' MATRICULA FROM DUAL UNION ALL
SELECT '160772-3' MATRICULA FROM DUAL UNION ALL
SELECT '160956-4' MATRICULA FROM DUAL UNION ALL
SELECT '161032-5' MATRICULA FROM DUAL UNION ALL
SELECT '161157-7' MATRICULA FROM DUAL UNION ALL
SELECT '161216-6' MATRICULA FROM DUAL UNION ALL
SELECT '161217-4' MATRICULA FROM DUAL UNION ALL
SELECT '161441-0' MATRICULA FROM DUAL UNION ALL
SELECT '161443-6' MATRICULA FROM DUAL UNION ALL
SELECT '161566-1' MATRICULA FROM DUAL UNION ALL
SELECT '161634-0' MATRICULA FROM DUAL UNION ALL
SELECT '164867-5' MATRICULA FROM DUAL UNION ALL
SELECT '166005-5' MATRICULA FROM DUAL UNION ALL
SELECT '166061-6' MATRICULA FROM DUAL UNION ALL
SELECT '166870-6' MATRICULA FROM DUAL UNION ALL
SELECT '166874-9' MATRICULA FROM DUAL UNION ALL
SELECT '167650-4' MATRICULA FROM DUAL UNION ALL
SELECT '167663-6' MATRICULA FROM DUAL UNION ALL
SELECT '167874-4' MATRICULA FROM DUAL UNION ALL
SELECT '167877-9' MATRICULA FROM DUAL UNION ALL
SELECT '167879-5' MATRICULA FROM DUAL UNION ALL
SELECT '168772-7' MATRICULA FROM DUAL UNION ALL
SELECT '168813-8' MATRICULA FROM DUAL UNION ALL
SELECT '168814-6' MATRICULA FROM DUAL UNION ALL
SELECT '168941-0' MATRICULA FROM DUAL UNION ALL
SELECT '168960-6' MATRICULA FROM DUAL UNION ALL
SELECT '169198-8' MATRICULA FROM DUAL UNION ALL
SELECT '169342-5' MATRICULA FROM DUAL UNION ALL
SELECT '169482-X' MATRICULA FROM DUAL UNION ALL
SELECT '169693-9' MATRICULA FROM DUAL UNION ALL
SELECT '169696-3' MATRICULA FROM DUAL UNION ALL
SELECT '169756-X' MATRICULA FROM DUAL UNION ALL
SELECT '170137-1' MATRICULA FROM DUAL UNION ALL
SELECT '170154-1' MATRICULA FROM DUAL UNION ALL
SELECT '170155-0' MATRICULA FROM DUAL UNION ALL
SELECT '170156-8' MATRICULA FROM DUAL UNION ALL
SELECT '170276-9' MATRICULA FROM DUAL UNION ALL
SELECT '170448-6' MATRICULA FROM DUAL UNION ALL
SELECT '170457-5' MATRICULA FROM DUAL UNION ALL
SELECT '170490-7' MATRICULA FROM DUAL UNION ALL
SELECT '170705-1' MATRICULA FROM DUAL UNION ALL
SELECT '171949-1' MATRICULA FROM DUAL UNION ALL
SELECT '171954-8' MATRICULA FROM DUAL UNION ALL
SELECT '172102-0' MATRICULA FROM DUAL UNION ALL
SELECT '174640-5' MATRICULA FROM DUAL UNION ALL
SELECT '178081-6' MATRICULA FROM DUAL UNION ALL
SELECT '178690-3' MATRICULA FROM DUAL UNION ALL
SELECT '180024-8' MATRICULA FROM DUAL UNION ALL
SELECT '180240-2' MATRICULA FROM DUAL UNION ALL
SELECT '180647-5' MATRICULA FROM DUAL UNION ALL
SELECT '180658-X' MATRICULA FROM DUAL UNION ALL
SELECT '180977-6' MATRICULA FROM DUAL UNION ALL
SELECT '181245-9' MATRICULA FROM DUAL UNION ALL
SELECT '181323-4' MATRICULA FROM DUAL UNION ALL
SELECT '191854-X' MATRICULA FROM DUAL UNION ALL
SELECT '191856-7' MATRICULA FROM DUAL UNION ALL
SELECT '191859-1' MATRICULA FROM DUAL UNION ALL
SELECT '191862-1' MATRICULA FROM DUAL UNION ALL
SELECT '193666-2' MATRICULA FROM DUAL UNION ALL
SELECT '193678-6' MATRICULA FROM DUAL UNION ALL
SELECT '193802-9' MATRICULA FROM DUAL UNION ALL
SELECT '194838-5' MATRICULA FROM DUAL UNION ALL
SELECT '194995-X' MATRICULA FROM DUAL UNION ALL
SELECT '195312-5' MATRICULA FROM DUAL UNION ALL
SELECT '195313-3' MATRICULA FROM DUAL UNION ALL
SELECT '195943-3' MATRICULA FROM DUAL UNION ALL
SELECT '195945-0' MATRICULA FROM DUAL UNION ALL
SELECT '195951-4' MATRICULA FROM DUAL UNION ALL
SELECT '196064-4' MATRICULA FROM DUAL UNION ALL
SELECT '196069-5' MATRICULA FROM DUAL UNION ALL
SELECT '196627-8' MATRICULA FROM DUAL UNION ALL
SELECT '196682-X' MATRICULA FROM DUAL UNION ALL
SELECT '196883-1' MATRICULA FROM DUAL UNION ALL
SELECT '196884-0' MATRICULA FROM DUAL UNION ALL
SELECT '197148-4' MATRICULA FROM DUAL UNION ALL
SELECT '197189-1' MATRICULA FROM DUAL UNION ALL
SELECT '197275-8' MATRICULA FROM DUAL UNION ALL
SELECT '197473-4' MATRICULA FROM DUAL UNION ALL
SELECT '197703-2' MATRICULA FROM DUAL UNION ALL
SELECT '197706-7' MATRICULA FROM DUAL UNION ALL
SELECT '197718-X' MATRICULA FROM DUAL UNION ALL
SELECT '197778-4' MATRICULA FROM DUAL UNION ALL
SELECT '197964-7' MATRICULA FROM DUAL UNION ALL
SELECT '198073-4' MATRICULA FROM DUAL UNION ALL
SELECT '198135-8' MATRICULA FROM DUAL UNION ALL
SELECT '198252-4' MATRICULA FROM DUAL UNION ALL
SELECT '198305-9' MATRICULA FROM DUAL UNION ALL
SELECT '198306-7' MATRICULA FROM DUAL UNION ALL
SELECT '198845-0' MATRICULA FROM DUAL UNION ALL
SELECT '199314-3' MATRICULA FROM DUAL UNION ALL
SELECT '202844-1' MATRICULA FROM DUAL UNION ALL
SELECT '204650-4' MATRICULA FROM DUAL UNION ALL
SELECT '206898-2' MATRICULA FROM DUAL UNION ALL
SELECT '207306-4' MATRICULA FROM DUAL UNION ALL
SELECT '207384-6' MATRICULA FROM DUAL UNION ALL
SELECT '208482-1' MATRICULA FROM DUAL UNION ALL
SELECT '208595-0' MATRICULA FROM DUAL UNION ALL
SELECT '208995-5' MATRICULA FROM DUAL UNION ALL
SELECT '209638-2' MATRICULA FROM DUAL UNION ALL
SELECT '209648-0' MATRICULA FROM DUAL UNION ALL
SELECT '210275-7' MATRICULA FROM DUAL UNION ALL
SELECT '210551-9' MATRICULA FROM DUAL UNION ALL
SELECT '211115-2' MATRICULA FROM DUAL UNION ALL
SELECT '211183-7' MATRICULA FROM DUAL UNION ALL
SELECT '211185-3' MATRICULA FROM DUAL UNION ALL
SELECT '211218-3' MATRICULA FROM DUAL UNION ALL
SELECT '211759-2' MATRICULA FROM DUAL UNION ALL
SELECT '211761-4' MATRICULA FROM DUAL UNION ALL
SELECT '212635-4' MATRICULA FROM DUAL UNION ALL
SELECT '212640-X' MATRICULA FROM DUAL UNION ALL
SELECT '212900-X' MATRICULA FROM DUAL UNION ALL
SELECT '213076-9' MATRICULA FROM DUAL UNION ALL
SELECT '213140-4' MATRICULA FROM DUAL UNION ALL
SELECT '213159-5' MATRICULA FROM DUAL UNION ALL
SELECT '213224-9' MATRICULA FROM DUAL UNION ALL
SELECT '213225-7' MATRICULA FROM DUAL UNION ALL
SELECT '213226-5' MATRICULA FROM DUAL UNION ALL
SELECT '213228-1' MATRICULA FROM DUAL UNION ALL
SELECT '213404-7' MATRICULA FROM DUAL UNION ALL
SELECT '213499-3' MATRICULA FROM DUAL UNION ALL
SELECT '213501-9' MATRICULA FROM DUAL UNION ALL
SELECT '213505-1' MATRICULA FROM DUAL UNION ALL
SELECT '214018-7' MATRICULA FROM DUAL UNION ALL
SELECT '214096-9' MATRICULA FROM DUAL UNION ALL
SELECT '215024-7' MATRICULA FROM DUAL UNION ALL
SELECT '219640-9' MATRICULA FROM DUAL UNION ALL
SELECT '219642-5' MATRICULA FROM DUAL UNION ALL
SELECT '219644-1' MATRICULA FROM DUAL UNION ALL
SELECT '219645-0' MATRICULA FROM DUAL UNION ALL
SELECT '220182-8' MATRICULA FROM DUAL UNION ALL
SELECT '220235-2' MATRICULA FROM DUAL UNION ALL
SELECT '223650-8' MATRICULA FROM DUAL UNION ALL
SELECT '223690-7' MATRICULA FROM DUAL UNION ALL
SELECT '223940-0' MATRICULA FROM DUAL UNION ALL
SELECT '223995-7' MATRICULA FROM DUAL UNION ALL
SELECT '224010-6' MATRICULA FROM DUAL UNION ALL
SELECT '224301-6' MATRICULA FROM DUAL UNION ALL
SELECT '224364-4' MATRICULA FROM DUAL UNION ALL
SELECT '225924-9' MATRICULA FROM DUAL UNION ALL
SELECT '225925-7' MATRICULA FROM DUAL UNION ALL
SELECT '226116-2' MATRICULA FROM DUAL UNION ALL
SELECT '226475-7' MATRICULA FROM DUAL UNION ALL
SELECT '226559-1' MATRICULA FROM DUAL UNION ALL
SELECT '227715-8' MATRICULA FROM DUAL UNION ALL
SELECT '227718-2' MATRICULA FROM DUAL UNION ALL
SELECT '227720-4' MATRICULA FROM DUAL UNION ALL
SELECT '228176-7' MATRICULA FROM DUAL UNION ALL
SELECT '228195-3' MATRICULA FROM DUAL UNION ALL
SELECT '228200-3' MATRICULA FROM DUAL UNION ALL
SELECT '228708-X' MATRICULA FROM DUAL UNION ALL
SELECT '228744-7' MATRICULA FROM DUAL UNION ALL
SELECT '228800-1' MATRICULA FROM DUAL UNION ALL
SELECT '229883-0' MATRICULA FROM DUAL UNION ALL
SELECT '229884-8' MATRICULA FROM DUAL UNION ALL
SELECT '229976-3' MATRICULA FROM DUAL UNION ALL
SELECT '230078-8' MATRICULA FROM DUAL UNION ALL
SELECT '230079-6' MATRICULA FROM DUAL UNION ALL
SELECT '230080-0' MATRICULA FROM DUAL UNION ALL
SELECT '231533-5' MATRICULA FROM DUAL UNION ALL
SELECT '231733-8' MATRICULA FROM DUAL UNION ALL
SELECT '231749-4' MATRICULA FROM DUAL UNION ALL
SELECT '231916-X' MATRICULA FROM DUAL UNION ALL
SELECT '232235-8' MATRICULA FROM DUAL UNION ALL
SELECT '232325-7' MATRICULA FROM DUAL UNION ALL
SELECT '241664-6' MATRICULA FROM DUAL UNION ALL
SELECT '241683-2' MATRICULA FROM DUAL UNION ALL
SELECT '242584-0' MATRICULA FROM DUAL UNION ALL
SELECT '242654-4' MATRICULA FROM DUAL UNION ALL
SELECT '243008-8' MATRICULA FROM DUAL UNION ALL
SELECT '243009-6' MATRICULA FROM DUAL UNION ALL
SELECT '243014-2' MATRICULA FROM DUAL UNION ALL
SELECT '243120-3' MATRICULA FROM DUAL UNION ALL
SELECT '243255-2' MATRICULA FROM DUAL UNION ALL
SELECT '243492-0' MATRICULA FROM DUAL UNION ALL
SELECT '243503-9' MATRICULA FROM DUAL UNION ALL
SELECT '243590-0' MATRICULA FROM DUAL UNION ALL
SELECT '243592-6' MATRICULA FROM DUAL UNION ALL
SELECT '243993-0' MATRICULA FROM DUAL UNION ALL
SELECT '244942-X' MATRICULA FROM DUAL UNION ALL
SELECT '244963-3' MATRICULA FROM DUAL UNION ALL
SELECT '244972-2' MATRICULA FROM DUAL UNION ALL
SELECT '245981-7' MATRICULA FROM DUAL UNION ALL
SELECT '246114-5' MATRICULA FROM DUAL UNION ALL
SELECT '246298-2' MATRICULA FROM DUAL UNION ALL
SELECT '246316-4' MATRICULA FROM DUAL UNION ALL
SELECT '246350-4' MATRICULA FROM DUAL UNION ALL
SELECT '246413-6' MATRICULA FROM DUAL UNION ALL
SELECT '246418-7' MATRICULA FROM DUAL UNION ALL
SELECT '246430-6' MATRICULA FROM DUAL UNION ALL
SELECT '247163-9' MATRICULA FROM DUAL UNION ALL
SELECT '247169-8' MATRICULA FROM DUAL UNION ALL
SELECT '247659-2' MATRICULA FROM DUAL UNION ALL
SELECT '247660-6' MATRICULA FROM DUAL UNION ALL
SELECT '247662-2' MATRICULA FROM DUAL UNION ALL
SELECT '247753-0' MATRICULA FROM DUAL UNION ALL
SELECT '247815-3' MATRICULA FROM DUAL UNION ALL
SELECT '253129-1' MATRICULA FROM DUAL UNION ALL
SELECT '253404-5' MATRICULA FROM DUAL UNION ALL
SELECT '253413-4' MATRICULA FROM DUAL UNION ALL
SELECT '253539-4' MATRICULA FROM DUAL UNION ALL
SELECT '253812-1' MATRICULA FROM DUAL UNION ALL
SELECT '257427-6' MATRICULA FROM DUAL UNION ALL
SELECT '257754-2' MATRICULA FROM DUAL UNION ALL
SELECT '257896-4' MATRICULA FROM DUAL UNION ALL
SELECT '257897-2' MATRICULA FROM DUAL UNION ALL
SELECT '257942-1' MATRICULA FROM DUAL UNION ALL
SELECT '258234-1' MATRICULA FROM DUAL UNION ALL
SELECT '258269-4' MATRICULA FROM DUAL UNION ALL
SELECT '258271-6' MATRICULA FROM DUAL UNION ALL
SELECT '258399-2' MATRICULA FROM DUAL UNION ALL
SELECT '258506-5' MATRICULA FROM DUAL UNION ALL
SELECT '258842-X' MATRICULA FROM DUAL UNION ALL
SELECT '259084-X' MATRICULA FROM DUAL UNION ALL
SELECT '259087-5' MATRICULA FROM DUAL UNION ALL
SELECT '259279-7' MATRICULA FROM DUAL UNION ALL
SELECT '259281-9' MATRICULA FROM DUAL UNION ALL
SELECT '259690-3' MATRICULA FROM DUAL UNION ALL
SELECT '259705-5' MATRICULA FROM DUAL UNION ALL
SELECT '259866-3' MATRICULA FROM DUAL UNION ALL
SELECT '259965-1' MATRICULA FROM DUAL UNION ALL
SELECT '259997-0' MATRICULA FROM DUAL UNION ALL
SELECT '260187-7' MATRICULA FROM DUAL UNION ALL
SELECT '260197-4' MATRICULA FROM DUAL UNION ALL
SELECT '260409-4' MATRICULA FROM DUAL UNION ALL
SELECT '260476-X' MATRICULA FROM DUAL UNION ALL
SELECT '260478-7' MATRICULA FROM DUAL UNION ALL
SELECT '266091-1' MATRICULA FROM DUAL UNION ALL
SELECT '268515-9' MATRICULA FROM DUAL UNION ALL
SELECT '268583-3' MATRICULA FROM DUAL UNION ALL
SELECT '268584-1' MATRICULA FROM DUAL UNION ALL
SELECT '268889-1' MATRICULA FROM DUAL UNION ALL
SELECT '269640-1' MATRICULA FROM DUAL UNION ALL
SELECT '269922-2' MATRICULA FROM DUAL UNION ALL
SELECT '269923-X' MATRICULA FROM DUAL UNION ALL
SELECT '269924-9' MATRICULA FROM DUAL UNION ALL
SELECT '269925-7' MATRICULA FROM DUAL UNION ALL
SELECT '269967-2' MATRICULA FROM DUAL UNION ALL
SELECT '270185-5' MATRICULA FROM DUAL UNION ALL
SELECT '270188-0' MATRICULA FROM DUAL UNION ALL
SELECT '270200-2' MATRICULA FROM DUAL UNION ALL
SELECT '270498-6' MATRICULA FROM DUAL UNION ALL
SELECT '270516-8' MATRICULA FROM DUAL UNION ALL
SELECT '270519-2' MATRICULA FROM DUAL UNION ALL
SELECT '270540-X' MATRICULA FROM DUAL UNION ALL
SELECT '270585-X' MATRICULA FROM DUAL UNION ALL
SELECT '270782-9' MATRICULA FROM DUAL UNION ALL
SELECT '271144-3' MATRICULA FROM DUAL UNION ALL
SELECT '271167-2' MATRICULA FROM DUAL UNION ALL
SELECT '271256-3' MATRICULA FROM DUAL UNION ALL
SELECT '271410-8' MATRICULA FROM DUAL UNION ALL
SELECT '271413-2' MATRICULA FROM DUAL UNION ALL
SELECT '271416-7' MATRICULA FROM DUAL UNION ALL
SELECT '271418-3' MATRICULA FROM DUAL UNION ALL
SELECT '271422-1' MATRICULA FROM DUAL UNION ALL
SELECT '271547-3' MATRICULA FROM DUAL UNION ALL
SELECT '271551-1' MATRICULA FROM DUAL UNION ALL
SELECT '271623-2' MATRICULA FROM DUAL UNION ALL
SELECT '271834-X' MATRICULA FROM DUAL UNION ALL
SELECT '272208-9' MATRICULA FROM DUAL UNION ALL
SELECT '272209-7' MATRICULA FROM DUAL UNION ALL
SELECT '272214-3' MATRICULA FROM DUAL UNION ALL
SELECT '272220-8' MATRICULA FROM DUAL UNION ALL
SELECT '272252-6' MATRICULA FROM DUAL UNION ALL
SELECT '272448-X' MATRICULA FROM DUAL UNION ALL
SELECT '272450-2' MATRICULA FROM DUAL UNION ALL
SELECT '272488-0' MATRICULA FROM DUAL UNION ALL
SELECT '272538-0' MATRICULA FROM DUAL UNION ALL
SELECT '277312-X' MATRICULA FROM DUAL UNION ALL
SELECT '277446-1' MATRICULA FROM DUAL UNION ALL
SELECT '277452-6' MATRICULA FROM DUAL UNION ALL
SELECT '277501-8' MATRICULA FROM DUAL UNION ALL
SELECT '277604-9' MATRICULA FROM DUAL UNION ALL
SELECT '277808-4' MATRICULA FROM DUAL UNION ALL
SELECT '280155-8' MATRICULA FROM DUAL UNION ALL
SELECT '280156-6' MATRICULA FROM DUAL UNION ALL
SELECT '280642-8' MATRICULA FROM DUAL UNION ALL
SELECT '280684-3' MATRICULA FROM DUAL UNION ALL
SELECT '280820-0' MATRICULA FROM DUAL UNION ALL
SELECT '281051-4' MATRICULA FROM DUAL UNION ALL
SELECT '281414-5' MATRICULA FROM DUAL UNION ALL
SELECT '281446-3' MATRICULA FROM DUAL UNION ALL
SELECT '281650-4' MATRICULA FROM DUAL UNION ALL
SELECT '281865-5' MATRICULA FROM DUAL UNION ALL
SELECT '282235-X' MATRICULA FROM DUAL UNION ALL
SELECT '282304-7' MATRICULA FROM DUAL UNION ALL
SELECT '282361-6' MATRICULA FROM DUAL UNION ALL
SELECT '282500-7' MATRICULA FROM DUAL UNION ALL
SELECT '282586-4' MATRICULA FROM DUAL UNION ALL
SELECT '282809-0' MATRICULA FROM DUAL UNION ALL
SELECT '283097-3' MATRICULA FROM DUAL UNION ALL
SELECT '283107-4' MATRICULA FROM DUAL UNION ALL
SELECT '283108-2' MATRICULA FROM DUAL UNION ALL
SELECT '283109-X' MATRICULA FROM DUAL UNION ALL
SELECT '285426-X' MATRICULA FROM DUAL UNION ALL
SELECT '286138-X' MATRICULA FROM DUAL UNION ALL
SELECT '286315-4' MATRICULA FROM DUAL UNION ALL
SELECT '286452-5' MATRICULA FROM DUAL UNION ALL
SELECT '286453-3' MATRICULA FROM DUAL UNION ALL
SELECT '286527-X' MATRICULA FROM DUAL UNION ALL
SELECT '286899-7' MATRICULA FROM DUAL UNION ALL
SELECT '286935-7' MATRICULA FROM DUAL UNION ALL
SELECT '286937-3' MATRICULA FROM DUAL UNION ALL
SELECT '286979-9' MATRICULA FROM DUAL UNION ALL
SELECT '287315-0' MATRICULA FROM DUAL UNION ALL
SELECT '288328-7' MATRICULA FROM DUAL UNION ALL
SELECT '288329-5' MATRICULA FROM DUAL UNION ALL
SELECT '288447-0' MATRICULA FROM DUAL UNION ALL
SELECT '288767-3' MATRICULA FROM DUAL UNION ALL
SELECT '289484-0' MATRICULA FROM DUAL UNION ALL
SELECT '289557-9' MATRICULA FROM DUAL UNION ALL
SELECT '289584-6' MATRICULA FROM DUAL UNION ALL
SELECT '289942-6' MATRICULA FROM DUAL UNION ALL
SELECT '290115-3' MATRICULA FROM DUAL UNION ALL
SELECT '290347-4' MATRICULA FROM DUAL UNION ALL
SELECT '291697-5' MATRICULA FROM DUAL UNION ALL
SELECT '291966-4' MATRICULA FROM DUAL UNION ALL
SELECT '292050-6' MATRICULA FROM DUAL UNION ALL
SELECT '292081-6' MATRICULA FROM DUAL UNION ALL
SELECT '292368-8' MATRICULA FROM DUAL UNION ALL
SELECT '292373-4' MATRICULA FROM DUAL UNION ALL
SELECT '295524-5' MATRICULA FROM DUAL UNION ALL
SELECT '296035-4' MATRICULA FROM DUAL UNION ALL
SELECT '296036-2' MATRICULA FROM DUAL UNION ALL
SELECT '296138-5' MATRICULA FROM DUAL UNION ALL
SELECT '296645-0' MATRICULA FROM DUAL UNION ALL
SELECT '296737-5' MATRICULA FROM DUAL UNION ALL
SELECT '296738-3' MATRICULA FROM DUAL UNION ALL
SELECT '296935-1' MATRICULA FROM DUAL UNION ALL
SELECT '297220-4' MATRICULA FROM DUAL UNION ALL
SELECT '298167-0' MATRICULA FROM DUAL UNION ALL
SELECT '298180-7' MATRICULA FROM DUAL UNION ALL
SELECT '298201-3' MATRICULA FROM DUAL UNION ALL
SELECT '298215-3' MATRICULA FROM DUAL UNION ALL
SELECT '298591-8' MATRICULA FROM DUAL UNION ALL
SELECT '299153-5' MATRICULA FROM DUAL UNION ALL
SELECT '299154-3' MATRICULA FROM DUAL UNION ALL
SELECT '299219-1' MATRICULA FROM DUAL UNION ALL
SELECT '304547-1' MATRICULA FROM DUAL UNION ALL
SELECT '307124-3' MATRICULA FROM DUAL UNION ALL
SELECT '307916-3' MATRICULA FROM DUAL UNION ALL
SELECT '307935-0' MATRICULA FROM DUAL UNION ALL
SELECT '307997-0' MATRICULA FROM DUAL UNION ALL
SELECT '308035-8' MATRICULA FROM DUAL UNION ALL
SELECT '308036-6' MATRICULA FROM DUAL UNION ALL
SELECT '308258-0' MATRICULA FROM DUAL UNION ALL
SELECT '308543-X' MATRICULA FROM DUAL UNION ALL
SELECT '308598-8' MATRICULA FROM DUAL UNION ALL
SELECT '308672-X' MATRICULA FROM DUAL UNION ALL
SELECT '308866-9' MATRICULA FROM DUAL UNION ALL
SELECT '308867-7' MATRICULA FROM DUAL UNION ALL
SELECT '310785-0' MATRICULA FROM DUAL UNION ALL
SELECT '311145-8' MATRICULA FROM DUAL UNION ALL
SELECT '311147-4' MATRICULA FROM DUAL UNION ALL
SELECT '311148-2' MATRICULA FROM DUAL UNION ALL
SELECT '311149-X' MATRICULA FROM DUAL UNION ALL
SELECT '311419-8' MATRICULA FROM DUAL UNION ALL
SELECT '311546-1' MATRICULA FROM DUAL UNION ALL
SELECT '315797-X' MATRICULA FROM DUAL UNION ALL
SELECT '318104-9' MATRICULA FROM DUAL UNION ALL
SELECT '318116-2' MATRICULA FROM DUAL UNION ALL
SELECT '318189-8' MATRICULA FROM DUAL UNION ALL
SELECT '318303-3' MATRICULA FROM DUAL UNION ALL
SELECT '318702-X' MATRICULA FROM DUAL UNION ALL
SELECT '319583-0' MATRICULA FROM DUAL UNION ALL
SELECT '319964-9' MATRICULA FROM DUAL UNION ALL
SELECT '320758-7' MATRICULA FROM DUAL UNION ALL
SELECT '321505-9' MATRICULA FROM DUAL UNION ALL
SELECT '321506-7' MATRICULA FROM DUAL UNION ALL
SELECT '321801-5' MATRICULA FROM DUAL UNION ALL
SELECT '321811-2' MATRICULA FROM DUAL UNION ALL
SELECT '321996-8' MATRICULA FROM DUAL UNION ALL
SELECT '322042-7' MATRICULA FROM DUAL UNION ALL
SELECT '322111-3' MATRICULA FROM DUAL UNION ALL
SELECT '322185-7' MATRICULA FROM DUAL UNION ALL
SELECT '322186-5' MATRICULA FROM DUAL UNION ALL
SELECT '322209-8' MATRICULA FROM DUAL UNION ALL
SELECT '322210-1' MATRICULA FROM DUAL UNION ALL
SELECT '322806-1' MATRICULA FROM DUAL UNION ALL
SELECT '322809-6' MATRICULA FROM DUAL UNION ALL
SELECT '322815-X' MATRICULA FROM DUAL UNION ALL
SELECT '322897-5' MATRICULA FROM DUAL UNION ALL
SELECT '322945-9' MATRICULA FROM DUAL UNION ALL
SELECT '327044-X' MATRICULA FROM DUAL UNION ALL
SELECT '327045-9' MATRICULA FROM DUAL UNION ALL
SELECT '327046-7' MATRICULA FROM DUAL UNION ALL
SELECT '329396-3' MATRICULA FROM DUAL UNION ALL
SELECT '329839-6' MATRICULA FROM DUAL UNION ALL
SELECT '330244-0' MATRICULA FROM DUAL UNION ALL
SELECT '330248-2' MATRICULA FROM DUAL UNION ALL
SELECT '330252-X' MATRICULA FROM DUAL UNION ALL
SELECT '330263-6' MATRICULA FROM DUAL UNION ALL
SELECT '330430-2' MATRICULA FROM DUAL UNION ALL
SELECT '330563-5' MATRICULA FROM DUAL UNION ALL
SELECT '330598-8' MATRICULA FROM DUAL UNION ALL
SELECT '330649-6' MATRICULA FROM DUAL UNION ALL
SELECT '331001-9' MATRICULA FROM DUAL UNION ALL
SELECT '331052-3' MATRICULA FROM DUAL UNION ALL
SELECT '331074-4' MATRICULA FROM DUAL UNION ALL
SELECT '331278-0' MATRICULA FROM DUAL UNION ALL
SELECT '332159-2' MATRICULA FROM DUAL UNION ALL
SELECT '332263-7' MATRICULA FROM DUAL UNION ALL
SELECT '332267-0' MATRICULA FROM DUAL UNION ALL
SELECT '332268-8' MATRICULA FROM DUAL UNION ALL
SELECT '332289-X' MATRICULA FROM DUAL UNION ALL
SELECT '332323-4' MATRICULA FROM DUAL UNION ALL
SELECT '332357-9' MATRICULA FROM DUAL UNION ALL
SELECT '332553-9' MATRICULA FROM DUAL UNION ALL
SELECT '332554-7' MATRICULA FROM DUAL UNION ALL
SELECT '332595-4' MATRICULA FROM DUAL UNION ALL
SELECT '332598-9' MATRICULA FROM DUAL UNION ALL
SELECT '332769-8' MATRICULA FROM DUAL UNION ALL
SELECT '332773-6' MATRICULA FROM DUAL UNION ALL
SELECT '333698-X' MATRICULA FROM DUAL UNION ALL
SELECT '333976-9' MATRICULA FROM DUAL UNION ALL
SELECT '333978-5' MATRICULA FROM DUAL UNION ALL
SELECT '340988-X' MATRICULA FROM DUAL UNION ALL
SELECT '341089-7' MATRICULA FROM DUAL UNION ALL
SELECT '341877-4' MATRICULA FROM DUAL UNION ALL
SELECT '341878-2' MATRICULA FROM DUAL UNION ALL
SELECT '341917-7' MATRICULA FROM DUAL UNION ALL
SELECT '342185-6' MATRICULA FROM DUAL UNION ALL
SELECT '342302-6' MATRICULA FROM DUAL UNION ALL
SELECT '342729-3' MATRICULA FROM DUAL UNION ALL
SELECT '342730-7' MATRICULA FROM DUAL UNION ALL
SELECT '342744-7' MATRICULA FROM DUAL UNION ALL
SELECT '342891-5' MATRICULA FROM DUAL UNION ALL
SELECT '342892-3' MATRICULA FROM DUAL UNION ALL
SELECT '342893-1' MATRICULA FROM DUAL UNION ALL
SELECT '342894-0' MATRICULA FROM DUAL UNION ALL
SELECT '343550-4' MATRICULA FROM DUAL UNION ALL
SELECT '343551-2' MATRICULA FROM DUAL UNION ALL
SELECT '343707-8' MATRICULA FROM DUAL UNION ALL
SELECT '343758-2' MATRICULA FROM DUAL UNION ALL
SELECT '343970-4' MATRICULA FROM DUAL UNION ALL
SELECT '344034-6' MATRICULA FROM DUAL UNION ALL
SELECT '344055-9' MATRICULA FROM DUAL UNION ALL
SELECT '344155-5' MATRICULA FROM DUAL UNION ALL
SELECT '344397-3' MATRICULA FROM DUAL UNION ALL
SELECT '344513-5' MATRICULA FROM DUAL UNION ALL
SELECT '344522-4' MATRICULA FROM DUAL UNION ALL
SELECT '344852-5' MATRICULA FROM DUAL UNION ALL
SELECT '344855-0' MATRICULA FROM DUAL UNION ALL
SELECT '344864-9' MATRICULA FROM DUAL UNION ALL
SELECT '344865-7' MATRICULA FROM DUAL UNION ALL
SELECT '344866-5' MATRICULA FROM DUAL UNION ALL
SELECT '344867-3' MATRICULA FROM DUAL UNION ALL
SELECT '344868-1' MATRICULA FROM DUAL UNION ALL
SELECT '344869-0' MATRICULA FROM DUAL UNION ALL
SELECT '344870-3' MATRICULA FROM DUAL UNION ALL
SELECT '344871-1' MATRICULA FROM DUAL UNION ALL
SELECT '344873-8' MATRICULA FROM DUAL UNION ALL
SELECT '344874-6' MATRICULA FROM DUAL UNION ALL
SELECT '344875-4' MATRICULA FROM DUAL UNION ALL
SELECT '344876-2' MATRICULA FROM DUAL UNION ALL
SELECT '344877-X' MATRICULA FROM DUAL UNION ALL
SELECT '344878-9' MATRICULA FROM DUAL UNION ALL
SELECT '344879-7' MATRICULA FROM DUAL UNION ALL
SELECT '344880-X' MATRICULA FROM DUAL UNION ALL
SELECT '344881-9' MATRICULA FROM DUAL UNION ALL
SELECT '344883-5' MATRICULA FROM DUAL UNION ALL
SELECT '344884-3' MATRICULA FROM DUAL UNION ALL
SELECT '344885-1' MATRICULA FROM DUAL UNION ALL
SELECT '349147-1' MATRICULA FROM DUAL UNION ALL
SELECT '351478-1' MATRICULA FROM DUAL UNION ALL
SELECT '352700-0' MATRICULA FROM DUAL UNION ALL
SELECT '352852-9' MATRICULA FROM DUAL UNION ALL
SELECT '353712-9' MATRICULA FROM DUAL UNION ALL
SELECT '353769-2' MATRICULA FROM DUAL UNION ALL
SELECT '354388-9' MATRICULA FROM DUAL UNION ALL
SELECT '354491-5' MATRICULA FROM DUAL UNION ALL
SELECT '355096-6' MATRICULA FROM DUAL UNION ALL
SELECT '355241-1' MATRICULA FROM DUAL UNION ALL
SELECT '356197-6' MATRICULA FROM DUAL UNION ALL
SELECT '356710-9' MATRICULA FROM DUAL UNION ALL
SELECT '357445-8' MATRICULA FROM DUAL UNION ALL
SELECT '360000-9' MATRICULA FROM DUAL UNION ALL
SELECT '360285-X' MATRICULA FROM DUAL UNION ALL
SELECT '364116-3' MATRICULA FROM DUAL UNION ALL
SELECT '365633-X' MATRICULA FROM DUAL UNION ALL
SELECT '369949-8' MATRICULA FROM DUAL UNION ALL
SELECT '370120-4' MATRICULA FROM DUAL UNION ALL
SELECT '400700-0' MATRICULA FROM DUAL UNION ALL
SELECT '400701-8' MATRICULA FROM DUAL UNION ALL
SELECT '400848-X' MATRICULA FROM DUAL UNION ALL
SELECT '402244-X' MATRICULA FROM DUAL UNION ALL
SELECT '403025-7' MATRICULA FROM DUAL UNION ALL
SELECT '403026-5' MATRICULA FROM DUAL UNION ALL
SELECT '403139-3' MATRICULA FROM DUAL UNION ALL
SELECT '405166-1' MATRICULA FROM DUAL UNION ALL
SELECT '405197-1' MATRICULA FROM DUAL UNION ALL
SELECT '405198-0' MATRICULA FROM DUAL UNION ALL
SELECT '405284-6' MATRICULA FROM DUAL UNION ALL
SELECT '419589-2' MATRICULA FROM DUAL UNION ALL
SELECT '430134-0' MATRICULA FROM DUAL UNION ALL
SELECT '433966-5' MATRICULA FROM DUAL
)
SELECT 
    'EMPRESA' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_EMPRESA.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'CBMPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_CBMPI.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'PGEPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_PGEPI.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'CGEPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_CGEPI.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SSPPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_SSPPI.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'COJUV' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_COJUV.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'ATIPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_ATIPI.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'FAPEPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_FAPEPI.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'DEFCIVIL' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_DEFCIVIL.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'ADH' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_ADH.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SEAGRO' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_SEAGRO.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'IDEPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_IDEPI.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SURPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_SURPI.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SEID' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_SEID.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SECID' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_SECID.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'FUPIP' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_FUPIP.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SETUR' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_SETUR.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'AGESPISA' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_AGESPISA.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SETRANS' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_SETRANS.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'TVANTARES' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_TVANTARES.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'VICEGOV' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_VICEGOV.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SEINFRA' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_SEINFRA.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'CCOM' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_CCOM.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'FUNDESPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_FUNDESPI.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SEDET' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_SEDET.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'INTERPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_INTERPI.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'JUCEPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_JUCEPI.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SEMAR' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_SEMAR.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'GMG' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_GMG.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SEPLAN' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_SEPLAN.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SAF' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_SAF.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SECULT' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_SECULT.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'DER' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_DER.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'DETRAN' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_DETRAN.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'IASPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_IASPI.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'ADAPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_ADAPI.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'IMEPIPROD' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_IMEPIPROD.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'CPVCI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_CPVCI.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'CENDROGAS' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_CENDROGAS.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'COFIR' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_COFIR.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SEMINPER' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_SEMINPER.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'AGRESP' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_AGRESP.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'CEPM' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_CEPM.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'EMATER' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_EMATER.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'FUESPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_FUESPI.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'EMATERPROD' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_EMATERPROD.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'DEFENSORIA' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_DEFENSORIA.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'PENSIONISTAS' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_PENSIONISTAS.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'CDTER' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_CDTER.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SERES' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_SERES.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SECESP' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_SECESP.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'INATIVOS_PENSIONISTAS' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_INATIVOS_PENSIONISTAS.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SEDUC_PRECATORIO' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_SEDUC_PRECATORIO.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'EMGERPI_CORESA' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_EMGERPI_CORESA.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'FUNPREV' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_FUNPREV.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'FESPPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_FESPPI.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SIA' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_SIA.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SETRE' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_SETRE.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'AGESPISA02' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_AGESPISA02.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SEGOV' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_SEGOV.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SASC' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_SASC.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'METRO' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_METRO.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'PIAUIPREV' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_PIAUIPREV.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'INATIVOS_SEDUC' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_INATIVOS_SEDUC.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'INATIVOS_TCE' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_INATIVOS_TCE.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SADA' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_SADA.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SECMULHERES' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_SECMULHERES.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'EMGERPI_EMATER' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_EMGERPI_EMATER.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'REENVIO' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_REENVIO.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SESAPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_SESAPI.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'PMPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_PMPI.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SEJUSPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_SEJUSPI.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SEFAZPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_SEFAZPI.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SEADPREVPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_SEADPREVPI.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'IMEPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_IMEPI.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'BEP' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_BEP.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'EMGERPI_COMEPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_EMGERPI_COMEPI.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'EMGERPI_COMDEPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_EMGERPI_COMDEPI.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'EMGERPI_COHAB' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_EMGERPI_COHAB.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'EMGERPI_PRODEPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_EMGERPI_PRODEPI.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'EMGERPI_CEASA' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_EMGERPI_CEASA.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'EMGERPI_PIEMTUR' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_EMGERPI_PIEMTUR.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'EMGERPI_ETELPI_FUNART' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_EMGERPI_ETELPI_FUNART.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'EMGERPI_CIDAPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_EMGERPI_CIDAPI.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SEDUC' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_SEDUC.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'EMGERPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_EMGERPI.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'EMGERPI_CODIPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PE.NOME_ESTADO_CIVIL
FROM
    SW_EMGERPI_CODIPI.PESSOA_VINCULO PV
    JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PE ON PE.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
;