SELECT 
    'SW_ADAPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_ADAPI.FOLHA FO 
    JOIN SW_ADAPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_ADAPI.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_ADAPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_ADAPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_ADH' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_ADH.FOLHA FO 
    JOIN SW_ADH.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_ADH.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_ADH.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_ADH.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_AGESPISA' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_AGESPISA.FOLHA FO 
    JOIN SW_AGESPISA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_AGESPISA.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_AGESPISA.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_AGESPISA.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_AGESPISA02' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_AGESPISA02.FOLHA FO 
    JOIN SW_AGESPISA02.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_AGESPISA02.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_AGESPISA02.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_AGESPISA02.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_AGRESP' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_AGRESP.FOLHA FO 
    JOIN SW_AGRESP.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_AGRESP.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_AGRESP.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_AGRESP.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_BEP' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_BEP.FOLHA FO 
    JOIN SW_BEP.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_BEP.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_BEP.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_BEP.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_CBMPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_CBMPI.FOLHA FO 
    JOIN SW_CBMPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_CBMPI.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_CBMPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_CBMPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_CCOM' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_CCOM.FOLHA FO 
    JOIN SW_CCOM.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_CCOM.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_CCOM.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_CCOM.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_CDTER' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_CDTER.FOLHA FO 
    JOIN SW_CDTER.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_CDTER.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_CDTER.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_CDTER.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_CENDROGAS' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_CENDROGAS.FOLHA FO 
    JOIN SW_CENDROGAS.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_CENDROGAS.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_CENDROGAS.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_CENDROGAS.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_COFIR' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_COFIR.FOLHA FO 
    JOIN SW_COFIR.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_COFIR.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_COFIR.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_COFIR.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_COJUV' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_COJUV.FOLHA FO 
    JOIN SW_COJUV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_COJUV.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_COJUV.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_COJUV.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_DEFCIVIL' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_DEFCIVIL.FOLHA FO 
    JOIN SW_DEFCIVIL.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_DEFCIVIL.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_DEFCIVIL.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_DEFCIVIL.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_DER' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_DER.FOLHA FO 
    JOIN SW_DER.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_DER.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_DER.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_DER.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_DETRAN' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_DETRAN.FOLHA FO 
    JOIN SW_DETRAN.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_DETRAN.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_DETRAN.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_DETRAN.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_EMGERPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_EMGERPI.FOLHA FO 
    JOIN SW_EMGERPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_EMGERPI.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_EMGERPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_EMGERPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_EMGERPI_CEASA' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_EMGERPI_CEASA.FOLHA FO 
    JOIN SW_EMGERPI_CEASA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_EMGERPI_CEASA.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_EMGERPI_CEASA.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_EMGERPI_CEASA.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_EMGERPI_CIDAPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_EMGERPI_CIDAPI.FOLHA FO 
    JOIN SW_EMGERPI_CIDAPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_EMGERPI_CIDAPI.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_EMGERPI_CIDAPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_EMGERPI_CIDAPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_EMGERPI_CODIPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_EMGERPI_CODIPI.FOLHA FO 
    JOIN SW_EMGERPI_CODIPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_EMGERPI_CODIPI.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_EMGERPI_CODIPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_EMGERPI_CODIPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_EMGERPI_COHAB' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_EMGERPI_COHAB.FOLHA FO 
    JOIN SW_EMGERPI_COHAB.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_EMGERPI_COHAB.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_EMGERPI_COHAB.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_EMGERPI_COHAB.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_EMGERPI_COMDEPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_EMGERPI_COMDEPI.FOLHA FO 
    JOIN SW_EMGERPI_COMDEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_EMGERPI_COMDEPI.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_EMGERPI_COMDEPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_EMGERPI_COMDEPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_EMGERPI_COMEPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_EMGERPI_COMEPI.FOLHA FO 
    JOIN SW_EMGERPI_COMEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_EMGERPI_COMEPI.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_EMGERPI_COMEPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_EMGERPI_COMEPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_EMGERPI_CORESA' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_EMGERPI_CORESA.FOLHA FO 
    JOIN SW_EMGERPI_CORESA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_EMGERPI_CORESA.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_EMGERPI_CORESA.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_EMGERPI_CORESA.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_EMGERPI_EMATER' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_EMGERPI_EMATER.FOLHA FO 
    JOIN SW_EMGERPI_EMATER.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_EMGERPI_EMATER.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_EMGERPI_EMATER.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_EMGERPI_EMATER.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_EMGERPI_ETELPI_FUNART' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_EMGERPI_ETELPI_FUNART.FOLHA FO 
    JOIN SW_EMGERPI_ETELPI_FUNART.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_EMGERPI_ETELPI_FUNART.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_EMGERPI_ETELPI_FUNART.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_EMGERPI_ETELPI_FUNART.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_EMGERPI_PIEMTUR' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_EMGERPI_PIEMTUR.FOLHA FO 
    JOIN SW_EMGERPI_PIEMTUR.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_EMGERPI_PIEMTUR.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_EMGERPI_PIEMTUR.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_EMGERPI_PIEMTUR.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_EMGERPI_PRODEPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_EMGERPI_PRODEPI.FOLHA FO 
    JOIN SW_EMGERPI_PRODEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_EMGERPI_PRODEPI.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_EMGERPI_PRODEPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_EMGERPI_PRODEPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_FAPEPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_FAPEPI.FOLHA FO 
    JOIN SW_FAPEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_FAPEPI.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_FAPEPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_FAPEPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_FESPPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_FESPPI.FOLHA FO 
    JOIN SW_FESPPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_FESPPI.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_FESPPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_FESPPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_FUESPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_FUESPI.FOLHA FO 
    JOIN SW_FUESPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_FUESPI.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_FUESPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_FUESPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_FUNPREV' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_FUNPREV.FOLHA FO 
    JOIN SW_FUNPREV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_FUNPREV.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_FUNPREV.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_FUNPREV.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_FUPIP' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_FUPIP.FOLHA FO 
    JOIN SW_FUPIP.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_FUPIP.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_FUPIP.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_FUPIP.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_GMG' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_GMG.FOLHA FO 
    JOIN SW_GMG.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_GMG.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_GMG.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_GMG.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_IASPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_IASPI.FOLHA FO 
    JOIN SW_IASPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_IASPI.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_IASPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_IASPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_IDEPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_IDEPI.FOLHA FO 
    JOIN SW_IDEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_IDEPI.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_IDEPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_IDEPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_IMEPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_IMEPI.FOLHA FO 
    JOIN SW_IMEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_IMEPI.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_IMEPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_IMEPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_IMEPIPROD' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_IMEPIPROD.FOLHA FO 
    JOIN SW_IMEPIPROD.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_IMEPIPROD.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_IMEPIPROD.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_IMEPIPROD.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_INTERPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_INTERPI.FOLHA FO 
    JOIN SW_INTERPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_INTERPI.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_INTERPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_INTERPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_JUCEPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_JUCEPI.FOLHA FO 
    JOIN SW_JUCEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_JUCEPI.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_JUCEPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_JUCEPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_METRO' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_METRO.FOLHA FO 
    JOIN SW_METRO.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_METRO.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_METRO.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_METRO.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_PGEPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_PGEPI.FOLHA FO 
    JOIN SW_PGEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_PGEPI.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_PGEPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_PGEPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_PMPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_PMPI.FOLHA FO 
    JOIN SW_PMPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_PMPI.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_PMPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_PMPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_SADA' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_SADA.FOLHA FO 
    JOIN SW_SADA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_SADA.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_SADA.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_SADA.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_SAF' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_SAF.FOLHA FO 
    JOIN SW_SAF.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_SAF.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_SAF.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_SAF.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_SASC' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_SASC.FOLHA FO 
    JOIN SW_SASC.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_SASC.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_SASC.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_SASC.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_SEADPREVPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_SEADPREVPI.FOLHA FO 
    JOIN SW_SEADPREVPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_SEADPREVPI.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_SEADPREVPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_SEADPREVPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_SEAGRO' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_SEAGRO.FOLHA FO 
    JOIN SW_SEAGRO.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_SEAGRO.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_SEAGRO.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_SEAGRO.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_SECESP' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_SECESP.FOLHA FO 
    JOIN SW_SECESP.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_SECESP.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_SECESP.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_SECESP.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_SECID' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_SECID.FOLHA FO 
    JOIN SW_SECID.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_SECID.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_SECID.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_SECID.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_SECMULHERES' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_SECMULHERES.FOLHA FO 
    JOIN SW_SECMULHERES.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_SECMULHERES.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_SECMULHERES.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_SECMULHERES.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_SECULT' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_SECULT.FOLHA FO 
    JOIN SW_SECULT.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_SECULT.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_SECULT.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_SECULT.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_SEDET' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_SEDET.FOLHA FO 
    JOIN SW_SEDET.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_SEDET.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_SEDET.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_SEDET.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_SEDUC' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_SEDUC.FOLHA FO 
    JOIN SW_SEDUC.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_SEDUC.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_SEDUC.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_SEDUC.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_SEFAZPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_SEFAZPI.FOLHA FO 
    JOIN SW_SEFAZPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_SEFAZPI.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_SEFAZPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_SEFAZPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_SEGOV' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_SEGOV.FOLHA FO 
    JOIN SW_SEGOV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_SEGOV.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_SEGOV.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_SEGOV.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_SEID' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_SEID.FOLHA FO 
    JOIN SW_SEID.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_SEID.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_SEID.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_SEID.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_SEINFRA' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_SEINFRA.FOLHA FO 
    JOIN SW_SEINFRA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_SEINFRA.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_SEINFRA.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_SEINFRA.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_SEJUSPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_SEJUSPI.FOLHA FO 
    JOIN SW_SEJUSPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_SEJUSPI.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_SEJUSPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_SEJUSPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_SEMAR' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_SEMAR.FOLHA FO 
    JOIN SW_SEMAR.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_SEMAR.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_SEMAR.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_SEMAR.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_SEMINPER' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_SEMINPER.FOLHA FO 
    JOIN SW_SEMINPER.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_SEMINPER.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_SEMINPER.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_SEMINPER.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_SEPLAN' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_SEPLAN.FOLHA FO 
    JOIN SW_SEPLAN.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_SEPLAN.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_SEPLAN.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_SEPLAN.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_SERES' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_SERES.FOLHA FO 
    JOIN SW_SERES.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_SERES.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_SERES.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_SERES.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_SESAPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_SESAPI.FOLHA FO 
    JOIN SW_SESAPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_SESAPI.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_SESAPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_SESAPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_SETRANS' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_SETRANS.FOLHA FO 
    JOIN SW_SETRANS.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_SETRANS.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_SETRANS.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_SETRANS.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_SETRE' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_SETRE.FOLHA FO 
    JOIN SW_SETRE.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_SETRE.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_SETRE.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_SETRE.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_SETUR' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_SETUR.FOLHA FO 
    JOIN SW_SETUR.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_SETUR.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_SETUR.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_SETUR.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_SIA' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_SIA.FOLHA FO 
    JOIN SW_SIA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_SIA.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_SIA.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_SIA.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_SSPPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_SSPPI.FOLHA FO 
    JOIN SW_SSPPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_SSPPI.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_SSPPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_SSPPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_SURPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_SURPI.FOLHA FO 
    JOIN SW_SURPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_SURPI.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_SURPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_SURPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_TVANTARES' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_TVANTARES.FOLHA FO 
    JOIN SW_TVANTARES.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_TVANTARES.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_TVANTARES.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_TVANTARES.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SW_VICEGOV' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    P.DATA_NASCIMENTO,
    FI.DATA_EXERCICIO,
    FO.MES,
    FO.ANO,
    RT.NOME_REGIME,
    R.NOME_RUBRICA,
    FR.VALOR_CALCULADO VALOR_CALCULADO_2026
FROM 
    SW_VICEGOV.FOLHA FO 
    JOIN SW_VICEGOV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    LEFT JOIN SW_VICEGOV.FOLHA_FICHA_FINANCEIRA FFF ON FFF.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO AND FFF.DATA_FIM IS NULL
    LEFT JOIN SW_VICEGOV.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FI.DATA_TERMINO IS NULL
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO RT ON RT.ID_REGIME = FI.ID_REGIME 
    LEFT JOIN SW_VICEGOV.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    LEFT JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA 
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND P.DATA_OBITO IS NULL
WHERE 
    RT.ID_REGIME = 2
    AND FR.ID_RUBRICA = 1553119
    AND FO.MES = 1 
    AND FO.ANO = 2026