SELECT 
    'FUNPREV' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.DATA_INICIO,
    PS.IND_PENSAO,
    PS.IND_ATIVO
FROM
    SW_FUNPREV.PESSOA_VINCULO PV
    JOIN SW_FUNPREV.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_FUNPREV.PENS_CIVI_SEM_INSTITUIDOR PS ON PS.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL