WITH VALORES AS (
SELECT '000345-0' MATRICULA FROM DUAL UNION ALL
SELECT '001022-7' MATRICULA FROM DUAL UNION ALL
SELECT '001410-9' MATRICULA FROM DUAL UNION ALL
SELECT '002471-6' MATRICULA FROM DUAL UNION ALL
SELECT '002481-3' MATRICULA FROM DUAL UNION ALL
SELECT '003263-8' MATRICULA FROM DUAL UNION ALL
SELECT '003524-6' MATRICULA FROM DUAL UNION ALL
SELECT '003599-8' MATRICULA FROM DUAL UNION ALL
SELECT '003704-4' MATRICULA FROM DUAL UNION ALL
SELECT '003803-2' MATRICULA FROM DUAL UNION ALL
SELECT '003832-6' MATRICULA FROM DUAL UNION ALL
SELECT '003975-6' MATRICULA FROM DUAL UNION ALL
SELECT '004108-4' MATRICULA FROM DUAL UNION ALL
SELECT '004147-5' MATRICULA FROM DUAL UNION ALL
SELECT '004229-3' MATRICULA FROM DUAL UNION ALL
SELECT '004448-2' MATRICULA FROM DUAL UNION ALL
SELECT '004625-6' MATRICULA FROM DUAL UNION ALL
SELECT '005015-6' MATRICULA FROM DUAL UNION ALL
SELECT '005061-0' MATRICULA FROM DUAL UNION ALL
SELECT '005794-X' MATRICULA FROM DUAL UNION ALL
SELECT '005795-9' MATRICULA FROM DUAL UNION ALL
SELECT '005803-3' MATRICULA FROM DUAL UNION ALL
SELECT '006303-7' MATRICULA FROM DUAL UNION ALL
SELECT '006857-8' MATRICULA FROM DUAL UNION ALL
SELECT '006984-1' MATRICULA FROM DUAL UNION ALL
SELECT '007240-X' MATRICULA FROM DUAL UNION ALL
SELECT '007301-6' MATRICULA FROM DUAL UNION ALL
SELECT '007441-1' MATRICULA FROM DUAL UNION ALL
SELECT '007454-3' MATRICULA FROM DUAL UNION ALL
SELECT '007579-5' MATRICULA FROM DUAL UNION ALL
SELECT '007687-2' MATRICULA FROM DUAL UNION ALL
SELECT '008298-8' MATRICULA FROM DUAL UNION ALL
SELECT '008551-X' MATRICULA FROM DUAL UNION ALL
SELECT '008592-8' MATRICULA FROM DUAL UNION ALL
SELECT '008792-X' MATRICULA FROM DUAL UNION ALL
SELECT '008850-1' MATRICULA FROM DUAL UNION ALL
SELECT '009071-9' MATRICULA FROM DUAL UNION ALL
SELECT '009223-1' MATRICULA FROM DUAL UNION ALL
SELECT '009419-6' MATRICULA FROM DUAL UNION ALL
SELECT '009809-4' MATRICULA FROM DUAL UNION ALL
SELECT '009875-2' MATRICULA FROM DUAL UNION ALL
SELECT '009927-9' MATRICULA FROM DUAL UNION ALL
SELECT '013470-8' MATRICULA FROM DUAL UNION ALL
SELECT '013657-3' MATRICULA FROM DUAL UNION ALL
SELECT '013660-3' MATRICULA FROM DUAL UNION ALL
SELECT '014695-1' MATRICULA FROM DUAL UNION ALL
SELECT '014712-5' MATRICULA FROM DUAL UNION ALL
SELECT '014728-1' MATRICULA FROM DUAL UNION ALL
SELECT '016188-8' MATRICULA FROM DUAL UNION ALL
SELECT '016213-2' MATRICULA FROM DUAL UNION ALL
SELECT '016214-X' MATRICULA FROM DUAL UNION ALL
SELECT '016218-3' MATRICULA FROM DUAL UNION ALL
SELECT '016225-6' MATRICULA FROM DUAL UNION ALL
SELECT '016229-9' MATRICULA FROM DUAL UNION ALL
SELECT '016230-2' MATRICULA FROM DUAL UNION ALL
SELECT '016231-X' MATRICULA FROM DUAL UNION ALL
SELECT '016238-8' MATRICULA FROM DUAL UNION ALL
SELECT '016242-6' MATRICULA FROM DUAL UNION ALL
SELECT '016245-X' MATRICULA FROM DUAL UNION ALL
SELECT '016275-2' MATRICULA FROM DUAL UNION ALL
SELECT '016282-5' MATRICULA FROM DUAL UNION ALL
SELECT '016302-3' MATRICULA FROM DUAL UNION ALL
SELECT '016314-7' MATRICULA FROM DUAL UNION ALL
SELECT '016325-2' MATRICULA FROM DUAL UNION ALL
SELECT '016328-7' MATRICULA FROM DUAL UNION ALL
SELECT '016333-3' MATRICULA FROM DUAL UNION ALL
SELECT '016360-X' MATRICULA FROM DUAL UNION ALL
SELECT '016371-6' MATRICULA FROM DUAL UNION ALL
SELECT '016382-1' MATRICULA FROM DUAL UNION ALL
SELECT '016399-6' MATRICULA FROM DUAL UNION ALL
SELECT '016402-0' MATRICULA FROM DUAL UNION ALL
SELECT '016411-9' MATRICULA FROM DUAL UNION ALL
SELECT '016414-3' MATRICULA FROM DUAL UNION ALL
SELECT '016440-2' MATRICULA FROM DUAL UNION ALL
SELECT '016443-7' MATRICULA FROM DUAL UNION ALL
SELECT '016457-7' MATRICULA FROM DUAL UNION ALL
SELECT '016469-X' MATRICULA FROM DUAL UNION ALL
SELECT '016472-X' MATRICULA FROM DUAL UNION ALL
SELECT '016487-9' MATRICULA FROM DUAL UNION ALL
SELECT '016509-3' MATRICULA FROM DUAL UNION ALL
SELECT '016566-2' MATRICULA FROM DUAL UNION ALL
SELECT '016602-2' MATRICULA FROM DUAL UNION ALL
SELECT '016609-0' MATRICULA FROM DUAL UNION ALL
SELECT '016636-7' MATRICULA FROM DUAL UNION ALL
SELECT '016642-1' MATRICULA FROM DUAL UNION ALL
SELECT '016657-0' MATRICULA FROM DUAL UNION ALL
SELECT '016682-X' MATRICULA FROM DUAL UNION ALL
SELECT '016699-5' MATRICULA FROM DUAL UNION ALL
SELECT '017778-4' MATRICULA FROM DUAL UNION ALL
SELECT '017909-4' MATRICULA FROM DUAL UNION ALL
SELECT '017918-3' MATRICULA FROM DUAL UNION ALL
SELECT '018002-5' MATRICULA FROM DUAL UNION ALL
SELECT '018015-7' MATRICULA FROM DUAL UNION ALL
SELECT '018082-3' MATRICULA FROM DUAL UNION ALL
SELECT '018102-1' MATRICULA FROM DUAL UNION ALL
SELECT '018203-6' MATRICULA FROM DUAL UNION ALL
SELECT '018231-1' MATRICULA FROM DUAL UNION ALL
SELECT '018347-4' MATRICULA FROM DUAL UNION ALL
SELECT '018652-0' MATRICULA FROM DUAL UNION ALL
SELECT '018689-9' MATRICULA FROM DUAL UNION ALL
SELECT '019567-7' MATRICULA FROM DUAL UNION ALL
SELECT '020543-5' MATRICULA FROM DUAL UNION ALL
SELECT '020973-2' MATRICULA FROM DUAL UNION ALL
SELECT '021005-6' MATRICULA FROM DUAL UNION ALL
SELECT '021163-0' MATRICULA FROM DUAL UNION ALL
SELECT '021313-6' MATRICULA FROM DUAL UNION ALL
SELECT '021764-6' MATRICULA FROM DUAL UNION ALL
SELECT '021785-9' MATRICULA FROM DUAL UNION ALL
SELECT '021809-0' MATRICULA FROM DUAL UNION ALL
SELECT '021822-7' MATRICULA FROM DUAL UNION ALL
SELECT '021956-8' MATRICULA FROM DUAL UNION ALL
SELECT '021971-1' MATRICULA FROM DUAL UNION ALL
SELECT '022003-5' MATRICULA FROM DUAL UNION ALL
SELECT '022009-4' MATRICULA FROM DUAL UNION ALL
SELECT '022025-6' MATRICULA FROM DUAL UNION ALL
SELECT '022058-2' MATRICULA FROM DUAL UNION ALL
SELECT '022061-2' MATRICULA FROM DUAL UNION ALL
SELECT '022064-7' MATRICULA FROM DUAL UNION ALL
SELECT '022067-1' MATRICULA FROM DUAL UNION ALL
SELECT '022068-0' MATRICULA FROM DUAL UNION ALL
SELECT '022085-0' MATRICULA FROM DUAL UNION ALL
SELECT '022089-2' MATRICULA FROM DUAL UNION ALL
SELECT '022093-X' MATRICULA FROM DUAL UNION ALL
SELECT '022101-5' MATRICULA FROM DUAL UNION ALL
SELECT '022124-4' MATRICULA FROM DUAL UNION ALL
SELECT '022139-2' MATRICULA FROM DUAL UNION ALL
SELECT '022170-8' MATRICULA FROM DUAL UNION ALL
SELECT '022225-9' MATRICULA FROM DUAL UNION ALL
SELECT '022227-5' MATRICULA FROM DUAL UNION ALL
SELECT '022249-6' MATRICULA FROM DUAL UNION ALL
SELECT '022270-4' MATRICULA FROM DUAL UNION ALL
SELECT '022279-8' MATRICULA FROM DUAL UNION ALL
SELECT '022300-0' MATRICULA FROM DUAL UNION ALL
SELECT '022308-5' MATRICULA FROM DUAL UNION ALL
SELECT '022351-4' MATRICULA FROM DUAL UNION ALL
SELECT '022408-1' MATRICULA FROM DUAL UNION ALL
SELECT '022417-X' MATRICULA FROM DUAL UNION ALL
SELECT '022468-5' MATRICULA FROM DUAL UNION ALL
SELECT '022519-3' MATRICULA FROM DUAL UNION ALL
SELECT '022646-7' MATRICULA FROM DUAL UNION ALL
SELECT '022671-8' MATRICULA FROM DUAL UNION ALL
SELECT '022689-X' MATRICULA FROM DUAL UNION ALL
SELECT '022692-X' MATRICULA FROM DUAL UNION ALL
SELECT '022982-2' MATRICULA FROM DUAL UNION ALL
SELECT '023010-3' MATRICULA FROM DUAL UNION ALL
SELECT '023014-6' MATRICULA FROM DUAL UNION ALL
SELECT '023208-4' MATRICULA FROM DUAL UNION ALL
SELECT '023210-6' MATRICULA FROM DUAL UNION ALL
SELECT '023236-0' MATRICULA FROM DUAL UNION ALL
SELECT '023243-2' MATRICULA FROM DUAL UNION ALL
SELECT '023251-3' MATRICULA FROM DUAL UNION ALL
SELECT '023254-8' MATRICULA FROM DUAL UNION ALL
SELECT '023294-7' MATRICULA FROM DUAL UNION ALL
SELECT '023418-4' MATRICULA FROM DUAL UNION ALL
SELECT '023439-7' MATRICULA FROM DUAL UNION ALL
SELECT '023530-0' MATRICULA FROM DUAL UNION ALL
SELECT '023537-7' MATRICULA FROM DUAL UNION ALL
SELECT '023616-X' MATRICULA FROM DUAL UNION ALL
SELECT '023637-3' MATRICULA FROM DUAL UNION ALL
SELECT '023657-8' MATRICULA FROM DUAL UNION ALL
SELECT '023679-9' MATRICULA FROM DUAL UNION ALL
SELECT '023811-2' MATRICULA FROM DUAL UNION ALL
SELECT '023885-6' MATRICULA FROM DUAL UNION ALL
SELECT '023887-2' MATRICULA FROM DUAL UNION ALL
SELECT '023892-9' MATRICULA FROM DUAL UNION ALL
SELECT '024505-4' MATRICULA FROM DUAL UNION ALL
SELECT '024660-3' MATRICULA FROM DUAL UNION ALL
SELECT '024687-5' MATRICULA FROM DUAL UNION ALL
SELECT '024859-2' MATRICULA FROM DUAL UNION ALL
SELECT '024861-4' MATRICULA FROM DUAL UNION ALL
SELECT '024981-5' MATRICULA FROM DUAL UNION ALL
SELECT '025587-4' MATRICULA FROM DUAL UNION ALL
SELECT '025626-9' MATRICULA FROM DUAL UNION ALL
SELECT '025713-3' MATRICULA FROM DUAL UNION ALL
SELECT '025987-0' MATRICULA FROM DUAL UNION ALL
SELECT '026229-3' MATRICULA FROM DUAL UNION ALL
SELECT '026300-1' MATRICULA FROM DUAL UNION ALL
SELECT '026320-6' MATRICULA FROM DUAL UNION ALL
SELECT '026350-8' MATRICULA FROM DUAL UNION ALL
SELECT '026377-0' MATRICULA FROM DUAL UNION ALL
SELECT '026380-0' MATRICULA FROM DUAL UNION ALL
SELECT '026386-9' MATRICULA FROM DUAL UNION ALL
SELECT '026477-6' MATRICULA FROM DUAL UNION ALL
SELECT '026550-X' MATRICULA FROM DUAL UNION ALL
SELECT '026559-4' MATRICULA FROM DUAL UNION ALL
SELECT '026581-X' MATRICULA FROM DUAL UNION ALL
SELECT '026625-6' MATRICULA FROM DUAL UNION ALL
SELECT '026995-6' MATRICULA FROM DUAL UNION ALL
SELECT '027227-2' MATRICULA FROM DUAL UNION ALL
SELECT '030275-9' MATRICULA FROM DUAL UNION ALL
SELECT '030361-5' MATRICULA FROM DUAL UNION ALL
SELECT '030708-4' MATRICULA FROM DUAL UNION ALL
SELECT '035894-X' MATRICULA FROM DUAL UNION ALL
SELECT '036017-1' MATRICULA FROM DUAL UNION ALL
SELECT '036370-7' MATRICULA FROM DUAL UNION ALL
SELECT '036440-1' MATRICULA FROM DUAL UNION ALL
SELECT '036666-8' MATRICULA FROM DUAL UNION ALL
SELECT '036786-9' MATRICULA FROM DUAL UNION ALL
SELECT '036801-6' MATRICULA FROM DUAL UNION ALL
SELECT '036849-X' MATRICULA FROM DUAL UNION ALL
SELECT '036986-1' MATRICULA FROM DUAL UNION ALL
SELECT '037896-8' MATRICULA FROM DUAL UNION ALL
SELECT '038299-0' MATRICULA FROM DUAL UNION ALL
SELECT '038356-2' MATRICULA FROM DUAL UNION ALL
SELECT '038701-X' MATRICULA FROM DUAL UNION ALL
SELECT '038835-1' MATRICULA FROM DUAL UNION ALL
SELECT '038935-8' MATRICULA FROM DUAL UNION ALL
SELECT '038955-2' MATRICULA FROM DUAL UNION ALL
SELECT '039201-4' MATRICULA FROM DUAL UNION ALL
SELECT '039254-5' MATRICULA FROM DUAL UNION ALL
SELECT '039309-6' MATRICULA FROM DUAL UNION ALL
SELECT '039333-9' MATRICULA FROM DUAL UNION ALL
SELECT '039589-7' MATRICULA FROM DUAL UNION ALL
SELECT '039793-8' MATRICULA FROM DUAL UNION ALL
SELECT '040072-6' MATRICULA FROM DUAL UNION ALL
SELECT '040139-X' MATRICULA FROM DUAL UNION ALL
SELECT '040556-6' MATRICULA FROM DUAL UNION ALL
SELECT '040723-2' MATRICULA FROM DUAL UNION ALL
SELECT '040964-2' MATRICULA FROM DUAL UNION ALL
SELECT '041048-9' MATRICULA FROM DUAL UNION ALL
SELECT '041077-2' MATRICULA FROM DUAL UNION ALL
SELECT '041285-6' MATRICULA FROM DUAL UNION ALL
SELECT '042114-6' MATRICULA FROM DUAL UNION ALL
SELECT '042235-5' MATRICULA FROM DUAL UNION ALL
SELECT '042256-8' MATRICULA FROM DUAL UNION ALL
SELECT '042323-8' MATRICULA FROM DUAL UNION ALL
SELECT '042342-4' MATRICULA FROM DUAL UNION ALL
SELECT '042353-0' MATRICULA FROM DUAL UNION ALL
SELECT '042624-5' MATRICULA FROM DUAL UNION ALL
SELECT '042693-8' MATRICULA FROM DUAL UNION ALL
SELECT '042694-6' MATRICULA FROM DUAL UNION ALL
SELECT '042745-4' MATRICULA FROM DUAL UNION ALL
SELECT '042762-4' MATRICULA FROM DUAL UNION ALL
SELECT '042871-0' MATRICULA FROM DUAL UNION ALL
SELECT '043079-0' MATRICULA FROM DUAL UNION ALL
SELECT '043152-4' MATRICULA FROM DUAL UNION ALL
SELECT '043382-9' MATRICULA FROM DUAL UNION ALL
SELECT '043467-1' MATRICULA FROM DUAL UNION ALL
SELECT '043478-7' MATRICULA FROM DUAL UNION ALL
SELECT '043482-5' MATRICULA FROM DUAL UNION ALL
SELECT '043484-1' MATRICULA FROM DUAL UNION ALL
SELECT '043490-6' MATRICULA FROM DUAL UNION ALL
SELECT '043511-2' MATRICULA FROM DUAL UNION ALL
SELECT '043517-1' MATRICULA FROM DUAL UNION ALL
SELECT '043519-8' MATRICULA FROM DUAL UNION ALL
SELECT '043525-2' MATRICULA FROM DUAL UNION ALL
SELECT '043583-0' MATRICULA FROM DUAL UNION ALL
SELECT '043613-5' MATRICULA FROM DUAL UNION ALL
SELECT '043619-4' MATRICULA FROM DUAL UNION ALL
SELECT '043683-6' MATRICULA FROM DUAL UNION ALL
SELECT '044353-X' MATRICULA FROM DUAL UNION ALL
SELECT '044845-1' MATRICULA FROM DUAL UNION ALL
SELECT '044875-3' MATRICULA FROM DUAL UNION ALL
SELECT '044918-X' MATRICULA FROM DUAL UNION ALL
SELECT '045386-2' MATRICULA FROM DUAL UNION ALL
SELECT '045390-X' MATRICULA FROM DUAL UNION ALL
SELECT '045431-1' MATRICULA FROM DUAL UNION ALL
SELECT '045495-8' MATRICULA FROM DUAL UNION ALL
SELECT '047213-1' MATRICULA FROM DUAL UNION ALL
SELECT '050583-8' MATRICULA FROM DUAL UNION ALL
SELECT '051329-6' MATRICULA FROM DUAL UNION ALL
SELECT '052683-5' MATRICULA FROM DUAL UNION ALL
SELECT '055263-1' MATRICULA FROM DUAL UNION ALL
SELECT '058811-3' MATRICULA FROM DUAL UNION ALL
SELECT '059315-0' MATRICULA FROM DUAL UNION ALL
SELECT '059468-7' MATRICULA FROM DUAL UNION ALL
SELECT '060310-4' MATRICULA FROM DUAL UNION ALL
SELECT '061090-9' MATRICULA FROM DUAL UNION ALL
SELECT '061271-5' MATRICULA FROM DUAL UNION ALL
SELECT '062014-9' MATRICULA FROM DUAL UNION ALL
SELECT '064860-4' MATRICULA FROM DUAL UNION ALL
SELECT '065804-9' MATRICULA FROM DUAL UNION ALL
SELECT '066099-0' MATRICULA FROM DUAL UNION ALL
SELECT '066446-4' MATRICULA FROM DUAL UNION ALL
SELECT '066821-4' MATRICULA FROM DUAL UNION ALL
SELECT '067147-9' MATRICULA FROM DUAL UNION ALL
SELECT '068370-1' MATRICULA FROM DUAL UNION ALL
SELECT '068526-7' MATRICULA FROM DUAL UNION ALL
SELECT '068866-5' MATRICULA FROM DUAL UNION ALL
SELECT '069662-5' MATRICULA FROM DUAL UNION ALL
SELECT '069885-7' MATRICULA FROM DUAL UNION ALL
SELECT '070558-6' MATRICULA FROM DUAL UNION ALL
SELECT '070860-7' MATRICULA FROM DUAL UNION ALL
SELECT '071119-5' MATRICULA FROM DUAL UNION ALL
SELECT '073782-8' MATRICULA FROM DUAL UNION ALL
SELECT '073992-8' MATRICULA FROM DUAL UNION ALL
SELECT '074535-9' MATRICULA FROM DUAL UNION ALL
SELECT '075004-2' MATRICULA FROM DUAL UNION ALL
SELECT '075808-6' MATRICULA FROM DUAL UNION ALL
SELECT '076945-2' MATRICULA FROM DUAL UNION ALL
SELECT '077582-7' MATRICULA FROM DUAL UNION ALL
SELECT '077587-8' MATRICULA FROM DUAL UNION ALL
SELECT '077976-8' MATRICULA FROM DUAL UNION ALL
SELECT '083223-5' MATRICULA FROM DUAL UNION ALL
SELECT '083516-1' MATRICULA FROM DUAL UNION ALL
SELECT '084085-8' MATRICULA FROM DUAL UNION ALL
SELECT '084149-8' MATRICULA FROM DUAL UNION ALL
SELECT '085909-5' MATRICULA FROM DUAL UNION ALL
SELECT '088357-3' MATRICULA FROM DUAL UNION ALL
SELECT '089514-8' MATRICULA FROM DUAL UNION ALL
SELECT '089715-9' MATRICULA FROM DUAL UNION ALL
SELECT '091497-5' MATRICULA FROM DUAL UNION ALL
SELECT '091979-9' MATRICULA FROM DUAL UNION ALL
SELECT '091980-2' MATRICULA FROM DUAL UNION ALL
SELECT '092420-2' MATRICULA FROM DUAL UNION ALL
SELECT '092814-3' MATRICULA FROM DUAL UNION ALL
SELECT '100858-7' MATRICULA FROM DUAL UNION ALL
SELECT '100859-5' MATRICULA FROM DUAL UNION ALL
SELECT '101692-0' MATRICULA FROM DUAL UNION ALL
SELECT '102659-3' MATRICULA FROM DUAL UNION ALL
SELECT '103496-X' MATRICULA FROM DUAL UNION ALL
SELECT '103709-9' MATRICULA FROM DUAL UNION ALL
SELECT '105359-X' MATRICULA FROM DUAL UNION ALL
SELECT '108109-8' MATRICULA FROM DUAL UNION ALL
SELECT '111025-0' MATRICULA FROM DUAL UNION ALL
SELECT '129241-2' MATRICULA FROM DUAL UNION ALL
SELECT '135849-9' MATRICULA FROM DUAL UNION ALL
SELECT '159500-8' MATRICULA FROM DUAL UNION ALL
SELECT '159502-4' MATRICULA FROM DUAL UNION ALL
SELECT '159530-0' MATRICULA FROM DUAL UNION ALL
SELECT '159541-5' MATRICULA FROM DUAL UNION ALL
SELECT '159615-2' MATRICULA FROM DUAL UNION ALL
SELECT '159617-9' MATRICULA FROM DUAL UNION ALL
SELECT '159619-5' MATRICULA FROM DUAL UNION ALL
SELECT '159621-7' MATRICULA FROM DUAL UNION ALL
SELECT '159622-5' MATRICULA FROM DUAL UNION ALL
SELECT '159628-4' MATRICULA FROM DUAL UNION ALL
SELECT '159673-0' MATRICULA FROM DUAL UNION ALL
SELECT '161050-3' MATRICULA FROM DUAL UNION ALL
SELECT '162353-2' MATRICULA FROM DUAL UNION ALL
SELECT '162858-5' MATRICULA FROM DUAL UNION ALL
SELECT '163836-0' MATRICULA FROM DUAL UNION ALL
SELECT '163879-3' MATRICULA FROM DUAL UNION ALL
SELECT '163883-1' MATRICULA FROM DUAL UNION ALL
SELECT '164140-9' MATRICULA FROM DUAL UNION ALL
SELECT '164153-X' MATRICULA FROM DUAL UNION ALL
SELECT '164609-5' MATRICULA FROM DUAL UNION ALL
SELECT '165092-X' MATRICULA FROM DUAL UNION ALL
SELECT '165610-4' MATRICULA FROM DUAL UNION ALL
SELECT '168562-7' MATRICULA FROM DUAL UNION ALL
SELECT '170515-6' MATRICULA FROM DUAL UNION ALL
SELECT '170956-9' MATRICULA FROM DUAL UNION ALL
SELECT '171978-5' MATRICULA FROM DUAL UNION ALL
SELECT '172099-6' MATRICULA FROM DUAL UNION ALL
SELECT '177555-3' MATRICULA FROM DUAL UNION ALL
SELECT '177931-1' MATRICULA FROM DUAL UNION ALL
SELECT '178289-4' MATRICULA FROM DUAL UNION ALL
SELECT '178313-X' MATRICULA FROM DUAL UNION ALL
SELECT '178314-9' MATRICULA FROM DUAL UNION ALL
SELECT '178315-7' MATRICULA FROM DUAL UNION ALL
SELECT '178320-3' MATRICULA FROM DUAL UNION ALL
SELECT '178322-0' MATRICULA FROM DUAL UNION ALL
SELECT '178330-X' MATRICULA FROM DUAL UNION ALL
SELECT '178335-1' MATRICULA FROM DUAL UNION ALL
SELECT '178338-6' MATRICULA FROM DUAL UNION ALL
SELECT '178339-4' MATRICULA FROM DUAL UNION ALL
SELECT '178340-8' MATRICULA FROM DUAL UNION ALL
SELECT '180092-2' MATRICULA FROM DUAL UNION ALL
SELECT '180597-5' MATRICULA FROM DUAL UNION ALL
SELECT '189453-6' MATRICULA FROM DUAL UNION ALL
SELECT '189454-4' MATRICULA FROM DUAL UNION ALL
SELECT '193853-3' MATRICULA FROM DUAL UNION ALL
SELECT '213590-6' MATRICULA FROM DUAL UNION ALL
SELECT '230546-1' MATRICULA FROM DUAL UNION ALL
SELECT '235237-X' MATRICULA FROM DUAL UNION ALL
SELECT '243695-7' MATRICULA FROM DUAL UNION ALL
SELECT '244001-6' MATRICULA FROM DUAL UNION ALL
SELECT '247303-8' MATRICULA FROM DUAL UNION ALL
SELECT '279051-3' MATRICULA FROM DUAL UNION ALL
SELECT '280384-4' MATRICULA FROM DUAL UNION ALL
SELECT '282909-6' MATRICULA FROM DUAL UNION ALL
SELECT '289294-4' MATRICULA FROM DUAL UNION ALL
SELECT '296501-1' MATRICULA FROM DUAL UNION ALL
SELECT '303170-5' MATRICULA FROM DUAL UNION ALL
SELECT '327246-0' MATRICULA FROM DUAL UNION ALL
SELECT '359470-0' MATRICULA FROM DUAL UNION ALL
SELECT '371339-3' MATRICULA FROM DUAL UNION ALL
SELECT '373189-8' MATRICULA FROM DUAL UNION ALL
SELECT '373562-1' MATRICULA FROM DUAL UNION ALL
SELECT '373568-X' MATRICULA FROM DUAL UNION ALL
SELECT '373647-4' MATRICULA FROM DUAL UNION ALL
SELECT '373804-3' MATRICULA FROM DUAL UNION ALL
SELECT '373909-X' MATRICULA FROM DUAL UNION ALL
SELECT '374523-6' MATRICULA FROM DUAL UNION ALL
SELECT '376355-2' MATRICULA FROM DUAL UNION ALL
SELECT '378248-4' MATRICULA FROM DUAL UNION ALL
SELECT '378301-4' MATRICULA FROM DUAL UNION ALL
SELECT '381093-3' MATRICULA FROM DUAL UNION ALL
SELECT '411197-4' MATRICULA FROM DUAL UNION ALL
SELECT '414072-9' MATRICULA FROM DUAL UNION ALL
SELECT '414098-2' MATRICULA FROM DUAL UNION ALL
SELECT '414099-X' MATRICULA FROM DUAL UNION ALL
SELECT '418047-0' MATRICULA FROM DUAL UNION ALL
SELECT '420326-7' MATRICULA FROM DUAL UNION ALL
SELECT '420331-3' MATRICULA FROM DUAL UNION ALL
SELECT '429392-4' MATRICULA FROM DUAL UNION ALL
SELECT '434055-8' MATRICULA FROM DUAL UNION ALL
SELECT '438669-8' MATRICULA FROM DUAL UNION ALL
SELECT '438721-0' MATRICULA FROM DUAL UNION ALL
SELECT '439835-1' MATRICULA FROM DUAL UNION ALL
SELECT '439908-X' MATRICULA FROM DUAL
)
SELECT 
    'EMPRESA' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_EMPRESA.PESSOA_VINCULO PV
    JOIN SW_EMPRESA.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_EMPRESA.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_EMPRESA.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'CBMPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_CBMPI.PESSOA_VINCULO PV
    JOIN SW_CBMPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_CBMPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_CBMPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'PGEPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_PGEPI.PESSOA_VINCULO PV
    JOIN SW_PGEPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_PGEPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_PGEPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'CGEPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_CGEPI.PESSOA_VINCULO PV
    JOIN SW_CGEPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_CGEPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_CGEPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SSPPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_SSPPI.PESSOA_VINCULO PV
    JOIN SW_SSPPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SSPPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SSPPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'COJUV' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_COJUV.PESSOA_VINCULO PV
    JOIN SW_COJUV.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_COJUV.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_COJUV.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'ATIPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_ATIPI.PESSOA_VINCULO PV
    JOIN SW_ATIPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_ATIPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_ATIPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'FAPEPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_FAPEPI.PESSOA_VINCULO PV
    JOIN SW_FAPEPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_FAPEPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_FAPEPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'DEFCIVIL' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_DEFCIVIL.PESSOA_VINCULO PV
    JOIN SW_DEFCIVIL.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_DEFCIVIL.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_DEFCIVIL.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'ADH' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_ADH.PESSOA_VINCULO PV
    JOIN SW_ADH.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_ADH.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_ADH.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SEAGRO' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_SEAGRO.PESSOA_VINCULO PV
    JOIN SW_SEAGRO.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SEAGRO.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SEAGRO.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'IDEPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_IDEPI.PESSOA_VINCULO PV
    JOIN SW_IDEPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_IDEPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_IDEPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SURPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_SURPI.PESSOA_VINCULO PV
    JOIN SW_SURPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SURPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SURPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SEID' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_SEID.PESSOA_VINCULO PV
    JOIN SW_SEID.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SEID.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SEID.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SECID' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_SECID.PESSOA_VINCULO PV
    JOIN SW_SECID.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SECID.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SECID.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'FUPIP' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_FUPIP.PESSOA_VINCULO PV
    JOIN SW_FUPIP.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_FUPIP.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_FUPIP.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SETUR' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_SETUR.PESSOA_VINCULO PV
    JOIN SW_SETUR.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SETUR.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SETUR.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'AGESPISA' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_AGESPISA.PESSOA_VINCULO PV
    JOIN SW_AGESPISA.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_AGESPISA.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_AGESPISA.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SETRANS' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_SETRANS.PESSOA_VINCULO PV
    JOIN SW_SETRANS.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SETRANS.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SETRANS.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'TVANTARES' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_TVANTARES.PESSOA_VINCULO PV
    JOIN SW_TVANTARES.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_TVANTARES.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_TVANTARES.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'VICEGOV' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_VICEGOV.PESSOA_VINCULO PV
    JOIN SW_VICEGOV.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_VICEGOV.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_VICEGOV.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SEINFRA' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_SEINFRA.PESSOA_VINCULO PV
    JOIN SW_SEINFRA.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SEINFRA.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SEINFRA.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'CCOM' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_CCOM.PESSOA_VINCULO PV
    JOIN SW_CCOM.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_CCOM.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_CCOM.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'FUNDESPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_FUNDESPI.PESSOA_VINCULO PV
    JOIN SW_FUNDESPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_FUNDESPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_FUNDESPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SEDET' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_SEDET.PESSOA_VINCULO PV
    JOIN SW_SEDET.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SEDET.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SEDET.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'INTERPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_INTERPI.PESSOA_VINCULO PV
    JOIN SW_INTERPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_INTERPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_INTERPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'JUCEPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_JUCEPI.PESSOA_VINCULO PV
    JOIN SW_JUCEPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_JUCEPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_JUCEPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SEMAR' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_SEMAR.PESSOA_VINCULO PV
    JOIN SW_SEMAR.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SEMAR.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SEMAR.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'GMG' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_GMG.PESSOA_VINCULO PV
    JOIN SW_GMG.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_GMG.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_GMG.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SEPLAN' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_SEPLAN.PESSOA_VINCULO PV
    JOIN SW_SEPLAN.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SEPLAN.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SEPLAN.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SAF' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_SAF.PESSOA_VINCULO PV
    JOIN SW_SAF.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SAF.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SAF.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SECULT' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_SECULT.PESSOA_VINCULO PV
    JOIN SW_SECULT.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SECULT.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SECULT.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'DER' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_DER.PESSOA_VINCULO PV
    JOIN SW_DER.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_DER.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_DER.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'DETRAN' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_DETRAN.PESSOA_VINCULO PV
    JOIN SW_DETRAN.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_DETRAN.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_DETRAN.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'IASPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_IASPI.PESSOA_VINCULO PV
    JOIN SW_IASPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_IASPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_IASPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'ADAPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_ADAPI.PESSOA_VINCULO PV
    JOIN SW_ADAPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_ADAPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_ADAPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'IMEPIPROD' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_IMEPIPROD.PESSOA_VINCULO PV
    JOIN SW_IMEPIPROD.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_IMEPIPROD.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_IMEPIPROD.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'CPVCI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_CPVCI.PESSOA_VINCULO PV
    JOIN SW_CPVCI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_CPVCI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_CPVCI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'CENDROGAS' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_CENDROGAS.PESSOA_VINCULO PV
    JOIN SW_CENDROGAS.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_CENDROGAS.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_CENDROGAS.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'COFIR' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_COFIR.PESSOA_VINCULO PV
    JOIN SW_COFIR.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_COFIR.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_COFIR.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SEMINPER' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_SEMINPER.PESSOA_VINCULO PV
    JOIN SW_SEMINPER.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SEMINPER.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SEMINPER.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'AGRESP' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_AGRESP.PESSOA_VINCULO PV
    JOIN SW_AGRESP.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_AGRESP.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_AGRESP.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'CEPM' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_CEPM.PESSOA_VINCULO PV
    JOIN SW_CEPM.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_CEPM.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_CEPM.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'EMATER' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_EMATER.PESSOA_VINCULO PV
    JOIN SW_EMATER.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_EMATER.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_EMATER.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'FUESPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_FUESPI.PESSOA_VINCULO PV
    JOIN SW_FUESPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_FUESPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_FUESPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'EMATERPROD' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_EMATERPROD.PESSOA_VINCULO PV
    JOIN SW_EMATERPROD.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_EMATERPROD.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_EMATERPROD.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'DEFENSORIA' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_DEFENSORIA.PESSOA_VINCULO PV
    JOIN SW_DEFENSORIA.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_DEFENSORIA.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_DEFENSORIA.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'PENSIONISTAS' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_PENSIONISTAS.PESSOA_VINCULO PV
    JOIN SW_PENSIONISTAS.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_PENSIONISTAS.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_PENSIONISTAS.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'CDTER' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_CDTER.PESSOA_VINCULO PV
    JOIN SW_CDTER.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_CDTER.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_CDTER.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SERES' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_SERES.PESSOA_VINCULO PV
    JOIN SW_SERES.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SERES.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SERES.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SECESP' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_SECESP.PESSOA_VINCULO PV
    JOIN SW_SECESP.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SECESP.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SECESP.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'INATIVOS_PENSIONISTAS' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_INATIVOS_PENSIONISTAS.PESSOA_VINCULO PV
    JOIN SW_INATIVOS_PENSIONISTAS.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_INATIVOS_PENSIONISTAS.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_INATIVOS_PENSIONISTAS.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SEDUC_PRECATORIO' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_SEDUC_PRECATORIO.PESSOA_VINCULO PV
    JOIN SW_SEDUC_PRECATORIO.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SEDUC_PRECATORIO.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SEDUC_PRECATORIO.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'EMGERPI_CORESA' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_EMGERPI_CORESA.PESSOA_VINCULO PV
    JOIN SW_EMGERPI_CORESA.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_EMGERPI_CORESA.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_EMGERPI_CORESA.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'FUNPREV' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_FUNPREV.PESSOA_VINCULO PV
    JOIN SW_FUNPREV.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_FUNPREV.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_FUNPREV.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'FESPPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_FESPPI.PESSOA_VINCULO PV
    JOIN SW_FESPPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_FESPPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_FESPPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SIA' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_SIA.PESSOA_VINCULO PV
    JOIN SW_SIA.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SIA.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SIA.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SETRE' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_SETRE.PESSOA_VINCULO PV
    JOIN SW_SETRE.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SETRE.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SETRE.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'AGESPISA02' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_AGESPISA02.PESSOA_VINCULO PV
    JOIN SW_AGESPISA02.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_AGESPISA02.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_AGESPISA02.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SEGOV' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_SEGOV.PESSOA_VINCULO PV
    JOIN SW_SEGOV.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SEGOV.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SEGOV.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SASC' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_SASC.PESSOA_VINCULO PV
    JOIN SW_SASC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SASC.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SASC.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'METRO' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_METRO.PESSOA_VINCULO PV
    JOIN SW_METRO.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_METRO.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_METRO.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'PIAUIPREV' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_PIAUIPREV.PESSOA_VINCULO PV
    JOIN SW_PIAUIPREV.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_PIAUIPREV.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_PIAUIPREV.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'INATIVOS_SEDUC' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_INATIVOS_SEDUC.PESSOA_VINCULO PV
    JOIN SW_INATIVOS_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_INATIVOS_SEDUC.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_INATIVOS_SEDUC.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'INATIVOS_TCE' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_INATIVOS_TCE.PESSOA_VINCULO PV
    JOIN SW_INATIVOS_TCE.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_INATIVOS_TCE.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_INATIVOS_TCE.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SADA' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_SADA.PESSOA_VINCULO PV
    JOIN SW_SADA.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SADA.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SADA.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SECMULHERES' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_SECMULHERES.PESSOA_VINCULO PV
    JOIN SW_SECMULHERES.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SECMULHERES.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SECMULHERES.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'EMGERPI_EMATER' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_EMGERPI_EMATER.PESSOA_VINCULO PV
    JOIN SW_EMGERPI_EMATER.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_EMGERPI_EMATER.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_EMGERPI_EMATER.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'REENVIO' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_REENVIO.PESSOA_VINCULO PV
    JOIN SW_REENVIO.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_REENVIO.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_REENVIO.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SESAPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_SESAPI.PESSOA_VINCULO PV
    JOIN SW_SESAPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SESAPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SESAPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'PMPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_PMPI.PESSOA_VINCULO PV
    JOIN SW_PMPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_PMPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_PMPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SEJUSPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_SEJUSPI.PESSOA_VINCULO PV
    JOIN SW_SEJUSPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SEJUSPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SEJUSPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SEFAZPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_SEFAZPI.PESSOA_VINCULO PV
    JOIN SW_SEFAZPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SEFAZPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SEFAZPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SEADPREVPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_SEADPREVPI.PESSOA_VINCULO PV
    JOIN SW_SEADPREVPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SEADPREVPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SEADPREVPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'IMEPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_IMEPI.PESSOA_VINCULO PV
    JOIN SW_IMEPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_IMEPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_IMEPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'BEP' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_BEP.PESSOA_VINCULO PV
    JOIN SW_BEP.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_BEP.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_BEP.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'EMGERPI_COMEPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_EMGERPI_COMEPI.PESSOA_VINCULO PV
    JOIN SW_EMGERPI_COMEPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_EMGERPI_COMEPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_EMGERPI_COMEPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'EMGERPI_COMDEPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_EMGERPI_COMDEPI.PESSOA_VINCULO PV
    JOIN SW_EMGERPI_COMDEPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_EMGERPI_COMDEPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_EMGERPI_COMDEPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'EMGERPI_COHAB' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_EMGERPI_COHAB.PESSOA_VINCULO PV
    JOIN SW_EMGERPI_COHAB.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_EMGERPI_COHAB.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_EMGERPI_COHAB.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'EMGERPI_PRODEPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_EMGERPI_PRODEPI.PESSOA_VINCULO PV
    JOIN SW_EMGERPI_PRODEPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_EMGERPI_PRODEPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_EMGERPI_PRODEPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'EMGERPI_CEASA' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_EMGERPI_CEASA.PESSOA_VINCULO PV
    JOIN SW_EMGERPI_CEASA.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_EMGERPI_CEASA.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_EMGERPI_CEASA.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'EMGERPI_PIEMTUR' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_EMGERPI_PIEMTUR.PESSOA_VINCULO PV
    JOIN SW_EMGERPI_PIEMTUR.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_EMGERPI_PIEMTUR.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_EMGERPI_PIEMTUR.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'EMGERPI_ETELPI_FUNART' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_EMGERPI_ETELPI_FUNART.PESSOA_VINCULO PV
    JOIN SW_EMGERPI_ETELPI_FUNART.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_EMGERPI_ETELPI_FUNART.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_EMGERPI_ETELPI_FUNART.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'EMGERPI_CIDAPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_EMGERPI_CIDAPI.PESSOA_VINCULO PV
    JOIN SW_EMGERPI_CIDAPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_EMGERPI_CIDAPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_EMGERPI_CIDAPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'SEDUC' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_SEDUC.PESSOA_VINCULO PV
    JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SEDUC.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SEDUC.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'EMGERPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_EMGERPI.PESSOA_VINCULO PV
    JOIN SW_EMGERPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_EMGERPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_EMGERPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
UNION ALL
SELECT 
    'EMGERPI_CODIPI' ORGAO,
    PV.COD_INSTITUCIONAL,
    PC.CPF_PESSOA,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO
FROM
    SW_EMGERPI_CODIPI.PESSOA_VINCULO PV
    JOIN SW_EMGERPI_CODIPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_EMGERPI_CODIPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_EMGERPI_CODIPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN VALORES V ON V.MATRICULA = PV.COD_INSTITUCIONAL
;