WITH ATIVOS AS (
    SELECT DISTINCT
        'ADAPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_ADAPI.FOLHA FO
        JOIN SW_ADAPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_ADAPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'ADH' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_ADH.FOLHA FO
        JOIN SW_ADH.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_ADH.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'AGESPISA' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_AGESPISA.FOLHA FO
        JOIN SW_AGESPISA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_AGESPISA.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'AGESPISA02' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_AGESPISA02.FOLHA FO
        JOIN SW_AGESPISA02.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_AGESPISA02.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'AGRESP' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_AGRESP.FOLHA FO
        JOIN SW_AGRESP.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_AGRESP.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'BEP' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_BEP.FOLHA FO
        JOIN SW_BEP.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_BEP.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'CBMPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_CBMPI.FOLHA FO
        JOIN SW_CBMPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_CBMPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'CCOM' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_CCOM.FOLHA FO
        JOIN SW_CCOM.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_CCOM.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'CDTER' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_CDTER.FOLHA FO
        JOIN SW_CDTER.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_CDTER.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'CENDROGAS' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_CENDROGAS.FOLHA FO
        JOIN SW_CENDROGAS.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_CENDROGAS.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'COFIR' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_COFIR.FOLHA FO
        JOIN SW_COFIR.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_COFIR.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'COJUV' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_COJUV.FOLHA FO
        JOIN SW_COJUV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_COJUV.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'DEFCIVIL' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_DEFCIVIL.FOLHA FO
        JOIN SW_DEFCIVIL.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_DEFCIVIL.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'DER' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_DER.FOLHA FO
        JOIN SW_DER.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_DER.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'DETRAN' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_DETRAN.FOLHA FO
        JOIN SW_DETRAN.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_DETRAN.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'EMGERPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_EMGERPI.FOLHA FO
        JOIN SW_EMGERPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'EMGERPI_CEASA' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_EMGERPI_CEASA.FOLHA FO
        JOIN SW_EMGERPI_CEASA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_CEASA.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'EMGERPI_CIDAPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_EMGERPI_CIDAPI.FOLHA FO
        JOIN SW_EMGERPI_CIDAPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_CIDAPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'EMGERPI_CODIPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_EMGERPI_CODIPI.FOLHA FO
        JOIN SW_EMGERPI_CODIPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_CODIPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'EMGERPI_COHAB' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_EMGERPI_COHAB.FOLHA FO
        JOIN SW_EMGERPI_COHAB.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_COHAB.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'EMGERPI_COMDEPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_EMGERPI_COMDEPI.FOLHA FO
        JOIN SW_EMGERPI_COMDEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_COMDEPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'EMGERPI_COMEPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_EMGERPI_COMEPI.FOLHA FO
        JOIN SW_EMGERPI_COMEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_COMEPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'EMGERPI_CORESA' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_EMGERPI_CORESA.FOLHA FO
        JOIN SW_EMGERPI_CORESA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_CORESA.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'EMGERPI_EMATER' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_EMGERPI_EMATER.FOLHA FO
        JOIN SW_EMGERPI_EMATER.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_EMATER.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'EMGERPI_ETELPI_FUNART' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_EMGERPI_ETELPI_FUNART.FOLHA FO
        JOIN SW_EMGERPI_ETELPI_FUNART.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_ETELPI_FUNART.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'EMGERPI_PIEMTUR' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_EMGERPI_PIEMTUR.FOLHA FO
        JOIN SW_EMGERPI_PIEMTUR.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_PIEMTUR.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'EMGERPI_PRODEPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_EMGERPI_PRODEPI.FOLHA FO
        JOIN SW_EMGERPI_PRODEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_PRODEPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'FAPEPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_FAPEPI.FOLHA FO
        JOIN SW_FAPEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_FAPEPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'FESPPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_FESPPI.FOLHA FO
        JOIN SW_FESPPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_FESPPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'FUESPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_FUESPI.FOLHA FO
        JOIN SW_FUESPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_FUESPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'FUPIP' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_FUPIP.FOLHA FO
        JOIN SW_FUPIP.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_FUPIP.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'GMG' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_GMG.FOLHA FO
        JOIN SW_GMG.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_GMG.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'IASPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_IASPI.FOLHA FO
        JOIN SW_IASPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_IASPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'IDEPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_IDEPI.FOLHA FO
        JOIN SW_IDEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_IDEPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'IMEPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_IMEPI.FOLHA FO
        JOIN SW_IMEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_IMEPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'IMEPIPROD' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_IMEPIPROD.FOLHA FO
        JOIN SW_IMEPIPROD.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_IMEPIPROD.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'INTERPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_INTERPI.FOLHA FO
        JOIN SW_INTERPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_INTERPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'JUCEPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_JUCEPI.FOLHA FO
        JOIN SW_JUCEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_JUCEPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'METRO' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_METRO.FOLHA FO
        JOIN SW_METRO.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_METRO.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'PGEPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_PGEPI.FOLHA FO
        JOIN SW_PGEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_PGEPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'PMPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_PMPI.FOLHA FO
        JOIN SW_PMPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_PMPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'SADA' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_SADA.FOLHA FO
        JOIN SW_SADA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SADA.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'SAF' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_SAF.FOLHA FO
        JOIN SW_SAF.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SAF.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'SASC' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_SASC.FOLHA FO
        JOIN SW_SASC.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SASC.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'SEADPREVPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_SEADPREVPI.FOLHA FO
        JOIN SW_SEADPREVPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEADPREVPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'SEAGRO' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_SEAGRO.FOLHA FO
        JOIN SW_SEAGRO.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEAGRO.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'SECESP' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_SECESP.FOLHA FO
        JOIN SW_SECESP.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SECESP.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'SECID' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_SECID.FOLHA FO
        JOIN SW_SECID.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SECID.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'SECMULHERES' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_SECMULHERES.FOLHA FO
        JOIN SW_SECMULHERES.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SECMULHERES.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'SECULT' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_SECULT.FOLHA FO
        JOIN SW_SECULT.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SECULT.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'SEDET' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_SEDET.FOLHA FO
        JOIN SW_SEDET.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEDET.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'SEDUC' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_SEDUC.FOLHA FO
        JOIN SW_SEDUC.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEDUC.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'SEFAZPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_SEFAZPI.FOLHA FO
        JOIN SW_SEFAZPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEFAZPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'SEGOV' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_SEGOV.FOLHA FO
        JOIN SW_SEGOV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEGOV.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'SEID' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_SEID.FOLHA FO
        JOIN SW_SEID.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEID.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'SEINFRA' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_SEINFRA.FOLHA FO
        JOIN SW_SEINFRA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEINFRA.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'SEJUSPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_SEJUSPI.FOLHA FO
        JOIN SW_SEJUSPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEJUSPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'SEMAR' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_SEMAR.FOLHA FO
        JOIN SW_SEMAR.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEMAR.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'SEMINPER' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_SEMINPER.FOLHA FO
        JOIN SW_SEMINPER.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEMINPER.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'SEPLAN' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_SEPLAN.FOLHA FO
        JOIN SW_SEPLAN.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEPLAN.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'SERES' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_SERES.FOLHA FO
        JOIN SW_SERES.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SERES.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'SESAPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_SESAPI.FOLHA FO
        JOIN SW_SESAPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SESAPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'SETRANS' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_SETRANS.FOLHA FO
        JOIN SW_SETRANS.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SETRANS.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'SETRE' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_SETRE.FOLHA FO
        JOIN SW_SETRE.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SETRE.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'SETUR' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_SETUR.FOLHA FO
        JOIN SW_SETUR.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SETUR.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'SIA' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_SIA.FOLHA FO
        JOIN SW_SIA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SIA.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'SSPPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_SSPPI.FOLHA FO
        JOIN SW_SSPPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SSPPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'SURPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_SURPI.FOLHA FO
        JOIN SW_SURPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SURPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'TVANTARES' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_TVANTARES.FOLHA FO
        JOIN SW_TVANTARES.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_TVANTARES.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025

UNION ALL

SELECT DISTINCT
        'VICEGOV' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(TO_DATE(FO.ANO || '1231', 'RRRRMMDD'), P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM SW_VICEGOV.FOLHA FO
        JOIN SW_VICEGOV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_VICEGOV.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    WHERE FI.ID_REGIME = 2
        AND FS.ID_SEXO = 2
        AND FO.ANO BETWEEN 2014 AND 2025
),
ORGAOS AS (
    SELECT DISTINCT ORGAO FROM ATIVOS
),
IDADES AS (
    SELECT LEVEL - 1 AS IDADE
    FROM DUAL
    CONNECT BY LEVEL <= 106
)
SELECT
    O.ORGAO,
    I.IDADE,
    COUNT(CASE WHEN A.ANO = 2025 THEN 1 END) AS "2025",
    COUNT(CASE WHEN A.ANO = 2024 THEN 1 END) AS "2024",
    COUNT(CASE WHEN A.ANO = 2023 THEN 1 END) AS "2023",
    COUNT(CASE WHEN A.ANO = 2022 THEN 1 END) AS "2022",
    COUNT(CASE WHEN A.ANO = 2021 THEN 1 END) AS "2021",
    COUNT(CASE WHEN A.ANO = 2020 THEN 1 END) AS "2020",
    COUNT(CASE WHEN A.ANO = 2019 THEN 1 END) AS "2019",
    COUNT(CASE WHEN A.ANO = 2018 THEN 1 END) AS "2018",
    COUNT(CASE WHEN A.ANO = 2017 THEN 1 END) AS "2017",
    COUNT(CASE WHEN A.ANO = 2016 THEN 1 END) AS "2016",
    COUNT(CASE WHEN A.ANO = 2015 THEN 1 END) AS "2015",
    COUNT(CASE WHEN A.ANO = 2014 THEN 1 END) AS "2014"
FROM
    ORGAOS O
    CROSS JOIN IDADES I
    LEFT JOIN ATIVOS A ON A.ORGAO = O.ORGAO AND A.IDADE = I.IDADE
GROUP BY
    O.ORGAO, I.IDADE
ORDER BY
    O.ORGAO, I.IDADE;