WITH APOSENTADORIA_INVALIDEZ AS (
    SELECT DISTINCT
        'SW_ADAPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_ADAPI.FOLHA FO
        JOIN SW_ADAPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_ADAPI.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_ADH' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_ADH.FOLHA FO
        JOIN SW_ADH.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_ADH.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_AGESPISA' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_AGESPISA.FOLHA FO
        JOIN SW_AGESPISA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_AGESPISA.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_AGESPISA02' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_AGESPISA02.FOLHA FO
        JOIN SW_AGESPISA02.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_AGESPISA02.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_AGRESP' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_AGRESP.FOLHA FO
        JOIN SW_AGRESP.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_AGRESP.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_BEP' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_BEP.FOLHA FO
        JOIN SW_BEP.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_BEP.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_CBMPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_CBMPI.FOLHA FO
        JOIN SW_CBMPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_CBMPI.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_CCOM' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_CCOM.FOLHA FO
        JOIN SW_CCOM.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_CCOM.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_CDTER' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_CDTER.FOLHA FO
        JOIN SW_CDTER.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_CDTER.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_CENDROGAS' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_CENDROGAS.FOLHA FO
        JOIN SW_CENDROGAS.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_CENDROGAS.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_COFIR' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_COFIR.FOLHA FO
        JOIN SW_COFIR.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_COFIR.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_COJUV' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_COJUV.FOLHA FO
        JOIN SW_COJUV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_COJUV.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_DEFCIVIL' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_DEFCIVIL.FOLHA FO
        JOIN SW_DEFCIVIL.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_DEFCIVIL.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_DER' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_DER.FOLHA FO
        JOIN SW_DER.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_DER.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_DETRAN' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_DETRAN.FOLHA FO
        JOIN SW_DETRAN.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_DETRAN.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_EMGERPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_EMGERPI.FOLHA FO
        JOIN SW_EMGERPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_EMGERPI_CEASA' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_EMGERPI_CEASA.FOLHA FO
        JOIN SW_EMGERPI_CEASA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_CEASA.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_EMGERPI_CIDAPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_EMGERPI_CIDAPI.FOLHA FO
        JOIN SW_EMGERPI_CIDAPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_CIDAPI.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_EMGERPI_CODIPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_EMGERPI_CODIPI.FOLHA FO
        JOIN SW_EMGERPI_CODIPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_CODIPI.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_EMGERPI_COHAB' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_EMGERPI_COHAB.FOLHA FO
        JOIN SW_EMGERPI_COHAB.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_COHAB.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_EMGERPI_COMDEPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_EMGERPI_COMDEPI.FOLHA FO
        JOIN SW_EMGERPI_COMDEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_COMDEPI.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_EMGERPI_COMEPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_EMGERPI_COMEPI.FOLHA FO
        JOIN SW_EMGERPI_COMEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_COMEPI.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_EMGERPI_CORESA' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_EMGERPI_CORESA.FOLHA FO
        JOIN SW_EMGERPI_CORESA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_CORESA.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_EMGERPI_EMATER' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_EMGERPI_EMATER.FOLHA FO
        JOIN SW_EMGERPI_EMATER.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_EMATER.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_EMGERPI_ETELPI_FUNART' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_EMGERPI_ETELPI_FUNART.FOLHA FO
        JOIN SW_EMGERPI_ETELPI_FUNART.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_ETELPI_FUNART.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_EMGERPI_PIEMTUR' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_EMGERPI_PIEMTUR.FOLHA FO
        JOIN SW_EMGERPI_PIEMTUR.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_PIEMTUR.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_EMGERPI_PRODEPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_EMGERPI_PRODEPI.FOLHA FO
        JOIN SW_EMGERPI_PRODEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_PRODEPI.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_FAPEPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_FAPEPI.FOLHA FO
        JOIN SW_FAPEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_FAPEPI.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_FESPPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_FESPPI.FOLHA FO
        JOIN SW_FESPPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_FESPPI.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_FUESPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_FUESPI.FOLHA FO
        JOIN SW_FUESPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_FUESPI.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_FUPIP' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_FUPIP.FOLHA FO
        JOIN SW_FUPIP.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_FUPIP.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_GMG' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_GMG.FOLHA FO
        JOIN SW_GMG.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_GMG.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_IASPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_IASPI.FOLHA FO
        JOIN SW_IASPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_IASPI.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_IDEPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_IDEPI.FOLHA FO
        JOIN SW_IDEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_IDEPI.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_IMEPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_IMEPI.FOLHA FO
        JOIN SW_IMEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_IMEPI.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_IMEPIPROD' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_IMEPIPROD.FOLHA FO
        JOIN SW_IMEPIPROD.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_IMEPIPROD.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_INTERPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_INTERPI.FOLHA FO
        JOIN SW_INTERPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_INTERPI.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_JUCEPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_JUCEPI.FOLHA FO
        JOIN SW_JUCEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_JUCEPI.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_METRO' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_METRO.FOLHA FO
        JOIN SW_METRO.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_METRO.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_PGEPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_PGEPI.FOLHA FO
        JOIN SW_PGEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_PGEPI.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_PMPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_PMPI.FOLHA FO
        JOIN SW_PMPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_PMPI.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_SADA' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_SADA.FOLHA FO
        JOIN SW_SADA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SADA.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_SAF' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_SAF.FOLHA FO
        JOIN SW_SAF.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SAF.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_SASC' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_SASC.FOLHA FO
        JOIN SW_SASC.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SASC.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_SEADPREVPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_SEADPREVPI.FOLHA FO
        JOIN SW_SEADPREVPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEADPREVPI.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_SEAGRO' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_SEAGRO.FOLHA FO
        JOIN SW_SEAGRO.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEAGRO.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_SECESP' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_SECESP.FOLHA FO
        JOIN SW_SECESP.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SECESP.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_SECID' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_SECID.FOLHA FO
        JOIN SW_SECID.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SECID.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_SECMULHERES' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_SECMULHERES.FOLHA FO
        JOIN SW_SECMULHERES.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SECMULHERES.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_SECULT' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_SECULT.FOLHA FO
        JOIN SW_SECULT.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SECULT.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_SEDET' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_SEDET.FOLHA FO
        JOIN SW_SEDET.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEDET.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_SEDUC' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_SEDUC.FOLHA FO
        JOIN SW_SEDUC.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEDUC.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_SEFAZPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_SEFAZPI.FOLHA FO
        JOIN SW_SEFAZPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEFAZPI.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_SEGOV' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_SEGOV.FOLHA FO
        JOIN SW_SEGOV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEGOV.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_SEID' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_SEID.FOLHA FO
        JOIN SW_SEID.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEID.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_SEINFRA' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_SEINFRA.FOLHA FO
        JOIN SW_SEINFRA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEINFRA.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_SEJUSPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_SEJUSPI.FOLHA FO
        JOIN SW_SEJUSPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEJUSPI.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_SEMAR' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_SEMAR.FOLHA FO
        JOIN SW_SEMAR.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEMAR.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_SEMINPER' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_SEMINPER.FOLHA FO
        JOIN SW_SEMINPER.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEMINPER.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_SEPLAN' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_SEPLAN.FOLHA FO
        JOIN SW_SEPLAN.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEPLAN.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_SERES' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_SERES.FOLHA FO
        JOIN SW_SERES.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SERES.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_SESAPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_SESAPI.FOLHA FO
        JOIN SW_SESAPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SESAPI.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_SETRANS' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_SETRANS.FOLHA FO
        JOIN SW_SETRANS.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SETRANS.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_SETRE' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_SETRE.FOLHA FO
        JOIN SW_SETRE.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SETRE.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_SETUR' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_SETUR.FOLHA FO
        JOIN SW_SETUR.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SETUR.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_SIA' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_SIA.FOLHA FO
        JOIN SW_SIA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SIA.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_SSPPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_SSPPI.FOLHA FO
        JOIN SW_SSPPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SSPPI.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_SURPI' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_SURPI.FOLHA FO
        JOIN SW_SURPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SURPI.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_TVANTARES' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_TVANTARES.FOLHA FO
        JOIN SW_TVANTARES.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_TVANTARES.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)

UNION ALL

    SELECT DISTINCT
        'SW_VICEGOV' AS ORGAO,
        FO.ANO,
        FF.ID_FUNCIONARIO,
        FLOOR(MONTHS_BETWEEN(FA.DATA_APOSENTADORIA, P.DATA_NASCIMENTO) / 12) AS IDADE
    FROM 
        SW_VICEGOV.FOLHA FO
        JOIN SW_VICEGOV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_VICEGOV.FOLHA_FUNC_RUBRICA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
        JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT FA ON FA.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
        JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
        JOIN SW_PUBLICO.RHB_APOSENTADORIA A ON A.ID_TIPO_APOSENTADORIA = FA.ID_TIPO_APOSENTADORIA
    WHERE 
        R.COD_RUBRICA = 620000
        AND FA.DATA_APOSENTADORIA IS NOT NULL
        AND EXTRACT(YEAR FROM FA.DATA_APOSENTADORIA) = FO.ANO
        AND FO.ANO BETWEEN 2020 AND 2025
        AND FS.ID_SEXO = 2 -- 1 masculino / 2 feminino
        AND A.ID_TIPO_APOSENTADORIA IN (27,34,1000007,13,6,19,57,11,5,50)
),
ORGAOS AS (
    SELECT DISTINCT ORGAO FROM APOSENTADORIA_INVALIDEZ
),
IDADES AS (
    SELECT LEVEL - 1 AS IDADE
    FROM DUAL
    CONNECT BY LEVEL <= 106
)
SELECT
    ORG.ORGAO,
    I.IDADE,
    COUNT(CASE WHEN AI.ANO = 2025 THEN 1 END) AS "2025",
    COUNT(CASE WHEN AI.ANO = 2024 THEN 1 END) AS "2024",
    COUNT(CASE WHEN AI.ANO = 2023 THEN 1 END) AS "2023",
    COUNT(CASE WHEN AI.ANO = 2022 THEN 1 END) AS "2022",
    COUNT(CASE WHEN AI.ANO = 2021 THEN 1 END) AS "2021",
    COUNT(CASE WHEN AI.ANO = 2020 THEN 1 END) AS "2020"
FROM
    ORGAOS ORG
    CROSS JOIN IDADES I
    LEFT JOIN APOSENTADORIA_INVALIDEZ AI ON AI.ORGAO = ORG.ORGAO AND AI.IDADE = I.IDADE
GROUP BY
    ORG.ORGAO, I.IDADE
ORDER BY
    ORG.ORGAO, I.IDADE;