WITH VALORES AS (
SELECT '001085-5' MATRICULA FROM DUAL UNION ALL
SELECT '003762-1' MATRICULA FROM DUAL UNION ALL
SELECT '036086-4' MATRICULA FROM DUAL UNION ALL
SELECT '036148-8' MATRICULA FROM DUAL UNION ALL
SELECT '043602-0' MATRICULA FROM DUAL UNION ALL
SELECT '043613-5' MATRICULA FROM DUAL UNION ALL
SELECT '045333-1' MATRICULA FROM DUAL UNION ALL
SELECT '066884-2' MATRICULA FROM DUAL UNION ALL
SELECT '078350-1' MATRICULA FROM DUAL UNION ALL
SELECT '159472-9' MATRICULA FROM DUAL UNION ALL
SELECT '159609-8' MATRICULA FROM DUAL UNION ALL
SELECT '169215-1' MATRICULA FROM DUAL UNION ALL
SELECT '170403-6' MATRICULA FROM DUAL UNION ALL
SELECT '170898-8' MATRICULA FROM DUAL UNION ALL
SELECT '204895-7' MATRICULA FROM DUAL UNION ALL
SELECT '205008-X' MATRICULA FROM DUAL UNION ALL
SELECT '205035-8' MATRICULA FROM DUAL UNION ALL
SELECT '205300-4' MATRICULA FROM DUAL UNION ALL
SELECT '205318-7' MATRICULA FROM DUAL UNION ALL
SELECT '205342-0' MATRICULA FROM DUAL UNION ALL
SELECT '205588-X' MATRICULA FROM DUAL UNION ALL
SELECT '205609-7' MATRICULA FROM DUAL UNION ALL
SELECT '205618-6' MATRICULA FROM DUAL UNION ALL
SELECT '205684-4' MATRICULA FROM DUAL UNION ALL
SELECT '205702-6' MATRICULA FROM DUAL UNION ALL
SELECT '205713-1' MATRICULA FROM DUAL UNION ALL
SELECT '206067-1' MATRICULA FROM DUAL UNION ALL
SELECT '206129-5' MATRICULA FROM DUAL UNION ALL
SELECT '207177-X' MATRICULA FROM DUAL UNION ALL
SELECT '207930-5' MATRICULA FROM DUAL UNION ALL
SELECT '207981-0' MATRICULA FROM DUAL UNION ALL
SELECT '207984-4' MATRICULA FROM DUAL UNION ALL
SELECT '208000-1' MATRICULA FROM DUAL UNION ALL
SELECT '208105-9' MATRICULA FROM DUAL UNION ALL
SELECT '208815-X' MATRICULA FROM DUAL UNION ALL
SELECT '208822-3' MATRICULA FROM DUAL UNION ALL
SELECT '208854-1' MATRICULA FROM DUAL UNION ALL
SELECT '208878-9' MATRICULA FROM DUAL UNION ALL
SELECT '208881-9' MATRICULA FROM DUAL UNION ALL
SELECT '208929-7' MATRICULA FROM DUAL UNION ALL
SELECT '209084-8' MATRICULA FROM DUAL UNION ALL
SELECT '209672-2' MATRICULA FROM DUAL UNION ALL
SELECT '209810-5' MATRICULA FROM DUAL UNION ALL
SELECT '214797-1' MATRICULA FROM DUAL UNION ALL
SELECT '214903-6' MATRICULA FROM DUAL UNION ALL
SELECT '219219-5' MATRICULA FROM DUAL UNION ALL
SELECT '220201-8' MATRICULA FROM DUAL UNION ALL
SELECT '220204-2' MATRICULA FROM DUAL UNION ALL
SELECT '220263-8' MATRICULA FROM DUAL UNION ALL
SELECT '221777-5' MATRICULA FROM DUAL UNION ALL
SELECT '221820-8' MATRICULA FROM DUAL UNION ALL
SELECT '222300-7' MATRICULA FROM DUAL UNION ALL
SELECT '222349-0' MATRICULA FROM DUAL UNION ALL
SELECT '222711-8' MATRICULA FROM DUAL UNION ALL
SELECT '223018-6' MATRICULA FROM DUAL UNION ALL
SELECT '224314-8' MATRICULA FROM DUAL UNION ALL
SELECT '224316-4' MATRICULA FROM DUAL UNION ALL
SELECT '226650-4' MATRICULA FROM DUAL UNION ALL
SELECT '226732-2' MATRICULA FROM DUAL UNION ALL
SELECT '228155-4' MATRICULA FROM DUAL UNION ALL
SELECT '229356-X' MATRICULA FROM DUAL UNION ALL
SELECT '229399-4' MATRICULA FROM DUAL UNION ALL
SELECT '229456-7' MATRICULA FROM DUAL UNION ALL
SELECT '229912-7' MATRICULA FROM DUAL UNION ALL
SELECT '230271-3' MATRICULA FROM DUAL UNION ALL
SELECT '230616-6' MATRICULA FROM DUAL UNION ALL
SELECT '231739-7' MATRICULA FROM DUAL UNION ALL
SELECT '232306-X' MATRICULA FROM DUAL UNION ALL
SELECT '237375-X' MATRICULA FROM DUAL UNION ALL
SELECT '265106-8' MATRICULA FROM DUAL UNION ALL
SELECT '265987-5' MATRICULA FROM DUAL UNION ALL
SELECT '269483-2' MATRICULA FROM DUAL UNION ALL
SELECT '281245-2' MATRICULA FROM DUAL UNION ALL
SELECT '282153-2' MATRICULA FROM DUAL UNION ALL
SELECT '283382-4' MATRICULA FROM DUAL UNION ALL
SELECT '308298-9' MATRICULA FROM DUAL UNION ALL
SELECT '308485-0' MATRICULA FROM DUAL UNION ALL
SELECT '320068-0' MATRICULA FROM DUAL UNION ALL
SELECT '344377-9' MATRICULA FROM DUAL UNION ALL
SELECT '344379-5' MATRICULA FROM DUAL UNION ALL
SELECT '344380-9' MATRICULA FROM DUAL UNION ALL
SELECT '002242-0' MATRICULA FROM DUAL UNION ALL
SELECT '002251-9' MATRICULA FROM DUAL UNION ALL
SELECT '002625-5' MATRICULA FROM DUAL UNION ALL
SELECT '002647-6' MATRICULA FROM DUAL UNION ALL
SELECT '002652-2' MATRICULA FROM DUAL UNION ALL
SELECT '002653-X' MATRICULA FROM DUAL UNION ALL
SELECT '002663-8' MATRICULA FROM DUAL UNION ALL
SELECT '002668-9' MATRICULA FROM DUAL UNION ALL
SELECT '002677-8' MATRICULA FROM DUAL UNION ALL
SELECT '002682-4' MATRICULA FROM DUAL UNION ALL
SELECT '002686-7' MATRICULA FROM DUAL UNION ALL
SELECT '002691-3' MATRICULA FROM DUAL UNION ALL
SELECT '002694-8' MATRICULA FROM DUAL UNION ALL
SELECT '002699-9' MATRICULA FROM DUAL UNION ALL
SELECT '002729-4' MATRICULA FROM DUAL UNION ALL
SELECT '003051-1' MATRICULA FROM DUAL UNION ALL
SELECT '086191-0' MATRICULA FROM DUAL UNION ALL
SELECT '086193-6' MATRICULA FROM DUAL UNION ALL
SELECT '086194-4' MATRICULA FROM DUAL UNION ALL
SELECT '086197-9' MATRICULA FROM DUAL UNION ALL
SELECT '086198-7' MATRICULA FROM DUAL UNION ALL
SELECT '086200-2' MATRICULA FROM DUAL UNION ALL
SELECT '086202-9' MATRICULA FROM DUAL UNION ALL
SELECT '086204-5' MATRICULA FROM DUAL UNION ALL
SELECT '086205-3' MATRICULA FROM DUAL UNION ALL
SELECT '086206-1' MATRICULA FROM DUAL UNION ALL
SELECT '088002-7' MATRICULA FROM DUAL UNION ALL
SELECT '088003-5' MATRICULA FROM DUAL UNION ALL
SELECT '088004-3' MATRICULA FROM DUAL UNION ALL
SELECT '088005-1' MATRICULA FROM DUAL UNION ALL
SELECT '088006-0' MATRICULA FROM DUAL UNION ALL
SELECT '088008-6' MATRICULA FROM DUAL UNION ALL
SELECT '088010-8' MATRICULA FROM DUAL UNION ALL
SELECT '088011-6' MATRICULA FROM DUAL UNION ALL
SELECT '088013-2' MATRICULA FROM DUAL UNION ALL
SELECT '088814-1' MATRICULA FROM DUAL UNION ALL
SELECT '091059-7' MATRICULA FROM DUAL UNION ALL
SELECT '091061-9' MATRICULA FROM DUAL UNION ALL
SELECT '091062-7' MATRICULA FROM DUAL UNION ALL
SELECT '091064-3' MATRICULA FROM DUAL UNION ALL
SELECT '091065-1' MATRICULA FROM DUAL UNION ALL
SELECT '091066-0' MATRICULA FROM DUAL UNION ALL
SELECT '091067-8' MATRICULA FROM DUAL UNION ALL
SELECT '091069-4' MATRICULA FROM DUAL UNION ALL
SELECT '091070-8' MATRICULA FROM DUAL UNION ALL
SELECT '091071-6' MATRICULA FROM DUAL UNION ALL
SELECT '091072-4' MATRICULA FROM DUAL UNION ALL
SELECT '091073-2' MATRICULA FROM DUAL UNION ALL
SELECT '091074-X' MATRICULA FROM DUAL UNION ALL
SELECT '091075-9' MATRICULA FROM DUAL UNION ALL
SELECT '091077-5' MATRICULA FROM DUAL UNION ALL
SELECT '091079-1' MATRICULA FROM DUAL UNION ALL
SELECT '091081-3' MATRICULA FROM DUAL UNION ALL
SELECT '091082-1' MATRICULA FROM DUAL UNION ALL
SELECT '091083-0' MATRICULA FROM DUAL UNION ALL
SELECT '091085-6' MATRICULA FROM DUAL UNION ALL
SELECT '091134-8' MATRICULA FROM DUAL UNION ALL
SELECT '092455-5' MATRICULA FROM DUAL UNION ALL
SELECT '092456-3' MATRICULA FROM DUAL UNION ALL
SELECT '092457-1' MATRICULA FROM DUAL UNION ALL
SELECT '092460-1' MATRICULA FROM DUAL UNION ALL
SELECT '092462-8' MATRICULA FROM DUAL UNION ALL
SELECT '092463-6' MATRICULA FROM DUAL UNION ALL
SELECT '092548-9' MATRICULA FROM DUAL UNION ALL
SELECT '092551-9' MATRICULA FROM DUAL UNION ALL
SELECT '092552-7' MATRICULA FROM DUAL UNION ALL
SELECT '092553-5' MATRICULA FROM DUAL UNION ALL
SELECT '092554-3' MATRICULA FROM DUAL UNION ALL
SELECT '092555-1' MATRICULA FROM DUAL UNION ALL
SELECT '092585-3' MATRICULA FROM DUAL UNION ALL
SELECT '092586-1' MATRICULA FROM DUAL UNION ALL
SELECT '092587-0' MATRICULA FROM DUAL UNION ALL
SELECT '092670-1' MATRICULA FROM DUAL UNION ALL
SELECT '112704-7' MATRICULA FROM DUAL UNION ALL
SELECT '112706-3' MATRICULA FROM DUAL UNION ALL
SELECT '112709-8' MATRICULA FROM DUAL UNION ALL
SELECT '112713-6' MATRICULA FROM DUAL UNION ALL
SELECT '115766-3' MATRICULA FROM DUAL UNION ALL
SELECT '115767-1' MATRICULA FROM DUAL UNION ALL
SELECT '115768-0' MATRICULA FROM DUAL UNION ALL
SELECT '115769-8' MATRICULA FROM DUAL UNION ALL
SELECT '170460-5' MATRICULA FROM DUAL UNION ALL
SELECT '170461-3' MATRICULA FROM DUAL UNION ALL
SELECT '170462-1' MATRICULA FROM DUAL UNION ALL
SELECT '170464-8' MATRICULA FROM DUAL UNION ALL
SELECT '170844-9' MATRICULA FROM DUAL UNION ALL
SELECT '170845-7' MATRICULA FROM DUAL UNION ALL
SELECT '170846-5' MATRICULA FROM DUAL UNION ALL
SELECT '170847-3' MATRICULA FROM DUAL UNION ALL
SELECT '170848-1' MATRICULA FROM DUAL UNION ALL
SELECT '170849-0' MATRICULA FROM DUAL UNION ALL
SELECT '170850-3' MATRICULA FROM DUAL UNION ALL
SELECT '172607-2' MATRICULA FROM DUAL UNION ALL
SELECT '213065-3' MATRICULA FROM DUAL UNION ALL
SELECT '213066-1' MATRICULA FROM DUAL UNION ALL
SELECT '213068-8' MATRICULA FROM DUAL UNION ALL
SELECT '213069-6' MATRICULA FROM DUAL UNION ALL
SELECT '213070-0' MATRICULA FROM DUAL UNION ALL
SELECT '213093-9' MATRICULA FROM DUAL UNION ALL
SELECT '213095-5' MATRICULA FROM DUAL UNION ALL
SELECT '232174-2' MATRICULA FROM DUAL UNION ALL
SELECT '280391-7' MATRICULA FROM DUAL UNION ALL
SELECT '280392-5' MATRICULA FROM DUAL UNION ALL
SELECT '315748-2' MATRICULA FROM DUAL 
)
SELECT 
    'EMPRESA' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_EMPRESA.FOLHA FO 
    JOIN SW_EMPRESA.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMPRESA.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'CBMPI' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_CBMPI.FOLHA FO 
    JOIN SW_CBMPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CBMPI.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'PGEPI' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_PGEPI.FOLHA FO 
    JOIN SW_PGEPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PGEPI.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'CGEPI' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_CGEPI.FOLHA FO 
    JOIN SW_CGEPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CGEPI.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'SSPPI' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_SSPPI.FOLHA FO 
    JOIN SW_SSPPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SSPPI.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'COJUV' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_COJUV.FOLHA FO 
    JOIN SW_COJUV.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_COJUV.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'ATIPI' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_ATIPI.FOLHA FO 
    JOIN SW_ATIPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_ATIPI.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'FAPEPI' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_FAPEPI.FOLHA FO 
    JOIN SW_FAPEPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FAPEPI.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'DEFCIVIL' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_DEFCIVIL.FOLHA FO 
    JOIN SW_DEFCIVIL.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_DEFCIVIL.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'ADH' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_ADH.FOLHA FO 
    JOIN SW_ADH.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_ADH.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'SEAGRO' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_SEAGRO.FOLHA FO 
    JOIN SW_SEAGRO.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEAGRO.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'IDEPI' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_IDEPI.FOLHA FO 
    JOIN SW_IDEPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_IDEPI.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'SURPI' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_SURPI.FOLHA FO 
    JOIN SW_SURPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SURPI.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'SEID' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_SEID.FOLHA FO 
    JOIN SW_SEID.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEID.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'SECID' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_SECID.FOLHA FO 
    JOIN SW_SECID.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SECID.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'FUPIP' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_FUPIP.FOLHA FO 
    JOIN SW_FUPIP.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUPIP.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'SETUR' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_SETUR.FOLHA FO 
    JOIN SW_SETUR.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SETUR.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'AGESPISA' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_AGESPISA.FOLHA FO 
    JOIN SW_AGESPISA.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_AGESPISA.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'SETRANS' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_SETRANS.FOLHA FO 
    JOIN SW_SETRANS.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SETRANS.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'TVANTARES' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_TVANTARES.FOLHA FO 
    JOIN SW_TVANTARES.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_TVANTARES.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'VICEGOV' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_VICEGOV.FOLHA FO 
    JOIN SW_VICEGOV.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_VICEGOV.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'SEINFRA' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_SEINFRA.FOLHA FO 
    JOIN SW_SEINFRA.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEINFRA.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'CCOM' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_CCOM.FOLHA FO 
    JOIN SW_CCOM.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CCOM.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'FUNDESPI' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_FUNDESPI.FOLHA FO 
    JOIN SW_FUNDESPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUNDESPI.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'SEDET' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_SEDET.FOLHA FO 
    JOIN SW_SEDET.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEDET.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'INTERPI' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_INTERPI.FOLHA FO 
    JOIN SW_INTERPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_INTERPI.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'JUCEPI' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_JUCEPI.FOLHA FO 
    JOIN SW_JUCEPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_JUCEPI.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'SEMAR' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_SEMAR.FOLHA FO 
    JOIN SW_SEMAR.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEMAR.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'GMG' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_GMG.FOLHA FO 
    JOIN SW_GMG.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_GMG.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'SEPLAN' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_SEPLAN.FOLHA FO 
    JOIN SW_SEPLAN.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEPLAN.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'SAF' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_SAF.FOLHA FO 
    JOIN SW_SAF.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SAF.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'SECULT' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_SECULT.FOLHA FO 
    JOIN SW_SECULT.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SECULT.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'DER' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_DER.FOLHA FO 
    JOIN SW_DER.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_DER.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'DETRAN' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_DETRAN.FOLHA FO 
    JOIN SW_DETRAN.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_DETRAN.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'IASPI' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_IASPI.FOLHA FO 
    JOIN SW_IASPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_IASPI.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'ADAPI' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_ADAPI.FOLHA FO 
    JOIN SW_ADAPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_ADAPI.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'IMEPIPROD' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_IMEPIPROD.FOLHA FO 
    JOIN SW_IMEPIPROD.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_IMEPIPROD.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'CPVCI' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_CPVCI.FOLHA FO 
    JOIN SW_CPVCI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CPVCI.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'CENDROGAS' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_CENDROGAS.FOLHA FO 
    JOIN SW_CENDROGAS.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CENDROGAS.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'COFIR' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_COFIR.FOLHA FO 
    JOIN SW_COFIR.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_COFIR.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'SEMINPER' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_SEMINPER.FOLHA FO 
    JOIN SW_SEMINPER.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEMINPER.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'AGRESP' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_AGRESP.FOLHA FO 
    JOIN SW_AGRESP.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_AGRESP.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'CEPM' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_CEPM.FOLHA FO 
    JOIN SW_CEPM.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CEPM.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'EMATER' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_EMATER.FOLHA FO 
    JOIN SW_EMATER.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMATER.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'FUESPI' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_FUESPI.FOLHA FO 
    JOIN SW_FUESPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUESPI.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'EMATERPROD' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_EMATERPROD.FOLHA FO 
    JOIN SW_EMATERPROD.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMATERPROD.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'DEFENSORIA' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_DEFENSORIA.FOLHA FO 
    JOIN SW_DEFENSORIA.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_DEFENSORIA.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'PENSIONISTAS' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_PENSIONISTAS.FOLHA FO 
    JOIN SW_PENSIONISTAS.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PENSIONISTAS.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'CDTER' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_CDTER.FOLHA FO 
    JOIN SW_CDTER.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CDTER.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'SERES' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_SERES.FOLHA FO 
    JOIN SW_SERES.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SERES.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'SECESP' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_SECESP.FOLHA FO 
    JOIN SW_SECESP.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SECESP.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'INATIVOS_PENSIONISTAS' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_INATIVOS_PENSIONISTAS.FOLHA FO 
    JOIN SW_INATIVOS_PENSIONISTAS.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_INATIVOS_PENSIONISTAS.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'SEDUC_PRECATORIO' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_SEDUC_PRECATORIO.FOLHA FO 
    JOIN SW_SEDUC_PRECATORIO.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEDUC_PRECATORIO.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'EMGERPI_CORESA' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_EMGERPI_CORESA.FOLHA FO 
    JOIN SW_EMGERPI_CORESA.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_CORESA.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'FESPPI' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_FESPPI.FOLHA FO 
    JOIN SW_FESPPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FESPPI.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'SIA' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_SIA.FOLHA FO 
    JOIN SW_SIA.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SIA.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'SETRE' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_SETRE.FOLHA FO 
    JOIN SW_SETRE.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SETRE.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'AGESPISA02' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_AGESPISA02.FOLHA FO 
    JOIN SW_AGESPISA02.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_AGESPISA02.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'SEGOV' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_SEGOV.FOLHA FO 
    JOIN SW_SEGOV.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEGOV.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'SASC' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_SASC.FOLHA FO 
    JOIN SW_SASC.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SASC.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'METRO' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_METRO.FOLHA FO 
    JOIN SW_METRO.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_METRO.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'PIAUIPREV' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_PIAUIPREV.FOLHA FO 
    JOIN SW_PIAUIPREV.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PIAUIPREV.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'INATIVOS_SEDUC' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_INATIVOS_SEDUC.FOLHA FO 
    JOIN SW_INATIVOS_SEDUC.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_INATIVOS_SEDUC.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'INATIVOS_TCE' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_INATIVOS_TCE.FOLHA FO 
    JOIN SW_INATIVOS_TCE.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_INATIVOS_TCE.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'SADA' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_SADA.FOLHA FO 
    JOIN SW_SADA.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SADA.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'SECMULHERES' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_SECMULHERES.FOLHA FO 
    JOIN SW_SECMULHERES.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SECMULHERES.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'EMGERPI_EMATER' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_EMGERPI_EMATER.FOLHA FO 
    JOIN SW_EMGERPI_EMATER.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_EMATER.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'REENVIO' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_REENVIO.FOLHA FO 
    JOIN SW_REENVIO.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_REENVIO.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'SESAPI' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_SESAPI.FOLHA FO 
    JOIN SW_SESAPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SESAPI.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'PMPI' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_PMPI.FOLHA FO 
    JOIN SW_PMPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PMPI.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'SEJUSPI' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_SEJUSPI.FOLHA FO 
    JOIN SW_SEJUSPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEJUSPI.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'SEFAZPI' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_SEFAZPI.FOLHA FO 
    JOIN SW_SEFAZPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEFAZPI.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'SEADPREVPI' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_SEADPREVPI.FOLHA FO 
    JOIN SW_SEADPREVPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEADPREVPI.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'IMEPI' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_IMEPI.FOLHA FO 
    JOIN SW_IMEPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_IMEPI.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'BEP' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_BEP.FOLHA FO 
    JOIN SW_BEP.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_BEP.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'EMGERPI_COMEPI' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_EMGERPI_COMEPI.FOLHA FO 
    JOIN SW_EMGERPI_COMEPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_COMEPI.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'EMGERPI_COMDEPI' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_EMGERPI_COMDEPI.FOLHA FO 
    JOIN SW_EMGERPI_COMDEPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_COMDEPI.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'EMGERPI_COHAB' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_EMGERPI_COHAB.FOLHA FO 
    JOIN SW_EMGERPI_COHAB.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_COHAB.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'EMGERPI_PRODEPI' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_EMGERPI_PRODEPI.FOLHA FO 
    JOIN SW_EMGERPI_PRODEPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_PRODEPI.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'EMGERPI_CEASA' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_EMGERPI_CEASA.FOLHA FO 
    JOIN SW_EMGERPI_CEASA.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_CEASA.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'EMGERPI_PIEMTUR' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_EMGERPI_PIEMTUR.FOLHA FO 
    JOIN SW_EMGERPI_PIEMTUR.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_PIEMTUR.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'EMGERPI_ETELPI_FUNART' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_EMGERPI_ETELPI_FUNART.FOLHA FO 
    JOIN SW_EMGERPI_ETELPI_FUNART.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_ETELPI_FUNART.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'EMGERPI_CIDAPI' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_EMGERPI_CIDAPI.FOLHA FO 
    JOIN SW_EMGERPI_CIDAPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_CIDAPI.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'SEDUC' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_SEDUC.FOLHA FO 
    JOIN SW_SEDUC.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEDUC.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'EMGERPI' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_EMGERPI.FOLHA FO 
    JOIN SW_EMGERPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
UNION ALL
SELECT 
    'EMGERPI_CODIPI' ORGAO,
    FC.COD_INSTITUCIONAL,
    FC.CPF_PESSOA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FFR.VALOR_CALCULADO
FROM
    SW_EMGERPI_CODIPI.FOLHA FO 
    JOIN SW_EMGERPI_CODIPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_CODIPI.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN VALORES V ON V.MATRICULA = FC.COD_INSTITUCIONAL
WHERE 
    FO.MES = 12
    AND FO.ANO = 2025
    AND R.COD_RUBRICA IN (999997,714100)
;