SELECT 
    'CBMPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_CBMPI.PESSOA_VINCULO PV
    JOIN SW_CBMPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_CBMPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_CBMPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'PGEPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_PGEPI.PESSOA_VINCULO PV
    JOIN SW_PGEPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_PGEPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_PGEPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'CGEPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_CGEPI.PESSOA_VINCULO PV
    JOIN SW_CGEPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_CGEPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_CGEPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'SSPPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_SSPPI.PESSOA_VINCULO PV
    JOIN SW_SSPPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SSPPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SSPPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'COJUV' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_COJUV.PESSOA_VINCULO PV
    JOIN SW_COJUV.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_COJUV.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_COJUV.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'ATIPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_ATIPI.PESSOA_VINCULO PV
    JOIN SW_ATIPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_ATIPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_ATIPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'FAPEPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_FAPEPI.PESSOA_VINCULO PV
    JOIN SW_FAPEPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_FAPEPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_FAPEPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'DEFCIVIL' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_DEFCIVIL.PESSOA_VINCULO PV
    JOIN SW_DEFCIVIL.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_DEFCIVIL.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_DEFCIVIL.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'ADH' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_ADH.PESSOA_VINCULO PV
    JOIN SW_ADH.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_ADH.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_ADH.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'SEAGRO' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_SEAGRO.PESSOA_VINCULO PV
    JOIN SW_SEAGRO.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SEAGRO.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SEAGRO.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'IDEPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_IDEPI.PESSOA_VINCULO PV
    JOIN SW_IDEPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_IDEPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_IDEPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'SURPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_SURPI.PESSOA_VINCULO PV
    JOIN SW_SURPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SURPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SURPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'SEID' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_SEID.PESSOA_VINCULO PV
    JOIN SW_SEID.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SEID.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SEID.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'SECID' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_SECID.PESSOA_VINCULO PV
    JOIN SW_SECID.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SECID.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SECID.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'FUPIP' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_FUPIP.PESSOA_VINCULO PV
    JOIN SW_FUPIP.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_FUPIP.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_FUPIP.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'SETUR' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_SETUR.PESSOA_VINCULO PV
    JOIN SW_SETUR.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SETUR.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SETUR.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'AGESPISA' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_AGESPISA.PESSOA_VINCULO PV
    JOIN SW_AGESPISA.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_AGESPISA.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_AGESPISA.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'SETRANS' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_SETRANS.PESSOA_VINCULO PV
    JOIN SW_SETRANS.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SETRANS.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SETRANS.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'TVANTARES' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_TVANTARES.PESSOA_VINCULO PV
    JOIN SW_TVANTARES.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_TVANTARES.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_TVANTARES.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'VICEGOV' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_VICEGOV.PESSOA_VINCULO PV
    JOIN SW_VICEGOV.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_VICEGOV.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_VICEGOV.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'SEINFRA' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_SEINFRA.PESSOA_VINCULO PV
    JOIN SW_SEINFRA.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SEINFRA.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SEINFRA.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'CCOM' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_CCOM.PESSOA_VINCULO PV
    JOIN SW_CCOM.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_CCOM.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_CCOM.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'FUNDESPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_FUNDESPI.PESSOA_VINCULO PV
    JOIN SW_FUNDESPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_FUNDESPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_FUNDESPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'SEDET' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_SEDET.PESSOA_VINCULO PV
    JOIN SW_SEDET.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SEDET.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SEDET.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'INTERPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_INTERPI.PESSOA_VINCULO PV
    JOIN SW_INTERPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_INTERPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_INTERPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'JUCEPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_JUCEPI.PESSOA_VINCULO PV
    JOIN SW_JUCEPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_JUCEPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_JUCEPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'SEMAR' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_SEMAR.PESSOA_VINCULO PV
    JOIN SW_SEMAR.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SEMAR.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SEMAR.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'GMG' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_GMG.PESSOA_VINCULO PV
    JOIN SW_GMG.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_GMG.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_GMG.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'SEPLAN' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_SEPLAN.PESSOA_VINCULO PV
    JOIN SW_SEPLAN.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SEPLAN.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SEPLAN.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'SAF' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_SAF.PESSOA_VINCULO PV
    JOIN SW_SAF.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SAF.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SAF.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'SECULT' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_SECULT.PESSOA_VINCULO PV
    JOIN SW_SECULT.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SECULT.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SECULT.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'DER' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_DER.PESSOA_VINCULO PV
    JOIN SW_DER.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_DER.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_DER.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'DETRAN' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_DETRAN.PESSOA_VINCULO PV
    JOIN SW_DETRAN.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_DETRAN.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_DETRAN.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'IASPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_IASPI.PESSOA_VINCULO PV
    JOIN SW_IASPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_IASPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_IASPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'ADAPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_ADAPI.PESSOA_VINCULO PV
    JOIN SW_ADAPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_ADAPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_ADAPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'IMEPIPROD' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_IMEPIPROD.PESSOA_VINCULO PV
    JOIN SW_IMEPIPROD.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_IMEPIPROD.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_IMEPIPROD.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'CPVCI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_CPVCI.PESSOA_VINCULO PV
    JOIN SW_CPVCI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_CPVCI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_CPVCI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'CENDROGAS' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_CENDROGAS.PESSOA_VINCULO PV
    JOIN SW_CENDROGAS.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_CENDROGAS.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_CENDROGAS.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'COFIR' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_COFIR.PESSOA_VINCULO PV
    JOIN SW_COFIR.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_COFIR.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_COFIR.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'SEMINPER' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_SEMINPER.PESSOA_VINCULO PV
    JOIN SW_SEMINPER.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SEMINPER.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SEMINPER.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'AGRESP' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_AGRESP.PESSOA_VINCULO PV
    JOIN SW_AGRESP.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_AGRESP.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_AGRESP.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'CEPM' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_CEPM.PESSOA_VINCULO PV
    JOIN SW_CEPM.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_CEPM.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_CEPM.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'EMATER' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_EMATER.PESSOA_VINCULO PV
    JOIN SW_EMATER.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_EMATER.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_EMATER.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'FUESPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_FUESPI.PESSOA_VINCULO PV
    JOIN SW_FUESPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_FUESPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_FUESPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'EMATERPROD' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_EMATERPROD.PESSOA_VINCULO PV
    JOIN SW_EMATERPROD.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_EMATERPROD.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_EMATERPROD.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL         
SELECT 
    'CDTER' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_CDTER.PESSOA_VINCULO PV
    JOIN SW_CDTER.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_CDTER.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_CDTER.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'SERES' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_SERES.PESSOA_VINCULO PV
    JOIN SW_SERES.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SERES.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SERES.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'SECESP' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_SECESP.PESSOA_VINCULO PV
    JOIN SW_SECESP.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SECESP.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SECESP.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL          
SELECT 
    'EMGERPI_CORESA' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_EMGERPI_CORESA.PESSOA_VINCULO PV
    JOIN SW_EMGERPI_CORESA.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_EMGERPI_CORESA.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_EMGERPI_CORESA.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'FUNPREV' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_FUNPREV.PESSOA_VINCULO PV
    JOIN SW_FUNPREV.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_FUNPREV.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_FUNPREV.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'FESPPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_FESPPI.PESSOA_VINCULO PV
    JOIN SW_FESPPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_FESPPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_FESPPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'SIA' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_SIA.PESSOA_VINCULO PV
    JOIN SW_SIA.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SIA.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SIA.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'SETRE' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_SETRE.PESSOA_VINCULO PV
    JOIN SW_SETRE.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SETRE.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SETRE.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'AGESPISA02' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_AGESPISA02.PESSOA_VINCULO PV
    JOIN SW_AGESPISA02.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_AGESPISA02.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_AGESPISA02.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'SEGOV' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_SEGOV.PESSOA_VINCULO PV
    JOIN SW_SEGOV.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SEGOV.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SEGOV.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'SASC' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_SASC.PESSOA_VINCULO PV
    JOIN SW_SASC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SASC.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SASC.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'METRO' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_METRO.PESSOA_VINCULO PV
    JOIN SW_METRO.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_METRO.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_METRO.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL             
SELECT 
    'SADA' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_SADA.PESSOA_VINCULO PV
    JOIN SW_SADA.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SADA.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SADA.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'SECMULHERES' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_SECMULHERES.PESSOA_VINCULO PV
    JOIN SW_SECMULHERES.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SECMULHERES.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SECMULHERES.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'EMGERPI_EMATER' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_EMGERPI_EMATER.PESSOA_VINCULO PV
    JOIN SW_EMGERPI_EMATER.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_EMGERPI_EMATER.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_EMGERPI_EMATER.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL      
SELECT 
    'SESAPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_SESAPI.PESSOA_VINCULO PV
    JOIN SW_SESAPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SESAPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SESAPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'PMPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_PMPI.PESSOA_VINCULO PV
    JOIN SW_PMPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_PMPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_PMPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'SEJUSPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_SEJUSPI.PESSOA_VINCULO PV
    JOIN SW_SEJUSPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SEJUSPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SEJUSPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'SEFAZPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_SEFAZPI.PESSOA_VINCULO PV
    JOIN SW_SEFAZPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SEFAZPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SEFAZPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'SEADPREVPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_SEADPREVPI.PESSOA_VINCULO PV
    JOIN SW_SEADPREVPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SEADPREVPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SEADPREVPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'IMEPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_IMEPI.PESSOA_VINCULO PV
    JOIN SW_IMEPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_IMEPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_IMEPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'BEP' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_BEP.PESSOA_VINCULO PV
    JOIN SW_BEP.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_BEP.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_BEP.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'EMGERPI_COMEPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_EMGERPI_COMEPI.PESSOA_VINCULO PV
    JOIN SW_EMGERPI_COMEPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_EMGERPI_COMEPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_EMGERPI_COMEPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'EMGERPI_COMDEPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_EMGERPI_COMDEPI.PESSOA_VINCULO PV
    JOIN SW_EMGERPI_COMDEPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_EMGERPI_COMDEPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_EMGERPI_COMDEPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'EMGERPI_COHAB' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_EMGERPI_COHAB.PESSOA_VINCULO PV
    JOIN SW_EMGERPI_COHAB.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_EMGERPI_COHAB.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_EMGERPI_COHAB.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'EMGERPI_PRODEPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_EMGERPI_PRODEPI.PESSOA_VINCULO PV
    JOIN SW_EMGERPI_PRODEPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_EMGERPI_PRODEPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_EMGERPI_PRODEPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'EMGERPI_CEASA' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_EMGERPI_CEASA.PESSOA_VINCULO PV
    JOIN SW_EMGERPI_CEASA.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_EMGERPI_CEASA.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_EMGERPI_CEASA.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'EMGERPI_PIEMTUR' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_EMGERPI_PIEMTUR.PESSOA_VINCULO PV
    JOIN SW_EMGERPI_PIEMTUR.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_EMGERPI_PIEMTUR.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_EMGERPI_PIEMTUR.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'EMGERPI_ETELPI_FUNART' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_EMGERPI_ETELPI_FUNART.PESSOA_VINCULO PV
    JOIN SW_EMGERPI_ETELPI_FUNART.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_EMGERPI_ETELPI_FUNART.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_EMGERPI_ETELPI_FUNART.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'EMGERPI_CIDAPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_EMGERPI_CIDAPI.PESSOA_VINCULO PV
    JOIN SW_EMGERPI_CIDAPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_EMGERPI_CIDAPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_EMGERPI_CIDAPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'SEDUC' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_SEDUC.PESSOA_VINCULO PV
    JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SEDUC.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SEDUC.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'EMGERPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_EMGERPI.PESSOA_VINCULO PV
    JOIN SW_EMGERPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_EMGERPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_EMGERPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
UNION ALL    
SELECT 
    'EMGERPI_CODIPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM
FROM
    SW_EMGERPI_CODIPI.PESSOA_VINCULO PV
    JOIN SW_EMGERPI_CODIPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_EMGERPI_CODIPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_EMGERPI_CODIPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE
    PD.NOME_DIVISAO LIKE '%Pensão Indenizatória%'
;   