SELECT 
    'CDTER' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    FP.ID_FUNCIONARIO,
    PTM.NOME_MOVIMENTACAO,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM,
    TI.NOME_TIPO_INCIDENCIA,
    IR.NOME_REMUNERACAO,
    PV.COD_INSTITUCIONAL,
    PV.ID_PESSOA_VINCULO,
    --'INSERT INTO SW_CDTER.FUNCIONARIO_PERFIL (DATA_FIM) VALUES (''11/02/2026'');' INSERT_,
    'DELETE FROM SW_CDTER.FUNCIONARIO_PERFIL WHERE ID_FUNCIONARIO_PERFIL = ' || FP.ID_FUNCIONARIO_PERFIL || ';' AS DELETE_
    --'UPDATE SW_CDTER.FUNCIONARIO_PERFIL SET DATA_FIM = NULL WHERE ID_FUNCIONARIO_PERFIL = ' || FP.ID_FUNCIONARIO_PERFIL || ';' AS UPDATE_
FROM
    SW_CDTER.PESSOA_VINCULO PV
    JOIN SW_CDTER.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_CDTER.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_CDTER.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.RHB_PERFIL_TIPO_FUNCIONARIO PTF ON PTF.ID_TIPO_FUNCIONARIO = FP.ID_TIPO_FUNCIONARIO
    JOIN SW_PUBLICO.RHB_PERFIL_TIPO_MOVIMENTACAO PTM ON PTM.ID_MOVIMENTACAO = FP.ID_MOVIMENTACAO
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REMUNERACAO IR ON IR.ID_REMUNERACAO = FP.ID_REMUNERACAO
    LEFT JOIN SW_PUBLICO.FOLHA_TAB_TIPO_INCIDENCIA TI ON TI.ID_TIPO_INCIDENCIA = FP.ID_TIPO_INCIDENCIA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
    --JOIN SW_CDTER.FUNC_DESLIGAMENTO
    --JOIN SW_CDTER.FUNCIONARIO_INGRESSO
WHERE 
    --FP.ID_FUNCIONARIO_PERFIL IN (1001022);
    --PV.COD_INSTITUCIONAL = '442683-5';
    F.ID_FUNCIONARIO IN (1000582,1000583);
    
    UPDATE SW_CDTER.FUNCIONARIO_INGRESSO SET ID_FUNCIONARIO_PERFIL = 1001021 WHERE ID_FUNCIONARIO = 1000583;
    
    DELETE FROM SW_CDTER.FUNCIONARIO_INGRESSO WHERE ID_FUNCIONARIO = 1000583;
    DELETE FROM SW_CDTER.FUNCIONARIO_PERFIL WHERE ID_FUNCIONARIO_PERFIL = 1001022;
 ---------------------------------------------------------------------------------------------------------------------------------------------------------------------   
SELECT 
    'SEGOV' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    FP.ID_FUNCIONARIO,
    PTM.NOME_MOVIMENTACAO,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM,
    TI.NOME_TIPO_INCIDENCIA,
    IR.NOME_REMUNERACAO,
    --'UPDATE SW_SEGOV.FUNCIONARIO_PERFIL SET DATA_FIM = ''02/03/2026'' WHERE ID_FUNCIONARIO_PERFIL =' || FP.ID_FUNCIONARIO_PERFIL || ';' INSERT_
    'DELETE FROM SW_SEGOV.FUNCIONARIO_PERFIL WHERE ID_FUNCIONARIO_PERFIL = ' || FP.ID_FUNCIONARIO_PERFIL || ';' AS DELETE_
    --'UPDATE SW_SEGOV.FUNCIONARIO_PERFIL SET DATA_FIM = NULL WHERE ID_FUNCIONARIO_PERFIL = ' || FP.ID_FUNCIONARIO_PERFIL || ';' AS UPDATE_
FROM
    SW_SEGOV.PESSOA_VINCULO PV
    JOIN SW_SEGOV.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SEGOV.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SEGOV.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.RHB_PERFIL_TIPO_FUNCIONARIO PTF ON PTF.ID_TIPO_FUNCIONARIO = FP.ID_TIPO_FUNCIONARIO
    JOIN SW_PUBLICO.RHB_PERFIL_TIPO_MOVIMENTACAO PTM ON PTM.ID_MOVIMENTACAO = FP.ID_MOVIMENTACAO
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REMUNERACAO IR ON IR.ID_REMUNERACAO = FP.ID_REMUNERACAO
    LEFT JOIN SW_PUBLICO.FOLHA_TAB_TIPO_INCIDENCIA TI ON TI.ID_TIPO_INCIDENCIA = FP.ID_TIPO_INCIDENCIA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
    --JOIN SW_SEGOV.FUNC_DESLIGAMENTO
    --JOIN SW_SEGOV.FUNCIONARIO_INGRESSO
    JOIN SW_SEGOV.FOLHA_IMP_FUNC_PERFIL
WHERE 
    FP.ID_FUNCIONARIO_PERFIL IN (1007557);
    
    DELETE FROM SW_SEGOV.FOLHA_IMP_FUNC_PERFIL WHERE ID_FUNCIONARIO_PERFIL = 1007557;
    DELETE FROM SW_SEGOV.FUNCIONARIO_PERFIL WHERE ID_FUNCIONARIO_PERFIL = 1007557;
---------------------------------------------------------------------------------------------------------------------------------------------------------------------

SELECT 
    'SEDUC' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    FP.ID_FUNCIONARIO,
    PTM.NOME_MOVIMENTACAO,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM,
    TI.NOME_TIPO_INCIDENCIA,
    IR.NOME_REMUNERACAO,
    --'UPDATE SW_SEDUC.FUNCIONARIO_PERFIL SET DATA_FIM = ''02/03/2026'' WHERE ID_FUNCIONARIO_PERFIL =' || FP.ID_FUNCIONARIO_PERFIL || ';' INSERT_
    'DELETE FROM SW_SEDUC.FUNCIONARIO_PERFIL WHERE ID_FUNCIONARIO_PERFIL = ' || FP.ID_FUNCIONARIO_PERFIL || ';' AS DELETE_
    --UPDATE SW_SEDUC.FUNC_DESLIGAMENTO SET ID_PERFIL = NULL WHERE ID_DESLIGAMENTO = 1008536;
    --'UPDATE SW_SEDUC.FUNCIONARIO_PERFIL SET DATA_FIM = NULL WHERE ID_FUNCIONARIO_PERFIL = ' || FP.ID_FUNCIONARIO_PERFIL || ';' AS UPDATE_
FROM
    SW_SEDUC.PESSOA_VINCULO PV
    JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SEDUC.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SEDUC.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.RHB_PERFIL_TIPO_FUNCIONARIO PTF ON PTF.ID_TIPO_FUNCIONARIO = FP.ID_TIPO_FUNCIONARIO
    JOIN SW_PUBLICO.RHB_PERFIL_TIPO_MOVIMENTACAO PTM ON PTM.ID_MOVIMENTACAO = FP.ID_MOVIMENTACAO
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REMUNERACAO IR ON IR.ID_REMUNERACAO = FP.ID_REMUNERACAO
    LEFT JOIN SW_PUBLICO.FOLHA_TAB_TIPO_INCIDENCIA TI ON TI.ID_TIPO_INCIDENCIA = FP.ID_TIPO_INCIDENCIA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
    --JOIN SW_SEDUC.FUNC_DESLIGAMENTO
    --JOIN SW_SEDUC.FUNCIONARIO_INGRESSO
    --JOIN SW_SEDUC.FOLHA_IMP_FUNC_PERFIL
WHERE 
    FP.ID_FUNCIONARIO_PERFIL IN (1143169);
    