SELECT 
    'FUNPREV' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    FP.ID_FUNCIONARIO,
    PTM.NOME_MOVIMENTACAO,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM,
    TI.NOME_TIPO_INCIDENCIA,
    IR.NOME_REMUNERACAO,
    PV.COD_INSTITUCIONAL,
    PV.ID_PESSOA_VINCULO,
    --'INSERT INTO SW_FUNPREV.FUNCIONARIO_PERFIL (DATA_FIM) VALUES (''11/02/2026'');' INSERT_,
    --'DELETE FROM SW_FUNPREV.FUNCIONARIO_PERFIL WHERE ID_FUNCIONARIO_PERFIL = ' || FP.ID_FUNCIONARIO_PERFIL || ';' AS DELETE_
    'UPDATE SW_FUNPREV.FUNCIONARIO_PERFIL SET DATA_FIM = NULL WHERE ID_FUNCIONARIO_PERFIL = ' || FP.ID_FUNCIONARIO_PERFIL || ';' AS UPDATE_
FROM
    SW_FUNPREV.PESSOA_VINCULO PV
    JOIN SW_FUNPREV.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_FUNPREV.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_FUNPREV.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.RHB_PERFIL_TIPO_FUNCIONARIO PTF ON PTF.ID_TIPO_FUNCIONARIO = FP.ID_TIPO_FUNCIONARIO
    JOIN SW_PUBLICO.RHB_PERFIL_TIPO_MOVIMENTACAO PTM ON PTM.ID_MOVIMENTACAO = FP.ID_MOVIMENTACAO
    LEFT JOIN SW_PUBLICO.RHB_INGRESSO_REMUNERACAO IR ON IR.ID_REMUNERACAO = FP.ID_REMUNERACAO
    LEFT JOIN SW_PUBLICO.FOLHA_TAB_TIPO_INCIDENCIA TI ON TI.ID_TIPO_INCIDENCIA = FP.ID_TIPO_INCIDENCIA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
    --JOIN SW_FUNPREV.FUNC_DESLIGAMENTO
    --JOIN SW_FUNPREV.FUNCIONARIO_INGRESSO
WHERE 
    FP.ID_FUNCIONARIO_PERFIL IN (1032869);
    --PV.COD_INSTITUCIONAL = '013561-5';
    --F.ID_FUNCIONARIO IN (1000582,1000583);

UPDATE SW_FUNPREV.FUNCIONARIO_PERFIL SET DATA_FIM = NULL WHERE ID_FUNCIONARIO_PERFIL = 1032869;