SELECT 
    'TFD' ORGAO,
    FO.ID_FOLHA,
    FO.CHAVE_FOLHA,
    PV.ID_PESSOA_VINCULO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    FF.COD_INSTITUCIONAL MATRICULA,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    'https://siape-ppf.ati.pi.gov.br/adm/tfd/folha-funcionario/folhas/folhas/folha-de-pagamento/'|| FO.ID_FOLHA ||'/funcionarios/pagamento/pagamento-individual/' || FF.ID_FOLHA_FUNCIONARIO ||'/dados-funcionais' LINK
FROM 
    SW_TFD.FOLHA FO 
    JOIN SW_TFD.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_TFD.FUNCIONARIO F ON F.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
    JOIN SW_TFD.PESSOA_VINCULO PV ON PV.ID_PESSOA_VINCULO = F.ID_PESSOA_VINCULO
    LEFT JOIN SW_TFD.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    LEFT JOIN SW_TFD.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    LEFT JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    LEFT JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    PC.ID_CPF IS NULL
    AND FO.MES = 7
    AND FO.ANO = 2026
    --AND FO.ID_FOLHA IN (1005857)
;