SELECT 
    'SEDUC' ORGAO,
    FO.ID_FOLHA,
    FO.CHAVE_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    FFR.VALOR_CALCULADO,
    R.COD_RUBRICA,
    R.NOME_RUBRICA
FROM 
    SW_SEDUC.FOLHA FO
    JOIN SW_SEDUC.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA 
    JOIN SW_SEDUC.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 620205
    AND FO.ANO = 2026
    AND FO.MES = 8