INSERT INTO SW_ADH.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_ADH.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_ADH.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_AGESPISA.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_AGESPISA.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_AGESPISA.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_AGESPISA02.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_AGESPISA02.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_AGESPISA02.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_AGRESP.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_AGRESP.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_AGRESP.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_BEP.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_BEP.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_BEP.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_CBMPI.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_CBMPI.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_CBMPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_CCOM.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_CCOM.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_CCOM.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_CDTER.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_CDTER.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_CDTER.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_CENDROGAS.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_CENDROGAS.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_CENDROGAS.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_COFIR.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_COFIR.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_COFIR.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_COJUV.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_COJUV.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_COJUV.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_DEFCIVIL.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_DEFCIVIL.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_DEFCIVIL.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_DER.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_DER.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_DER.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_DETRAN.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_DETRAN.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_DETRAN.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_EMGERPI.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_EMGERPI.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_EMGERPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_EMGERPI_CEASA.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_EMGERPI_CEASA.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_EMGERPI_CEASA.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_EMGERPI_CIDAPI.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_EMGERPI_CIDAPI.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_EMGERPI_CIDAPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_EMGERPI_CODIPI.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_EMGERPI_CODIPI.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_EMGERPI_CODIPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_EMGERPI_COHAB.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_EMGERPI_COHAB.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_EMGERPI_COHAB.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_EMGERPI_COMDEPI.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_EMGERPI_COMDEPI.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_EMGERPI_COMDEPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_EMGERPI_COMEPI.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_EMGERPI_COMEPI.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_EMGERPI_COMEPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_EMGERPI_CORESA.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_EMGERPI_CORESA.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_EMGERPI_CORESA.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_EMGERPI_EMATER.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_EMGERPI_EMATER.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_EMGERPI_EMATER.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_EMGERPI_ETELPI_FUNART.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_EMGERPI_ETELPI_FUNART.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_EMGERPI_ETELPI_FUNART.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_EMGERPI_PIEMTUR.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_EMGERPI_PIEMTUR.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_EMGERPI_PIEMTUR.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_EMGERPI_PRODEPI.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_EMGERPI_PRODEPI.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_EMGERPI_PRODEPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_FAPEPI.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_FAPEPI.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_FAPEPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_FESPPI.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_FESPPI.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_FESPPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_FUESPI.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_FUESPI.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_FUESPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_FUNPREV.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_FUNPREV.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_FUNPREV.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_FUPIP.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_FUPIP.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_FUPIP.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_GMG.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_GMG.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_GMG.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_IASPI.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_IASPI.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_IASPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_IDEPI.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_IDEPI.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_IDEPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_IMEPI.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_IMEPI.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_IMEPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_IMEPIPROD.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_IMEPIPROD.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_IMEPIPROD.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_INTERPI.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_INTERPI.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_INTERPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_JUCEPI.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_JUCEPI.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_JUCEPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_METRO.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_METRO.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_METRO.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_PGEPI.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_PGEPI.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_PGEPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_PMPI.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_PMPI.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_PMPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_SADA.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SADA.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_SADA.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_SAF.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SAF.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_SAF.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_SASC.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SASC.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_SASC.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;
/*
INSERT INTO SW_SEADPREVPI.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SEADPREVPI.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_SEADPREVPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )
    ;
*/


INSERT INTO SW_SEAGRO.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SEAGRO.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_SEAGRO.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_SECESP.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SECESP.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_SECESP.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_SECID.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SECID.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_SECID.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_SECMULHERES.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SECMULHERES.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_SECMULHERES.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_SECULT.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SECULT.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_SECULT.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_SEDET.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SEDET.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_SEDET.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_SEDUC.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SEDUC.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_SEDUC.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_SEFAZPI.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SEFAZPI.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_SEFAZPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_SEGOV.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SEGOV.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_SEGOV.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_SEID.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SEID.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_SEID.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_SEINFRA.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SEINFRA.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_SEINFRA.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_SEJUSPI.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SEJUSPI.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_SEJUSPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_SEMAR.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SEMAR.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_SEMAR.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_SEMINPER.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SEMINPER.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_SEMINPER.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_SEPLAN.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SEPLAN.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_SEPLAN.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_SERES.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SERES.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_SERES.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_SESAPI.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SESAPI.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_SESAPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_SETRANS.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SETRANS.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_SETRANS.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_SETRE.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SETRE.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_SETRE.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_SETUR.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SETUR.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_SETUR.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_SIA.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SIA.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_SIA.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_SSPPI.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SSPPI.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_SSPPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_SURPI.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SURPI.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_SURPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_TVANTARES.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_TVANTARES.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_TVANTARES.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )

;

INSERT INTO SW_VICEGOV.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_VICEGOV.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    P.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SEADPREVPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001341) -- ID GRUPO DE USUARIO
    AND P.ID_PERMISSAO IN (2024293)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_VICEGOV.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = P.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )