-- Grupo: SECRETARIA DE DEFESA CIVIL | Orgao: DEFCIVIL | ID_GRUPO_DE_USUARIO: 1000580
INSERT INTO SW_DEFCIVIL.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_DEFCIVIL.SQ_PK_PERMISSAO.NEXTVAL,
    1000580,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_DEFCIVIL.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000580
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: ADAPI | Orgao: ADAPI | ID_GRUPO_DE_USUARIO: 1000741
INSERT INTO SW_ADAPI.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_ADAPI.SQ_PK_PERMISSAO.NEXTVAL,
    1000741,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_ADAPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000741
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: ADH | Orgao: ADH | ID_GRUPO_DE_USUARIO: 1000561
INSERT INTO SW_ADH.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_ADH.SQ_PK_PERMISSAO.NEXTVAL,
    1000561,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_ADH.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000561
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: AGESPISA | Orgao: AGESPISA | ID_GRUPO_DE_USUARIO: 1000603
INSERT INTO SW_AGESPISA.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_AGESPISA.SQ_PK_PERMISSAO.NEXTVAL,
    1000603,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_AGESPISA.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000603
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: AGESPISA02 | Orgao: AGESPISA02 | ID_GRUPO_DE_USUARIO: 2002080
INSERT INTO SW_AGESPISA02.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_AGESPISA02.SQ_PK_PERMISSAO.NEXTVAL,
    2002080,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_AGESPISA02.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 2002080
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: AGRESP | Orgao: AGRESP | ID_GRUPO_DE_USUARIO: 1000544
INSERT INTO SW_AGRESP.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_AGRESP.SQ_PK_PERMISSAO.NEXTVAL,
    1000544,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_AGRESP.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000544
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: CBMPI | Orgao: CBMPI | ID_GRUPO_DE_USUARIO: 1000020
INSERT INTO SW_CBMPI.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_CBMPI.SQ_PK_PERMISSAO.NEXTVAL,
    1000020,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_CBMPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000020
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: CCOM | Orgao: CCOM | ID_GRUPO_DE_USUARIO: 1000722
INSERT INTO SW_CCOM.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_CCOM.SQ_PK_PERMISSAO.NEXTVAL,
    1000722,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_CCOM.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000722
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: CDTER | Orgao: CDTER | ID_GRUPO_DE_USUARIO: 1001421
INSERT INTO SW_CDTER.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_CDTER.SQ_PK_PERMISSAO.NEXTVAL,
    1001421,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_CDTER.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1001421
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: CENDROGAS | Orgao: CENDROGAS | ID_GRUPO_DE_USUARIO: 1000541
INSERT INTO SW_CENDROGAS.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_CENDROGAS.SQ_PK_PERMISSAO.NEXTVAL,
    1000541,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_CENDROGAS.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000541
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: CGEPI | Orgao: CGEPI | ID_GRUPO_DE_USUARIO: 1000021
INSERT INTO SW_CGEPI.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_CGEPI.SQ_PK_PERMISSAO.NEXTVAL,
    1000021,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_CGEPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000021
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: COJUV | Orgao: COJUV | ID_GRUPO_DE_USUARIO: 1000546
INSERT INTO SW_COJUV.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_COJUV.SQ_PK_PERMISSAO.NEXTVAL,
    1000546,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_COJUV.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000546
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: CPVCI | Orgao: CPVCI | ID_GRUPO_DE_USUARIO: 1000540
INSERT INTO SW_CPVCI.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_CPVCI.SQ_PK_PERMISSAO.NEXTVAL,
    1000540,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_CPVCI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000540
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: DER | Orgao: DER | ID_GRUPO_DE_USUARIO: 1000731
INSERT INTO SW_DER.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_DER.SQ_PK_PERMISSAO.NEXTVAL,
    1000731,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_DER.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000731
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: DETRAN | Orgao: DETRAN | ID_GRUPO_DE_USUARIO: 1000601
INSERT INTO SW_DETRAN.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_DETRAN.SQ_PK_PERMISSAO.NEXTVAL,
    1000601,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_DETRAN.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000601
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: EMATER | Orgao: EMATER | ID_GRUPO_DE_USUARIO: 1000720
INSERT INTO SW_EMATER.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_EMATER.SQ_PK_PERMISSAO.NEXTVAL,
    1000720,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_EMATER.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000720
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: EMGERPI | Orgao: EMGERPI | ID_GRUPO_DE_USUARIO: 1000025
INSERT INTO SW_EMGERPI.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_EMGERPI.SQ_PK_PERMISSAO.NEXTVAL,
    1000025,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_EMGERPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000025
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: FAPEPI | Orgao: FAPEPI | ID_GRUPO_DE_USUARIO: 1000560
INSERT INTO SW_FAPEPI.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_FAPEPI.SQ_PK_PERMISSAO.NEXTVAL,
    1000560,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_FAPEPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000560
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: FESPPI | Orgao: FESPPI | ID_GRUPO_DE_USUARIO: 1001560
INSERT INTO SW_FESPPI.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_FESPPI.SQ_PK_PERMISSAO.NEXTVAL,
    1001560,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_FESPPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1001560
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: FUESPI | Orgao: FUESPI | ID_GRUPO_DE_USUARIO: 1000729
INSERT INTO SW_FUESPI.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_FUESPI.SQ_PK_PERMISSAO.NEXTVAL,
    1000729,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_FUESPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000729
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: FUND RADIO E TV EDU | Orgao: TVANTARES | ID_GRUPO_DE_USUARIO: 1000605
INSERT INTO SW_TVANTARES.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_TVANTARES.SQ_PK_PERMISSAO.NEXTVAL,
    1000605,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_TVANTARES.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000605
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: FUPIP | Orgao: FUPIP | ID_GRUPO_DE_USUARIO: 1000742
INSERT INTO SW_FUPIP.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_FUPIP.SQ_PK_PERMISSAO.NEXTVAL,
    1000742,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_FUPIP.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000742
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: GMG | Orgao: GMG | ID_GRUPO_DE_USUARIO: 1000727
INSERT INTO SW_GMG.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_GMG.SQ_PK_PERMISSAO.NEXTVAL,
    1000727,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_GMG.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000727
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: IASPI | Orgao: IASPI | ID_GRUPO_DE_USUARIO: 1000723
INSERT INTO SW_IASPI.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_IASPI.SQ_PK_PERMISSAO.NEXTVAL,
    1000723,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_IASPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000723
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: IDEPI | Orgao: IDEPI | ID_GRUPO_DE_USUARIO: 1000562
INSERT INTO SW_IDEPI.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_IDEPI.SQ_PK_PERMISSAO.NEXTVAL,
    1000562,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_IDEPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000562
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: IMEPI | Orgao: IMEPI | ID_GRUPO_DE_USUARIO: 1000180
INSERT INTO SW_IMEPI.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_IMEPI.SQ_PK_PERMISSAO.NEXTVAL,
    1000180,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_IMEPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000180
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: INTERPI | Orgao: INTERPI | ID_GRUPO_DE_USUARIO: 1000724
INSERT INTO SW_INTERPI.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_INTERPI.SQ_PK_PERMISSAO.NEXTVAL,
    1000724,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_INTERPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000724
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: JUCEPI | Orgao: JUCEPI | ID_GRUPO_DE_USUARIO: 1000730
INSERT INTO SW_JUCEPI.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_JUCEPI.SQ_PK_PERMISSAO.NEXTVAL,
    1000730,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_JUCEPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000730
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: METROPI | Orgao: METRO | ID_GRUPO_DE_USUARIO: 1000026
INSERT INTO SW_METRO.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_METRO.SQ_PK_PERMISSAO.NEXTVAL,
    1000026,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_METRO.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000026
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: PGEPI | Orgao: PGEPI | ID_GRUPO_DE_USUARIO: 1000022
INSERT INTO SW_PGEPI.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_PGEPI.SQ_PK_PERMISSAO.NEXTVAL,
    1000022,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_PGEPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000022
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: PIAUIPREV | Orgao: PIAUIPREV | ID_GRUPO_DE_USUARIO: 1001260
INSERT INTO SW_PIAUIPREV.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_PIAUIPREV.SQ_PK_PERMISSAO.NEXTVAL,
    1001260,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_PIAUIPREV.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1001260
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: PMPI | Orgao: PMPI | ID_GRUPO_DE_USUARIO: 1000240
INSERT INTO SW_PMPI.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_PMPI.SQ_PK_PERMISSAO.NEXTVAL,
    1000240,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_PMPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000240
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: SADA | Orgao: SADA | ID_GRUPO_DE_USUARIO: 1001461
INSERT INTO SW_SADA.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SADA.SQ_PK_PERMISSAO.NEXTVAL,
    1001461,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_SADA.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1001461
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: SAF | Orgao: SAF | ID_GRUPO_DE_USUARIO: 1000728
INSERT INTO SW_SAF.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SAF.SQ_PK_PERMISSAO.NEXTVAL,
    1000728,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_SAF.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000728
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: SASC | Orgao: SASC | ID_GRUPO_DE_USUARIO: 1000745
INSERT INTO SW_SASC.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SASC.SQ_PK_PERMISSAO.NEXTVAL,
    1000745,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_SASC.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000745
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: SEADPREV | Orgao: SEADPREVPI | ID_GRUPO_DE_USUARIO: 1000140
INSERT INTO SW_SEADPREVPI.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SEADPREVPI.SQ_PK_PERMISSAO.NEXTVAL,
    1000140,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_SEADPREVPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000140
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: SEAGRO | Orgao: SEAGRO | ID_GRUPO_DE_USUARIO: 1000581
INSERT INTO SW_SEAGRO.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SEAGRO.SQ_PK_PERMISSAO.NEXTVAL,
    1000581,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_SEAGRO.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000581
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: SECESP | Orgao: SECESP | ID_GRUPO_DE_USUARIO: 1001440
INSERT INTO SW_SECESP.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SECESP.SQ_PK_PERMISSAO.NEXTVAL,
    1001440,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_SECESP.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1001440
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: SECID | Orgao: SECID | ID_GRUPO_DE_USUARIO: 1000600
INSERT INTO SW_SECID.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SECID.SQ_PK_PERMISSAO.NEXTVAL,
    1000600,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_SECID.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000600
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: SECULT | Orgao: SECULT | ID_GRUPO_DE_USUARIO: 1000721
INSERT INTO SW_SECULT.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SECULT.SQ_PK_PERMISSAO.NEXTVAL,
    1000721,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_SECULT.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000721
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: SEDET | Orgao: SEDET | ID_GRUPO_DE_USUARIO: 1000740
INSERT INTO SW_SEDET.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SEDET.SQ_PK_PERMISSAO.NEXTVAL,
    1000740,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_SEDET.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000740
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: SEDUC | Orgao: SEDUC | ID_GRUPO_DE_USUARIO: 1000980
INSERT INTO SW_SEDUC.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SEDUC.SQ_PK_PERMISSAO.NEXTVAL,
    1000980,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_SEDUC.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000980
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: SEFAZ | Orgao: SEFAZPI | ID_GRUPO_DE_USUARIO: 1000261
INSERT INTO SW_SEFAZPI.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SEFAZPI.SQ_PK_PERMISSAO.NEXTVAL,
    1000261,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_SEFAZPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000261
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: SEGOV | Orgao: SEGOV | ID_GRUPO_DE_USUARIO: 1000700
INSERT INTO SW_SEGOV.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SEGOV.SQ_PK_PERMISSAO.NEXTVAL,
    1000700,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_SEGOV.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000700
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: SEID | Orgao: SEID | ID_GRUPO_DE_USUARIO: 1000564
INSERT INTO SW_SEID.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SEID.SQ_PK_PERMISSAO.NEXTVAL,
    1000564,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_SEID.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000564
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: SEINFRA | Orgao: SEINFRA | ID_GRUPO_DE_USUARIO: 1000725
INSERT INTO SW_SEINFRA.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SEINFRA.SQ_PK_PERMISSAO.NEXTVAL,
    1000725,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_SEINFRA.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000725
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: SEJUS | Orgao: SEJUSPI | ID_GRUPO_DE_USUARIO: 1000260
INSERT INTO SW_SEJUSPI.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SEJUSPI.SQ_PK_PERMISSAO.NEXTVAL,
    1000260,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_SEJUSPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000260
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: SEMAR | Orgao: SEMAR | ID_GRUPO_DE_USUARIO: 1000726
INSERT INTO SW_SEMAR.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SEMAR.SQ_PK_PERMISSAO.NEXTVAL,
    1000726,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_SEMAR.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000726
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: SEMINPER | Orgao: SEMINPER | ID_GRUPO_DE_USUARIO: 1000543
INSERT INTO SW_SEMINPER.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SEMINPER.SQ_PK_PERMISSAO.NEXTVAL,
    1000543,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_SEMINPER.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000543
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: SEMPI | Orgao: SECMULHERES | ID_GRUPO_DE_USUARIO: 1001460
INSERT INTO SW_SECMULHERES.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SECMULHERES.SQ_PK_PERMISSAO.NEXTVAL,
    1001460,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_SECMULHERES.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1001460
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: SEPLAN | Orgao: SEPLAN | ID_GRUPO_DE_USUARIO: 1000744
INSERT INTO SW_SEPLAN.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SEPLAN.SQ_PK_PERMISSAO.NEXTVAL,
    1000744,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_SEPLAN.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000744
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: SERES | Orgao: SERES | ID_GRUPO_DE_USUARIO: 1001420
INSERT INTO SW_SERES.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SERES.SQ_PK_PERMISSAO.NEXTVAL,
    1001420,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_SERES.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1001420
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: SETRANS | Orgao: SETRANS | ID_GRUPO_DE_USUARIO: 1000604
INSERT INTO SW_SETRANS.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SETRANS.SQ_PK_PERMISSAO.NEXTVAL,
    1000604,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_SETRANS.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000604
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: SETRE | Orgao: SETRE | ID_GRUPO_DE_USUARIO: 1001920
INSERT INTO SW_SETRE.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SETRE.SQ_PK_PERMISSAO.NEXTVAL,
    1001920,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_SETRE.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1001920
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: SETUR | Orgao: SETUR | ID_GRUPO_DE_USUARIO: 1000602
INSERT INTO SW_SETUR.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SETUR.SQ_PK_PERMISSAO.NEXTVAL,
    1000602,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_SETUR.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000602
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: SIA | Orgao: SIA | ID_GRUPO_DE_USUARIO: 1001660
INSERT INTO SW_SIA.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SIA.SQ_PK_PERMISSAO.NEXTVAL,
    1001660,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_SIA.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1001660
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: SSPPI | Orgao: SSPPI | ID_GRUPO_DE_USUARIO: 1000023
INSERT INTO SW_SSPPI.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SSPPI.SQ_PK_PERMISSAO.NEXTVAL,
    1000023,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_SSPPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000023
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: SURPI | Orgao: SURPI | ID_GRUPO_DE_USUARIO: 1000563
INSERT INTO SW_SURPI.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_SURPI.SQ_PK_PERMISSAO.NEXTVAL,
    1000563,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_SURPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000563
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );

-- Grupo: VICEGOV | Orgao: VICEGOV | ID_GRUPO_DE_USUARIO: 1000606
INSERT INTO SW_VICEGOV.PERMISSAO (
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_VICEGOV.SQ_PK_PERMISSAO.NEXTVAL,
    1000606,
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (
        SELECT 1
        FROM SW_VICEGOV.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000606
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    );