INSERT INTO SW_IASPI.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_IASPI.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    G.ID_GRUPO_DE_USUARIO,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_IASPI.PERMISSAO P               -- SCHEMA ORIGEM
    JOIN SW_PUBLICO.GRUPO_DE_USUARIO G ON G.NOME NOT LIKE '%admin%' 
WHERE
    P.ID_GRUPO_DE_USUARIO IN (1001080) -- ID GRUPO DE USUARIO
    AND ID_PERMISSAO IN (2800423)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_IASPI.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = G.ID_GRUPO_DE_USUARIO -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )