INSERT INTO SW_COFIR.PERMISSAO (           -- SCHEMA DESTINO
    ID_PERMISSAO,
    ID_GRUPO_DE_USUARIO,
    ID_OBJETO_AUTORIZACAO,
    IND_TIPO,
    IND_VISUALIZAR,
    IND_ALTERAR,
    IND_ADICIONAR,
    IND_EXCLUIR,
    IND_VISUALIZAR_NA_GRID,
    IND_PESQUISAR
)
SELECT
    SW_COFIR.SQ_PK_PERMISSAO.NEXTVAL,      -- SEQUENCE DO SCHEMA DESTINO
    1000542,                      --ID_GRUPO
    P.ID_OBJETO_AUTORIZACAO,
    P.IND_TIPO,
    P.IND_VISUALIZAR,
    P.IND_ALTERAR,
    P.IND_ADICIONAR,
    P.IND_EXCLUIR,
    P.IND_VISUALIZAR_NA_GRID,
    P.IND_PESQUISAR
FROM
    SW_SESAPI.PERMISSAO P               -- SCHEMA ORIGEM
WHERE
    P.ID_PERMISSAO IN (1117764)
    AND NOT EXISTS (                        -- VERIFICA SE EXISTE A PERMISSS�O NO DESTINO
        SELECT
            1
        FROM
            SW_COFIR.PERMISSAO P2
        WHERE
                P2.ID_GRUPO_DE_USUARIO = 1000542 -- SE FOR PARA UM GRUPO DIFERENTE TEM QUE COLOCAR O ID AQUI
            AND P2.ID_OBJETO_AUTORIZACAO = P.ID_OBJETO_AUTORIZACAO
    )