SELECT 
    'SEDUC' ORGAO,
    FO.CHAVE_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    FFR.VALOR_CALCULADO VALOR,
    FD.ID_FUNCIONARIO,
    'DELETE FROM SW_SEDUC.FOLHA_FUNC_RUBRICA WHERE ID_FOLHA_FUNCIONARIO =' || FFR.ID_FOLHA_FUNCIONARIO || ';' AS DELETE_,
    'DELETE FROM SW_SEDUC.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_FOLHA_FUNCIONARIO = ' || FFR.ID_FOLHA_FUNCIONARIO || ';' AS DELETE_1
FROM 
    SW_SEDUC.FOLHA FO
    JOIN SW_SEDUC.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEDUC.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEDUC.FUNC_DESLIGAMENTO FD ON FD.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FD.DATA_REINGRESSO IS NULL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFR.ID_RUBRICA
WHERE 
    FO.MES = 7
    AND FO.ANO = 2026
    AND R.COD_RUBRICA = 999997
    AND FFR.VALOR_CALCULADO > 0