WITH RELATORIO AS (
SELECT '416872-X' MATRICULA, 48.38 VALOR FROM DUAL UNION ALL
SELECT '426921-7' MATRICULA, 468.99 VALOR FROM DUAL UNION ALL
SELECT '403040-X' MATRICULA, 444.61 VALOR FROM DUAL UNION ALL
SELECT '428116-X' MATRICULA, 21.55 VALOR FROM DUAL UNION ALL
SELECT '130116-X' MATRICULA, 235.27 VALOR FROM DUAL UNION ALL
SELECT '079631-0' MATRICULA, 6.8 VALOR FROM DUAL UNION ALL
SELECT '376390-X' MATRICULA, 34.41 VALOR FROM DUAL UNION ALL
SELECT '002751-X' MATRICULA, 2050.91 VALOR FROM DUAL UNION ALL
SELECT '440959-X' MATRICULA, 258.78 VALOR FROM DUAL UNION ALL
SELECT '159602-X' MATRICULA, 94.43 VALOR FROM DUAL UNION ALL
SELECT '178487-X' MATRICULA, 199.56 VALOR FROM DUAL UNION ALL
SELECT '413602-X' MATRICULA, 24.38 VALOR FROM DUAL UNION ALL
SELECT '003916-X' MATRICULA, 287.22 VALOR FROM DUAL UNION ALL
SELECT '442274-X' MATRICULA, 414.99 VALOR FROM DUAL UNION ALL
SELECT '434518-5' MATRICULA, 177.98 VALOR FROM DUAL UNION ALL
SELECT '021557-X' MATRICULA, 1011.86 VALOR FROM DUAL UNION ALL
SELECT '019355-X' MATRICULA, 424.93 VALOR FROM DUAL UNION ALL
SELECT '024746-4' MATRICULA, 87.12 VALOR FROM DUAL UNION ALL
SELECT '164511-X' MATRICULA, 103.02 VALOR FROM DUAL UNION ALL
SELECT '021028-5' MATRICULA, 197.06 VALOR FROM DUAL UNION ALL
SELECT '180739-X' MATRICULA, 385.48 VALOR FROM DUAL UNION ALL
SELECT '385039-X' MATRICULA, 295.01 VALOR FROM DUAL UNION ALL
SELECT '006213-8' MATRICULA, 10.93 VALOR FROM DUAL UNION ALL
SELECT '407482-3' MATRICULA, 66.52 VALOR FROM DUAL UNION ALL
SELECT '411575-9' MATRICULA, 24.99 VALOR FROM DUAL UNION ALL
SELECT '232568-3' MATRICULA, 245.53 VALOR FROM DUAL UNION ALL
SELECT '418462-9' MATRICULA, 105.01 VALOR FROM DUAL UNION ALL
SELECT '157953-3' MATRICULA, 7.11 VALOR FROM DUAL UNION ALL
SELECT '232550-X' MATRICULA, 242.84 VALOR FROM DUAL UNION ALL
SELECT '109650-8' MATRICULA, 22.34 VALOR FROM DUAL UNION ALL
SELECT '235238-9' MATRICULA, 27.4 VALOR FROM DUAL UNION ALL
SELECT '331944-0' MATRICULA, 489.08 VALOR FROM DUAL UNION ALL
SELECT '425125-3' MATRICULA, 139.03 VALOR FROM DUAL UNION ALL
SELECT '172175-5' MATRICULA, 130.72 VALOR FROM DUAL UNION ALL
SELECT '205771-9' MATRICULA, 51.52 VALOR FROM DUAL UNION ALL
SELECT '233018-X' MATRICULA, 721.93 VALOR FROM DUAL UNION ALL
SELECT '226781-X' MATRICULA, 21.61 VALOR FROM DUAL UNION ALL
SELECT '438825-9' MATRICULA, 93.3 VALOR FROM DUAL UNION ALL
SELECT '233761-4' MATRICULA, 2.34 VALOR FROM DUAL UNION ALL
SELECT '403930-X' MATRICULA, 1.94 VALOR FROM DUAL UNION ALL
SELECT '411851-X' MATRICULA, 47.16 VALOR FROM DUAL UNION ALL
SELECT '444011-X' MATRICULA, 420.5 VALOR FROM DUAL UNION ALL
SELECT '109497-1' MATRICULA, 110.06 VALOR FROM DUAL UNION ALL
SELECT '434212-7' MATRICULA, 58.94 VALOR FROM DUAL UNION ALL
SELECT '444588-X' MATRICULA, 119.94 VALOR FROM DUAL UNION ALL
SELECT '233689-8' MATRICULA, 78.44 VALOR FROM DUAL UNION ALL
SELECT '444076-5' MATRICULA, 2.11 VALOR FROM DUAL UNION ALL
SELECT '143321-X' MATRICULA, 452.72 VALOR FROM DUAL UNION ALL
SELECT '103403-X' MATRICULA, 223.44 VALOR FROM DUAL UNION ALL
SELECT '086294-X' MATRICULA, 67.27 VALOR FROM DUAL UNION ALL
SELECT '320689-X' MATRICULA, 44.62 VALOR FROM DUAL UNION ALL
SELECT '161365-X' MATRICULA, 50.69 VALOR FROM DUAL UNION ALL
SELECT '086049-2' MATRICULA, 366.97 VALOR FROM DUAL UNION ALL
SELECT '406309-X' MATRICULA, 355.36 VALOR FROM DUAL UNION ALL
SELECT '232712-X' MATRICULA, 201.28 VALOR FROM DUAL UNION ALL
SELECT '394715-7' MATRICULA, 66.52 VALOR FROM DUAL UNION ALL
SELECT '171247-X' MATRICULA, 151.9 VALOR FROM DUAL UNION ALL
SELECT '143416-X' MATRICULA, 161.77 VALOR FROM DUAL UNION ALL
SELECT '221783-0' MATRICULA, 110.93 VALOR FROM DUAL UNION ALL
SELECT '237389-X' MATRICULA, 58.67 VALOR FROM DUAL UNION ALL
SELECT '064374-2' MATRICULA, 506.28 VALOR FROM DUAL UNION ALL
SELECT '317066-7' MATRICULA, 11.87 VALOR FROM DUAL UNION ALL
SELECT '444092-7' MATRICULA, 55.48 VALOR FROM DUAL UNION ALL
SELECT '429055-X' MATRICULA, 0.89 VALOR FROM DUAL UNION ALL
SELECT '109426-2' MATRICULA, 179.19 VALOR FROM DUAL UNION ALL
SELECT '148933-0' MATRICULA, 123.97 VALOR FROM DUAL UNION ALL
SELECT '234041-X' MATRICULA, 272.06 VALOR FROM DUAL UNION ALL
SELECT '426228-0' MATRICULA, 76.94 VALOR FROM DUAL UNION ALL
SELECT '417550-6' MATRICULA, 232.64 VALOR FROM DUAL UNION ALL
SELECT '316982-X' MATRICULA, 445.95 VALOR FROM DUAL UNION ALL
SELECT '156778-X' MATRICULA, 30.41 VALOR FROM DUAL UNION ALL
SELECT '411383-7' MATRICULA, 41.53 VALOR FROM DUAL UNION ALL
SELECT '406391-X' MATRICULA, 166.76 VALOR FROM DUAL UNION ALL
SELECT '221867-4' MATRICULA, 148.66 VALOR FROM DUAL UNION ALL
SELECT '406026-1' MATRICULA, 39.33 VALOR FROM DUAL UNION ALL
SELECT '229853-8' MATRICULA, 2.04 VALOR FROM DUAL UNION ALL
SELECT '103972-5' MATRICULA, 240.63 VALOR FROM DUAL UNION ALL
SELECT '441941-3' MATRICULA, 157.77 VALOR FROM DUAL UNION ALL
SELECT '425047-8' MATRICULA, 89.31 VALOR FROM DUAL UNION ALL
SELECT '403443-X' MATRICULA, 246.5 VALOR FROM DUAL UNION ALL
SELECT '403880-X' MATRICULA, 189.84 VALOR FROM DUAL UNION ALL
SELECT '414799-5' MATRICULA, 98.5 VALOR FROM DUAL UNION ALL
SELECT '403783-9' MATRICULA, 151.59 VALOR FROM DUAL UNION ALL
SELECT '025519-0' MATRICULA, 289.65 VALOR FROM DUAL UNION ALL
SELECT '025461-4' MATRICULA, 574.95 VALOR FROM DUAL UNION ALL
SELECT '037192-X' MATRICULA, 47.53 VALOR FROM DUAL UNION ALL
SELECT '025080-5' MATRICULA, 394.54 VALOR FROM DUAL UNION ALL
SELECT '330210-5' MATRICULA, 668.58 VALOR FROM DUAL UNION ALL
SELECT '025482-7' MATRICULA, 182.53 VALOR FROM DUAL UNION ALL
SELECT '025169-X' MATRICULA, 59.61 VALOR FROM DUAL UNION ALL
SELECT '146134-6' MATRICULA, 356.12 VALOR FROM DUAL UNION ALL
SELECT '082911-X' MATRICULA, 684.12 VALOR FROM DUAL UNION ALL
SELECT '408061-X' MATRICULA, 117.73 VALOR FROM DUAL UNION ALL
SELECT '082870-0' MATRICULA, 264.39 VALOR FROM DUAL UNION ALL
SELECT '013680-8' MATRICULA, 16.76 VALOR FROM DUAL UNION ALL
SELECT '404804-X' MATRICULA, 47.06 VALOR FROM DUAL UNION ALL
SELECT '014642-X' MATRICULA, 135.99 VALOR FROM DUAL UNION ALL
SELECT '298038-0' MATRICULA, 121.34 VALOR FROM DUAL UNION ALL
SELECT '281036-X' MATRICULA, 130.63 VALOR FROM DUAL 
)
SELECT
    S.ID_FOLHA,
    S.ID_FOLHA_FUNCIONARIO,
    S.ORGAO,
    S.CHAVE_FOLHA,
    NVL(S.MATRICULA, RE.MATRICULA) MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RE.VALOR VALOR_PICPAY,
    S.VALOR_LIQUIDO,
    S.VALOR_LIQUIDO - RE.VALOR SUB,
    'INSERT INTO SW_' || S.ORGAO || '.FOLHA_FUNC_RUBRICA_IMPORTADA (ID_RUBRICA_IMPORTADA, ID_FOLHA_FUNCIONARIO,  ID_RUBRICA,  IND_TIPO, ID_FOLHA_VALORES, PRAZO_PARCELA, PRAZO_TOTAL, IND_PARAMETRO, IND_ORIGEM, VALOR_MULTIPLICADOR, IND_FORMA_ATUALIZACAO, DATA_CADASTRO, DATA_INICIO, DATA_FIM, ANO_REFERENCIA, MES_REFERENCIA, IND_SUBSTITUICAO, OBSERVACAO) VALUES (SW_' || S.ORGAO || '.SQ_PK_RUBRICA_IMPORTADA.NEXTVAL, ' || S.ID_FOLHA_FUNCIONARIO || ', ' || R.ID_RUBRICA || ', ''' || R.TIPO || ''', ' || S.ID_FOLHA || ', ''001'', ''001'', ''V'', ''D'', ' || REPLACE(RE.VALOR, ',', '.') || ', ''D'', ''' || SYSDATE || ''', ''01/08/2026'', ''31/08/2026'', 2026, 8, ''S'', ''Adiantamento PICPAY REDMINE 7933'');' INSERT_,
    'UPDATE SW_' || S.ORGAO || '.FOLHA_FUNC SET IND_CALCULAR = ''S'', IND_GERAR_EVENTOS = ''S'', IND_GERAR_RUBRICAS = ''S'' WHERE ID_FOLHA_FUNCIONARIO = ' || S.ID_FOLHA_FUNCIONARIO || ';' MARCAR
FROM
    RELATORIO RE
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.COD_RUBRICA = 511027
    LEFT JOIN (
    SELECT
        'ADAPI' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_ADAPI.FOLHA FO
        JOIN SW_ADAPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_ADAPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'ADH' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_ADH.FOLHA FO
        JOIN SW_ADH.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_ADH.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'AGESPISA' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_AGESPISA.FOLHA FO
        JOIN SW_AGESPISA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_AGESPISA.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'AGRESP' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_AGRESP.FOLHA FO
        JOIN SW_AGRESP.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_AGRESP.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'BEP' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_BEP.FOLHA FO
        JOIN SW_BEP.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_BEP.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'CBMPI' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_CBMPI.FOLHA FO
        JOIN SW_CBMPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_CBMPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'CCOM' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_CCOM.FOLHA FO
        JOIN SW_CCOM.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_CCOM.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'CDTER' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_CDTER.FOLHA FO
        JOIN SW_CDTER.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_CDTER.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'CENDROGAS' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_CENDROGAS.FOLHA FO
        JOIN SW_CENDROGAS.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_CENDROGAS.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'COFIR' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_COFIR.FOLHA FO
        JOIN SW_COFIR.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_COFIR.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'COJUV' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_COJUV.FOLHA FO
        JOIN SW_COJUV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_COJUV.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'CPVCI' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_CPVCI.FOLHA FO
        JOIN SW_CPVCI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_CPVCI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'DEFCIVIL' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_DEFCIVIL.FOLHA FO
        JOIN SW_DEFCIVIL.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_DEFCIVIL.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'DER' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_DER.FOLHA FO
        JOIN SW_DER.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_DER.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'DETRAN' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_DETRAN.FOLHA FO
        JOIN SW_DETRAN.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_DETRAN.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'EMGERPI' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_EMGERPI.FOLHA FO
        JOIN SW_EMGERPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'EMGERPI_CEASA' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_EMGERPI_CEASA.FOLHA FO
        JOIN SW_EMGERPI_CEASA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_CEASA.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'EMGERPI_CIDAPI' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_EMGERPI_CIDAPI.FOLHA FO
        JOIN SW_EMGERPI_CIDAPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_CIDAPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'EMGERPI_CODIPI' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_EMGERPI_CODIPI.FOLHA FO
        JOIN SW_EMGERPI_CODIPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_CODIPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'EMGERPI_COHAB' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_EMGERPI_COHAB.FOLHA FO
        JOIN SW_EMGERPI_COHAB.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_COHAB.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'EMGERPI_COMDEPI' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_EMGERPI_COMDEPI.FOLHA FO
        JOIN SW_EMGERPI_COMDEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_COMDEPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'EMGERPI_COMEPI' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_EMGERPI_COMEPI.FOLHA FO
        JOIN SW_EMGERPI_COMEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_COMEPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'EMGERPI_CORESA' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_EMGERPI_CORESA.FOLHA FO
        JOIN SW_EMGERPI_CORESA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_CORESA.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'EMGERPI_EMATER' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_EMGERPI_EMATER.FOLHA FO
        JOIN SW_EMGERPI_EMATER.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_EMATER.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'EMGERPI_ETELPI_FUNART' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_EMGERPI_ETELPI_FUNART.FOLHA FO
        JOIN SW_EMGERPI_ETELPI_FUNART.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_ETELPI_FUNART.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'EMGERPI_PIEMTUR' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_EMGERPI_PIEMTUR.FOLHA FO
        JOIN SW_EMGERPI_PIEMTUR.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_PIEMTUR.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'EMGERPI_PRODEPI' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_EMGERPI_PRODEPI.FOLHA FO
        JOIN SW_EMGERPI_PRODEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_EMGERPI_PRODEPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'FAPEPI' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_FAPEPI.FOLHA FO
        JOIN SW_FAPEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_FAPEPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'FESPPI' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_FESPPI.FOLHA FO
        JOIN SW_FESPPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_FESPPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'FUESPI' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_FUESPI.FOLHA FO
        JOIN SW_FUESPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_FUESPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'FUPIP' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_FUPIP.FOLHA FO
        JOIN SW_FUPIP.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_FUPIP.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'GMG' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_GMG.FOLHA FO
        JOIN SW_GMG.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_GMG.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'IASPI' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_IASPI.FOLHA FO
        JOIN SW_IASPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_IASPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'IDEPI' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_IDEPI.FOLHA FO
        JOIN SW_IDEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_IDEPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'IMEPI' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_IMEPI.FOLHA FO
        JOIN SW_IMEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_IMEPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'INTERPI' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_INTERPI.FOLHA FO
        JOIN SW_INTERPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_INTERPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'JUCEPI' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_JUCEPI.FOLHA FO
        JOIN SW_JUCEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_JUCEPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'METRO' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_METRO.FOLHA FO
        JOIN SW_METRO.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_METRO.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'PGEPI' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_PGEPI.FOLHA FO
        JOIN SW_PGEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_PGEPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'PMPI' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_PMPI.FOLHA FO
        JOIN SW_PMPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_PMPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'SADA' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_SADA.FOLHA FO
        JOIN SW_SADA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SADA.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'SAF' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_SAF.FOLHA FO
        JOIN SW_SAF.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SAF.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'SASC' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_SASC.FOLHA FO
        JOIN SW_SASC.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SASC.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'SEADPREVPI' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_SEADPREVPI.FOLHA FO
        JOIN SW_SEADPREVPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEADPREVPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'SEAGRO' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_SEAGRO.FOLHA FO
        JOIN SW_SEAGRO.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEAGRO.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'SECESP' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_SECESP.FOLHA FO
        JOIN SW_SECESP.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SECESP.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'SECID' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_SECID.FOLHA FO
        JOIN SW_SECID.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SECID.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'SECMULHERES' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_SECMULHERES.FOLHA FO
        JOIN SW_SECMULHERES.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SECMULHERES.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'SECULT' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_SECULT.FOLHA FO
        JOIN SW_SECULT.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SECULT.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'SEDET' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_SEDET.FOLHA FO
        JOIN SW_SEDET.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEDET.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'SEDUC' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_SEDUC.FOLHA FO
        JOIN SW_SEDUC.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEDUC.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'SEFAZPI' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_SEFAZPI.FOLHA FO
        JOIN SW_SEFAZPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEFAZPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'SEGOV' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_SEGOV.FOLHA FO
        JOIN SW_SEGOV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEGOV.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'SEID' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_SEID.FOLHA FO
        JOIN SW_SEID.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEID.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'SEINFRA' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_SEINFRA.FOLHA FO
        JOIN SW_SEINFRA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEINFRA.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'SEJUSPI' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_SEJUSPI.FOLHA FO
        JOIN SW_SEJUSPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEJUSPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'SEMAR' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_SEMAR.FOLHA FO
        JOIN SW_SEMAR.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEMAR.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'SEMINPER' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_SEMINPER.FOLHA FO
        JOIN SW_SEMINPER.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEMINPER.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'SEPLAN' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_SEPLAN.FOLHA FO
        JOIN SW_SEPLAN.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEPLAN.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'SERES' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_SERES.FOLHA FO
        JOIN SW_SERES.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SERES.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'SESAPI' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_SESAPI.FOLHA FO
        JOIN SW_SESAPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SESAPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'SETRANS' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_SETRANS.FOLHA FO
        JOIN SW_SETRANS.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SETRANS.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'SETUR' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_SETUR.FOLHA FO
        JOIN SW_SETUR.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SETUR.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'SIA' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_SIA.FOLHA FO
        JOIN SW_SIA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SIA.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'SSPPI' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_SSPPI.FOLHA FO
        JOIN SW_SSPPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SSPPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'SURPI' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_SURPI.FOLHA FO
        JOIN SW_SURPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SURPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'TVANTARES' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_TVANTARES.FOLHA FO
        JOIN SW_TVANTARES.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_TVANTARES.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    UNION ALL
    SELECT
        'VICEGOV' ORGAO,
        FO.CHAVE_FOLHA,
        FF.COD_INSTITUCIONAL MATRICULA,
        FR.VALOR_CALCULADO VALOR_LIQUIDO,
        FO.ID_FOLHA,
        FF.ID_FOLHA_FUNCIONARIO
    FROM
        SW_VICEGOV.FOLHA FO
        JOIN SW_VICEGOV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_VICEGOV.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    WHERE
        FO.MES = 8
        AND FO.ANO = 2026
        AND FF.IND_REMUNERACAO  = 'S'
        AND FR.ID_RUBRICA = 51025
        AND SUBSTR(FO.CHAVE_FOLHA, 9) IN ('100', '110', '120','230','240','250','260','270','280','290')
    ) S ON S.MATRICULA = RE.MATRICULA