DELETE FROM SW_SEDUC.ATUA_AUTO_PROG_GER_LIST_PESSOA WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.AUDITORIA_ERRO_IMPORTACAO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.BATI_FREQ_PONTO WHERE ID_PESSOA_VINCULO IN (SELECT DISTINCT F.ID_PESSOA_VINCULO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.DIARIA_FUNCIONARIO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.DISPOSITIVO_PONTO WHERE ID_PESSOA_VINCULO IN (SELECT DISTINCT F.ID_PESSOA_VINCULO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FOLHA_APOSEN_CALC_REM_MEDIA WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FOLHA_CONSIG_CONSIGNADO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FOLHA_EXERCICIO_ANTERIOR_FUNC WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FOLHA_FICHA_FINANCEIRA WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FOLHA_FUNC_ANOTACAO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FOLHA_FUNC_ANOTACAO_IMPOR WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FOLHA_FUNC_RUBRICA WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_FOLHA_FUNCIONARIO IN (SELECT DISTINCT FF.ID_FOLHA_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO JOIN SW_SEDUC.FOLHA_FUNC FF ON FF.ID_FUNCIONARIO = F.ID_FUNCIONARIO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FOLHA_IMP_FUNC WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FOLHA_IMP_FUNC_RUBRICA WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FOLHA_MSG_FUNCIONARIO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FOLHA_SALDO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FOL_REL_FICH_FINA WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FOL_REL_FICH_FINA_PER WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FOL_REL_GER_COMP_FOLHA WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FOL_REL_GER_COMP_FOLHA_ABE WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_APOSENTADORIA WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_APOSENTADORIA_CERTIDOES WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_APOSENT_CERTI_WORD WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_AUTORIZACAO_FERIAS WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_AVERBACAO_TEMPO_FICTO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_BENEFICIO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_CENTRO_CUSTO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_CESSAO_REQUISICAO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_DEPENDENTE_IR_SF WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_DESLIGAMENTO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_ENT_EXT_APOSENTADORIA WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_ENT_EXT_CARGO_ACUMULA WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_ENT_EXT_FUNC_COMISSIONADA WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_ENT_EXT_TEMPO_FERIAS WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_FREQ_ATRASO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_FREQ_BANCO_HORA WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_FREQ_FALTA WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_FREQ_FALTAS_LEGADO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_FREQ_FALTAS_MENSAIS WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_FREQ_FE_PREM_CONT_DOB WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_FREQ_FE_PREM_CONV_ESPE WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_FREQ_FERIAS WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_FREQ_FERIAS_PREMIO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_FREQ_FERIAS_PREMIO_PERIOD WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_FREQ_HORA_EXTRA WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_FREQ_JUST_FALTAS_MENSAIS WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_FREQ_LICENCA WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_FREQ_PONTO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_FREQ_RECESSO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_FREQ_SUSPENSAO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNCIONARIO_ADC_TEMPO_SERVICO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNCIONARIO_CRACHA_PROVISORIO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNCIONARIO_DOC_DIGITAL WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNCIONARIO_FUNCAO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FOLHA_IMP_FUNC_FUNCAO_NOMEACAO WHERE ID_FUNCIONARIO_FUNCAO IN (SELECT DISTINCT FN.ID_FUNCIONARIO_FUNCAO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO JOIN SW_SEDUC.FUNCIONARIO_FUNCAO_NOMEACAO FN ON FN.ID_FUNCIONARIO = F.ID_FUNCIONARIO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FOLHA_IMP_FUNC_CET_NOMEACAO WHERE ID_FOLHA_PERFIL IN (SELECT DISTINCT FP.ID_FOLHA_PERFIL FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO JOIN SW_SEDUC.FOLHA_FUNC FF ON FF.ID_FUNCIONARIO = F.ID_FUNCIONARIO JOIN SW_SEDUC.FOLHA_FUNC_PERFIL FP ON FP.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FOLHA_FUNC_CET_NOMEACAO WHERE ID_FOLHA_PERFIL IN (SELECT DISTINCT FP.ID_FOLHA_PERFIL FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO JOIN SW_SEDUC.FOLHA_FUNC FF ON FF.ID_FUNCIONARIO = F.ID_FUNCIONARIO JOIN SW_SEDUC.FOLHA_FUNC_PERFIL FP ON FP.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNCIONARIO_FUNCAO_CET_NOMEAC WHERE ID_FUNCIONARIO_FUNCAO IN (SELECT DISTINCT FN.ID_FUNCIONARIO_FUNCAO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO JOIN SW_SEDUC.FUNCIONARIO_FUNCAO_NOMEACAO FN ON FN.ID_FUNCIONARIO = F.ID_FUNCIONARIO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FOLHA_FUNC_FUNCAO_NOMEACAO WHERE ID_FUNCIONARIO_FUNCAO IN (SELECT DISTINCT FN.ID_FUNCIONARIO_FUNCAO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO JOIN SW_SEDUC.FUNCIONARIO_FUNCAO_NOMEACAO FN ON FN.ID_FUNCIONARIO = F.ID_FUNCIONARIO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNCIONARIO_FUNCAO_NOMEACAO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNCIONARIO_FUNCAO_NOME_TEMP WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNCIONARIO_INF_GOVE_LOT_TRIB WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNCIONARIO_INF_GOVERNO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNCIONARIO_INF_GOVERNO_HIST WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNCIONARIO_INF_PARAMETRIZADA WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNCIONARIO_INGRESSO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNCIONARIO_JORNADA WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNCIONARIO_SEGURIDADE_SOCIAL WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNCIONARIO_SINDICALIZACAO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNCIONARIO_TRIBUNAL_CONTAS WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_LOTACAO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_OCORR_ANOTACAO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_OCORR_DECLARACAO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_OCORR_ELOGIO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_OCORR_IMPEDIMENTO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_OCORR_INDICACAO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_OCORR_INDICACAO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_OCORR_PENALIDADE WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_OCORR_RESSARCIMENTO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_PEN_ALIM_GRUPO_FAMILIAR WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_PEN_ALIM_PENSIONISTA WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_PEN_CIVIL_GRUPO_FAMILIAR WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_PENSAO_CIVIL WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_PRESTACAO_SERVICO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_REMOCAO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_SUBSTITUICAO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_VANTAGEM_ADICION_QUALIFIC WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_VANTAGEM_PESSOAL WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_VANTAGEM_TEMPO_CARREIRA WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_VANTAGEM_TEMPO_CATEG WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_VANTAGEM_TEMPO_SERVICO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.JORNADA_ESPECIAL_SOLICITACAO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.JORNADA_TIPO_JORNADA WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.JUSTIFICATIVA_PONTO WHERE ID_PESSOA_VINCULO IN (SELECT DISTINCT F.ID_PESSOA_VINCULO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.PENS_CIVI_SEM_INSTITUIDOR WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.PREVIDENCIA_PROPRIA_PESSOA WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.RHB_AUTORIZACAO_ABONO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.RHB_AUTORIZACAO_FERIAS WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.RHB_CARREIRA_VAGA WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.SEG_TRAB_ACIDENTE WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.SEG_TRAB_FUNCIONARIO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.SOLICITACAO_FERIAS WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNCIONARIO_REFERENCIA WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FOLHA_IMP_FUNC_PERFIL WHERE ID_FUNCIONARIO_PERFIL IN (SELECT DISTINCT FP.ID_FUNCIONARIO_PERFIL FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO JOIN SW_SEDUC.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FOLHA_IMP_FUNC_PERFIL WHERE ID_FOLHA_PERFIL IN (SELECT DISTINCT FP.ID_FOLHA_PERFIL FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO JOIN SW_SEDUC.FOLHA_FUNC FF ON FF.ID_FUNCIONARIO = F.ID_FUNCIONARIO JOIN SW_SEDUC.FOLHA_FUNC_PERFIL FP ON FP.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FOLHA_FUNC_EVENTO WHERE ID_FOLHA_PERFIL IN (SELECT DISTINCT FP.ID_FOLHA_PERFIL FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO JOIN SW_SEDUC.FOLHA_FUNC FF ON FF.ID_FUNCIONARIO = F.ID_FUNCIONARIO JOIN SW_SEDUC.FOLHA_FUNC_PERFIL FP ON FP.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FOLHA_FUNC_PERFIL WHERE ID_FOLHA_PERFIL IN (SELECT DISTINCT FP.ID_FOLHA_PERFIL FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO JOIN SW_SEDUC.FOLHA_FUNC FF ON FF.ID_FUNCIONARIO = F.ID_FUNCIONARIO JOIN SW_SEDUC.FOLHA_FUNC_PERFIL FP ON FP.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNCIONARIO_PERFIL WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FOLHA_CONTRACHEQUE WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FOLHA_AVOS_NATALINA WHERE ID_FOLHA_FUNCIONARIO IN (SELECT DISTINCT FF.ID_FOLHA_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO JOIN SW_SEDUC.FOLHA_FUNC FF ON FF.ID_FUNCIONARIO = F.ID_FUNCIONARIO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FOLHA_FUNC_AUDITORIA WHERE ID_FOLHA_FUNCIONARIO IN (SELECT DISTINCT FF.ID_FOLHA_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO JOIN SW_SEDUC.FOLHA_FUNC FF ON FF.ID_FUNCIONARIO = F.ID_FUNCIONARIO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FOLHA_FUNC WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.AUDITORIA_CALCULO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNCIONARIO_FUNCAO_NOMEACAO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNCIONARIO WHERE ID_FUNCIONARIO IN (SELECT DISTINCT F.ID_FUNCIONARIO FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.FUNC_PENSAO_CIVIL WHERE ID_PENSIONISTA IN (SELECT DISTINCT PC.ID_PENSIONISTA FROM SW_SEDUC.PESSOA_VINCULO PV JOIN SW_SEDUC.FUNC_PENSAO_CIVIL PC ON PC.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.MENSAGEM WHERE ID_PESSOA_VINCULO IN (SELECT PV.ID_PESSOA_VINCULO FROM SW_SEDUC.PESSOA_VINCULO PV WHERE PV.ID_PESSOA_VINCULO IN (1212265));

DELETE FROM SW_SEDUC.PESSOA_VINCULO WHERE ID_PESSOA_VINCULO IN (SELECT PV.ID_PESSOA_VINCULO FROM SW_SEDUC.PESSOA_VINCULO PV WHERE PV.ID_PESSOA_VINCULO IN (1212265));