DELETE FROM SW_DEFENSORIA.ESOCIAL_EVENTO_ATRIBUTO
WHERE ID_ESOCIAL_EVENTO = 1300619;

DELETE FROM SW_DEFENSORIA.ESOCIAL_TRANSMISSAO
WHERE ID_ESOCIAL_EVENTO = 1300619;

DELETE FROM SW_DEFENSORIA.ESOCIAL_EVENTO_OCORRENCIA
WHERE ID_ESOCIAL_EVENTO = 1300619;

DELETE FROM SW_DEFENSORIA.ESOCIAL_EVENTO_RETORNO
WHERE ID_ESOCIAL_EVENTO_PAI = 1300619;

DELETE FROM SW_DEFENSORIA.ESOCIAL_EVENTO
WHERE ID_ESOCIAL_EVENTO = 1300619;