SELECT 
    'CBMPI' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_CBMPI.FOLHA FO
    JOIN SW_CBMPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CBMPI.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'PGEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_PGEPI.FOLHA FO
    JOIN SW_PGEPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PGEPI.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'CGEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_CGEPI.FOLHA FO
    JOIN SW_CGEPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CGEPI.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'SSPPI' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_SSPPI.FOLHA FO
    JOIN SW_SSPPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SSPPI.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'COJUV' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_COJUV.FOLHA FO
    JOIN SW_COJUV.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_COJUV.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'ATIPI' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_ATIPI.FOLHA FO
    JOIN SW_ATIPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_ATIPI.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'FAPEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_FAPEPI.FOLHA FO
    JOIN SW_FAPEPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FAPEPI.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'DEFCIVIL' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_DEFCIVIL.FOLHA FO
    JOIN SW_DEFCIVIL.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_DEFCIVIL.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'ADH' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_ADH.FOLHA FO
    JOIN SW_ADH.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_ADH.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'SEAGRO' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_SEAGRO.FOLHA FO
    JOIN SW_SEAGRO.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEAGRO.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'IDEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_IDEPI.FOLHA FO
    JOIN SW_IDEPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_IDEPI.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'SURPI' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_SURPI.FOLHA FO
    JOIN SW_SURPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SURPI.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'SEID' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_SEID.FOLHA FO
    JOIN SW_SEID.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEID.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'SECID' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_SECID.FOLHA FO
    JOIN SW_SECID.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SECID.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'FUPIP' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_FUPIP.FOLHA FO
    JOIN SW_FUPIP.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUPIP.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'SETUR' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_SETUR.FOLHA FO
    JOIN SW_SETUR.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SETUR.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'AGESPISA' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_AGESPISA.FOLHA FO
    JOIN SW_AGESPISA.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_AGESPISA.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'SETRANS' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_SETRANS.FOLHA FO
    JOIN SW_SETRANS.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SETRANS.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'TVANTARES' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_TVANTARES.FOLHA FO
    JOIN SW_TVANTARES.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_TVANTARES.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'VICEGOV' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_VICEGOV.FOLHA FO
    JOIN SW_VICEGOV.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_VICEGOV.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'SEINFRA' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_SEINFRA.FOLHA FO
    JOIN SW_SEINFRA.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEINFRA.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'CCOM' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_CCOM.FOLHA FO
    JOIN SW_CCOM.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CCOM.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'FUNDESPI' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_FUNDESPI.FOLHA FO
    JOIN SW_FUNDESPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUNDESPI.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'SEDET' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_SEDET.FOLHA FO
    JOIN SW_SEDET.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEDET.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'INTERPI' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_INTERPI.FOLHA FO
    JOIN SW_INTERPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_INTERPI.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'JUCEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_JUCEPI.FOLHA FO
    JOIN SW_JUCEPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_JUCEPI.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'SEMAR' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_SEMAR.FOLHA FO
    JOIN SW_SEMAR.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEMAR.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'GMG' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_GMG.FOLHA FO
    JOIN SW_GMG.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_GMG.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'SEPLAN' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_SEPLAN.FOLHA FO
    JOIN SW_SEPLAN.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEPLAN.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'SAF' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_SAF.FOLHA FO
    JOIN SW_SAF.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SAF.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'SECULT' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_SECULT.FOLHA FO
    JOIN SW_SECULT.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SECULT.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'DER' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_DER.FOLHA FO
    JOIN SW_DER.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_DER.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'DETRAN' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_DETRAN.FOLHA FO
    JOIN SW_DETRAN.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_DETRAN.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'IASPI' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_IASPI.FOLHA FO
    JOIN SW_IASPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_IASPI.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'ADAPI' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_ADAPI.FOLHA FO
    JOIN SW_ADAPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_ADAPI.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'IMEPIPROD' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_IMEPIPROD.FOLHA FO
    JOIN SW_IMEPIPROD.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_IMEPIPROD.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'CPVCI' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_CPVCI.FOLHA FO
    JOIN SW_CPVCI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CPVCI.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'CENDROGAS' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_CENDROGAS.FOLHA FO
    JOIN SW_CENDROGAS.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CENDROGAS.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'COFIR' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_COFIR.FOLHA FO
    JOIN SW_COFIR.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_COFIR.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'SEMINPER' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_SEMINPER.FOLHA FO
    JOIN SW_SEMINPER.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEMINPER.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'AGRESP' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_AGRESP.FOLHA FO
    JOIN SW_AGRESP.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_AGRESP.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'CEPM' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_CEPM.FOLHA FO
    JOIN SW_CEPM.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CEPM.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'EMATER' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_EMATER.FOLHA FO
    JOIN SW_EMATER.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMATER.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'FUESPI' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_FUESPI.FOLHA FO
    JOIN SW_FUESPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUESPI.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'EMATERPROD' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_EMATERPROD.FOLHA FO
    JOIN SW_EMATERPROD.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMATERPROD.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'CDTER' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_CDTER.FOLHA FO
    JOIN SW_CDTER.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CDTER.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'SERES' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_SERES.FOLHA FO
    JOIN SW_SERES.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SERES.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'SECESP' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_SECESP.FOLHA FO
    JOIN SW_SECESP.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SECESP.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'EMGERPI_CORESA' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_EMGERPI_CORESA.FOLHA FO
    JOIN SW_EMGERPI_CORESA.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_CORESA.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'FUNPREV' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_FUNPREV.FOLHA FO
    JOIN SW_FUNPREV.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUNPREV.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'FESPPI' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_FESPPI.FOLHA FO
    JOIN SW_FESPPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FESPPI.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'SIA' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_SIA.FOLHA FO
    JOIN SW_SIA.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SIA.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'SETRE' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_SETRE.FOLHA FO
    JOIN SW_SETRE.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SETRE.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'AGESPISA02' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_AGESPISA02.FOLHA FO
    JOIN SW_AGESPISA02.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_AGESPISA02.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'SEGOV' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEGOV.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'SASC' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_SASC.FOLHA FO
    JOIN SW_SASC.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SASC.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'METRO' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_METRO.FOLHA FO
    JOIN SW_METRO.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_METRO.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'SADA' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_SADA.FOLHA FO
    JOIN SW_SADA.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SADA.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'SECMULHERES' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_SECMULHERES.FOLHA FO
    JOIN SW_SECMULHERES.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SECMULHERES.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'EMGERPI_EMATER' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_EMGERPI_EMATER.FOLHA FO
    JOIN SW_EMGERPI_EMATER.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_EMATER.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'SESAPI' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_SESAPI.FOLHA FO
    JOIN SW_SESAPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SESAPI.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'PMPI' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_PMPI.FOLHA FO
    JOIN SW_PMPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PMPI.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'SEJUSPI' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_SEJUSPI.FOLHA FO
    JOIN SW_SEJUSPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEJUSPI.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'SEFAZPI' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_SEFAZPI.FOLHA FO
    JOIN SW_SEFAZPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEFAZPI.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'SEADPREVPI' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_SEADPREVPI.FOLHA FO
    JOIN SW_SEADPREVPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEADPREVPI.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'IMEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_IMEPI.FOLHA FO
    JOIN SW_IMEPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_IMEPI.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'BEP' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_BEP.FOLHA FO
    JOIN SW_BEP.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_BEP.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'EMGERPI_COMEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_EMGERPI_COMEPI.FOLHA FO
    JOIN SW_EMGERPI_COMEPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_COMEPI.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'EMGERPI_COMDEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_EMGERPI_COMDEPI.FOLHA FO
    JOIN SW_EMGERPI_COMDEPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_COMDEPI.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'EMGERPI_COHAB' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_EMGERPI_COHAB.FOLHA FO
    JOIN SW_EMGERPI_COHAB.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_COHAB.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'EMGERPI_PRODEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_EMGERPI_PRODEPI.FOLHA FO
    JOIN SW_EMGERPI_PRODEPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_PRODEPI.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'EMGERPI_CEASA' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_EMGERPI_CEASA.FOLHA FO
    JOIN SW_EMGERPI_CEASA.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_CEASA.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'EMGERPI_PIEMTUR' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_EMGERPI_PIEMTUR.FOLHA FO
    JOIN SW_EMGERPI_PIEMTUR.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_PIEMTUR.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'EMGERPI_ETELPI_FUNART' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_EMGERPI_ETELPI_FUNART.FOLHA FO
    JOIN SW_EMGERPI_ETELPI_FUNART.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_ETELPI_FUNART.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'EMGERPI_CIDAPI' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_EMGERPI_CIDAPI.FOLHA FO
    JOIN SW_EMGERPI_CIDAPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_CIDAPI.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'SEDUC' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_SEDUC.FOLHA FO
    JOIN SW_SEDUC.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEDUC.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'EMGERPI' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_EMGERPI.FOLHA FO
    JOIN SW_EMGERPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL
SELECT 
    'EMGERPI_CODIPI' ORGAO,
    FO.CHAVE_FOLHA,
    FC.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    FF.VALOR_CALCULADO
FROM 
    SW_EMGERPI_CODIPI.FOLHA FO
    JOIN SW_EMGERPI_CODIPI.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_CODIPI.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
WHERE 
    R.COD_RUBRICA = 625000
    AND FO.MES = 3
    AND FO.ANO = 2026;