INSERT INTO SW_AGESPISA02.FOLHA_FUNC_RUBRICA_IMPORTADA (ID_RUBRICA_IMPORTADA, ID_FOLHA_FUNCIONARIO, ID_RUBRICA, IND_TIPO, ID_FOLHA_VALORES, ID_PENSIONISTA_PA, PRAZO_PARCELA, PRAZO_TOTAL, IND_PARAMETRO, IND_ORIGEM, VALOR_MULTIPLICADOR, IND_FORMA_ATUALIZACAO, DATA_CADASTRO, DATA_INICIO, DATA_FIM, ANO_REFERENCIA, MES_REFERENCIA, IND_SUBSTITUICAO)
SELECT
    SW_AGESPISA02.SQ_PK_RUBRICA_IMPORTADA.NEXTVAL,
    FF2.ID_FOLHA_FUNCIONARIO,
    RI.ID_RUBRICA,
    RI.IND_TIPO,
    FO2.ID_FOLHA,
    RI.ID_PENSIONISTA_PA,
    RI.PRAZO_PARCELA,
    --LPAD(TO_NUMBER(RI.PRAZO_PARCELA) + 1, 3, '0') PRAZO_PARCELA,
    RI.PRAZO_TOTAL,
    RI.IND_PARAMETRO,
    RI.IND_ORIGEM,
    RI.VALOR_MULTIPLICADOR,
    RI.IND_FORMA_ATUALIZACAO,
    '01/09/2026' DATA_CADASTRO,
    '01/09/2026' DATA_INICIO,
    '30/09/2026' DATA_FIM,
    RI.ANO_REFERENCIA,
    8 MES_REFERENCIA,
    RI.IND_SUBSTITUICAO
FROM
    SW_AGESPISA02.FOLHA FO
    JOIN SW_AGESPISA02.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_AGESPISA02.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_AGESPISA02.FUNC_PEN_ALIM_PENSIONISTA AP ON AP.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA AND AP.DATA_FIM IS NULL
    JOIN SW_AGESPISA02.FOLHA_FUNC FF2 ON FF2.COD_INSTITUCIONAL = FF.COD_INSTITUCIONAL
    JOIN SW_AGESPISA02.FOLHA FO2 ON FO2.ID_FOLHA = FF2.ID_FOLHA
WHERE
    FO2.MES = 8
    AND FO.ANO = 2026
    AND FO2.MES = 9
    AND FO2.ANO = 2026
    AND RI.IND_ORIGEM = 'P'
    AND AP.IND_ATIVO = 'S'
    AND SUBSTR(FO.CHAVE_FOLHA, 9) = SUBSTR(FO2.CHAVE_FOLHA, 9)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_AGESPISA02.FOLHA_FUNC_RUBRICA_IMPORTADA RI2
        WHERE
            RI2.ID_FOLHA_FUNCIONARIO = FF2.ID_FOLHA_FUNCIONARIO
            AND RI2.ID_RUBRICA = RI.ID_RUBRICA
            AND RI2.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA
    );
INSERT INTO SW_FUNPREV.FOLHA_FUNC_RUBRICA_IMPORTADA (ID_RUBRICA_IMPORTADA, ID_FOLHA_FUNCIONARIO, ID_RUBRICA, IND_TIPO, ID_FOLHA_VALORES, ID_PENSIONISTA_PA, PRAZO_PARCELA, PRAZO_TOTAL, IND_PARAMETRO, IND_ORIGEM, VALOR_MULTIPLICADOR, IND_FORMA_ATUALIZACAO, DATA_CADASTRO, DATA_INICIO, DATA_FIM, ANO_REFERENCIA, MES_REFERENCIA, IND_SUBSTITUICAO)
SELECT
    SW_FUNPREV.SQ_PK_RUBRICA_IMPORTADA.NEXTVAL,
    FF2.ID_FOLHA_FUNCIONARIO,
    RI.ID_RUBRICA,
    RI.IND_TIPO,
    FO2.ID_FOLHA,
    RI.ID_PENSIONISTA_PA,
    RI.PRAZO_PARCELA,
    --LPAD(TO_NUMBER(RI.PRAZO_PARCELA) + 1, 3, '0') PRAZO_PARCELA,
    RI.PRAZO_TOTAL,
    RI.IND_PARAMETRO,
    RI.IND_ORIGEM,
    RI.VALOR_MULTIPLICADOR,
    RI.IND_FORMA_ATUALIZACAO,
    '01/09/2026' DATA_CADASTRO,
    '01/09/2026' DATA_INICIO,
    '30/09/2026' DATA_FIM,
    RI.ANO_REFERENCIA,
    8 MES_REFERENCIA,
    RI.IND_SUBSTITUICAO
FROM
    SW_FUNPREV.FOLHA FO
    JOIN SW_FUNPREV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUNPREV.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_FUNPREV.FUNC_PEN_ALIM_PENSIONISTA AP ON AP.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA AND AP.DATA_FIM IS NULL
    JOIN SW_FUNPREV.FOLHA_FUNC FF2 ON FF2.COD_INSTITUCIONAL = FF.COD_INSTITUCIONAL
    JOIN SW_FUNPREV.FOLHA FO2 ON FO2.ID_FOLHA = FF2.ID_FOLHA
WHERE
    FO2.MES = 8
    AND FO.ANO = 2026
    AND FO2.MES = 9
    AND FO2.ANO = 2026
    AND RI.IND_ORIGEM = 'P'
    AND AP.IND_ATIVO = 'S'
    AND SUBSTR(FO.CHAVE_FOLHA, 9) = SUBSTR(FO2.CHAVE_FOLHA, 9)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_FUNPREV.FOLHA_FUNC_RUBRICA_IMPORTADA RI2
        WHERE
            RI2.ID_FOLHA_FUNCIONARIO = FF2.ID_FOLHA_FUNCIONARIO
            AND RI2.ID_RUBRICA = RI.ID_RUBRICA
            AND RI2.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA
    );
INSERT INTO SW_PMPI.FOLHA_FUNC_RUBRICA_IMPORTADA (ID_RUBRICA_IMPORTADA, ID_FOLHA_FUNCIONARIO, ID_RUBRICA, IND_TIPO, ID_FOLHA_VALORES, ID_PENSIONISTA_PA, PRAZO_PARCELA, PRAZO_TOTAL, IND_PARAMETRO, IND_ORIGEM, VALOR_MULTIPLICADOR, IND_FORMA_ATUALIZACAO, DATA_CADASTRO, DATA_INICIO, DATA_FIM, ANO_REFERENCIA, MES_REFERENCIA, IND_SUBSTITUICAO)
SELECT
    SW_PMPI.SQ_PK_RUBRICA_IMPORTADA.NEXTVAL,
    FF2.ID_FOLHA_FUNCIONARIO,
    RI.ID_RUBRICA,
    RI.IND_TIPO,
    FO2.ID_FOLHA,
    RI.ID_PENSIONISTA_PA,
    RI.PRAZO_PARCELA,
    --LPAD(TO_NUMBER(RI.PRAZO_PARCELA) + 1, 3, '0') PRAZO_PARCELA,
    RI.PRAZO_TOTAL,
    RI.IND_PARAMETRO,
    RI.IND_ORIGEM,
    RI.VALOR_MULTIPLICADOR,
    RI.IND_FORMA_ATUALIZACAO,
    '01/09/2026' DATA_CADASTRO,
    '01/09/2026' DATA_INICIO,
    '30/09/2026' DATA_FIM,
    RI.ANO_REFERENCIA,
    8 MES_REFERENCIA,
    RI.IND_SUBSTITUICAO
FROM
    SW_PMPI.FOLHA FO
    JOIN SW_PMPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PMPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_PMPI.FUNC_PEN_ALIM_PENSIONISTA AP ON AP.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA AND AP.DATA_FIM IS NULL
    JOIN SW_PMPI.FOLHA_FUNC FF2 ON FF2.COD_INSTITUCIONAL = FF.COD_INSTITUCIONAL
    JOIN SW_PMPI.FOLHA FO2 ON FO2.ID_FOLHA = FF2.ID_FOLHA
WHERE
    FO2.MES = 8
    AND FO.ANO = 2026
    AND FO2.MES = 9
    AND FO2.ANO = 2026
    AND RI.IND_ORIGEM = 'P'
    AND AP.IND_ATIVO = 'S'
    AND SUBSTR(FO.CHAVE_FOLHA, 9) = SUBSTR(FO2.CHAVE_FOLHA, 9)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_PMPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI2
        WHERE
            RI2.ID_FOLHA_FUNCIONARIO = FF2.ID_FOLHA_FUNCIONARIO
            AND RI2.ID_RUBRICA = RI.ID_RUBRICA
            AND RI2.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA
    );
INSERT INTO SW_SEDUC.FOLHA_FUNC_RUBRICA_IMPORTADA (ID_RUBRICA_IMPORTADA, ID_FOLHA_FUNCIONARIO, ID_RUBRICA, IND_TIPO, ID_FOLHA_VALORES, ID_PENSIONISTA_PA, PRAZO_PARCELA, PRAZO_TOTAL, IND_PARAMETRO, IND_ORIGEM, VALOR_MULTIPLICADOR, IND_FORMA_ATUALIZACAO, DATA_CADASTRO, DATA_INICIO, DATA_FIM, ANO_REFERENCIA, MES_REFERENCIA, IND_SUBSTITUICAO)
SELECT
    SW_SEDUC.SQ_PK_RUBRICA_IMPORTADA.NEXTVAL,
    FF2.ID_FOLHA_FUNCIONARIO,
    RI.ID_RUBRICA,
    RI.IND_TIPO,
    FO2.ID_FOLHA,
    RI.ID_PENSIONISTA_PA,
    RI.PRAZO_PARCELA,
    --LPAD(TO_NUMBER(RI.PRAZO_PARCELA) + 1, 3, '0') PRAZO_PARCELA,
    RI.PRAZO_TOTAL,
    RI.IND_PARAMETRO,
    RI.IND_ORIGEM,
    RI.VALOR_MULTIPLICADOR,
    RI.IND_FORMA_ATUALIZACAO,
    '01/09/2026' DATA_CADASTRO,
    '01/09/2026' DATA_INICIO,
    '30/09/2026' DATA_FIM,
    RI.ANO_REFERENCIA,
    8 MES_REFERENCIA,
    RI.IND_SUBSTITUICAO
FROM
    SW_SEDUC.FOLHA FO
    JOIN SW_SEDUC.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEDUC.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEDUC.FUNC_PEN_ALIM_PENSIONISTA AP ON AP.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA AND AP.DATA_FIM IS NULL
    JOIN SW_SEDUC.FOLHA_FUNC FF2 ON FF2.COD_INSTITUCIONAL = FF.COD_INSTITUCIONAL
    JOIN SW_SEDUC.FOLHA FO2 ON FO2.ID_FOLHA = FF2.ID_FOLHA
WHERE
    FO2.MES = 8
    AND FO.ANO = 2026
    AND FO2.MES = 9
    AND FO2.ANO = 2026
    AND RI.IND_ORIGEM = 'P'
    AND AP.IND_ATIVO = 'S'
    AND SUBSTR(FO.CHAVE_FOLHA, 9) = SUBSTR(FO2.CHAVE_FOLHA, 9)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEDUC.FOLHA_FUNC_RUBRICA_IMPORTADA RI2
        WHERE
            RI2.ID_FOLHA_FUNCIONARIO = FF2.ID_FOLHA_FUNCIONARIO
            AND RI2.ID_RUBRICA = RI.ID_RUBRICA
            AND RI2.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA
    );
INSERT INTO SW_SEFAZPI.FOLHA_FUNC_RUBRICA_IMPORTADA (ID_RUBRICA_IMPORTADA, ID_FOLHA_FUNCIONARIO, ID_RUBRICA, IND_TIPO, ID_FOLHA_VALORES, ID_PENSIONISTA_PA, PRAZO_PARCELA, PRAZO_TOTAL, IND_PARAMETRO, IND_ORIGEM, VALOR_MULTIPLICADOR, IND_FORMA_ATUALIZACAO, DATA_CADASTRO, DATA_INICIO, DATA_FIM, ANO_REFERENCIA, MES_REFERENCIA, IND_SUBSTITUICAO)
SELECT
    SW_SEFAZPI.SQ_PK_RUBRICA_IMPORTADA.NEXTVAL,
    FF2.ID_FOLHA_FUNCIONARIO,
    RI.ID_RUBRICA,
    RI.IND_TIPO,
    FO2.ID_FOLHA,
    RI.ID_PENSIONISTA_PA,
    RI.PRAZO_PARCELA,
    --LPAD(TO_NUMBER(RI.PRAZO_PARCELA) + 1, 3, '0') PRAZO_PARCELA,
    RI.PRAZO_TOTAL,
    RI.IND_PARAMETRO,
    RI.IND_ORIGEM,
    RI.VALOR_MULTIPLICADOR,
    RI.IND_FORMA_ATUALIZACAO,
    '01/09/2026' DATA_CADASTRO,
    '01/09/2026' DATA_INICIO,
    '30/09/2026' DATA_FIM,
    RI.ANO_REFERENCIA,
    8 MES_REFERENCIA,
    RI.IND_SUBSTITUICAO
FROM
    SW_SEFAZPI.FOLHA FO
    JOIN SW_SEFAZPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEFAZPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEFAZPI.FUNC_PEN_ALIM_PENSIONISTA AP ON AP.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA AND AP.DATA_FIM IS NULL
    JOIN SW_SEFAZPI.FOLHA_FUNC FF2 ON FF2.COD_INSTITUCIONAL = FF.COD_INSTITUCIONAL
    JOIN SW_SEFAZPI.FOLHA FO2 ON FO2.ID_FOLHA = FF2.ID_FOLHA
WHERE
    FO2.MES = 8
    AND FO.ANO = 2026
    AND FO2.MES = 9
    AND FO2.ANO = 2026
    AND RI.IND_ORIGEM = 'P'
    AND AP.IND_ATIVO = 'S'
    AND SUBSTR(FO.CHAVE_FOLHA, 9) = SUBSTR(FO2.CHAVE_FOLHA, 9)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEFAZPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI2
        WHERE
            RI2.ID_FOLHA_FUNCIONARIO = FF2.ID_FOLHA_FUNCIONARIO
            AND RI2.ID_RUBRICA = RI.ID_RUBRICA
            AND RI2.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA
    );
INSERT INTO SW_SESAPI.FOLHA_FUNC_RUBRICA_IMPORTADA (ID_RUBRICA_IMPORTADA, ID_FOLHA_FUNCIONARIO, ID_RUBRICA, IND_TIPO, ID_FOLHA_VALORES, ID_PENSIONISTA_PA, PRAZO_PARCELA, PRAZO_TOTAL, IND_PARAMETRO, IND_ORIGEM, VALOR_MULTIPLICADOR, IND_FORMA_ATUALIZACAO, DATA_CADASTRO, DATA_INICIO, DATA_FIM, ANO_REFERENCIA, MES_REFERENCIA, IND_SUBSTITUICAO)
SELECT
    SW_SESAPI.SQ_PK_RUBRICA_IMPORTADA.NEXTVAL,
    FF2.ID_FOLHA_FUNCIONARIO,
    RI.ID_RUBRICA,
    RI.IND_TIPO,
    FO2.ID_FOLHA,
    RI.ID_PENSIONISTA_PA,
    RI.PRAZO_PARCELA,
    --LPAD(TO_NUMBER(RI.PRAZO_PARCELA) + 1, 3, '0') PRAZO_PARCELA,
    RI.PRAZO_TOTAL,
    RI.IND_PARAMETRO,
    RI.IND_ORIGEM,
    RI.VALOR_MULTIPLICADOR,
    RI.IND_FORMA_ATUALIZACAO,
    '01/09/2026' DATA_CADASTRO,
    '01/09/2026' DATA_INICIO,
    '30/09/2026' DATA_FIM,
    RI.ANO_REFERENCIA,
    8 MES_REFERENCIA,
    RI.IND_SUBSTITUICAO
FROM
    SW_SESAPI.FOLHA FO
    JOIN SW_SESAPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SESAPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SESAPI.FUNC_PEN_ALIM_PENSIONISTA AP ON AP.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA AND AP.DATA_FIM IS NULL
    JOIN SW_SESAPI.FOLHA_FUNC FF2 ON FF2.COD_INSTITUCIONAL = FF.COD_INSTITUCIONAL
    JOIN SW_SESAPI.FOLHA FO2 ON FO2.ID_FOLHA = FF2.ID_FOLHA
WHERE
    FO2.MES = 8
    AND FO.ANO = 2026
    AND FO2.MES = 9
    AND FO2.ANO = 2026
    AND RI.IND_ORIGEM = 'P'
    AND AP.IND_ATIVO = 'S'
    AND SUBSTR(FO.CHAVE_FOLHA, 9) = SUBSTR(FO2.CHAVE_FOLHA, 9)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SESAPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI2
        WHERE
            RI2.ID_FOLHA_FUNCIONARIO = FF2.ID_FOLHA_FUNCIONARIO
            AND RI2.ID_RUBRICA = RI.ID_RUBRICA
            AND RI2.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA
    );
INSERT INTO SW_SSPPI.FOLHA_FUNC_RUBRICA_IMPORTADA (ID_RUBRICA_IMPORTADA, ID_FOLHA_FUNCIONARIO, ID_RUBRICA, IND_TIPO, ID_FOLHA_VALORES, ID_PENSIONISTA_PA, PRAZO_PARCELA, PRAZO_TOTAL, IND_PARAMETRO, IND_ORIGEM, VALOR_MULTIPLICADOR, IND_FORMA_ATUALIZACAO, DATA_CADASTRO, DATA_INICIO, DATA_FIM, ANO_REFERENCIA, MES_REFERENCIA, IND_SUBSTITUICAO)
SELECT
    SW_SSPPI.SQ_PK_RUBRICA_IMPORTADA.NEXTVAL,
    FF2.ID_FOLHA_FUNCIONARIO,
    RI.ID_RUBRICA,
    RI.IND_TIPO,
    FO2.ID_FOLHA,
    RI.ID_PENSIONISTA_PA,
    RI.PRAZO_PARCELA,
    --LPAD(TO_NUMBER(RI.PRAZO_PARCELA) + 1, 3, '0') PRAZO_PARCELA,
    RI.PRAZO_TOTAL,
    RI.IND_PARAMETRO,
    RI.IND_ORIGEM,
    RI.VALOR_MULTIPLICADOR,
    RI.IND_FORMA_ATUALIZACAO,
    '01/09/2026' DATA_CADASTRO,
    '01/09/2026' DATA_INICIO,
    '30/09/2026' DATA_FIM,
    RI.ANO_REFERENCIA,
    8 MES_REFERENCIA,
    RI.IND_SUBSTITUICAO
FROM
    SW_SSPPI.FOLHA FO
    JOIN SW_SSPPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SSPPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SSPPI.FUNC_PEN_ALIM_PENSIONISTA AP ON AP.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA AND AP.DATA_FIM IS NULL
    JOIN SW_SSPPI.FOLHA_FUNC FF2 ON FF2.COD_INSTITUCIONAL = FF.COD_INSTITUCIONAL
    JOIN SW_SSPPI.FOLHA FO2 ON FO2.ID_FOLHA = FF2.ID_FOLHA
WHERE
    FO2.MES = 8
    AND FO.ANO = 2026
    AND FO2.MES = 9
    AND FO2.ANO = 2026
    AND RI.IND_ORIGEM = 'P'
    AND AP.IND_ATIVO = 'S'
    AND SUBSTR(FO.CHAVE_FOLHA, 9) = SUBSTR(FO2.CHAVE_FOLHA, 9)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SSPPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI2
        WHERE
            RI2.ID_FOLHA_FUNCIONARIO = FF2.ID_FOLHA_FUNCIONARIO
            AND RI2.ID_RUBRICA = RI.ID_RUBRICA
            AND RI2.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA
    );