INSERT INTO SW_CBMPI.FOLHA_FUNC_RUBRICA_IMPORTADA (ID_RUBRICA_IMPORTADA, ID_FOLHA_FUNCIONARIO, ID_RUBRICA, IND_TIPO, ID_FOLHA_VALORES, ID_PENSIONISTA_PA, PRAZO_PARCELA, PRAZO_TOTAL, IND_PARAMETRO, IND_ORIGEM, VALOR_MULTIPLICADOR, IND_FORMA_ATUALIZACAO, DATA_CADASTRO, DATA_INICIO, DATA_FIM, ANO_REFERENCIA, MES_REFERENCIA, IND_SUBSTITUICAO, OBSERVACAO)
SELECT
    SW_CBMPI.SQ_PK_RUBRICA_IMPORTADA.NEXTVAL,
    FF2.ID_FOLHA_FUNCIONARIO,
    RI.ID_RUBRICA,
    RI.IND_TIPO,
    FO2.ID_FOLHA,
    RI.ID_PENSIONISTA_PA,
    RI.PRAZO_PARCELA,
    --LPAD(TO_NUMBER(RI.PRAZO_PARCELA) + 1, 3, '0') PRAZO_PARCELA,
    RI.PRAZO_TOTAL,
    RI.IND_PARAMETRO,
    RI.IND_ORIGEM,
    RI.VALOR_MULTIPLICADOR,
    RI.IND_FORMA_ATUALIZACAO,
    '01/10/2026' DATA_CADASTRO,
    '01/10/2026' DATA_INICIO,
    '31/10/2026' DATA_FIM,
    RI.ANO_REFERENCIA,
    10 MES_REFERENCIA,
    RI.IND_SUBSTITUICAO,
    'CARD 6648'
FROM
    SW_CBMPI.FOLHA FO
    JOIN SW_CBMPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CBMPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_CBMPI.FUNC_PEN_ALIM_PENSIONISTA AP ON AP.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA AND AP.DATA_FIM IS NULL
    JOIN SW_CBMPI.FOLHA_FUNC FF2 ON FF2.COD_INSTITUCIONAL = FF.COD_INSTITUCIONAL
    JOIN SW_CBMPI.FOLHA FO2 ON FO2.ID_FOLHA = FF2.ID_FOLHA
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND FO2.MES = 10
    AND FO2.ANO = 2026
    AND RI.IND_ORIGEM = 'P'
    AND AP.IND_ATIVO = 'S'
    AND SUBSTR(FO.CHAVE_FOLHA, 9) = SUBSTR(FO2.CHAVE_FOLHA, 9)
    AND FF.COD_INSTITUCIONAL IN ('085327-5','207508-3','085807-2','207488-5','207491-5','015343-5')
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_CBMPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI2
        WHERE
            RI2.ID_FOLHA_FUNCIONARIO = FF2.ID_FOLHA_FUNCIONARIO
            AND RI2.ID_RUBRICA = RI.ID_RUBRICA
            AND RI2.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA
    );
    

INSERT INTO SW_FUNPREV.FOLHA_FUNC_RUBRICA_IMPORTADA (ID_RUBRICA_IMPORTADA, ID_FOLHA_FUNCIONARIO, ID_RUBRICA, IND_TIPO, ID_FOLHA_VALORES, ID_PENSIONISTA_PA, PRAZO_PARCELA, PRAZO_TOTAL, IND_PARAMETRO, IND_ORIGEM, VALOR_MULTIPLICADOR, IND_FORMA_ATUALIZACAO, DATA_CADASTRO, DATA_INICIO, DATA_FIM, ANO_REFERENCIA, MES_REFERENCIA, IND_SUBSTITUICAO, OBSERVACAO)
SELECT
    SW_FUNPREV.SQ_PK_RUBRICA_IMPORTADA.NEXTVAL,
    FF2.ID_FOLHA_FUNCIONARIO,
    RI.ID_RUBRICA,
    RI.IND_TIPO,
    FO2.ID_FOLHA,
    RI.ID_PENSIONISTA_PA,
    RI.PRAZO_PARCELA,
    --LPAD(TO_NUMBER(RI.PRAZO_PARCELA) + 1, 3, '0') PRAZO_PARCELA,
    RI.PRAZO_TOTAL,
    RI.IND_PARAMETRO,
    RI.IND_ORIGEM,
    RI.VALOR_MULTIPLICADOR,
    RI.IND_FORMA_ATUALIZACAO,
    '01/10/2026' DATA_CADASTRO,
    '01/10/2026' DATA_INICIO,
    '31/10/2026' DATA_FIM,
    RI.ANO_REFERENCIA,
    10 MES_REFERENCIA,
    RI.IND_SUBSTITUICAO,
    'CARD 6648'
FROM
    SW_FUNPREV.FOLHA FO
    JOIN SW_FUNPREV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUNPREV.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_FUNPREV.FUNC_PEN_ALIM_PENSIONISTA AP ON AP.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA AND AP.DATA_FIM IS NULL
    JOIN SW_FUNPREV.FOLHA_FUNC FF2 ON FF2.COD_INSTITUCIONAL = FF.COD_INSTITUCIONAL
    JOIN SW_FUNPREV.FOLHA FO2 ON FO2.ID_FOLHA = FF2.ID_FOLHA
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND FO2.MES = 10
    AND FO2.ANO = 2026
    AND RI.IND_ORIGEM = 'P'
    AND AP.IND_ATIVO = 'S'
    AND SUBSTR(FO.CHAVE_FOLHA, 9) = SUBSTR(FO2.CHAVE_FOLHA, 9)
    AND FF.COD_INSTITUCIONAL IN ('009560-5','013386-8','010362-4','043734-4','030221-0','010675-5','011254-2','054209-1','010672-X','014195-0','003263-8','092549-7','085470-X','056933-0','010596-1','009011-5','012845-7','046679-4','009782-9')
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_FUNPREV.FOLHA_FUNC_RUBRICA_IMPORTADA RI2
        WHERE
            RI2.ID_FOLHA_FUNCIONARIO = FF2.ID_FOLHA_FUNCIONARIO
            AND RI2.ID_RUBRICA = RI.ID_RUBRICA
            AND RI2.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA
    );
    


INSERT INTO SW_IASPI.FOLHA_FUNC_RUBRICA_IMPORTADA (ID_RUBRICA_IMPORTADA, ID_FOLHA_FUNCIONARIO, ID_RUBRICA, IND_TIPO, ID_FOLHA_VALORES, ID_PENSIONISTA_PA, PRAZO_PARCELA, PRAZO_TOTAL, IND_PARAMETRO, IND_ORIGEM, VALOR_MULTIPLICADOR, IND_FORMA_ATUALIZACAO, DATA_CADASTRO, DATA_INICIO, DATA_FIM, ANO_REFERENCIA, MES_REFERENCIA, IND_SUBSTITUICAO, OBSERVACAO)
SELECT
    SW_IASPI.SQ_PK_RUBRICA_IMPORTADA.NEXTVAL,
    FF2.ID_FOLHA_FUNCIONARIO,
    RI.ID_RUBRICA,
    RI.IND_TIPO,
    FO2.ID_FOLHA,
    RI.ID_PENSIONISTA_PA,
    RI.PRAZO_PARCELA,
    --LPAD(TO_NUMBER(RI.PRAZO_PARCELA) + 1, 3, '0') PRAZO_PARCELA,
    RI.PRAZO_TOTAL,
    RI.IND_PARAMETRO,
    RI.IND_ORIGEM,
    RI.VALOR_MULTIPLICADOR,
    RI.IND_FORMA_ATUALIZACAO,
    '01/10/2026' DATA_CADASTRO,
    '01/10/2026' DATA_INICIO,
    '31/10/2026' DATA_FIM,
    RI.ANO_REFERENCIA,
    10 MES_REFERENCIA,
    RI.IND_SUBSTITUICAO,
    'CARD 6648'
FROM
    SW_IASPI.FOLHA FO
    JOIN SW_IASPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_IASPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_IASPI.FUNC_PEN_ALIM_PENSIONISTA AP ON AP.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA AND AP.DATA_FIM IS NULL
    JOIN SW_IASPI.FOLHA_FUNC FF2 ON FF2.COD_INSTITUCIONAL = FF.COD_INSTITUCIONAL
    JOIN SW_IASPI.FOLHA FO2 ON FO2.ID_FOLHA = FF2.ID_FOLHA
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND FO2.MES = 10
    AND FO2.ANO = 2026
    AND RI.IND_ORIGEM = 'P'
    AND AP.IND_ATIVO = 'S'
    AND SUBSTR(FO.CHAVE_FOLHA, 9) = SUBSTR(FO2.CHAVE_FOLHA, 9)
    AND FF.COD_INSTITUCIONAL IN ('178320-3','149425-2')
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_IASPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI2
        WHERE
            RI2.ID_FOLHA_FUNCIONARIO = FF2.ID_FOLHA_FUNCIONARIO
            AND RI2.ID_RUBRICA = RI.ID_RUBRICA
            AND RI2.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA
    );
    


INSERT INTO SW_PMPI.FOLHA_FUNC_RUBRICA_IMPORTADA (ID_RUBRICA_IMPORTADA, ID_FOLHA_FUNCIONARIO, ID_RUBRICA, IND_TIPO, ID_FOLHA_VALORES, ID_PENSIONISTA_PA, PRAZO_PARCELA, PRAZO_TOTAL, IND_PARAMETRO, IND_ORIGEM, VALOR_MULTIPLICADOR, IND_FORMA_ATUALIZACAO, DATA_CADASTRO, DATA_INICIO, DATA_FIM, ANO_REFERENCIA, MES_REFERENCIA, IND_SUBSTITUICAO, OBSERVACAO)
SELECT
    SW_PMPI.SQ_PK_RUBRICA_IMPORTADA.NEXTVAL,
    FF2.ID_FOLHA_FUNCIONARIO,
    RI.ID_RUBRICA,
    RI.IND_TIPO,
    FO2.ID_FOLHA,
    RI.ID_PENSIONISTA_PA,
    RI.PRAZO_PARCELA,
    --LPAD(TO_NUMBER(RI.PRAZO_PARCELA) + 1, 3, '0') PRAZO_PARCELA,
    RI.PRAZO_TOTAL,
    RI.IND_PARAMETRO,
    RI.IND_ORIGEM,
    RI.VALOR_MULTIPLICADOR,
    RI.IND_FORMA_ATUALIZACAO,
    '01/10/2026' DATA_CADASTRO,
    '01/10/2026' DATA_INICIO,
    '31/10/2026' DATA_FIM,
    RI.ANO_REFERENCIA,
    10 MES_REFERENCIA,
    RI.IND_SUBSTITUICAO,
    'CARD 6648'
FROM
    SW_PMPI.FOLHA FO
    JOIN SW_PMPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PMPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_PMPI.FUNC_PEN_ALIM_PENSIONISTA AP ON AP.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA AND AP.DATA_FIM IS NULL
    JOIN SW_PMPI.FOLHA_FUNC FF2 ON FF2.COD_INSTITUCIONAL = FF.COD_INSTITUCIONAL
    JOIN SW_PMPI.FOLHA FO2 ON FO2.ID_FOLHA = FF2.ID_FOLHA
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND FO2.MES = 10
    AND FO2.ANO = 2026
    AND RI.IND_ORIGEM = 'P'
    AND AP.IND_ATIVO = 'S'
    AND SUBSTR(FO.CHAVE_FOLHA, 9) = SUBSTR(FO2.CHAVE_FOLHA, 9)
    AND FF.COD_INSTITUCIONAL IN ('014575-X','244219-1','107831-3','013288-8','085316-0','079695-6','082691-0','084892-1','015742-2','046735-9','015646-9','085300-3','084348-2','082848-3','160615-8','179424-8','085857-9','015059-2','297734-6','086326-2','244983-8','160401-5','160485-6','297700-1','244223-0','013834-7','084387-3','288849-1','331441-3','084881-6','013103-2','013911-4','310007-3','107722-8','107643-4','160630-1','160288-8','404915-2','160264-X','244984-6','206686-6')
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_PMPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI2
        WHERE
            RI2.ID_FOLHA_FUNCIONARIO = FF2.ID_FOLHA_FUNCIONARIO
            AND RI2.ID_RUBRICA = RI.ID_RUBRICA
            AND RI2.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA
    );
    



INSERT INTO SW_SECULT.FOLHA_FUNC_RUBRICA_IMPORTADA (ID_RUBRICA_IMPORTADA, ID_FOLHA_FUNCIONARIO, ID_RUBRICA, IND_TIPO, ID_FOLHA_VALORES, ID_PENSIONISTA_PA, PRAZO_PARCELA, PRAZO_TOTAL, IND_PARAMETRO, IND_ORIGEM, VALOR_MULTIPLICADOR, IND_FORMA_ATUALIZACAO, DATA_CADASTRO, DATA_INICIO, DATA_FIM, ANO_REFERENCIA, MES_REFERENCIA, IND_SUBSTITUICAO, OBSERVACAO)
SELECT
    SW_SECULT.SQ_PK_RUBRICA_IMPORTADA.NEXTVAL,
    FF2.ID_FOLHA_FUNCIONARIO,
    RI.ID_RUBRICA,
    RI.IND_TIPO,
    FO2.ID_FOLHA,
    RI.ID_PENSIONISTA_PA,
    RI.PRAZO_PARCELA,
    --LPAD(TO_NUMBER(RI.PRAZO_PARCELA) + 1, 3, '0') PRAZO_PARCELA,
    RI.PRAZO_TOTAL,
    RI.IND_PARAMETRO,
    RI.IND_ORIGEM,
    RI.VALOR_MULTIPLICADOR,
    RI.IND_FORMA_ATUALIZACAO,
    '01/10/2026' DATA_CADASTRO,
    '01/10/2026' DATA_INICIO,
    '31/10/2026' DATA_FIM,
    RI.ANO_REFERENCIA,
    10 MES_REFERENCIA,
    RI.IND_SUBSTITUICAO,
    'CARD 6648'
FROM
    SW_SECULT.FOLHA FO
    JOIN SW_SECULT.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SECULT.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SECULT.FUNC_PEN_ALIM_PENSIONISTA AP ON AP.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA AND AP.DATA_FIM IS NULL
    JOIN SW_SECULT.FOLHA_FUNC FF2 ON FF2.COD_INSTITUCIONAL = FF.COD_INSTITUCIONAL
    JOIN SW_SECULT.FOLHA FO2 ON FO2.ID_FOLHA = FF2.ID_FOLHA
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND FO2.MES = 10
    AND FO2.ANO = 2026
    AND RI.IND_ORIGEM = 'P'
    AND AP.IND_ATIVO = 'S'
    AND SUBSTR(FO.CHAVE_FOLHA, 9) = SUBSTR(FO2.CHAVE_FOLHA, 9)
    AND FF.COD_INSTITUCIONAL IN ('006750-4','020610-5','006902-7','007219-2')
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SECULT.FOLHA_FUNC_RUBRICA_IMPORTADA RI2
        WHERE
            RI2.ID_FOLHA_FUNCIONARIO = FF2.ID_FOLHA_FUNCIONARIO
            AND RI2.ID_RUBRICA = RI.ID_RUBRICA
            AND RI2.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA
    );
    


INSERT INTO SW_SEDUC.FOLHA_FUNC_RUBRICA_IMPORTADA (ID_RUBRICA_IMPORTADA, ID_FOLHA_FUNCIONARIO, ID_RUBRICA, IND_TIPO, ID_FOLHA_VALORES, ID_PENSIONISTA_PA, PRAZO_PARCELA, PRAZO_TOTAL, IND_PARAMETRO, IND_ORIGEM, VALOR_MULTIPLICADOR, IND_FORMA_ATUALIZACAO, DATA_CADASTRO, DATA_INICIO, DATA_FIM, ANO_REFERENCIA, MES_REFERENCIA, IND_SUBSTITUICAO, OBSERVACAO)
SELECT
    SW_SEDUC.SQ_PK_RUBRICA_IMPORTADA.NEXTVAL,
    FF2.ID_FOLHA_FUNCIONARIO,
    RI.ID_RUBRICA,
    RI.IND_TIPO,
    FO2.ID_FOLHA,
    RI.ID_PENSIONISTA_PA,
    RI.PRAZO_PARCELA,
    --LPAD(TO_NUMBER(RI.PRAZO_PARCELA) + 1, 3, '0') PRAZO_PARCELA,
    RI.PRAZO_TOTAL,
    RI.IND_PARAMETRO,
    RI.IND_ORIGEM,
    RI.VALOR_MULTIPLICADOR,
    RI.IND_FORMA_ATUALIZACAO,
    '01/10/2026' DATA_CADASTRO,
    '01/10/2026' DATA_INICIO,
    '31/10/2026' DATA_FIM,
    RI.ANO_REFERENCIA,
    10 MES_REFERENCIA,
    RI.IND_SUBSTITUICAO,
    'CARD 6648'
FROM
    SW_SEDUC.FOLHA FO
    JOIN SW_SEDUC.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEDUC.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEDUC.FUNC_PEN_ALIM_PENSIONISTA AP ON AP.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA AND AP.DATA_FIM IS NULL
    JOIN SW_SEDUC.FOLHA_FUNC FF2 ON FF2.COD_INSTITUCIONAL = FF.COD_INSTITUCIONAL
    JOIN SW_SEDUC.FOLHA FO2 ON FO2.ID_FOLHA = FF2.ID_FOLHA
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND FO2.MES = 10
    AND FO2.ANO = 2026
    AND RI.IND_ORIGEM = 'P'
    AND AP.IND_ATIVO = 'S'
    AND SUBSTR(FO.CHAVE_FOLHA, 9) = SUBSTR(FO2.CHAVE_FOLHA, 9)
    AND FF.COD_INSTITUCIONAL IN ('230991-2','204996-1','377193-8')
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEDUC.FOLHA_FUNC_RUBRICA_IMPORTADA RI2
        WHERE
            RI2.ID_FOLHA_FUNCIONARIO = FF2.ID_FOLHA_FUNCIONARIO
            AND RI2.ID_RUBRICA = RI.ID_RUBRICA
            AND RI2.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA
    );
    


INSERT INTO SW_SEFAZPI.FOLHA_FUNC_RUBRICA_IMPORTADA (ID_RUBRICA_IMPORTADA, ID_FOLHA_FUNCIONARIO, ID_RUBRICA, IND_TIPO, ID_FOLHA_VALORES, ID_PENSIONISTA_PA, PRAZO_PARCELA, PRAZO_TOTAL, IND_PARAMETRO, IND_ORIGEM, VALOR_MULTIPLICADOR, IND_FORMA_ATUALIZACAO, DATA_CADASTRO, DATA_INICIO, DATA_FIM, ANO_REFERENCIA, MES_REFERENCIA, IND_SUBSTITUICAO, OBSERVACAO)
SELECT
    SW_SEFAZPI.SQ_PK_RUBRICA_IMPORTADA.NEXTVAL,
    FF2.ID_FOLHA_FUNCIONARIO,
    RI.ID_RUBRICA,
    RI.IND_TIPO,
    FO2.ID_FOLHA,
    RI.ID_PENSIONISTA_PA,
    RI.PRAZO_PARCELA,
    --LPAD(TO_NUMBER(RI.PRAZO_PARCELA) + 1, 3, '0') PRAZO_PARCELA,
    RI.PRAZO_TOTAL,
    RI.IND_PARAMETRO,
    RI.IND_ORIGEM,
    RI.VALOR_MULTIPLICADOR,
    RI.IND_FORMA_ATUALIZACAO,
    '01/10/2026' DATA_CADASTRO,
    '01/10/2026' DATA_INICIO,
    '31/10/2026' DATA_FIM,
    RI.ANO_REFERENCIA,
    10 MES_REFERENCIA,
    RI.IND_SUBSTITUICAO,
    'CARD 6648'
FROM
    SW_SEFAZPI.FOLHA FO
    JOIN SW_SEFAZPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEFAZPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEFAZPI.FUNC_PEN_ALIM_PENSIONISTA AP ON AP.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA AND AP.DATA_FIM IS NULL
    JOIN SW_SEFAZPI.FOLHA_FUNC FF2 ON FF2.COD_INSTITUCIONAL = FF.COD_INSTITUCIONAL
    JOIN SW_SEFAZPI.FOLHA FO2 ON FO2.ID_FOLHA = FF2.ID_FOLHA
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND FO2.MES = 10
    AND FO2.ANO = 2026
    AND RI.IND_ORIGEM = 'P'
    AND AP.IND_ATIVO = 'S'
    AND SUBSTR(FO.CHAVE_FOLHA, 9) = SUBSTR(FO2.CHAVE_FOLHA, 9)
    AND FF.COD_INSTITUCIONAL IN ('091070-8','002729-4','213095-5','115766-3','091061-9','002691-3','170461-3','092456-3','091067-8','172607-2','092463-6','115769-8','088006-0')
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEFAZPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI2
        WHERE
            RI2.ID_FOLHA_FUNCIONARIO = FF2.ID_FOLHA_FUNCIONARIO
            AND RI2.ID_RUBRICA = RI.ID_RUBRICA
            AND RI2.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA
    );
    
INSERT INTO SW_SEGOV.FOLHA_FUNC_RUBRICA_IMPORTADA (ID_RUBRICA_IMPORTADA, ID_FOLHA_FUNCIONARIO, ID_RUBRICA, IND_TIPO, ID_FOLHA_VALORES, ID_PENSIONISTA_PA, PRAZO_PARCELA, PRAZO_TOTAL, IND_PARAMETRO, IND_ORIGEM, VALOR_MULTIPLICADOR, IND_FORMA_ATUALIZACAO, DATA_CADASTRO, DATA_INICIO, DATA_FIM, ANO_REFERENCIA, MES_REFERENCIA, IND_SUBSTITUICAO, OBSERVACAO)
SELECT
    SW_SEGOV.SQ_PK_RUBRICA_IMPORTADA.NEXTVAL,
    FF2.ID_FOLHA_FUNCIONARIO,
    RI.ID_RUBRICA,
    RI.IND_TIPO,
    FO2.ID_FOLHA,
    RI.ID_PENSIONISTA_PA,
    RI.PRAZO_PARCELA,
    --LPAD(TO_NUMBER(RI.PRAZO_PARCELA) + 1, 3, '0') PRAZO_PARCELA,
    RI.PRAZO_TOTAL,
    RI.IND_PARAMETRO,
    RI.IND_ORIGEM,
    RI.VALOR_MULTIPLICADOR,
    RI.IND_FORMA_ATUALIZACAO,
    '01/10/2026' DATA_CADASTRO,
    '01/10/2026' DATA_INICIO,
    '31/10/2026' DATA_FIM,
    RI.ANO_REFERENCIA,
    10 MES_REFERENCIA,
    RI.IND_SUBSTITUICAO,
    'CARD 6648'
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEGOV.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEGOV.FUNC_PEN_ALIM_PENSIONISTA AP ON AP.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA AND AP.DATA_FIM IS NULL
    JOIN SW_SEGOV.FOLHA_FUNC FF2 ON FF2.COD_INSTITUCIONAL = FF.COD_INSTITUCIONAL
    JOIN SW_SEGOV.FOLHA FO2 ON FO2.ID_FOLHA = FF2.ID_FOLHA
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND FO2.MES = 10
    AND FO2.ANO = 2026
    AND RI.IND_ORIGEM = 'P'
    AND AP.IND_ATIVO = 'S'
    AND SUBSTR(FO.CHAVE_FOLHA, 9) = SUBSTR(FO2.CHAVE_FOLHA, 9)
    AND FF.COD_INSTITUCIONAL IN ('013591-7')
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEGOV.FOLHA_FUNC_RUBRICA_IMPORTADA RI2
        WHERE
            RI2.ID_FOLHA_FUNCIONARIO = FF2.ID_FOLHA_FUNCIONARIO
            AND RI2.ID_RUBRICA = RI.ID_RUBRICA
            AND RI2.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA
    );
    
INSERT INTO SW_SEJUSPI.FOLHA_FUNC_RUBRICA_IMPORTADA (ID_RUBRICA_IMPORTADA, ID_FOLHA_FUNCIONARIO, ID_RUBRICA, IND_TIPO, ID_FOLHA_VALORES, ID_PENSIONISTA_PA, PRAZO_PARCELA, PRAZO_TOTAL, IND_PARAMETRO, IND_ORIGEM, VALOR_MULTIPLICADOR, IND_FORMA_ATUALIZACAO, DATA_CADASTRO, DATA_INICIO, DATA_FIM, ANO_REFERENCIA, MES_REFERENCIA, IND_SUBSTITUICAO, OBSERVACAO)
SELECT
    SW_SEJUSPI.SQ_PK_RUBRICA_IMPORTADA.NEXTVAL,
    FF2.ID_FOLHA_FUNCIONARIO,
    RI.ID_RUBRICA,
    RI.IND_TIPO,
    FO2.ID_FOLHA,
    RI.ID_PENSIONISTA_PA,
    RI.PRAZO_PARCELA,
    --LPAD(TO_NUMBER(RI.PRAZO_PARCELA) + 1, 3, '0') PRAZO_PARCELA,
    RI.PRAZO_TOTAL,
    RI.IND_PARAMETRO,
    RI.IND_ORIGEM,
    RI.VALOR_MULTIPLICADOR,
    RI.IND_FORMA_ATUALIZACAO,
    '01/10/2026' DATA_CADASTRO,
    '01/10/2026' DATA_INICIO,
    '31/10/2026' DATA_FIM,
    RI.ANO_REFERENCIA,
    10 MES_REFERENCIA,
    RI.IND_SUBSTITUICAO,
    'CARD 6648'
FROM
    SW_SEJUSPI.FOLHA FO
    JOIN SW_SEJUSPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEJUSPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEJUSPI.FUNC_PEN_ALIM_PENSIONISTA AP ON AP.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA AND AP.DATA_FIM IS NULL
    JOIN SW_SEJUSPI.FOLHA_FUNC FF2 ON FF2.COD_INSTITUCIONAL = FF.COD_INSTITUCIONAL
    JOIN SW_SEJUSPI.FOLHA FO2 ON FO2.ID_FOLHA = FF2.ID_FOLHA
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND FO2.MES = 10
    AND FO2.ANO = 2026
    AND RI.IND_ORIGEM = 'P'
    AND AP.IND_ATIVO = 'S'
    AND SUBSTR(FO.CHAVE_FOLHA, 9) = SUBSTR(FO2.CHAVE_FOLHA, 9)
    AND FF.COD_INSTITUCIONAL IN ('044153-8','107722-8')
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEJUSPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI2
        WHERE
            RI2.ID_FOLHA_FUNCIONARIO = FF2.ID_FOLHA_FUNCIONARIO
            AND RI2.ID_RUBRICA = RI.ID_RUBRICA
            AND RI2.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA
    );
    
INSERT INTO SW_SESAPI.FOLHA_FUNC_RUBRICA_IMPORTADA (ID_RUBRICA_IMPORTADA, ID_FOLHA_FUNCIONARIO, ID_RUBRICA, IND_TIPO, ID_FOLHA_VALORES, ID_PENSIONISTA_PA, PRAZO_PARCELA, PRAZO_TOTAL, IND_PARAMETRO, IND_ORIGEM, VALOR_MULTIPLICADOR, IND_FORMA_ATUALIZACAO, DATA_CADASTRO, DATA_INICIO, DATA_FIM, ANO_REFERENCIA, MES_REFERENCIA, IND_SUBSTITUICAO, OBSERVACAO)
SELECT
    SW_SESAPI.SQ_PK_RUBRICA_IMPORTADA.NEXTVAL,
    FF2.ID_FOLHA_FUNCIONARIO,
    RI.ID_RUBRICA,
    RI.IND_TIPO,
    FO2.ID_FOLHA,
    RI.ID_PENSIONISTA_PA,
    RI.PRAZO_PARCELA,
    --LPAD(TO_NUMBER(RI.PRAZO_PARCELA) + 1, 3, '0') PRAZO_PARCELA,
    RI.PRAZO_TOTAL,
    RI.IND_PARAMETRO,
    RI.IND_ORIGEM,
    RI.VALOR_MULTIPLICADOR,
    RI.IND_FORMA_ATUALIZACAO,
    '01/10/2026' DATA_CADASTRO,
    '01/10/2026' DATA_INICIO,
    '31/10/2026' DATA_FIM,
    RI.ANO_REFERENCIA,
    10 MES_REFERENCIA,
    RI.IND_SUBSTITUICAO,
    'CARD 6648'
FROM
    SW_SESAPI.FOLHA FO
    JOIN SW_SESAPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SESAPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SESAPI.FUNC_PEN_ALIM_PENSIONISTA AP ON AP.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA AND AP.DATA_FIM IS NULL
    JOIN SW_SESAPI.FOLHA_FUNC FF2 ON FF2.COD_INSTITUCIONAL = FF.COD_INSTITUCIONAL
    JOIN SW_SESAPI.FOLHA FO2 ON FO2.ID_FOLHA = FF2.ID_FOLHA
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND FO2.MES = 10
    AND FO2.ANO = 2026
    AND RI.IND_ORIGEM = 'P'
    AND AP.IND_ATIVO = 'S'
    AND SUBSTR(FO.CHAVE_FOLHA, 9) = SUBSTR(FO2.CHAVE_FOLHA, 9)
    AND FF.COD_INSTITUCIONAL IN ('164789-0','384717-9')
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SESAPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI2
        WHERE
            RI2.ID_FOLHA_FUNCIONARIO = FF2.ID_FOLHA_FUNCIONARIO
            AND RI2.ID_RUBRICA = RI.ID_RUBRICA
            AND RI2.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA
    );
    
INSERT INTO SW_SSPPI.FOLHA_FUNC_RUBRICA_IMPORTADA (ID_RUBRICA_IMPORTADA, ID_FOLHA_FUNCIONARIO, ID_RUBRICA, IND_TIPO, ID_FOLHA_VALORES, ID_PENSIONISTA_PA, PRAZO_PARCELA, PRAZO_TOTAL, IND_PARAMETRO, IND_ORIGEM, VALOR_MULTIPLICADOR, IND_FORMA_ATUALIZACAO, DATA_CADASTRO, DATA_INICIO, DATA_FIM, ANO_REFERENCIA, MES_REFERENCIA, IND_SUBSTITUICAO, OBSERVACAO)
SELECT
    SW_SSPPI.SQ_PK_RUBRICA_IMPORTADA.NEXTVAL,
    FF2.ID_FOLHA_FUNCIONARIO,
    RI.ID_RUBRICA,
    RI.IND_TIPO,
    FO2.ID_FOLHA,
    RI.ID_PENSIONISTA_PA,
    RI.PRAZO_PARCELA,
    --LPAD(TO_NUMBER(RI.PRAZO_PARCELA) + 1, 3, '0') PRAZO_PARCELA,
    RI.PRAZO_TOTAL,
    RI.IND_PARAMETRO,
    RI.IND_ORIGEM,
    RI.VALOR_MULTIPLICADOR,
    RI.IND_FORMA_ATUALIZACAO,
    '01/10/2026' DATA_CADASTRO,
    '01/10/2026' DATA_INICIO,
    '31/10/2026' DATA_FIM,
    RI.ANO_REFERENCIA,
    10 MES_REFERENCIA,
    RI.IND_SUBSTITUICAO,
    'CARD 6648'
FROM
    SW_SSPPI.FOLHA FO
    JOIN SW_SSPPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SSPPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SSPPI.FUNC_PEN_ALIM_PENSIONISTA AP ON AP.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA AND AP.DATA_FIM IS NULL
    JOIN SW_SSPPI.FOLHA_FUNC FF2 ON FF2.COD_INSTITUCIONAL = FF.COD_INSTITUCIONAL
    JOIN SW_SSPPI.FOLHA FO2 ON FO2.ID_FOLHA = FF2.ID_FOLHA
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND FO2.MES = 10
    AND FO2.ANO = 2026
    AND RI.IND_ORIGEM = 'P'
    AND AP.IND_ATIVO = 'S'
    AND SUBSTR(FO.CHAVE_FOLHA, 9) = SUBSTR(FO2.CHAVE_FOLHA, 9)
    AND FF.COD_INSTITUCIONAL IN ('009586-9','009560-5','258575-8','008837-4','092354-X','009887-6','009898-1','108420-8','108486-X','299113-6','311265-9','311294-2','108624-3','356942-0','000879-6','311298-5','290318-X','286176-3','086697-X','299141-1','353854-X','297992-6')
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SSPPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI2
        WHERE
            RI2.ID_FOLHA_FUNCIONARIO = FF2.ID_FOLHA_FUNCIONARIO
            AND RI2.ID_RUBRICA = RI.ID_RUBRICA
            AND RI2.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA
    );