INSERT INTO SW_CBMPI.FOLHA_FUNC_RUBRICA_IMPORTADA (ID_RUBRICA_IMPORTADA, ID_FOLHA_FUNCIONARIO, ID_RUBRICA, IND_TIPO, ID_FOLHA_VALORES, ID_PENSIONISTA_PA, PRAZO_PARCELA, PRAZO_TOTAL, IND_PARAMETRO, IND_ORIGEM, VALOR_MULTIPLICADOR, IND_FORMA_ATUALIZACAO, DATA_CADASTRO, DATA_INICIO, DATA_FIM, ANO_REFERENCIA, MES_REFERENCIA, IND_SUBSTITUICAO, OBSERVACAO)
SELECT
    SW_CBMPI.SQ_PK_RUBRICA_IMPORTADA.NEXTVAL,
    FF2.ID_FOLHA_FUNCIONARIO,
    RI.ID_RUBRICA,
    RI.IND_TIPO,
    FO2.ID_FOLHA,
    RI.ID_PENSIONISTA_PA,
    RI.PRAZO_PARCELA,
    --LPAD(TO_NUMBER(RI.PRAZO_PARCELA) + 1, 3, '0') PRAZO_PARCELA,
    RI.PRAZO_TOTAL,
    RI.IND_PARAMETRO,
    RI.IND_ORIGEM,
    RI.VALOR_MULTIPLICADOR,
    RI.IND_FORMA_ATUALIZACAO,
    '01/09/2026' DATA_CADASTRO,
    '01/09/2026' DATA_INICIO,
    '30/09/2026' DATA_FIM,
    RI.ANO_REFERENCIA,
    9 MES_REFERENCIA,
    RI.IND_SUBSTITUICAO,
    'CARD 6648'
FROM
    SW_CBMPI.FOLHA FO
    JOIN SW_CBMPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CBMPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_CBMPI.FUNC_PEN_ALIM_PENSIONISTA AP ON AP.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA AND AP.DATA_FIM IS NULL
    JOIN SW_CBMPI.FOLHA_FUNC FF2 ON FF2.COD_INSTITUCIONAL = FF.COD_INSTITUCIONAL
    JOIN SW_CBMPI.FOLHA FO2 ON FO2.ID_FOLHA = FF2.ID_FOLHA
WHERE
    FO.MES = 8
    AND FO.ANO = 2026
    AND FO2.MES = 9
    AND FO2.ANO = 2026
    AND RI.IND_ORIGEM = 'P'
    AND AP.IND_ATIVO = 'S'
    AND SUBSTR(FO.CHAVE_FOLHA, 9) = SUBSTR(FO2.CHAVE_FOLHA, 9)
    AND FF.COD_INSTITUCIONAL IN ( '015343-5', '085327-5', '085807-2', '207488-5', '207491-5', '207508-3')
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_CBMPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI2
        WHERE
            RI2.ID_FOLHA_FUNCIONARIO = FF2.ID_FOLHA_FUNCIONARIO
            AND RI2.ID_RUBRICA = RI.ID_RUBRICA
    );
    
INSERT INTO SW_FUESPI.FOLHA_FUNC_RUBRICA_IMPORTADA (ID_RUBRICA_IMPORTADA, ID_FOLHA_FUNCIONARIO, ID_RUBRICA, IND_TIPO, ID_FOLHA_VALORES, ID_PENSIONISTA_PA, PRAZO_PARCELA, PRAZO_TOTAL, IND_PARAMETRO, IND_ORIGEM, VALOR_MULTIPLICADOR, IND_FORMA_ATUALIZACAO, DATA_CADASTRO, DATA_INICIO, DATA_FIM, ANO_REFERENCIA, MES_REFERENCIA, IND_SUBSTITUICAO, OBSERVACAO)
SELECT
    SW_FUESPI.SQ_PK_RUBRICA_IMPORTADA.NEXTVAL,
    FF2.ID_FOLHA_FUNCIONARIO,
    RI.ID_RUBRICA,
    RI.IND_TIPO,
    FO2.ID_FOLHA,
    RI.ID_PENSIONISTA_PA,
    RI.PRAZO_PARCELA,
    --LPAD(TO_NUMBER(RI.PRAZO_PARCELA) + 1, 3, '0') PRAZO_PARCELA,
    RI.PRAZO_TOTAL,
    RI.IND_PARAMETRO,
    RI.IND_ORIGEM,
    RI.VALOR_MULTIPLICADOR,
    RI.IND_FORMA_ATUALIZACAO,
    '01/09/2026' DATA_CADASTRO,
    '01/09/2026' DATA_INICIO,
    '30/09/2026' DATA_FIM,
    RI.ANO_REFERENCIA,
    9 MES_REFERENCIA,
    RI.IND_SUBSTITUICAO,
    'CARD 6648'
FROM
    SW_FUESPI.FOLHA FO
    JOIN SW_FUESPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUESPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_FUESPI.FUNC_PEN_ALIM_PENSIONISTA AP ON AP.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA AND AP.DATA_FIM IS NULL
    JOIN SW_FUESPI.FOLHA_FUNC FF2 ON FF2.COD_INSTITUCIONAL = FF.COD_INSTITUCIONAL
    JOIN SW_FUESPI.FOLHA FO2 ON FO2.ID_FOLHA = FF2.ID_FOLHA
WHERE
    FO.MES = 8
    AND FO.ANO = 2026
    AND FO2.MES = 9
    AND FO2.ANO = 2026
    AND RI.IND_ORIGEM = 'P'
    AND AP.IND_ATIVO = 'S'
    AND SUBSTR(FO.CHAVE_FOLHA, 9) = SUBSTR(FO2.CHAVE_FOLHA, 9)
    AND FF.COD_INSTITUCIONAL IN ('268989-8')
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_FUESPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI2
        WHERE
            RI2.ID_FOLHA_FUNCIONARIO = FF2.ID_FOLHA_FUNCIONARIO
            AND RI2.ID_RUBRICA = RI.ID_RUBRICA
    );
    
    
INSERT INTO SW_FUNPREV.FOLHA_FUNC_RUBRICA_IMPORTADA (ID_RUBRICA_IMPORTADA, ID_FOLHA_FUNCIONARIO, ID_RUBRICA, IND_TIPO, ID_FOLHA_VALORES, ID_PENSIONISTA_PA, PRAZO_PARCELA, PRAZO_TOTAL, IND_PARAMETRO, IND_ORIGEM, VALOR_MULTIPLICADOR, IND_FORMA_ATUALIZACAO, DATA_CADASTRO, DATA_INICIO, DATA_FIM, ANO_REFERENCIA, MES_REFERENCIA, IND_SUBSTITUICAO, OBSERVACAO)
SELECT
    SW_FUNPREV.SQ_PK_RUBRICA_IMPORTADA.NEXTVAL,
    FF2.ID_FOLHA_FUNCIONARIO,
    RI.ID_RUBRICA,
    RI.IND_TIPO,
    FO2.ID_FOLHA,
    RI.ID_PENSIONISTA_PA,
    RI.PRAZO_PARCELA,
    --LPAD(TO_NUMBER(RI.PRAZO_PARCELA) + 1, 3, '0') PRAZO_PARCELA,
    RI.PRAZO_TOTAL,
    RI.IND_PARAMETRO,
    RI.IND_ORIGEM,
    RI.VALOR_MULTIPLICADOR,
    RI.IND_FORMA_ATUALIZACAO,
    '01/09/2026' DATA_CADASTRO,
    '01/09/2026' DATA_INICIO,
    '30/09/2026' DATA_FIM,
    RI.ANO_REFERENCIA,
    9 MES_REFERENCIA,
    RI.IND_SUBSTITUICAO,
    'CARD 6648'
FROM
    SW_FUNPREV.FOLHA FO
    JOIN SW_FUNPREV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUNPREV.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_FUNPREV.FUNC_PEN_ALIM_PENSIONISTA AP ON AP.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA AND AP.DATA_FIM IS NULL
    JOIN SW_FUNPREV.FOLHA_FUNC FF2 ON FF2.COD_INSTITUCIONAL = FF.COD_INSTITUCIONAL
    JOIN SW_FUNPREV.FOLHA FO2 ON FO2.ID_FOLHA = FF2.ID_FOLHA
WHERE
    FO.MES = 8
    AND FO.ANO = 2026
    AND FO2.MES = 9
    AND FO2.ANO = 2026
    AND RI.IND_ORIGEM = 'P'
    AND AP.IND_ATIVO = 'S'
    AND SUBSTR(FO.CHAVE_FOLHA, 9) = SUBSTR(FO2.CHAVE_FOLHA, 9)
    AND FF.COD_INSTITUCIONAL IN ( '003263-8', '009011-5', '009782-9', '010596-1', '010672-X', '010675-5', '011254-2', '012845-7', '013386-8', '014195-0', '030221-0', '043734-4', '056933-0', '085470-X', '092549-7')
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_FUNPREV.FOLHA_FUNC_RUBRICA_IMPORTADA RI2
        WHERE
            RI2.ID_FOLHA_FUNCIONARIO = FF2.ID_FOLHA_FUNCIONARIO
            AND RI2.ID_RUBRICA = RI.ID_RUBRICA
    );
    
INSERT INTO SW_PMPI.FOLHA_FUNC_RUBRICA_IMPORTADA (ID_RUBRICA_IMPORTADA, ID_FOLHA_FUNCIONARIO, ID_RUBRICA, IND_TIPO, ID_FOLHA_VALORES, ID_PENSIONISTA_PA, PRAZO_PARCELA, PRAZO_TOTAL, IND_PARAMETRO, IND_ORIGEM, VALOR_MULTIPLICADOR, IND_FORMA_ATUALIZACAO, DATA_CADASTRO, DATA_INICIO, DATA_FIM, ANO_REFERENCIA, MES_REFERENCIA, IND_SUBSTITUICAO, OBSERVACAO)
SELECT
    SW_PMPI.SQ_PK_RUBRICA_IMPORTADA.NEXTVAL,
    FF2.ID_FOLHA_FUNCIONARIO,
    RI.ID_RUBRICA,
    RI.IND_TIPO,
    FO2.ID_FOLHA,
    RI.ID_PENSIONISTA_PA,
    RI.PRAZO_PARCELA,
    --LPAD(TO_NUMBER(RI.PRAZO_PARCELA) + 1, 3, '0') PRAZO_PARCELA,
    RI.PRAZO_TOTAL,
    RI.IND_PARAMETRO,
    RI.IND_ORIGEM,
    RI.VALOR_MULTIPLICADOR,
    RI.IND_FORMA_ATUALIZACAO,
    '01/09/2026' DATA_CADASTRO,
    '01/09/2026' DATA_INICIO,
    '30/09/2026' DATA_FIM,
    RI.ANO_REFERENCIA,
    9 MES_REFERENCIA,
    RI.IND_SUBSTITUICAO,
    'CARD 6648'
FROM
    SW_PMPI.FOLHA FO
    JOIN SW_PMPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PMPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_PMPI.FUNC_PEN_ALIM_PENSIONISTA AP ON AP.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA AND AP.DATA_FIM IS NULL
    JOIN SW_PMPI.FOLHA_FUNC FF2 ON FF2.COD_INSTITUCIONAL = FF.COD_INSTITUCIONAL
    JOIN SW_PMPI.FOLHA FO2 ON FO2.ID_FOLHA = FF2.ID_FOLHA
WHERE
    FO.MES = 8
    AND FO.ANO = 2026
    AND FO2.MES = 9
    AND FO2.ANO = 2026
    AND RI.IND_ORIGEM = 'P'
    AND AP.IND_ATIVO = 'S'
    AND SUBSTR(FO.CHAVE_FOLHA, 9) = SUBSTR(FO2.CHAVE_FOLHA, 9)
    AND FF.COD_INSTITUCIONAL IN ( '013103-2', '013288-8', '013834-7', '013911-4', '015059-2', '015646-9', '015742-2', '046735-9', '082691-0', '084348-2', '084881-6', '084892-1', '085316-0', '085857-9', '086326-2', '107643-4', '107831-3', '160264-X', '160288-8', '160401-5', '160485-6', '160615-8', '160630-1', '179424-8', '244219-1', '244223-0', '244983-8', '244984-6', '297700-1', '297734-6', '310007-3', '331441-3', '404915-2')
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_PMPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI2
        WHERE
            RI2.ID_FOLHA_FUNCIONARIO = FF2.ID_FOLHA_FUNCIONARIO
            AND RI2.ID_RUBRICA = RI.ID_RUBRICA
    );
    
INSERT INTO SW_SECULT.FOLHA_FUNC_RUBRICA_IMPORTADA (ID_RUBRICA_IMPORTADA, ID_FOLHA_FUNCIONARIO, ID_RUBRICA, IND_TIPO, ID_FOLHA_VALORES, ID_PENSIONISTA_PA, PRAZO_PARCELA, PRAZO_TOTAL, IND_PARAMETRO, IND_ORIGEM, VALOR_MULTIPLICADOR, IND_FORMA_ATUALIZACAO, DATA_CADASTRO, DATA_INICIO, DATA_FIM, ANO_REFERENCIA, MES_REFERENCIA, IND_SUBSTITUICAO, OBSERVACAO)
SELECT
    SW_SECULT.SQ_PK_RUBRICA_IMPORTADA.NEXTVAL,
    FF2.ID_FOLHA_FUNCIONARIO,
    RI.ID_RUBRICA,
    RI.IND_TIPO,
    FO2.ID_FOLHA,
    RI.ID_PENSIONISTA_PA,
    RI.PRAZO_PARCELA,
    --LPAD(TO_NUMBER(RI.PRAZO_PARCELA) + 1, 3, '0') PRAZO_PARCELA,
    RI.PRAZO_TOTAL,
    RI.IND_PARAMETRO,
    RI.IND_ORIGEM,
    RI.VALOR_MULTIPLICADOR,
    RI.IND_FORMA_ATUALIZACAO,
    '01/09/2026' DATA_CADASTRO,
    '01/09/2026' DATA_INICIO,
    '30/09/2026' DATA_FIM,
    RI.ANO_REFERENCIA,
    9 MES_REFERENCIA,
    RI.IND_SUBSTITUICAO,
    'CARD 6648'
FROM
    SW_SECULT.FOLHA FO
    JOIN SW_SECULT.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SECULT.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SECULT.FUNC_PEN_ALIM_PENSIONISTA AP ON AP.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA AND AP.DATA_FIM IS NULL
    JOIN SW_SECULT.FOLHA_FUNC FF2 ON FF2.COD_INSTITUCIONAL = FF.COD_INSTITUCIONAL
    JOIN SW_SECULT.FOLHA FO2 ON FO2.ID_FOLHA = FF2.ID_FOLHA
WHERE
    FO.MES = 8
    AND FO.ANO = 2026
    AND FO2.MES = 9
    AND FO2.ANO = 2026
    AND RI.IND_ORIGEM = 'P'
    AND AP.IND_ATIVO = 'S'
    AND SUBSTR(FO.CHAVE_FOLHA, 9) = SUBSTR(FO2.CHAVE_FOLHA, 9)
    AND FF.COD_INSTITUCIONAL IN ( '006750-4', '006902-7', '007219-2', '020610-5')
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SECULT.FOLHA_FUNC_RUBRICA_IMPORTADA RI2
        WHERE
            RI2.ID_FOLHA_FUNCIONARIO = FF2.ID_FOLHA_FUNCIONARIO
            AND RI2.ID_RUBRICA = RI.ID_RUBRICA
    );
    
INSERT INTO SW_SEDUC.FOLHA_FUNC_RUBRICA_IMPORTADA (ID_RUBRICA_IMPORTADA, ID_FOLHA_FUNCIONARIO, ID_RUBRICA, IND_TIPO, ID_FOLHA_VALORES, ID_PENSIONISTA_PA, PRAZO_PARCELA, PRAZO_TOTAL, IND_PARAMETRO, IND_ORIGEM, VALOR_MULTIPLICADOR, IND_FORMA_ATUALIZACAO, DATA_CADASTRO, DATA_INICIO, DATA_FIM, ANO_REFERENCIA, MES_REFERENCIA, IND_SUBSTITUICAO, OBSERVACAO)
SELECT
    SW_SEDUC.SQ_PK_RUBRICA_IMPORTADA.NEXTVAL,
    FF2.ID_FOLHA_FUNCIONARIO,
    RI.ID_RUBRICA,
    RI.IND_TIPO,
    FO2.ID_FOLHA,
    RI.ID_PENSIONISTA_PA,
    RI.PRAZO_PARCELA,
    --LPAD(TO_NUMBER(RI.PRAZO_PARCELA) + 1, 3, '0') PRAZO_PARCELA,
    RI.PRAZO_TOTAL,
    RI.IND_PARAMETRO,
    RI.IND_ORIGEM,
    RI.VALOR_MULTIPLICADOR,
    RI.IND_FORMA_ATUALIZACAO,
    '01/09/2026' DATA_CADASTRO,
    '01/09/2026' DATA_INICIO,
    '30/09/2026' DATA_FIM,
    RI.ANO_REFERENCIA,
    9 MES_REFERENCIA,
    RI.IND_SUBSTITUICAO,
    'CARD 6648'
FROM
    SW_SEDUC.FOLHA FO
    JOIN SW_SEDUC.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEDUC.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEDUC.FUNC_PEN_ALIM_PENSIONISTA AP ON AP.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA AND AP.DATA_FIM IS NULL
    JOIN SW_SEDUC.FOLHA_FUNC FF2 ON FF2.COD_INSTITUCIONAL = FF.COD_INSTITUCIONAL
    JOIN SW_SEDUC.FOLHA FO2 ON FO2.ID_FOLHA = FF2.ID_FOLHA
WHERE
    FO.MES = 8
    AND FO.ANO = 2026
    AND FO2.MES = 9
    AND FO2.ANO = 2026
    AND RI.IND_ORIGEM = 'P'
    AND AP.IND_ATIVO = 'S'
    AND SUBSTR(FO.CHAVE_FOLHA, 9) = SUBSTR(FO2.CHAVE_FOLHA, 9)
    AND FF.COD_INSTITUCIONAL IN ( '116026-5', '204996-1', '230991-2', '377193-8')
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEDUC.FOLHA_FUNC_RUBRICA_IMPORTADA RI2
        WHERE
            RI2.ID_FOLHA_FUNCIONARIO = FF2.ID_FOLHA_FUNCIONARIO
            AND RI2.ID_RUBRICA = RI.ID_RUBRICA
    );
    
INSERT INTO SW_SEFAZPI.FOLHA_FUNC_RUBRICA_IMPORTADA (ID_RUBRICA_IMPORTADA, ID_FOLHA_FUNCIONARIO, ID_RUBRICA, IND_TIPO, ID_FOLHA_VALORES, ID_PENSIONISTA_PA, PRAZO_PARCELA, PRAZO_TOTAL, IND_PARAMETRO, IND_ORIGEM, VALOR_MULTIPLICADOR, IND_FORMA_ATUALIZACAO, DATA_CADASTRO, DATA_INICIO, DATA_FIM, ANO_REFERENCIA, MES_REFERENCIA, IND_SUBSTITUICAO, OBSERVACAO)
SELECT
    SW_SEFAZPI.SQ_PK_RUBRICA_IMPORTADA.NEXTVAL,
    FF2.ID_FOLHA_FUNCIONARIO,
    RI.ID_RUBRICA,
    RI.IND_TIPO,
    FO2.ID_FOLHA,
    RI.ID_PENSIONISTA_PA,
    RI.PRAZO_PARCELA,
    --LPAD(TO_NUMBER(RI.PRAZO_PARCELA) + 1, 3, '0') PRAZO_PARCELA,
    RI.PRAZO_TOTAL,
    RI.IND_PARAMETRO,
    RI.IND_ORIGEM,
    RI.VALOR_MULTIPLICADOR,
    RI.IND_FORMA_ATUALIZACAO,
    '01/09/2026' DATA_CADASTRO,
    '01/09/2026' DATA_INICIO,
    '30/09/2026' DATA_FIM,
    RI.ANO_REFERENCIA,
    9 MES_REFERENCIA,
    RI.IND_SUBSTITUICAO,
    'CARD 6648'
FROM
    SW_SEFAZPI.FOLHA FO
    JOIN SW_SEFAZPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEFAZPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEFAZPI.FUNC_PEN_ALIM_PENSIONISTA AP ON AP.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA AND AP.DATA_FIM IS NULL
    JOIN SW_SEFAZPI.FOLHA_FUNC FF2 ON FF2.COD_INSTITUCIONAL = FF.COD_INSTITUCIONAL
    JOIN SW_SEFAZPI.FOLHA FO2 ON FO2.ID_FOLHA = FF2.ID_FOLHA
WHERE
    FO.MES = 8
    AND FO.ANO = 2026
    AND FO2.MES = 9
    AND FO2.ANO = 2026
    AND RI.IND_ORIGEM = 'P'
    AND AP.IND_ATIVO = 'S'
    AND SUBSTR(FO.CHAVE_FOLHA, 9) = SUBSTR(FO2.CHAVE_FOLHA, 9)
    AND FF.COD_INSTITUCIONAL IN ( '002691-3', '002729-4', '088006-0', '091061-9', '091067-8', '091070-8', '092456-3', '092463-6', '115766-3', '115769-8', '170461-3', '172607-2', '213095-5')
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEFAZPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI2
        WHERE
            RI2.ID_FOLHA_FUNCIONARIO = FF2.ID_FOLHA_FUNCIONARIO
            AND RI2.ID_RUBRICA = RI.ID_RUBRICA
    );
INSERT INTO SW_SEGOV.FOLHA_FUNC_RUBRICA_IMPORTADA (ID_RUBRICA_IMPORTADA, ID_FOLHA_FUNCIONARIO, ID_RUBRICA, IND_TIPO, ID_FOLHA_VALORES, ID_PENSIONISTA_PA, PRAZO_PARCELA, PRAZO_TOTAL, IND_PARAMETRO, IND_ORIGEM, VALOR_MULTIPLICADOR, IND_FORMA_ATUALIZACAO, DATA_CADASTRO, DATA_INICIO, DATA_FIM, ANO_REFERENCIA, MES_REFERENCIA, IND_SUBSTITUICAO, OBSERVACAO)
SELECT
    SW_SEGOV.SQ_PK_RUBRICA_IMPORTADA.NEXTVAL,
    FF2.ID_FOLHA_FUNCIONARIO,
    RI.ID_RUBRICA,
    RI.IND_TIPO,
    FO2.ID_FOLHA,
    RI.ID_PENSIONISTA_PA,
    RI.PRAZO_PARCELA,
    --LPAD(TO_NUMBER(RI.PRAZO_PARCELA) + 1, 3, '0') PRAZO_PARCELA,
    RI.PRAZO_TOTAL,
    RI.IND_PARAMETRO,
    RI.IND_ORIGEM,
    RI.VALOR_MULTIPLICADOR,
    RI.IND_FORMA_ATUALIZACAO,
    '01/09/2026' DATA_CADASTRO,
    '01/09/2026' DATA_INICIO,
    '30/09/2026' DATA_FIM,
    RI.ANO_REFERENCIA,
    9 MES_REFERENCIA,
    RI.IND_SUBSTITUICAO,
    'CARD 6648'
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEGOV.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEGOV.FUNC_PEN_ALIM_PENSIONISTA AP ON AP.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA AND AP.DATA_FIM IS NULL
    JOIN SW_SEGOV.FOLHA_FUNC FF2 ON FF2.COD_INSTITUCIONAL = FF.COD_INSTITUCIONAL
    JOIN SW_SEGOV.FOLHA FO2 ON FO2.ID_FOLHA = FF2.ID_FOLHA
WHERE
    FO.MES = 8
    AND FO.ANO = 2026
    AND FO2.MES = 9
    AND FO2.ANO = 2026
    AND RI.IND_ORIGEM = 'P'
    AND AP.IND_ATIVO = 'S'
    AND SUBSTR(FO.CHAVE_FOLHA, 9) = SUBSTR(FO2.CHAVE_FOLHA, 9)
    AND FF.COD_INSTITUCIONAL IN ( '013591-7')
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEGOV.FOLHA_FUNC_RUBRICA_IMPORTADA RI2
        WHERE
            RI2.ID_FOLHA_FUNCIONARIO = FF2.ID_FOLHA_FUNCIONARIO
            AND RI2.ID_RUBRICA = RI.ID_RUBRICA
    );
    
INSERT INTO SW_SESAPI.FOLHA_FUNC_RUBRICA_IMPORTADA (ID_RUBRICA_IMPORTADA, ID_FOLHA_FUNCIONARIO, ID_RUBRICA, IND_TIPO, ID_FOLHA_VALORES, ID_PENSIONISTA_PA, PRAZO_PARCELA, PRAZO_TOTAL, IND_PARAMETRO, IND_ORIGEM, VALOR_MULTIPLICADOR, IND_FORMA_ATUALIZACAO, DATA_CADASTRO, DATA_INICIO, DATA_FIM, ANO_REFERENCIA, MES_REFERENCIA, IND_SUBSTITUICAO, OBSERVACAO)
SELECT
    SW_SESAPI.SQ_PK_RUBRICA_IMPORTADA.NEXTVAL,
    FF2.ID_FOLHA_FUNCIONARIO,
    RI.ID_RUBRICA,
    RI.IND_TIPO,
    FO2.ID_FOLHA,
    RI.ID_PENSIONISTA_PA,
    RI.PRAZO_PARCELA,
    --LPAD(TO_NUMBER(RI.PRAZO_PARCELA) + 1, 3, '0') PRAZO_PARCELA,
    RI.PRAZO_TOTAL,
    RI.IND_PARAMETRO,
    RI.IND_ORIGEM,
    RI.VALOR_MULTIPLICADOR,
    RI.IND_FORMA_ATUALIZACAO,
    '01/09/2026' DATA_CADASTRO,
    '01/09/2026' DATA_INICIO,
    '30/09/2026' DATA_FIM,
    RI.ANO_REFERENCIA,
    9 MES_REFERENCIA,
    RI.IND_SUBSTITUICAO,
    'CARD 6648'
FROM
    SW_SESAPI.FOLHA FO
    JOIN SW_SESAPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SESAPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SESAPI.FUNC_PEN_ALIM_PENSIONISTA AP ON AP.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA AND AP.DATA_FIM IS NULL
    JOIN SW_SESAPI.FOLHA_FUNC FF2 ON FF2.COD_INSTITUCIONAL = FF.COD_INSTITUCIONAL
    JOIN SW_SESAPI.FOLHA FO2 ON FO2.ID_FOLHA = FF2.ID_FOLHA
WHERE
    FO.MES = 8
    AND FO.ANO = 2026
    AND FO2.MES = 9
    AND FO2.ANO = 2026
    AND RI.IND_ORIGEM = 'P'
    AND AP.IND_ATIVO = 'S'
    AND SUBSTR(FO.CHAVE_FOLHA, 9) = SUBSTR(FO2.CHAVE_FOLHA, 9)
    AND FF.COD_INSTITUCIONAL IN ( '164789-0', '209669-2', '384717-9')
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SESAPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI2
        WHERE
            RI2.ID_FOLHA_FUNCIONARIO = FF2.ID_FOLHA_FUNCIONARIO
            AND RI2.ID_RUBRICA = RI.ID_RUBRICA
    );
    
INSERT INTO SW_SSPPI.FOLHA_FUNC_RUBRICA_IMPORTADA (ID_RUBRICA_IMPORTADA, ID_FOLHA_FUNCIONARIO, ID_RUBRICA, IND_TIPO, ID_FOLHA_VALORES, ID_PENSIONISTA_PA, PRAZO_PARCELA, PRAZO_TOTAL, IND_PARAMETRO, IND_ORIGEM, VALOR_MULTIPLICADOR, IND_FORMA_ATUALIZACAO, DATA_CADASTRO, DATA_INICIO, DATA_FIM, ANO_REFERENCIA, MES_REFERENCIA, IND_SUBSTITUICAO, OBSERVACAO)
SELECT
    SW_SSPPI.SQ_PK_RUBRICA_IMPORTADA.NEXTVAL,
    FF2.ID_FOLHA_FUNCIONARIO,
    RI.ID_RUBRICA,
    RI.IND_TIPO,
    FO2.ID_FOLHA,
    RI.ID_PENSIONISTA_PA,
    RI.PRAZO_PARCELA,
    --LPAD(TO_NUMBER(RI.PRAZO_PARCELA) + 1, 3, '0') PRAZO_PARCELA,
    RI.PRAZO_TOTAL,
    RI.IND_PARAMETRO,
    RI.IND_ORIGEM,
    RI.VALOR_MULTIPLICADOR,
    RI.IND_FORMA_ATUALIZACAO,
    '01/09/2026' DATA_CADASTRO,
    '01/09/2026' DATA_INICIO,
    '30/09/2026' DATA_FIM,
    RI.ANO_REFERENCIA,
    9 MES_REFERENCIA,
    RI.IND_SUBSTITUICAO,
    'CARD 6648'
FROM
    SW_SSPPI.FOLHA FO
    JOIN SW_SSPPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SSPPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SSPPI.FUNC_PEN_ALIM_PENSIONISTA AP ON AP.ID_PENSIONISTA_PA = RI.ID_PENSIONISTA_PA AND AP.DATA_FIM IS NULL
    JOIN SW_SSPPI.FOLHA_FUNC FF2 ON FF2.COD_INSTITUCIONAL = FF.COD_INSTITUCIONAL
    JOIN SW_SSPPI.FOLHA FO2 ON FO2.ID_FOLHA = FF2.ID_FOLHA
WHERE
    FO.MES = 8
    AND FO.ANO = 2026
    AND FO2.MES = 9
    AND FO2.ANO = 2026
    AND RI.IND_ORIGEM = 'P'
    AND AP.IND_ATIVO = 'S'
    AND SUBSTR(FO.CHAVE_FOLHA, 9) = SUBSTR(FO2.CHAVE_FOLHA, 9)
    AND FF.COD_INSTITUCIONAL IN ( '000879-6', '009586-9', '009887-6', '009898-1', '086697-X', '092354-X', '108420-8', '108486-X', '108624-3', '258575-8', '290318-X', '297992-6', '299113-6', '299141-1', '311265-9', '311294-2', '311298-5', '353854-X')
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SSPPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI2
        WHERE
            RI2.ID_FOLHA_FUNCIONARIO = FF2.ID_FOLHA_FUNCIONARIO
            AND RI2.ID_RUBRICA = RI.ID_RUBRICA
    );