SELECT
    'AGESPISA02' AS ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA,
    RF.ID_FORMULA,
    'INSERT INTO SW_AGESPISA02.FOLHA_RUBRICA_FORMULA (ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_FOLHA, ID_RUBRICA, ID_CATEGORIA_ECONOMICA_ADM, ID_CATEGORIA_ECONOMICA_FINANC, VALOR_INFORMADO, ID_FORMULA, ORDENACAO) VALUES (SW_AGESPISA02.SQ_PK_RUBRICA_FORMULA.NEXTVAL, SYSDATE, '
    || FO.ID_FOLHA || ', '
    || NVL(TO_CHAR(RF.ID_RUBRICA), 'NULL') || ', '
    || NVL(TO_CHAR(RF.ID_CATEGORIA_ECONOMICA_ADM), 'NULL') || ', '
    || NVL(TO_CHAR(RF.ID_CATEGORIA_ECONOMICA_FINANC), 'NULL') || ', '
    || NVL(REPLACE(TO_CHAR(RF.VALOR_INFORMADO), ',', '.'), 'NULL') || ', '
    || NVL(TO_CHAR(RF.ID_FORMULA), 'NULL') || ', '
    || NVL(TO_CHAR(RF.ORDENACAO), 'NULL') || ');' AS INSERT_
FROM
    SW_AGESPISA02.FOLHA FO
    JOIN (
        SELECT DISTINCT
            RF_O.ID_RUBRICA,
            RF_O.ID_CATEGORIA_ECONOMICA_ADM,
            RF_O.ID_CATEGORIA_ECONOMICA_FINANC,
            RF_O.VALOR_INFORMADO,
            RF_O.ID_FORMULA,
            RF_O.ORDENACAO
        FROM
            SW_AGESPISA.FOLHA_RUBRICA_FORMULA RF_O
            JOIN SW_AGESPISA.FOLHA FO_O ON FO_O.ID_FOLHA = RF_O.ID_FOLHA
        WHERE
            FO_O.MES = 10
            AND FO_O.ANO = 2026
            AND FO_O.CHAVE_FOLHA = '10/2026-100'
    ) RF ON 1 = 1
WHERE
    FO.MES = 10
    AND FO.ANO = 2026
    AND FO.CHAVE_FOLHA = '10/2026-100'
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_AGESPISA02.FOLHA_RUBRICA_FORMULA RF2
        WHERE
            RF2.ID_FOLHA = FO.ID_FOLHA
            AND RF2.ID_RUBRICA = RF.ID_RUBRICA
    );