SELECT
    'ADAPI' ORGAO,
    ANTERIOR.CHAVE_FOLHA_MES03,
    ANTERIOR.MATRICULA,
    ANTERIOR.NOME,
    ANTERIOR.DIVISAO,
    ANTERIOR.SITUACAO,
    ANTERIOR.COD_RUBRICA_MES03,
    ANTERIOR.VALOR_MULTIPLICADOR_MES03,
    ATUAL.CHAVE_FOLHA_MES04,
    ATUAL.MATRICULA,
    ATUAL.DIVISAO,
    ATUAL.COD_RUBRICA_MES04,
    ATUAL.VALOR_MULTIPLICADOR_MES04
FROM
    (
    SELECT
        FO.CHAVE_FOLHA CHAVE_FOLHA_MES03,
        FF.COD_INSTITUCIONAL MATRICULA,
        HN.NOME,
        PD.NOME_DIVISAO DIVISAO,
        PS.NOME_SITUACAO SITUACAO,
        R.COD_RUBRICA COD_RUBRICA_MES03,
        FR.VALOR_MULTIPLICADOR VALOR_MULTIPLICADOR_MES03
    FROM
        SW_ADAPI.FOLHA FO
        JOIN SW_ADAPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_ADAPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
        JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
        JOIN SW_ADAPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
        JOIN SW_ADAPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
        JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
        JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    WHERE
        FO.MES = 4
        AND FO.ANO = 2026
        AND R.COD_RUBRICA IN (620205)
    ) ANTERIOR
    LEFT JOIN (
    SELECT
        FO.CHAVE_FOLHA CHAVE_FOLHA_MES04,
        FF.COD_INSTITUCIONAL MATRICULA,
        HN.NOME,
        PD.NOME_DIVISAO DIVISAO,
        PS.NOME_SITUACAO SITUACAO,
        R.COD_RUBRICA COD_RUBRICA_MES04,
        FR.VALOR_MULTIPLICADOR VALOR_MULTIPLICADOR_MES04
    FROM
        SW_ADAPI.FOLHA FO
        JOIN SW_ADAPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_ADAPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
        JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
        JOIN SW_ADAPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
        JOIN SW_ADAPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
        JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
        JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    WHERE
        FO.MES = 5
        AND FO.ANO = 2026
        AND R.COD_RUBRICA IN (620205)
    ) ATUAL ON ATUAL.MATRICULA = ANTERIOR.MATRICULA AND ATUAL.COD_RUBRICA_MES04 = ANTERIOR.COD_RUBRICA_MES03 AND SUBSTR(ATUAL.CHAVE_FOLHA_MES04, 9) = SUBSTR(ANTERIOR.CHAVE_FOLHA_MES03, 9);