SELECT
    JAN.ORGAO,
    JAN.NOME,
    JAN.CPF_PESSOA,
    JAN.CHAVE_FOLHA,
    JAN.COD_RUBRICA,
    JAN.RUBRICA,
    JAN.QUANTIDADE  QUANTIDADE_JAN,
    JAN.TOTAL_VALOR TOTAL_JAN,
    FEV.QUANTIDADE  QUANTIDADE_FEV,
    FEV.TOTAL_VALOR TOTAL_FEV,
    MAR.QUANTIDADE  QUANTIDADE_MAR,
    MAR.TOTAL_VALOR TOTAL_MAR,
    ABR.QUANTIDADE  QUANTIDADE_ABR,
    ABR.TOTAL_VALOR TOTAL_ABR,
    MAI.QUANTIDADE  QUANTIDADE_MAI,
    MAI.TOTAL_VALOR TOTAL_MAI,
    JUN.QUANTIDADE  QUANTIDADE_JUN,
    JUN.TOTAL_VALOR TOTAL_JUN
FROM
    (
    SELECT
        'SEADPREVPI' ORGAO,
        HN.NOME,
        PC.CPF_PESSOA,
        FO.CHAVE_FOLHA,
        R.COD_RUBRICA,
        R.NOME_RUBRICA RUBRICA,
        COUNT(R.COD_RUBRICA) QUANTIDADE,
        SUM(FR.VALOR_CALCULADO) TOTAL_VALOR
    FROM
        SW_SEADPREVPI.FOLHA FO
        JOIN SW_SEADPREVPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEADPREVPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
        JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    WHERE
        FO.MES = 1
        AND FO.ANO = 2026
        AND R.COD_RUBRICA IN (112992)
    GROUP BY
        'SEADPREVPI',
        HN.NOME,
        PC.CPF_PESSOA,
        FO.CHAVE_FOLHA,
        R.COD_RUBRICA,
        R.NOME_RUBRICA
    ) JAN
    LEFT JOIN (
    SELECT
        'SEADPREVPI' ORGAO,
        HN.NOME,
        PC.CPF_PESSOA,
        FO.CHAVE_FOLHA,
        R.COD_RUBRICA,
        R.NOME_RUBRICA RUBRICA,
        COUNT(R.COD_RUBRICA) QUANTIDADE,
        SUM(FR.VALOR_CALCULADO) TOTAL_VALOR
    FROM
        SW_SEADPREVPI.FOLHA FO
        JOIN SW_SEADPREVPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEADPREVPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
        JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    WHERE
        FO.MES = 2
        AND FO.ANO = 2026
        AND R.COD_RUBRICA IN (112992)
    GROUP BY
        'SEADPREVPI',
        HN.NOME,
        PC.CPF_PESSOA,
        FO.CHAVE_FOLHA,
        R.COD_RUBRICA,
        R.NOME_RUBRICA
    ) FEV ON FEV.CPF_PESSOA = JAN.CPF_PESSOA AND SUBSTR(FEV.CHAVE_FOLHA, 9) = SUBSTR(JAN.CHAVE_FOLHA, 9) AND FEV.COD_RUBRICA = JAN.COD_RUBRICA
    LEFT JOIN (
    SELECT
        'SEADPREVPI' ORGAO,
        HN.NOME,
        PC.CPF_PESSOA,
        FO.CHAVE_FOLHA,
        R.COD_RUBRICA,
        R.NOME_RUBRICA RUBRICA,
        COUNT(R.COD_RUBRICA) QUANTIDADE,
        SUM(FR.VALOR_CALCULADO) TOTAL_VALOR
    FROM
        SW_SEADPREVPI.FOLHA FO
        JOIN SW_SEADPREVPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEADPREVPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
        JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    WHERE
        FO.MES = 3
        AND FO.ANO = 2026
        AND R.COD_RUBRICA IN (112992)
    GROUP BY
        'SEADPREVPI',
        HN.NOME,
        PC.CPF_PESSOA,
        FO.CHAVE_FOLHA,
        R.COD_RUBRICA,
        R.NOME_RUBRICA
    ) MAR ON MAR.CPF_PESSOA = JAN.CPF_PESSOA AND SUBSTR(MAR.CHAVE_FOLHA, 9) = SUBSTR(JAN.CHAVE_FOLHA, 9) AND MAR.COD_RUBRICA = JAN.COD_RUBRICA
    LEFT JOIN (
    SELECT
        'SEADPREVPI' ORGAO,
        HN.NOME,
        PC.CPF_PESSOA,
        FO.CHAVE_FOLHA,
        R.COD_RUBRICA,
        R.NOME_RUBRICA RUBRICA,
        COUNT(R.COD_RUBRICA) QUANTIDADE,
        SUM(FR.VALOR_CALCULADO) TOTAL_VALOR
    FROM
        SW_SEADPREVPI.FOLHA FO
        JOIN SW_SEADPREVPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEADPREVPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
        JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    WHERE
        FO.MES = 4
        AND FO.ANO = 2026
        AND R.COD_RUBRICA IN (112992)
    GROUP BY
        'SEADPREVPI',
        HN.NOME,
        PC.CPF_PESSOA,
        FO.CHAVE_FOLHA,
        R.COD_RUBRICA,
        R.NOME_RUBRICA
    ) ABR ON ABR.CPF_PESSOA = JAN.CPF_PESSOA AND SUBSTR(ABR.CHAVE_FOLHA, 9) = SUBSTR(JAN.CHAVE_FOLHA, 9) AND ABR.COD_RUBRICA = JAN.COD_RUBRICA
    LEFT JOIN (
    SELECT
        'SEADPREVPI' ORGAO,
        HN.NOME,
        PC.CPF_PESSOA,
        FO.CHAVE_FOLHA,
        R.COD_RUBRICA,
        R.NOME_RUBRICA RUBRICA,
        COUNT(R.COD_RUBRICA) QUANTIDADE,
        SUM(FR.VALOR_CALCULADO) TOTAL_VALOR
    FROM
        SW_SEADPREVPI.FOLHA FO
        JOIN SW_SEADPREVPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEADPREVPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
        JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    WHERE
        FO.MES = 5
        AND FO.ANO = 2026
        AND R.COD_RUBRICA IN (112992)
    GROUP BY
        'SEADPREVPI',
        HN.NOME,
        PC.CPF_PESSOA,
        FO.CHAVE_FOLHA,
        R.COD_RUBRICA,
        R.NOME_RUBRICA
    ) MAI ON MAI.CPF_PESSOA = JAN.CPF_PESSOA AND SUBSTR(MAI.CHAVE_FOLHA, 9) = SUBSTR(JAN.CHAVE_FOLHA, 9) AND MAI.COD_RUBRICA = JAN.COD_RUBRICA
    LEFT JOIN (
    SELECT
        'SEADPREVPI' ORGAO,
        HN.NOME,
        PC.CPF_PESSOA,
        FO.CHAVE_FOLHA,
        R.COD_RUBRICA,
        R.NOME_RUBRICA RUBRICA,
        COUNT(R.COD_RUBRICA) QUANTIDADE,
        SUM(FR.VALOR_CALCULADO) TOTAL_VALOR
    FROM
        SW_SEADPREVPI.FOLHA FO
        JOIN SW_SEADPREVPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
        JOIN SW_SEADPREVPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
        JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
        JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
        JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    WHERE
        FO.MES = 6
        AND FO.ANO = 2026
        AND R.COD_RUBRICA IN (112992)
    GROUP BY
        'SEADPREVPI',
        HN.NOME,
        PC.CPF_PESSOA,
        FO.CHAVE_FOLHA,
        R.COD_RUBRICA,
        R.NOME_RUBRICA
    ) JUN ON JUN.CPF_PESSOA = JAN.CPF_PESSOA AND SUBSTR(JUN.CHAVE_FOLHA, 9) = SUBSTR(JAN.CHAVE_FOLHA, 9) AND JUN.COD_RUBRICA = JAN.COD_RUBRICA
;