SELECT DISTINCT
    FO.CHAVE_FOLHA,
    FO.DESCRICAO,
    FC.ANO,
    FC.MES,
    22 COD_IBGE,
    'Governo do Estado do Piauí' NOME_ENTE,
    'PI' UF,
    CASE
        WHEN CF.ID_CATEGORIA_FUNCIONAL = 1000081 THEN 2 -- Militar (3º Sargento)
        ELSE 1                                          -- Civil
    END COMP_MASSA,
    1 TIPO_FUNDO, -- Plano Previdenciário
    E.CNPJ CNPJ_ORGAO,
    E.RAZAO_SOCIAL NOME_ORGAO,
    1 PODER, -- Executivo
    1 TIPO_PODER, -- Administração Direta
    CASE
        WHEN EXISTS (
            SELECT 1 FROM SW_DEFENSORIA.FOLHA_FICHA_FINANCEIRA
            WHERE ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
              AND ID_RUBRICA = 11
        ) THEN 2  -- Servidores Ativos Iminentes (abono permanência)
        ELSE 1    -- Servidores Ativos
    END TIPO_POPULACAO,
    CASE
        WHEN CF.ID_CATEGORIA_FUNCIONAL = 1000081             THEN 8  -- 3º Sargento → Militar
        WHEN CF.ID_CATEGORIA_FUNCIONAL = 1                   THEN 1  -- Defensor → Magistrados/Membros MP/Tribunal de Contas
        WHEN CF.ID_CATEGORIA_FUNCIONAL IN (1000020, 1000060) THEN 2  -- Professores Educ. Infantil/Fund./Médio
        WHEN CF.ID_CATEGORIA_FUNCIONAL = 1000040             THEN 5  -- Agente Penitenciário
        ELSE 7                                                        -- Demais Servidores
    END TIPO_CARGO,
    CASE
        WHEN CF.ID_CATEGORIA_FUNCIONAL = 1000081             THEN 8  -- 3º Sargento → Militar em Atividade
        WHEN CF.ID_CATEGORIA_FUNCIONAL = 1                   THEN 1  -- Defensor → Sem critério diferenciado
        WHEN CF.ID_CATEGORIA_FUNCIONAL IN (1000020, 1000060) THEN 3  -- Critério para aposentadoria como professor
        WHEN CF.ID_CATEGORIA_FUNCIONAL = 1000040             THEN 4  -- Atividade de risco (Art. 40, §4º, inc. II, CF)
        ELSE 1                                                        -- Sem critério diferenciado
    END CRITERIO_ELEGIBILIDADE,
    FC.COD_INSTITUCIONAL MATRICULA,
    FC.CPF_PESSOA CPF,
    FC.PISPASEP,
    CASE
        WHEN P.ID_SEXO = 1 THEN 'M'
        WHEN P.ID_SEXO = 2 THEN 'F'
    END SEXO_SERVIDOR,
    CASE
        WHEN EC.ID_ESTADO_CIVIL = 1      THEN 1
        WHEN EC.ID_ESTADO_CIVIL = 2      THEN 2
        WHEN EC.ID_ESTADO_CIVIL = 4      THEN 3
        WHEN EC.ID_ESTADO_CIVIL = 5      THEN 4
        WHEN EC.ID_ESTADO_CIVIL = 550000 THEN 5
        WHEN EC.ID_ESTADO_CIVIL = 6      THEN 6
    END ESTADO_CIVIL_SERVIDOR,
    FC.DATA_NASCIMENTO,
    1 SITUACAO_FUNCIONAL, -- BUSCAR PELO PERFIL COM REMUNERAÇÃO LICENCIADO CADASTRO DE LICENÇA AFASTAMENTO
    CASE -- DATA DE EXERCÍCIO ANTERIOR A 1983 TIPO 3
        WHEN SUBSTR(FO.CHAVE_FOLHA, - 3) = '100' AND PER.ID_DIVISAO = 1000001 AND FP.IND_FUNCAO = 'S' THEN 2
        WHEN SUBSTR(FO.CHAVE_FOLHA, - 3) IN ( '100', '200' ) AND FP.IND_FUNCAO = 'N' THEN 1
        WHEN SUBSTR(FO.CHAVE_FOLHA, - 3) IN ( '100', '200' ) AND FP.IND_FUNCAO = 'S'
             AND (
            SELECT
                ID_RUBRICA
            FROM
                SW_DEFENSORIA.FOLHA_FICHA_FINANCEIRA
            WHERE
                ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
                AND ID_RUBRICA = 7
        ) IS NOT NULL THEN 1
        WHEN SUBSTR(FO.CHAVE_FOLHA, - 3) IN ( '100', '200' ) AND FP.IND_FUNCAO = 'S' THEN 2
        ELSE 4
    END TIPO_VINCULO,
    '' DATA_INGRESSO_SERVICO_PUBLICO,
    FC.DATA_ADMISSAO DATA_INGRESSO_ENTE,
    FI.DATA_EXERCICIO DATA_INGRESSO_CARREIRA,
    C.NOME_CARREIRA CARREIRA,
    CF.NOME_CATEGORIA_FUNCIONAL CARGO,
    NVL((
        SELECT
            SUM(VALOR_CALCULADO)
        FROM
            SW_DEFENSORIA.FOLHA_FICHA_FINANCEIRA
        WHERE
                ID_RUBRICA = 1553119
            AND ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    ), 0) VALOR_BASE_CALCULO,
    NVL((
        SELECT
            SUM(VALOR_CALCULADO)
        FROM
            SW_DEFENSORIA.FOLHA_FICHA_FINANCEIRA
        WHERE
                ID_RUBRICA = 51027
            AND ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    ), 0) VALOR_REMUNERACAO,
    NVL((
        SELECT
            SUM(VALOR_CALCULADO)
        FROM
            SW_DEFENSORIA.FOLHA_FICHA_FINANCEIRA
        WHERE
            ID_RUBRICA IN (1552873, 1001040, 1000600, 1553806)
            AND ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
        GROUP BY
            ID_FOLHA_FUNCIONARIO
    ), 0) VALOR_CONTRIBUICAO,
    '' TEMPO_RGPS,
    '' TEMPO_RPPS_MUNICIPAL,
    '' TEMPO_RPPS_ESTADUAL,
    '' TEMPO_RPPS_FEDERAL,
    NVL((
        SELECT
            COUNT(ID_PESSOA_DEPENDENTE)
        FROM
            SW_PUBLICO.PESSOA_DECLARACAO_FAMILIA
        WHERE
            ID_PESSOA_TITULAR = FC.ID_PESSOA
            AND DATA_FINAL IS NULL
    ), 0) NUMERO_DEPENDENTES,
    NVL((
        SELECT
            1
        FROM
            SW_DEFENSORIA.FOLHA_FICHA_FINANCEIRA
        WHERE
            ID_RUBRICA = 11
            AND ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    ), 2) ABONO_PERMANENCIA,
    '' INICIO_ABONO,
    NVL((
        SELECT
            1
        FROM
            SW_DEFENSORIA.FOLHA_FICHA_FINANCEIRA
        WHERE
                ID_RUBRICA = 1001042
            AND ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    ), 2) PREVIDENCIA_COMPLEMENTAR,
    NVL((
        SELECT
            SUM(VALOR_CALCULADO)
        FROM
            SW_DEFENSORIA.FOLHA_FICHA_FINANCEIRA
        WHERE
            ID_RUBRICA = 431
            AND ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
        GROUP BY
            ID_FOLHA_FUNCIONARIO
    ), 0) TETO_ESPECIFICO,
    CASE
        WHEN CF.ID_CATEGORIA_FUNCIONAL = 1000081 THEN
            -- 3º Sargento: aposentadoria compulsória aos 54 anos (conforme regra militar)
            P.DATA_NASCIMENTO + ( 54 * 365 )
        ELSE
            P.DATA_NASCIMENTO + ( 70 * 365 )
    END DATA_PROVAVEL_APOSENTADORIA
FROM
    SW_DEFENSORIA.FOLHA FO
    JOIN SW_DEFENSORIA.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_DEFENSORIA.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FC.ID_FUNCIONARIO
    LEFT JOIN SW_DEFENSORIA.FUNCIONARIO_REFERENCIA FREF ON FREF.ID_FUNCIONARIO = FC.ID_FUNCIONARIO AND FREF.DATA_TERMINO IS NULL
    LEFT JOIN SW_DEFENSORIA.RHB_CARREIRA_CATEG_FUNCIONAL CF ON CF.ID_CATEGORIA_FUNCIONAL = FREF.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.EMPRESA E ON E.SIGLA = 'DEFENSORIA'
    JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FC.ID_PESSOA
    LEFT JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = P.ID_PESSOA AND EC.DATA_FIM IS NULL
    LEFT JOIN SW_DEFENSORIA.FOLHA_FUNC_PERFIL FP ON FP.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO AND FP.DATA_FIM IS NULL
    LEFT JOIN SW_DEFENSORIA.RHB_PERFIL PER ON PER.ID_PERFIL = FP.ID_PERFIL
    LEFT JOIN SW_DEFENSORIA.RHB_CARREIRA C ON C.ID_CARREIRA = CF.ID_CARREIRA
    LEFT JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = PER.ID_SITUACAO AND PS.ID_SITUACAO IN (1000020,1000000,1000859,1000860,1000862,1000030,1000799)
WHERE
    FO.MES = 7
    AND FO.ANO = 2025
    AND REGEXP_LIKE(FO.CHAVE_FOLHA, '-100|-110|-120|-200')
    AND FO.ID_TIPO_FOLHA = 1000000;