SELECT 
    'SEFAZPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO,
    '' REFERENCIA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    PC.CPF_PESSOA CPF,
    '' DEPENDENTES_IR,
    '' DEPENDESTES_SF,
    '' JOIA_PREVIDENCIA,
    '' GRATIFICACAO,
    CCF.NOME_CATEGORIA_FUNCIONAL CARGO_EFETIVO,
    CCE.NOME_ESPECIALIDADE ESPECIALIDADE,
    '' CARGO_COMISSAO,
    PD.NOME_DIVISAO DIVISAO,
    PS.NOME_SITUACAO SITUACAO,
    PTF.NOME_TIPO_FUNCIONARIO TIPO_SERVIDOR,
    PE.DATA_NASCIMENTO,
    FI.DATA_POSSE DATA_ADMISSAO,
    FI.DATA_POSSE,
    L.NOME_LOTACAO LOTACAO,
    '' CENTRO,
    '' CONTRIBUICAO_PREV_PRIVADA,
    B.BANCO_DESCRICAO NOME_BANCO,
    BA.NOME_AGENCIA,
    PB.CONTA_CORRENTE CONTA_BANCO, -- RETIRAR OS 0 A ESQUERDA
    A.DATA_APOSENTADORIA,
    /*
    CASE FPC.IND_CALCULO
        WHEN 'R' THEN 'Remuneração'
        WHEN 'P' THEN 'Com Paridade'
        WHEN 'B' THEN 'Benefício Médio'
    END CALCULO
    */
    RA.NOME_APOSENTADORIA,
    AR.NOME_REGRA REGRA,
    '' CPF_INSTITUIDOR,
    '' MATRICULA_INSTITUIDOR,
    '' NOME_INSTITUIDOR,
    PE.DATA_OBITO,
    FS.NOME_SEXO SEXO,
    PEC.NOME_ESTADO_CIVIL ESTADO_CIVIL,
    FRC.NOME_RACA_COR,
    FFR.NOME_TIPO_SANGUE TIPO_SANGUE
FROM 
    SW_SEFAZPI.FOLHA FO 
    JOIN SW_SEFAZPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEFAZPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
    LEFT JOIN SW_SEFAZPI.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_SEFAZPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
    JOIN SW_SEFAZPI.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = NVL(FR.ID_CATEGORIA_FUNCIONAL, FI.ID_CATEGORIA_FUNCIONAL)
    LEFT JOIN SW_SEFAZPI.RHB_CARREIRA_CATEG_ESPECIALID CCE ON CCE.ID_ESPECIALIDADE = FR.ID_ESPECIALIDADE
    LEFT JOIN SW_SEFAZPI.FUNC_LOTACAO FL ON FL.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
    LEFT JOIN SW_SEFAZPI.RHB_LOTACAO L ON L.ID_LOTACAO = FL.ID_LOTACAO
    LEFT JOIN SW_SEFAZPI.FUNC_PENSAO_CIVIL FPC ON FPC.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
    LEFT JOIN SW_SEFAZPI.FUNC_APOSENTADORIA A ON A.ID_FUNCIONARIO = FF.ID_FUNCIONARIO
    LEFT JOIN SW_PUBLICO.RHB_APOSENTADORIA RA ON RA.ID_TIPO_APOSENTADORIA = A.ID_TIPO_APOSENTADORIA
    LEFT JOIN SW_PUBLICO.RHB_APOSENTADORIA_REGRA AR ON AR.ID_REGRA = A.ID_REGRA_TIPO
    LEFT JOIN SW_SEFAZPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    LEFT JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    LEFT JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    LEFT JOIN SW_PUBLICO.RHB_PERFIL_TIPO_FUNCIONARIO PTF ON PTF.ID_TIPO_FUNCIONARIO = FP.ID_TIPO_FUNCIONARIO
    JOIN SW_PUBLICO.PESSOA PE ON PE.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
    LEFT JOIN SW_PUBLICO.PESSOA_BANCO PB ON PB.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
    LEFT JOIN SW_PUBLICO.RHB_BANCO B ON B.ID_BANCO = PB.ID_PESSOA_BANCO
    LEFT JOIN SW_PUBLICO.RHB_BANCO_AGENCIA BA ON BA.ID_AGENCIA = PB.ID_AGENCIA
    LEFT JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = PE.ID_SEXO
    LEFT JOIN SW_PUBLICO.PESSOA_ESTADO_CIVIL EC ON EC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
    LEFT JOIN SW_PUBLICO.RHB_INF_PESSOAL_ESTADO_CIVIL PEC ON PEC.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
    LEFT JOIN SW_PUBLICO.PESSOA_CARACTERISTICA_FISICA PCF ON PCF.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO
    LEFT JOIN SW_PUBLICO.RHB_CARACT_FISICA_RACA_COR FRC ON FRC.ID_RACA_COR = PCF.ID_RACA_COR
    LEFT JOIN SW_PUBLICO.RHB_CARACT_FISICA_FATOR_RH FFR ON FFR.ID_TIPO_SANGUE = PCF.ID_TIPO_SANGUE
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL