SELECT 
'VICEGOV' ORGAO,
HN.NOME,
V.ID_VINCULO,
V.DESCRICAO_VINCULO,
PV.ID_PESSOA_VINCULO,
PV.COD_INSTITUCIONAL,
'UPDATE SW_VICEGOV.PESSOA_VINCULO SET ID_VINCULO = 2 WHERE ID_PESSOA_VINCULO = ' || PV.ID_PESSOA_VINCULO || ';' UPDATE_
FROM 
    SW_VICEGOV.PESSOA_VINCULO PV
    JOIN SW_VICEGOV.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
WHERE 
    PV.ID_PESSOA_VINCULO = 1002261;

UPDATE SW_VICEGOV.PESSOA_VINCULO SET ID_VINCULO = 2 WHERE ID_PESSOA_VINCULO = 1002261;