SELECT
    'AGESPISA' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_AGESPISA.FOLHA FO
    LEFT JOIN SW_AGESPISA.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'CAPSI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_CAPSI.FOLHA FO
    LEFT JOIN SW_CAPSI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'CBMPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_CBMPI.FOLHA FO
    LEFT JOIN SW_CBMPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'CENDFOL' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_CENDFOL.FOLHA FO
    LEFT JOIN SW_CENDFOL.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'CRS_I' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_CRS_I.FOLHA FO
    LEFT JOIN SW_CRS_I.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'CRS_III' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_CRS_III.FOLHA FO
    LEFT JOIN SW_CRS_III.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'CRS_IV' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_CRS_IV.FOLHA FO
    LEFT JOIN SW_CRS_IV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'CRS_IX' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_CRS_IX.FOLHA FO
    LEFT JOIN SW_CRS_IX.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'CRS_V' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_CRS_V.FOLHA FO
    LEFT JOIN SW_CRS_V.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'CRS_VII' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_CRS_VII.FOLHA FO
    LEFT JOIN SW_CRS_VII.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'CRS_VIII' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_CRS_VIII.FOLHA FO
    LEFT JOIN SW_CRS_VIII.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'CRS_X' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_CRS_X.FOLHA FO
    LEFT JOIN SW_CRS_X.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'CRS_XII' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_CRS_XII.FOLHA FO
    LEFT JOIN SW_CRS_XII.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'CRS_XIII' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_CRS_XIII.FOLHA FO
    LEFT JOIN SW_CRS_XIII.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'CRS_XV' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_CRS_XV.FOLHA FO
    LEFT JOIN SW_CRS_XV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'DEFCIVIL' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_DEFCIVIL.FOLHA FO
    LEFT JOIN SW_DEFCIVIL.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'DGPCPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_DGPCPI.FOLHA FO
    LEFT JOIN SW_DGPCPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'FAPEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_FAPEPI.FOLHA FO
    LEFT JOIN SW_FAPEPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'FESPPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_FESPPI.FOLHA FO
    LEFT JOIN SW_FESPPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'FUESPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_FUESPI.FOLHA FO
    LEFT JOIN SW_FUESPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'FUNAP' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_FUNAP.FOLHA FO
    LEFT JOIN SW_FUNAP.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'FUNPESPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_FUNPESPI.FOLHA FO
    LEFT JOIN SW_FUNPESPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'FUNSAUDE' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_FUNSAUDE.FOLHA FO
    LEFT JOIN SW_FUNSAUDE.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'GAMIL' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_GAMIL.FOLHA FO
    LEFT JOIN SW_GAMIL.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'HAA' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_HAA.FOLHA FO
    LEFT JOIN SW_HAA.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'HCC' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_HCC.FOLHA FO
    LEFT JOIN SW_HCC.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'HEDA' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_HEDA.FOLHA FO
    LEFT JOIN SW_HEDA.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'HEJBC' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_HEJBC.FOLHA FO
    LEFT JOIN SW_HEJBC.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'HEJFM' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_HEJFM.FOLHA FO
    LEFT JOIN SW_HEJFM.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'HEJH' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_HEJH.FOLHA FO
    LEFT JOIN SW_HEJH.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'HEJLM' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_HEJLM.FOLHA FO
    LEFT JOIN SW_HEJLM.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'HEMOPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_HEMOPI.FOLHA FO
    LEFT JOIN SW_HEMOPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'HENM' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_HENM.FOLHA FO
    LEFT JOIN SW_HENM.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'HGV' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_HGV.FOLHA FO
    LEFT JOIN SW_HGV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'HILP' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_HILP.FOLHA FO
    LEFT JOIN SW_HILP.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'HLDC' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_HLDC.FOLHA FO
    LEFT JOIN SW_HLDC.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'HLGCB' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_HLGCB.FOLHA FO
    LEFT JOIN SW_HLGCB.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'HLJMF' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_HLJMF.FOLHA FO
    LEFT JOIN SW_HLJMF.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'HPM' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_HPM.FOLHA FO
    LEFT JOIN SW_HPM.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'HRCF' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_HRCF.FOLHA FO
    LEFT JOIN SW_HRCF.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'HRCM' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_HRCM.FOLHA FO
    LEFT JOIN SW_HRCM.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'HRCR' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_HRCR.FOLHA FO
    LEFT JOIN SW_HRCR.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'HRDA' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_HRDA.FOLHA FO
    LEFT JOIN SW_HRDA.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'HRDC' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_HRDC.FOLHA FO
    LEFT JOIN SW_HRDC.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'HREP' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_HREP.FOLHA FO
    LEFT JOIN SW_HREP.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'HRFAC' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_HRFAC.FOLHA FO
    LEFT JOIN SW_HRFAC.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'HRJL' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_HRJL.FOLHA FO
    LEFT JOIN SW_HRJL.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'HRJPC' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_HRJPC.FOLHA FO
    LEFT JOIN SW_HRJPC.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'HRLM' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_HRLM.FOLHA FO
    LEFT JOIN SW_HRLM.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'HRP' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_HRP.FOLHA FO
    LEFT JOIN SW_HRP.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'HRTN' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_HRTN.FOLHA FO
    LEFT JOIN SW_HRTN.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'HRTNB' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_HRTNB.FOLHA FO
    LEFT JOIN SW_HRTNB.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'IASPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_IASPI.FOLHA FO
    LEFT JOIN SW_IASPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'IDTNP' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_IDTNP.FOLHA FO
    LEFT JOIN SW_IDTNP.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'INTERPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_INTERPI.FOLHA FO
    LEFT JOIN SW_INTERPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'LACEN' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_LACEN.FOLHA FO
    LEFT JOIN SW_LACEN.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'MDER' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_MDER.FOLHA FO
    LEFT JOIN SW_MDER.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'METRO' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_METRO.FOLHA FO
    LEFT JOIN SW_METRO.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'PMPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_PMPI.FOLHA FO
    LEFT JOIN SW_PMPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'PRODSUS' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_PRODSUS.FOLHA FO
    LEFT JOIN SW_PRODSUS.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'RMSS' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_RMSS.FOLHA FO
    LEFT JOIN SW_RMSS.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'SAF' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SAF.FOLHA FO
    LEFT JOIN SW_SAF.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'SASC' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SASC.FOLHA FO
    LEFT JOIN SW_SASC.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'SEADPREVPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SEADPREVPI.FOLHA FO
    LEFT JOIN SW_SEADPREVPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'SECEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SECEPI.FOLHA FO
    LEFT JOIN SW_SECEPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'SECULT' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SECULT.FOLHA FO
    LEFT JOIN SW_SECULT.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'SEDUC' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SEDUC.FOLHA FO
    LEFT JOIN SW_SEDUC.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'SEDUC_ALFA' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SEDUC_ALFA.FOLHA FO
    LEFT JOIN SW_SEDUC_ALFA.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'SEDUC_EDIT' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SEDUC_EDIT.FOLHA FO
    LEFT JOIN SW_SEDUC_EDIT.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'SEDUC_EJA' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SEDUC_EJA.FOLHA FO
    LEFT JOIN SW_SEDUC_EJA.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'SEDUC_PTEC' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SEDUC_PTEC.FOLHA FO
    LEFT JOIN SW_SEDUC_PTEC.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'SEFAZ' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SEFAZ.FOLHA FO
    LEFT JOIN SW_SEFAZ.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'SEJUSPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SEJUSPI.FOLHA FO
    LEFT JOIN SW_SEJUSPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'SEMARH' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SEMARH.FOLHA FO
    LEFT JOIN SW_SEMARH.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'SEPLAN' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SEPLAN.FOLHA FO
    LEFT JOIN SW_SEPLAN.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'SETRE' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SETRE.FOLHA FO
    LEFT JOIN SW_SETRE.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'SSPPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SSPPI.FOLHA FO
    LEFT JOIN SW_SSPPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'TFD' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_TFD.FOLHA FO
    LEFT JOIN SW_TFD.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'UIS' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_UIS.FOLHA FO
    LEFT JOIN SW_UIS.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'UMS_AVLN' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_UMS_AVLN.FOLHA FO
    LEFT JOIN SW_UMS_AVLN.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'UMSBOC' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_UMSBOC.FOLHA FO
    LEFT JOIN SW_UMSBOC.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'UMS_FILO' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_UMS_FILO.FOLHA FO
    LEFT JOIN SW_UMS_FILO.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'UMS_FRANC' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_UMS_FRANC.FOLHA FO
    LEFT JOIN SW_UMS_FRANC.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'UMS_ITAIN' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_UMS_ITAIN.FOLHA FO
    LEFT JOIN SW_UMS_ITAIN.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026

UNION ALL

SELECT
    'UMS_PAES' ORGAO,
    FO.CHAVE_FOLHA,
    FO.MES, 
    FO.ANO,
    FO.DATA_INICIO,
    FO.DATA_FECHAMENTO,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_UMS_PAES.FOLHA FO
    LEFT JOIN SW_UMS_PAES.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
WHERE 
    FO.MES = 8
    AND FO.ANO = 2026