SELECT DISTINCT
    S.ID_TABELA,
    S.NOME_TABELA
FROM
    (
    SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_AGESPISA.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_CAPSI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_CBMPI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_CENDFOL.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_CRS_I.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_CRS_III.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_CRS_IV.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_CRS_IX.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_CRS_V.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_CRS_VII.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_CRS_VIII.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_CRS_X.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_CRS_XII.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_CRS_XIII.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_CRS_XV.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_DEFCIVIL.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_DGPCPI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_EMPRESA.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_FAPEPI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_FESPPI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_FUESPI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_FUNAP.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_FUNDESPI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_FUNPESPI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_FUNSAUDE.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_GAMIL.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_HAA.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_HCC.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_HEDA.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_HEJBC.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_HEJFM.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_HEJH.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_HEJLM.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_HEMOPI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_HENM.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_HGV.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_HILP.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_HLDC.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_HLGCB.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_HLJMF.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_HPM.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_HRCF.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_HRCM.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_HRCR.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_HRDA.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_HRDC.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_HREP.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_HRFAC.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_HRJL.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_HRJPC.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_HRLM.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_HRP.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_HRTN.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_HRTNB.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_IASPI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_IDTNP.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_INTERPI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_LACEN.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_MDER.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_METRO.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_PMPI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_PRODSUS.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_RMSS.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_SAF.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_SASC.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_SEADPREVPI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_SECEPI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_SECULT.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_SEDUC.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_SEDUC_ALFA.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_SEDUC_EDIT.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_SEDUC_EJA.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_SEDUC_PTEC.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_SEDUC_SHOI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_SEFAZ.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_SEJUSPI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_SEMARH.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_SEPLAN.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_SETRE.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_SSPPI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_TFD.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_UIS.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_UMS_AVLN.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_UMSBOC.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_UMS_FILO.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_UMS_FRANC.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_UMS_ITAIN.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
UNION ALL    
SELECT 
    VT.ID_TABELA,
    T.NOME_TABELA
FROM 
    SW_UMS_PAES.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
    ) S;