SELECT 
    'AGESPISA' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_AGESPISA.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'AGESPISA',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'CAPSI' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_CAPSI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'CAPSI',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'CBMPI' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_CBMPI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'CBMPI',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'CENDFOL' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_CENDFOL.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'CENDFOL',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'CRS_I' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_CRS_I.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'CRS_I',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'CRS_III' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_CRS_III.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'CRS_III',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'CRS_IV' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_CRS_IV.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'CRS_IV',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'CRS_IX' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_CRS_IX.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'CRS_IX',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'CRS_V' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_CRS_V.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'CRS_V',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'CRS_VII' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_CRS_VII.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'CRS_VII',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'CRS_VIII' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_CRS_VIII.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'CRS_VIII',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'CRS_X' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_CRS_X.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'CRS_X',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'CRS_XII' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_CRS_XII.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'CRS_XII',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'CRS_XIII' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_CRS_XIII.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'CRS_XIII',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'CRS_XV' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_CRS_XV.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'CRS_XV',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'DEFCIVIL' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_DEFCIVIL.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'DEFCIVIL',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'DGPCPI' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_DGPCPI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'DGPCPI',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'EMPRESA' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_EMPRESA.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'EMPRESA',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'FAPEPI' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_FAPEPI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'FAPEPI',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'FESPPI' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_FESPPI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'FESPPI',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'FUESPI' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_FUESPI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'FUESPI',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'FUNAP' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_FUNAP.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'FUNAP',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'FUNDESPI' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_FUNDESPI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'FUNDESPI',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'FUNPESPI' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_FUNPESPI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'FUNPESPI',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'FUNSAUDE' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_FUNSAUDE.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'FUNSAUDE',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'GAMIL' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_GAMIL.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'GAMIL',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'HAA' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_HAA.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'HAA',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'HCC' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_HCC.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'HCC',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'HEDA' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_HEDA.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'HEDA',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'HEJBC' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_HEJBC.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'HEJBC',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'HEJFM' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_HEJFM.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'HEJFM',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'HEJH' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_HEJH.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'HEJH',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'HEJLM' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_HEJLM.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'HEJLM',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'HEMOPI' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_HEMOPI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'HEMOPI',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'HENM' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_HENM.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'HENM',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'HGV' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_HGV.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'HGV',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'HILP' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_HILP.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'HILP',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'HLDC' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_HLDC.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'HLDC',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'HLGCB' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_HLGCB.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'HLGCB',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'HLJMF' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_HLJMF.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'HLJMF',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'HPM' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_HPM.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'HPM',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'HRCF' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_HRCF.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'HRCF',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'HRCM' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_HRCM.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'HRCM',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'HRCR' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_HRCR.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'HRCR',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'HRDA' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_HRDA.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'HRDA',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'HRDC' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_HRDC.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'HRDC',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'HREP' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_HREP.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'HREP',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'HRFAC' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_HRFAC.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'HRFAC',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'HRJL' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_HRJL.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'HRJL',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'HRJPC' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_HRJPC.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'HRJPC',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'HRLM' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_HRLM.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'HRLM',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'HRP' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_HRP.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'HRP',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'HRTN' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_HRTN.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'HRTN',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'HRTNB' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_HRTNB.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'HRTNB',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'IASPI' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_IASPI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'IASPI',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'IDTNP' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_IDTNP.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'IDTNP',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'INTERPI' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_INTERPI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'INTERPI',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'LACEN' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_LACEN.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'LACEN',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'MDER' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_MDER.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'MDER',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'METRO' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_METRO.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'METRO',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'PMPI' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_PMPI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'PMPI',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'PRODSUS' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_PRODSUS.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'PRODSUS',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'RMSS' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_RMSS.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'RMSS',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'SAF' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_SAF.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'SAF',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'SASC' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_SASC.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'SASC',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'SEADPREVPI' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_SEADPREVPI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'SEADPREVPI',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'SECEPI' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_SECEPI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'SECEPI',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'SECULT' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_SECULT.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'SECULT',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'SEDUC' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_SEDUC.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'SEDUC',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'SEDUC_ALFA' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_SEDUC_ALFA.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'SEDUC_ALFA',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'SEDUC_EDIT' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_SEDUC_EDIT.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'SEDUC_EDIT',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'SEDUC_EJA' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_SEDUC_EJA.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'SEDUC_EJA',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'SEDUC_PTEC' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_SEDUC_PTEC.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'SEDUC_PTEC',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'SEDUC_SHOI' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_SEDUC_SHOI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'SEDUC_SHOI',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'SEFAZ' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_SEFAZ.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'SEFAZ',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'SEJUSPI' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_SEJUSPI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'SEJUSPI',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'SEMARH' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_SEMARH.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'SEMARH',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'SEPLAN' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_SEPLAN.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'SEPLAN',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'SETRE' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_SETRE.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'SETRE',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'SSPPI' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_SSPPI.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'SSPPI',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'TFD' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_TFD.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'TFD',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'UIS' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_UIS.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'UIS',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'UMS_AVLN' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_UMS_AVLN.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'UMS_AVLN',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'UMSBOC' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_UMSBOC.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'UMSBOC',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'UMS_FILO' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_UMS_FILO.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'UMS_FILO',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'UMS_FRANC' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_UMS_FRANC.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'UMS_FRANC',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'UMS_ITAIN' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_UMS_ITAIN.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'UMS_ITAIN',
    VT.ID_TABELA,
    T.NOME_TABELA
UNION ALL
SELECT 
    'UMS_PAES' ORGAO,
    VT.ID_TABELA,
    T.NOME_TABELA,
    COUNT(VT.ID_VALOR_TABELA) QUANTIDADE
FROM
    SW_UMS_PAES.FOLHA_VALOR_TABELA VT
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA T ON T.ID_TABELA = VT.ID_TABELA
GROUP BY
    'UMS_PAES',
    VT.ID_TABELA,
    T.NOME_TABELA
;