WITH MATRICULA AS (
SELECT '157377-2' MATRICULA FROM DUAL UNION ALL
SELECT '170850-3' MATRICULA FROM DUAL UNION ALL
SELECT '226251-7' MATRICULA FROM DUAL UNION ALL
SELECT '315808-0' MATRICULA FROM DUAL UNION ALL
SELECT '228837-X' MATRICULA FROM DUAL UNION ALL
SELECT '088004-3' MATRICULA FROM DUAL UNION ALL
SELECT '002691-3' MATRICULA FROM DUAL UNION ALL
SELECT '298786-4' MATRICULA FROM DUAL UNION ALL
SELECT '092586-1' MATRICULA FROM DUAL UNION ALL
SELECT '092555-1' MATRICULA FROM DUAL UNION ALL
SELECT '303122-5' MATRICULA FROM DUAL UNION ALL
SELECT '213064-5' MATRICULA FROM DUAL UNION ALL
SELECT '298774-X' MATRICULA FROM DUAL UNION ALL
SELECT '298785-6' MATRICULA FROM DUAL UNION ALL
SELECT '091061-9' MATRICULA FROM DUAL UNION ALL
SELECT '091079-1' MATRICULA FROM DUAL UNION ALL
SELECT '086206-1' MATRICULA FROM DUAL UNION ALL
SELECT '092455-5' MATRICULA FROM DUAL UNION ALL
SELECT '170460-5' MATRICULA FROM DUAL UNION ALL
SELECT '280392-5' MATRICULA FROM DUAL UNION ALL
SELECT '298794-5' MATRICULA FROM DUAL UNION ALL
SELECT '092551-9' MATRICULA FROM DUAL UNION ALL
SELECT '091059-7' MATRICULA FROM DUAL UNION ALL
SELECT '115767-1' MATRICULA FROM DUAL UNION ALL
SELECT '086191-0' MATRICULA FROM DUAL UNION ALL
SELECT '213070-0' MATRICULA FROM DUAL UNION ALL
SELECT '002677-8' MATRICULA FROM DUAL UNION ALL
SELECT '091073-2' MATRICULA FROM DUAL UNION ALL
SELECT '003051-1' MATRICULA FROM DUAL UNION ALL
SELECT '303120-9' MATRICULA FROM DUAL UNION ALL
SELECT '092456-3' MATRICULA FROM DUAL UNION ALL
SELECT '091069-4' MATRICULA FROM DUAL UNION ALL
SELECT '298784-8' MATRICULA FROM DUAL UNION ALL
SELECT '197292-8' MATRICULA FROM DUAL UNION ALL
SELECT '213069-6' MATRICULA FROM DUAL UNION ALL
SELECT '091075-9' MATRICULA FROM DUAL UNION ALL
SELECT '170461-3' MATRICULA FROM DUAL UNION ALL
SELECT '002686-7' MATRICULA FROM DUAL UNION ALL
SELECT '315750-4' MATRICULA FROM DUAL UNION ALL
SELECT '307911-2' MATRICULA FROM DUAL UNION ALL
SELECT '092462-8' MATRICULA FROM DUAL UNION ALL
SELECT '226261-4' MATRICULA FROM DUAL UNION ALL
SELECT '002668-9' MATRICULA FROM DUAL UNION ALL
SELECT '213065-3' MATRICULA FROM DUAL UNION ALL
SELECT '298767-8' MATRICULA FROM DUAL UNION ALL
SELECT '091067-8' MATRICULA FROM DUAL UNION ALL
SELECT '002699-9' MATRICULA FROM DUAL UNION ALL
SELECT '091070-8' MATRICULA FROM DUAL UNION ALL
SELECT '088010-8' MATRICULA FROM DUAL UNION ALL
SELECT '315748-2' MATRICULA FROM DUAL UNION ALL
SELECT '112709-8' MATRICULA FROM DUAL UNION ALL
SELECT '298781-3' MATRICULA FROM DUAL UNION ALL
SELECT '092670-1' MATRICULA FROM DUAL UNION ALL
SELECT '092554-3' MATRICULA FROM DUAL UNION ALL
SELECT '280391-7' MATRICULA FROM DUAL UNION ALL
SELECT '170846-5' MATRICULA FROM DUAL UNION ALL
SELECT '213094-7' MATRICULA FROM DUAL UNION ALL
SELECT '315753-9' MATRICULA FROM DUAL UNION ALL
SELECT '112713-6' MATRICULA FROM DUAL UNION ALL
SELECT '092463-6' MATRICULA FROM DUAL UNION ALL
SELECT '092585-3' MATRICULA FROM DUAL UNION ALL
SELECT '086194-4' MATRICULA FROM DUAL UNION ALL
SELECT '002653-X' MATRICULA FROM DUAL UNION ALL
SELECT '088008-6' MATRICULA FROM DUAL UNION ALL
SELECT '086205-3' MATRICULA FROM DUAL UNION ALL
SELECT '092460-1' MATRICULA FROM DUAL UNION ALL
SELECT '315749-X' MATRICULA FROM DUAL UNION ALL
SELECT '091071-6' MATRICULA FROM DUAL UNION ALL
SELECT '170847-3' MATRICULA FROM DUAL UNION ALL
SELECT '315752-X' MATRICULA FROM DUAL UNION ALL
SELECT '086200-2' MATRICULA FROM DUAL UNION ALL
SELECT '091081-3' MATRICULA FROM DUAL UNION ALL
SELECT '091082-1' MATRICULA FROM DUAL UNION ALL
SELECT '091134-8' MATRICULA FROM DUAL UNION ALL
SELECT '091077-5' MATRICULA FROM DUAL UNION ALL
SELECT '112704-7' MATRICULA FROM DUAL UNION ALL
SELECT '002729-4' MATRICULA FROM DUAL UNION ALL
SELECT '213068-8' MATRICULA FROM DUAL UNION ALL
SELECT '092457-1' MATRICULA FROM DUAL UNION ALL
SELECT '002652-2' MATRICULA FROM DUAL UNION ALL
SELECT '002694-8' MATRICULA FROM DUAL UNION ALL
SELECT '307926-X' MATRICULA FROM DUAL UNION ALL
SELECT '170849-0' MATRICULA FROM DUAL UNION ALL
SELECT '088005-1' MATRICULA FROM DUAL UNION ALL
SELECT '170464-8' MATRICULA FROM DUAL UNION ALL
SELECT '091074-X' MATRICULA FROM DUAL UNION ALL
SELECT '315816-X' MATRICULA FROM DUAL UNION ALL
SELECT '088013-2' MATRICULA FROM DUAL UNION ALL
SELECT '088006-0' MATRICULA FROM DUAL UNION ALL
SELECT '303123-3' MATRICULA FROM DUAL UNION ALL
SELECT '088011-6' MATRICULA FROM DUAL UNION ALL
SELECT '129156-4' MATRICULA FROM DUAL UNION ALL
SELECT '298779-1' MATRICULA FROM DUAL UNION ALL
SELECT '170462-1' MATRICULA FROM DUAL UNION ALL
SELECT '091085-6' MATRICULA FROM DUAL UNION ALL
SELECT '213095-5' MATRICULA FROM DUAL UNION ALL
SELECT '213093-9' MATRICULA FROM DUAL UNION ALL
SELECT '298777-5' MATRICULA FROM DUAL UNION ALL
SELECT '092553-5' MATRICULA FROM DUAL UNION ALL
SELECT '088002-7' MATRICULA FROM DUAL UNION ALL
SELECT '115768-0' MATRICULA FROM DUAL UNION ALL
SELECT '092552-7' MATRICULA FROM DUAL UNION ALL
SELECT '298772-4' MATRICULA FROM DUAL UNION ALL
SELECT '298778-3' MATRICULA FROM DUAL UNION ALL
SELECT '091072-4' MATRICULA FROM DUAL UNION ALL
SELECT '002663-8' MATRICULA FROM DUAL UNION ALL
SELECT '298776-7' MATRICULA FROM DUAL UNION ALL
SELECT '092548-9' MATRICULA FROM DUAL UNION ALL
SELECT '170845-7' MATRICULA FROM DUAL UNION ALL
SELECT '002647-6' MATRICULA FROM DUAL UNION ALL
SELECT '086197-9' MATRICULA FROM DUAL UNION ALL
SELECT '115766-3' MATRICULA FROM DUAL UNION ALL
SELECT '298780-5' MATRICULA FROM DUAL UNION ALL
SELECT '298775-9' MATRICULA FROM DUAL UNION ALL
SELECT '002242-0' MATRICULA FROM DUAL UNION ALL
SELECT '086193-6' MATRICULA FROM DUAL UNION ALL
SELECT '002682-4' MATRICULA FROM DUAL UNION ALL
SELECT '088003-5' MATRICULA FROM DUAL UNION ALL
SELECT '213067-0' MATRICULA FROM DUAL UNION ALL
SELECT '088814-1' MATRICULA FROM DUAL UNION ALL
SELECT '226264-9' MATRICULA FROM DUAL UNION ALL
SELECT '091064-3' MATRICULA FROM DUAL UNION ALL
SELECT '315754-7' MATRICULA FROM DUAL UNION ALL
SELECT '115769-8' MATRICULA FROM DUAL UNION ALL
SELECT '091083-0' MATRICULA FROM DUAL UNION ALL
SELECT '086204-5' MATRICULA FROM DUAL UNION ALL
SELECT '091065-1' MATRICULA FROM DUAL UNION ALL
SELECT '002625-5' MATRICULA FROM DUAL UNION ALL
SELECT '091062-7' MATRICULA FROM DUAL UNION ALL
SELECT '112706-3' MATRICULA FROM DUAL UNION ALL
SELECT '002251-9' MATRICULA FROM DUAL UNION ALL
SELECT '298771-6' MATRICULA FROM DUAL UNION ALL
SELECT '197295-2' MATRICULA FROM DUAL UNION ALL
SELECT '315817-9' MATRICULA FROM DUAL UNION ALL
SELECT '213066-1' MATRICULA FROM DUAL UNION ALL
SELECT '170844-9' MATRICULA FROM DUAL UNION ALL
SELECT '172607-2' MATRICULA FROM DUAL UNION ALL
SELECT '170848-1' MATRICULA FROM DUAL UNION ALL
SELECT '232174-2' MATRICULA FROM DUAL UNION ALL
SELECT '086198-7' MATRICULA FROM DUAL UNION ALL
SELECT '086202-9' MATRICULA FROM DUAL UNION ALL
SELECT '092587-0' MATRICULA FROM DUAL UNION ALL
SELECT '091066-0' MATRICULA FROM DUAL UNION ALL
SELECT '226345-9' MATRICULA FROM DUAL UNION ALL
SELECT '298773-2' MATRICULA FROM DUAL UNION ALL
SELECT '197293-6' MATRICULA FROM DUAL UNION ALL
SELECT '194572-6' MATRICULA FROM DUAL UNION ALL
SELECT '196331-7' MATRICULA FROM DUAL UNION ALL
SELECT '266149-7' MATRICULA FROM DUAL UNION ALL
SELECT '299050-4' MATRICULA FROM DUAL UNION ALL
SELECT '270534-6' MATRICULA FROM DUAL UNION ALL
SELECT '269842-X' MATRICULA FROM DUAL UNION ALL
SELECT '253524-6' MATRICULA FROM DUAL UNION ALL
SELECT '285399-0' MATRICULA FROM DUAL UNION ALL
SELECT '282215-6' MATRICULA FROM DUAL UNION ALL
SELECT '245975-2' MATRICULA FROM DUAL UNION ALL
SELECT '257829-8' MATRICULA FROM DUAL UNION ALL
SELECT '269843-9' MATRICULA FROM DUAL UNION ALL
SELECT '257833-6' MATRICULA FROM DUAL UNION ALL
SELECT '130087-3' MATRICULA FROM DUAL UNION ALL
SELECT '299056-3' MATRICULA FROM DUAL UNION ALL
SELECT '299047-4' MATRICULA FROM DUAL 
)
SELECT 
    'SEFAZPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO
FROM
    SW_SEFAZPI.FOLHA FO
    JOIN SW_SEFAZPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEFAZPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN MATRICULA M ON M.MATRICULA = FF.COD_INSTITUCIONAL 
WHERE
    FO.MES = 7
    AND FO.ANO = 2026
    AND R.COD_RUBRICA = 620090
UNION ALL
SELECT 
    'FUESPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO
FROM
    SW_FUESPI.FOLHA FO
    JOIN SW_FUESPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUESPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN MATRICULA M ON M.MATRICULA = FF.COD_INSTITUCIONAL 
WHERE
    FO.MES = 7
    AND FO.ANO = 2026
    AND R.COD_RUBRICA = 620090
UNION ALL
SELECT 
    'FUPIP' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO
FROM
    SW_FUPIP.FOLHA FO
    JOIN SW_FUPIP.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUPIP.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN MATRICULA M ON M.MATRICULA = FF.COD_INSTITUCIONAL 
WHERE
    FO.MES = 7
    AND FO.ANO = 2026
    AND R.COD_RUBRICA = 620090
UNION ALL
SELECT 
    'SEGOV' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEGOV.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN MATRICULA M ON M.MATRICULA = FF.COD_INSTITUCIONAL 
WHERE
    FO.MES = 7
    AND FO.ANO = 2026
    AND R.COD_RUBRICA = 620090
UNION ALL
SELECT 
    'SEADPREVPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO
FROM
    SW_SEADPREVPI.FOLHA FO
    JOIN SW_SEADPREVPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEADPREVPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN MATRICULA M ON M.MATRICULA = FF.COD_INSTITUCIONAL 
WHERE
    FO.MES = 7
    AND FO.ANO = 2026
    AND R.COD_RUBRICA = 620090
UNION ALL
SELECT 
    'SEMAR' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO
FROM
    SW_SEMAR.FOLHA FO
    JOIN SW_SEMAR.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEMAR.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN MATRICULA M ON M.MATRICULA = FF.COD_INSTITUCIONAL 
WHERE
    FO.MES = 7
    AND FO.ANO = 2026
    AND R.COD_RUBRICA = 620090
UNION ALL
SELECT 
    'SESAPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO
FROM
    SW_SESAPI.FOLHA FO
    JOIN SW_SESAPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SESAPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN MATRICULA M ON M.MATRICULA = FF.COD_INSTITUCIONAL 
WHERE
    FO.MES = 7
    AND FO.ANO = 2026
    AND R.COD_RUBRICA = 620090
UNION ALL
SELECT 
    'SSPPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FF.COD_INSTITUCIONAL MATRICULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO
FROM
    SW_SSPPI.FOLHA FO
    JOIN SW_SSPPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SSPPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN MATRICULA M ON M.MATRICULA = FF.COD_INSTITUCIONAL 
WHERE
    FO.MES = 7
    AND FO.ANO = 2026
    AND R.COD_RUBRICA = 620090