SELECT 
    'SW_ADAPI' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_ADAPI.FOLHA FO
    JOIN SW_ADAPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_ADH' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_ADH.FOLHA FO
    JOIN SW_ADH.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_AGESPISA' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_AGESPISA.FOLHA FO
    JOIN SW_AGESPISA.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_AGESPISA02' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_AGESPISA02.FOLHA FO
    JOIN SW_AGESPISA02.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_AGRESP' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_AGRESP.FOLHA FO
    JOIN SW_AGRESP.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_BEP' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_BEP.FOLHA FO
    JOIN SW_BEP.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_CBMPI' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_CBMPI.FOLHA FO
    JOIN SW_CBMPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_CCOM' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_CCOM.FOLHA FO
    JOIN SW_CCOM.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_CDTER' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_CDTER.FOLHA FO
    JOIN SW_CDTER.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_CENDROGAS' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_CENDROGAS.FOLHA FO
    JOIN SW_CENDROGAS.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_COFIR' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_COFIR.FOLHA FO
    JOIN SW_COFIR.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_COJUV' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_COJUV.FOLHA FO
    JOIN SW_COJUV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_DEFCIVIL' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_DEFCIVIL.FOLHA FO
    JOIN SW_DEFCIVIL.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_DER' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_DER.FOLHA FO
    JOIN SW_DER.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_DETRAN' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_DETRAN.FOLHA FO
    JOIN SW_DETRAN.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_EMGERPI' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_EMGERPI.FOLHA FO
    JOIN SW_EMGERPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_EMGERPI_CEASA' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_EMGERPI_CEASA.FOLHA FO
    JOIN SW_EMGERPI_CEASA.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_EMGERPI_CIDAPI' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_EMGERPI_CIDAPI.FOLHA FO
    JOIN SW_EMGERPI_CIDAPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_EMGERPI_CODIPI' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_EMGERPI_CODIPI.FOLHA FO
    JOIN SW_EMGERPI_CODIPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_EMGERPI_COHAB' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_EMGERPI_COHAB.FOLHA FO
    JOIN SW_EMGERPI_COHAB.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_EMGERPI_COMDEPI' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_EMGERPI_COMDEPI.FOLHA FO
    JOIN SW_EMGERPI_COMDEPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_EMGERPI_COMEPI' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_EMGERPI_COMEPI.FOLHA FO
    JOIN SW_EMGERPI_COMEPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_EMGERPI_CORESA' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_EMGERPI_CORESA.FOLHA FO
    JOIN SW_EMGERPI_CORESA.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_EMGERPI_EMATER' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_EMGERPI_EMATER.FOLHA FO
    JOIN SW_EMGERPI_EMATER.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_EMGERPI_ETELPI_FUNART' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_EMGERPI_ETELPI_FUNART.FOLHA FO
    JOIN SW_EMGERPI_ETELPI_FUNART.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_EMGERPI_PIEMTUR' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_EMGERPI_PIEMTUR.FOLHA FO
    JOIN SW_EMGERPI_PIEMTUR.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_EMGERPI_PRODEPI' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_EMGERPI_PRODEPI.FOLHA FO
    JOIN SW_EMGERPI_PRODEPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_FAPEPI' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_FAPEPI.FOLHA FO
    JOIN SW_FAPEPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_FESPPI' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_FESPPI.FOLHA FO
    JOIN SW_FESPPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_FUESPI' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_FUESPI.FOLHA FO
    JOIN SW_FUESPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_FUNPREV' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_FUNPREV.FOLHA FO
    JOIN SW_FUNPREV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_FUPIP' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_FUPIP.FOLHA FO
    JOIN SW_FUPIP.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_GMG' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_GMG.FOLHA FO
    JOIN SW_GMG.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_IASPI' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_IASPI.FOLHA FO
    JOIN SW_IASPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_IDEPI' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_IDEPI.FOLHA FO
    JOIN SW_IDEPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_IMEPI' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_IMEPI.FOLHA FO
    JOIN SW_IMEPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_IMEPIPROD' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_IMEPIPROD.FOLHA FO
    JOIN SW_IMEPIPROD.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_INTERPI' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_INTERPI.FOLHA FO
    JOIN SW_INTERPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_JUCEPI' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_JUCEPI.FOLHA FO
    JOIN SW_JUCEPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_METRO' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_METRO.FOLHA FO
    JOIN SW_METRO.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_PGEPI' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_PGEPI.FOLHA FO
    JOIN SW_PGEPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_PMPI' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_PMPI.FOLHA FO
    JOIN SW_PMPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_SADA' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SADA.FOLHA FO
    JOIN SW_SADA.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_SAF' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SAF.FOLHA FO
    JOIN SW_SAF.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_SASC' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SASC.FOLHA FO
    JOIN SW_SASC.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_SEADPREVPI' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SEADPREVPI.FOLHA FO
    JOIN SW_SEADPREVPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_SEAGRO' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SEAGRO.FOLHA FO
    JOIN SW_SEAGRO.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_SECESP' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SECESP.FOLHA FO
    JOIN SW_SECESP.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_SECID' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SECID.FOLHA FO
    JOIN SW_SECID.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_SECMULHERES' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SECMULHERES.FOLHA FO
    JOIN SW_SECMULHERES.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_SECULT' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SECULT.FOLHA FO
    JOIN SW_SECULT.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_SEDET' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SEDET.FOLHA FO
    JOIN SW_SEDET.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_SEDUC' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SEDUC.FOLHA FO
    JOIN SW_SEDUC.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_SEFAZPI' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SEFAZPI.FOLHA FO
    JOIN SW_SEFAZPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_SEGOV' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_SEID' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SEID.FOLHA FO
    JOIN SW_SEID.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_SEINFRA' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SEINFRA.FOLHA FO
    JOIN SW_SEINFRA.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_SEJUSPI' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SEJUSPI.FOLHA FO
    JOIN SW_SEJUSPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_SEMAR' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SEMAR.FOLHA FO
    JOIN SW_SEMAR.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_SEMINPER' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SEMINPER.FOLHA FO
    JOIN SW_SEMINPER.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_SEPLAN' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SEPLAN.FOLHA FO
    JOIN SW_SEPLAN.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_SERES' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SERES.FOLHA FO
    JOIN SW_SERES.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_SESAPI' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SESAPI.FOLHA FO
    JOIN SW_SESAPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_SETRANS' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SETRANS.FOLHA FO
    JOIN SW_SETRANS.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_SETRE' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SETRE.FOLHA FO
    JOIN SW_SETRE.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_SETUR' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SETUR.FOLHA FO
    JOIN SW_SETUR.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_SIA' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SIA.FOLHA FO
    JOIN SW_SIA.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_SSPPI' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SSPPI.FOLHA FO
    JOIN SW_SSPPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_SURPI' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_SURPI.FOLHA FO
    JOIN SW_SURPI.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_TVANTARES' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_TVANTARES.FOLHA FO
    JOIN SW_TVANTARES.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11

UNION ALL

SELECT 
    'SW_VICEGOV' ORGAO,
    FO.CHAVE_FOLHA,
    VT.ID_TABELA,
    TT.NOME_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2
FROM
    SW_VICEGOV.FOLHA FO
    JOIN SW_VICEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_TAB_TABELA TT ON TT.ID_TABELA = VT.ID_TABELA 
WHERE
    FO.ANO = 2026
    AND FO.MES = 9
    AND VT.ID_TABELA = 11