-- RELAT�RIO GRUPOS MENSAL

WITH TABELA_AUX AS (
	SELECT
		X.ORGAO,
		X.CODIGO_SEFAZ,
		X.ID_FUNCIONARIO,
		X.ID_FOLHA_FUNCIONARIO,
		X.MATRICULA,
		X.CPF,
		X.COD_GRUPO,
		X.DESCRICAO_GRUPO,
		X.TIPO_RELATORIO,
		CASE
            WHEN X.COD_RUBRICA IN (714100, 714110) THEN 'BASE'
            WHEN X.COD_RUBRICA_LEGADO IN ('901') THEN 'FUNDO'
            WHEN X.COD_RUBRICA IN (714400, 714405, 714410, 714420, 714430, 714403) THEN 'PATRONAL'
            WHEN X.COD_RUBRICA IN (999997) THEN 'BRUTO'
        END AS TIPO_RUBRICA,
		X.VALOR_CALCULADO
	FROM
		(
            SELECT
				FF.ID_FOLHA_FUNCIONARIO,
				F.ID_FUNCIONARIO,
				REGEXP_REPLACE(NVL(FF.MATR_DEPENDENTE, PV.COD_INSTITUCIONAL), '[^0-9A-Za-z]', '')    AS MATRICULA,
				PDC.CPF_PESSOA                                              AS CPF,
				E.ORGAO_SIAFI                                               AS ORGAO,
				CS.CODIGO_SEFAZ,
				FR.COD_RUBRICA,
				FR.COD_RUBRICA_LEGADO,
				FFR.VALOR_CALCULADO,
				FO.MES,
				FO.ANO,
				FO.ID_TIPO_FOLHA,
				NVL(GRUP_REL.CODIGO, 'SEM GRUPO')                           AS COD_GRUPO,
				NVL(GRUP_REL.DESCRICAO, 'SEM GRUPO')                        AS DESCRICAO_GRUPO,
				GRUP_REL.TIPO_RELATORIO                                     AS TIPO_RELATORIO
			FROM
				SW_PUBLICO.PESSOA P
				JOIN SW_PUBLICO.PESSOA_DOC_CPF PDC ON PDC.ID_PESSOA = P.ID_PESSOA AND PDC.DATA_BAIXA IS NULL
				JOIN SW_PUBLICO.EMPRESA E ON E.SIGLA = 'FUNPREV'
				JOIN SW_FUNPREV.PESSOA_VINCULO PV ON PV.ID_PESSOA = P.ID_PESSOA
				JOIN SW_FUNPREV.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
				JOIN SW_FUNPREV.FOLHA_FUNC FF ON FF.ID_FUNCIONARIO = F.ID_FUNCIONARIO
				LEFT JOIN SW_FUNPREV.RHB_LOTACAO LOT ON LOT.COD_LOTACAO = FF.COD_LOTACAO
				LEFT JOIN SW_FUNPREV.RHB_LOTACAO_GRUPO LOT_GRUP ON LOT_GRUP.ID_LOTACAO = LOT.ID_LOTACAO
				LEFT JOIN SW_FUNPREV.RHB_LOTA_GRUPO_RELATORIO GRUP_REL ON GRUP_REL.ID_LOTA_GRUPO_RELATORIO = COALESCE(LOT_GRUP.ID_LOTA_GRUPO_RELATORIO,(
					SELECT
						X.ID_LOTA_GRUPO_RELATORIO
					FROM
						SW_FUNPREV.RHB_LOTA_GRUPO_RELATORIO X
					WHERE
						X.CODIGO = E.ORGAO_SIAFI
				))
				JOIN SW_FUNPREV.FOLHA FO ON FO.ID_FOLHA = FF.ID_FOLHA
				JOIN SW_FUNPREV.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
				JOIN SW_PUBLICO.FOLHA_RUBRICA FR ON FR.ID_RUBRICA = FFR.ID_RUBRICA
                LEFT JOIN SW_FUNPREV.FOLHA_CODIGO_SEFAZ CS ON CS.ID_CODIGO_SEFAZ = FO.ID_CODIGO_SEFAZ
			WHERE
				FO.ID_TIPO_FOLHA = 1000000
				AND FO.MES = 7
				AND FO.ANO = 2026
				AND ( FR.COD_RUBRICA IN (714100, 714110)
					OR FR.COD_RUBRICA_LEGADO IN ( '901' )
					OR FR.COD_RUBRICA IN (714400, 714405, 714410, 714420, 714430, 714403)
					OR FR.COD_RUBRICA IN (999997) )
                AND NOT EXISTS (
                    SELECT
                        1
                    FROM
                        SW_FUNPREV.FOLHA_FICHA_FINANCEIRA
                    WHERE  
                        ID_RUBRICA IN (1000347, 1555749)
                        AND ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
                )
        ) X
)
SELECT
	BRUTO.ORGAO                                                                 AS "Codigo empresa",
    CASE
        WHEN
            BASE.IND_CONTRIBUICAO = 'S'
            OR FUNDO.IND_CONTRIBUICAO = 'S'
            OR PATRONAL.IND_CONTRIBUICAO = 'S'
        THEN 'S'
        ELSE 'N'
    END                                                                         AS IND_CONTRIBUICAO,
	BRUTO.CODIGO_SEFAZ,
	COUNT(DISTINCT BRUTO.MATRICULA)                                             AS "Contracheques",
	COUNT(DISTINCT BRUTO.CPF)                                                   AS "CPFs",
	BRUTO.COD_GRUPO                                                             AS "Codigo Grupo",
	BRUTO.DESCRICAO_GRUPO                                                       AS "Grupo",
	CASE BRUTO.TIPO_RELATORIO
		WHEN 'E' THEN 'Executivo'
		ELSE 'Outros Poderes'
	END                                                                         AS "Tipo de Relatorio",
	NVL(SUM(BASE.VALOR_CALCULADO), 0)                                           AS "Valor base",
	NVL(SUM(FUNDO.VALOR_CALCULADO), 0)                                          AS "Valor fundo",
	NVL(SUM(PATRONAL.VALOR_CALCULADO), 0)                                       AS "Valor 28%",
	NVL(SUM(FUNDO.VALOR_CALCULADO), 0) + NVL(SUM(PATRONAL.VALOR_CALCULADO), 0)  AS "Repasse",
	NVL(SUM(BRUTO.VALOR_CALCULADO), 0)                                          AS "Valor Bruto"
FROM
	(
		SELECT
			BRUTO.ORGAO,
			BRUTO.CODIGO_SEFAZ,
			BRUTO.ID_FUNCIONARIO,
			BRUTO.MATRICULA,
			BRUTO.CPF,
			BRUTO.COD_GRUPO,
			BRUTO.DESCRICAO_GRUPO,
			BRUTO.TIPO_RELATORIO,
			SUM(BRUTO.VALOR_CALCULADO) AS VALOR_CALCULADO
		FROM
			TABELA_AUX BRUTO
		WHERE
			BRUTO.TIPO_RUBRICA = 'BRUTO'
		GROUP BY
			BRUTO.ORGAO,
			BRUTO.CODIGO_SEFAZ,
			BRUTO.ID_FUNCIONARIO,
			BRUTO.MATRICULA,
			BRUTO.CPF,
			BRUTO.COD_GRUPO,
			BRUTO.DESCRICAO_GRUPO,
			BRUTO.TIPO_RELATORIO
	) BRUTO
	LEFT JOIN (
		SELECT
			FUNDO.ORGAO,
			FUNDO.CODIGO_SEFAZ,
			FUNDO.ID_FUNCIONARIO,
			FUNDO.MATRICULA,
			FUNDO.CPF,
			FUNDO.COD_GRUPO,
			FUNDO.DESCRICAO_GRUPO,
			FUNDO.TIPO_RELATORIO,
			SUM(FUNDO.VALOR_CALCULADO) AS VALOR_CALCULADO,
            CASE
                WHEN SUM(FUNDO.VALOR_CALCULADO) = 0 THEN 'N'
                ELSE 'S'
            END AS IND_CONTRIBUICAO
		FROM
			TABELA_AUX FUNDO
		WHERE
			FUNDO.TIPO_RUBRICA = 'FUNDO'
		GROUP BY
			FUNDO.ORGAO,
			FUNDO.CODIGO_SEFAZ,
			FUNDO.ID_FUNCIONARIO,
			FUNDO.MATRICULA,
			FUNDO.CPF,
			FUNDO.COD_GRUPO,
			FUNDO.DESCRICAO_GRUPO,
			FUNDO.TIPO_RELATORIO
	) FUNDO ON FUNDO.ORGAO = BRUTO.ORGAO
            AND FUNDO.CODIGO_SEFAZ = BRUTO.CODIGO_SEFAZ
            AND FUNDO.MATRICULA = BRUTO.MATRICULA
            AND FUNDO.CPF = BRUTO.CPF
            AND FUNDO.ID_FUNCIONARIO = BRUTO.ID_FUNCIONARIO
            AND FUNDO.COD_GRUPO = BRUTO.COD_GRUPO
	LEFT JOIN (
		SELECT
			PATRONAL.ORGAO,
			PATRONAL.CODIGO_SEFAZ,
			PATRONAL.ID_FUNCIONARIO,
			PATRONAL.MATRICULA,
			PATRONAL.CPF,
			PATRONAL.COD_GRUPO,
			PATRONAL.DESCRICAO_GRUPO,
			PATRONAL.TIPO_RELATORIO,
			SUM(PATRONAL.VALOR_CALCULADO) AS VALOR_CALCULADO,
            CASE
                WHEN SUM(PATRONAL.VALOR_CALCULADO) = 0 THEN 'N'
                ELSE 'S'
            END AS IND_CONTRIBUICAO
		FROM
			TABELA_AUX PATRONAL
		WHERE
			PATRONAL.TIPO_RUBRICA = 'PATRONAL'
		GROUP BY
			PATRONAL.ORGAO,
			PATRONAL.CODIGO_SEFAZ,
			PATRONAL.ID_FUNCIONARIO,
			PATRONAL.MATRICULA,
			PATRONAL.CPF,
			PATRONAL.COD_GRUPO,
			PATRONAL.DESCRICAO_GRUPO,
			PATRONAL.TIPO_RELATORIO
	) PATRONAL ON PATRONAL.ORGAO = BRUTO.ORGAO
            AND PATRONAL.CODIGO_SEFAZ = BRUTO.CODIGO_SEFAZ
            AND PATRONAL.MATRICULA = BRUTO.MATRICULA
            AND PATRONAL.CPF = BRUTO.CPF
            AND PATRONAL.ID_FUNCIONARIO = BRUTO.ID_FUNCIONARIO
            AND PATRONAL.COD_GRUPO = BRUTO.COD_GRUPO
	LEFT JOIN (
		SELECT
			BASE.ORGAO,
			BASE.CODIGO_SEFAZ,
			BASE.ID_FUNCIONARIO,
			BASE.MATRICULA,
			BASE.CPF,
			BASE.COD_GRUPO,
			BASE.DESCRICAO_GRUPO,
			BASE.TIPO_RELATORIO,
			SUM(BASE.VALOR_CALCULADO) AS VALOR_CALCULADO,
            CASE
                WHEN SUM(BASE.VALOR_CALCULADO) = 0 THEN 'N'
                ELSE 'S'
            END AS IND_CONTRIBUICAO
		FROM
			TABELA_AUX BASE
		WHERE
			BASE.TIPO_RUBRICA = 'BASE'
		GROUP BY
			BASE.ORGAO,
			BASE.CODIGO_SEFAZ,
			BASE.ID_FUNCIONARIO,
			BASE.MATRICULA,
			BASE.CPF,
			BASE.COD_GRUPO,
			BASE.DESCRICAO_GRUPO,
			BASE.TIPO_RELATORIO
	) BASE ON BASE.ORGAO = BRUTO.ORGAO
            AND BASE.CODIGO_SEFAZ = BRUTO.CODIGO_SEFAZ
            AND BASE.MATRICULA = BRUTO.MATRICULA
            AND BASE.CPF = BRUTO.CPF
            AND BASE.ID_FUNCIONARIO = BRUTO.ID_FUNCIONARIO
            AND BASE.COD_GRUPO = BRUTO.COD_GRUPO
GROUP BY
	BRUTO.ORGAO,
	BRUTO.CODIGO_SEFAZ,
	BRUTO.COD_GRUPO,
	BRUTO.DESCRICAO_GRUPO,
	BRUTO.TIPO_RELATORIO,
    BASE.IND_CONTRIBUICAO,
    FUNDO.IND_CONTRIBUICAO,
    PATRONAL.IND_CONTRIBUICAO
ORDER BY
	BRUTO.ORGAO,
	BRUTO.CODIGO_SEFAZ,
	BRUTO.COD_GRUPO,
	BRUTO.DESCRICAO_GRUPO,
	BRUTO.TIPO_RELATORIO;


-- RELAT�RIO GRUPOS NATAL

WITH TABELA_AUX AS (
	SELECT
		X.ORGAO,
		X.CODIGO_SEFAZ,
		X.ID_FUNCIONARIO,
		X.ID_FOLHA_FUNCIONARIO,
		X.MATRICULA,
		X.CPF,
		X.COD_GRUPO,
		X.DESCRICAO_GRUPO,
		X.TIPO_RELATORIO,
		CASE
            WHEN X.COD_RUBRICA IN (714250) THEN 'BASE' 
            WHEN X.COD_RUBRICA_LEGADO IN ('900') THEN 'FUNDO'
            WHEN X.COD_RUBRICA IN (714450, 714455, 714460, 714435, 714440) THEN 'PATRONAL'
            WHEN X.COD_RUBRICA IN (999997) THEN 'BRUTO'
		END AS TIPO_RUBRICA,
		X.VALOR_CALCULADO
	FROM
		(
            SELECT
				FF.ID_FOLHA_FUNCIONARIO,
				F.ID_FUNCIONARIO,
				REGEXP_REPLACE(NVL(FF.MATR_DEPENDENTE, PV.COD_INSTITUCIONAL), '[^0-9A-Za-z]', '')    AS MATRICULA,
				PDC.CPF_PESSOA                                              AS CPF,
				E.ORGAO_SIAFI                                               AS ORGAO,
				CS.CODIGO_SEFAZ,
				FR.COD_RUBRICA,
				FR.COD_RUBRICA_LEGADO,
				FFR.VALOR_CALCULADO,
				FO.MES,
				FO.ANO,
				FO.ID_TIPO_FOLHA,
				NVL(GRUP_REL.CODIGO, 'SEM GRUPO')                           AS COD_GRUPO,
				NVL(GRUP_REL.DESCRICAO, 'SEM GRUPO')                        AS DESCRICAO_GRUPO,
				GRUP_REL.TIPO_RELATORIO                                     AS TIPO_RELATORIO
			FROM
				SW_PUBLICO.PESSOA P
				JOIN SW_PUBLICO.PESSOA_DOC_CPF PDC ON PDC.ID_PESSOA = P.ID_PESSOA AND PDC.DATA_BAIXA IS NULL
				JOIN SW_PUBLICO.EMPRESA E ON E.SIGLA = 'FUNPREV'
				JOIN SW_FUNPREV.PESSOA_VINCULO PV ON PV.ID_PESSOA = P.ID_PESSOA
				JOIN SW_FUNPREV.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
				JOIN SW_FUNPREV.FOLHA_FUNC FF ON FF.ID_FUNCIONARIO = F.ID_FUNCIONARIO
				LEFT JOIN SW_FUNPREV.RHB_LOTACAO LOT ON LOT.COD_LOTACAO = FF.COD_LOTACAO
				LEFT JOIN SW_FUNPREV.RHB_LOTACAO_GRUPO LOT_GRUP ON LOT_GRUP.ID_LOTACAO = LOT.ID_LOTACAO
				LEFT JOIN SW_FUNPREV.RHB_LOTA_GRUPO_RELATORIO GRUP_REL ON GRUP_REL.ID_LOTA_GRUPO_RELATORIO = COALESCE(LOT_GRUP.ID_LOTA_GRUPO_RELATORIO,(
					SELECT
						X.ID_LOTA_GRUPO_RELATORIO
					FROM
						SW_FUNPREV.RHB_LOTA_GRUPO_RELATORIO X
					WHERE
						X.CODIGO = E.ORGAO_SIAFI
				))
				JOIN SW_FUNPREV.FOLHA FO ON FO.ID_FOLHA = FF.ID_FOLHA
				JOIN SW_FUNPREV.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
				JOIN SW_PUBLICO.FOLHA_RUBRICA FR ON FR.ID_RUBRICA = FFR.ID_RUBRICA
				LEFT JOIN SW_FUNPREV.FOLHA_CODIGO_SEFAZ CS ON CS.ID_CODIGO_SEFAZ = FO.ID_CODIGO_SEFAZ
			WHERE
				FO.ID_TIPO_FOLHA = 1000000
				AND FO.MES = 7
				AND FO.ANO = 2026
				AND ( FR.COD_RUBRICA IN (714250)
					OR (FR.COD_RUBRICA_LEGADO IN ('900') AND FR.COD_RUBRICA <> 620050)
					OR FR.COD_RUBRICA IN (714450, 714455, 714460, 714435, 714440)
					OR FR.COD_RUBRICA IN (999997) )
                AND NOT EXISTS (
                    SELECT
                        1
                    FROM
                        SW_FUNPREV.FOLHA_FICHA_FINANCEIRA
                    WHERE  
                        ID_RUBRICA IN (1000347, 1555749)
                        AND ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
                )
        ) X
)
SELECT
	BRUTO.ORGAO                                                                 AS "Codigo empresa",
    CASE
        WHEN
            BASE.IND_CONTRIBUICAO = 'S'
            OR FUNDO.IND_CONTRIBUICAO = 'S'
            OR PATRONAL.IND_CONTRIBUICAO = 'S'
        THEN 'S'
        ELSE 'N'
    END                                                                         AS IND_CONTRIBUICAO,
	BRUTO.CODIGO_SEFAZ,
	COUNT(DISTINCT BRUTO.MATRICULA)                                             AS "Contracheques",
	COUNT(DISTINCT BRUTO.CPF)                                                   AS "CPFs",
	BRUTO.COD_GRUPO                                                             AS "Codigo Grupo",
	BRUTO.DESCRICAO_GRUPO                                                       AS "Grupo",
	CASE BRUTO.TIPO_RELATORIO
		WHEN 'E' THEN 'Executivo'
		ELSE 'Outros Poderes'
	END                                                                         AS "Tipo de Relatorio",
	NVL(SUM(BASE.VALOR_CALCULADO), 0)                                           AS "Valor base",
	NVL(SUM(FUNDO.VALOR_CALCULADO), 0)                                          AS "Valor fundo",
	NVL(SUM(PATRONAL.VALOR_CALCULADO), 0)                                       AS "Valor 28%",
	NVL(SUM(FUNDO.VALOR_CALCULADO), 0) + NVL(SUM(PATRONAL.VALOR_CALCULADO), 0)  AS "Repasse",
	NVL(SUM(BRUTO.VALOR_CALCULADO), 0)                                          AS "Valor Bruto"
FROM
	(
		SELECT
			BRUTO.ORGAO,
			BRUTO.CODIGO_SEFAZ,
			BRUTO.ID_FUNCIONARIO,
			BRUTO.MATRICULA,
			BRUTO.CPF,
			BRUTO.COD_GRUPO,
			BRUTO.DESCRICAO_GRUPO,
			BRUTO.TIPO_RELATORIO,
			SUM(BRUTO.VALOR_CALCULADO) AS VALOR_CALCULADO
		FROM
			TABELA_AUX BRUTO
		WHERE
			BRUTO.TIPO_RUBRICA = 'BRUTO'
		GROUP BY
			BRUTO.ORGAO,
			BRUTO.CODIGO_SEFAZ,
			BRUTO.ID_FUNCIONARIO,
			BRUTO.MATRICULA,
			BRUTO.CPF,
			BRUTO.COD_GRUPO,
			BRUTO.DESCRICAO_GRUPO,
			BRUTO.TIPO_RELATORIO
	) BRUTO
	LEFT JOIN (
		SELECT
			FUNDO.ORGAO,
			FUNDO.CODIGO_SEFAZ,
			FUNDO.ID_FUNCIONARIO,
			FUNDO.MATRICULA,
			FUNDO.CPF,
			FUNDO.COD_GRUPO,
			FUNDO.DESCRICAO_GRUPO,
			FUNDO.TIPO_RELATORIO,
			SUM(FUNDO.VALOR_CALCULADO) AS VALOR_CALCULADO,
            CASE
                WHEN SUM(FUNDO.VALOR_CALCULADO) = 0 THEN 'N'
                ELSE 'S'
            END AS IND_CONTRIBUICAO
		FROM
			TABELA_AUX FUNDO
		WHERE
			FUNDO.TIPO_RUBRICA = 'FUNDO'
		GROUP BY
			FUNDO.ORGAO,
			FUNDO.CODIGO_SEFAZ,
			FUNDO.ID_FUNCIONARIO,
			FUNDO.MATRICULA,
			FUNDO.CPF,
			FUNDO.COD_GRUPO,
			FUNDO.DESCRICAO_GRUPO,
			FUNDO.TIPO_RELATORIO
	) FUNDO ON FUNDO.ORGAO = BRUTO.ORGAO
            AND FUNDO.CODIGO_SEFAZ = BRUTO.CODIGO_SEFAZ
            AND FUNDO.MATRICULA = BRUTO.MATRICULA
            AND FUNDO.CPF = BRUTO.CPF
            AND FUNDO.ID_FUNCIONARIO = BRUTO.ID_FUNCIONARIO
            AND FUNDO.COD_GRUPO = BRUTO.COD_GRUPO
	LEFT JOIN (
		SELECT
			PATRONAL.ORGAO,
			PATRONAL.CODIGO_SEFAZ,
			PATRONAL.ID_FUNCIONARIO,
			PATRONAL.MATRICULA,
			PATRONAL.CPF,
			PATRONAL.COD_GRUPO,
			PATRONAL.DESCRICAO_GRUPO,
			PATRONAL.TIPO_RELATORIO,
			SUM(PATRONAL.VALOR_CALCULADO) AS VALOR_CALCULADO,
            CASE
                WHEN SUM(PATRONAL.VALOR_CALCULADO) = 0 THEN 'N'
                ELSE 'S'
            END AS IND_CONTRIBUICAO
		FROM
			TABELA_AUX PATRONAL
		WHERE
			PATRONAL.TIPO_RUBRICA = 'PATRONAL'
		GROUP BY
			PATRONAL.ORGAO,
			PATRONAL.CODIGO_SEFAZ,
			PATRONAL.ID_FUNCIONARIO,
			PATRONAL.MATRICULA,
			PATRONAL.CPF,
			PATRONAL.COD_GRUPO,
			PATRONAL.DESCRICAO_GRUPO,
			PATRONAL.TIPO_RELATORIO
	) PATRONAL ON PATRONAL.ORGAO = BRUTO.ORGAO
            AND PATRONAL.CODIGO_SEFAZ = BRUTO.CODIGO_SEFAZ
            AND PATRONAL.MATRICULA = BRUTO.MATRICULA
            AND PATRONAL.CPF = BRUTO.CPF
            AND PATRONAL.ID_FUNCIONARIO = BRUTO.ID_FUNCIONARIO
            AND PATRONAL.COD_GRUPO = BRUTO.COD_GRUPO
	LEFT JOIN (
		SELECT
			BASE.ORGAO,
			BASE.CODIGO_SEFAZ,
			BASE.ID_FUNCIONARIO,
			BASE.MATRICULA,
			BASE.CPF,
			BASE.COD_GRUPO,
			BASE.DESCRICAO_GRUPO,
			BASE.TIPO_RELATORIO,
			SUM(BASE.VALOR_CALCULADO) AS VALOR_CALCULADO,
            CASE
                WHEN SUM(BASE.VALOR_CALCULADO) = 0 THEN 'N'
                ELSE 'S'
            END AS IND_CONTRIBUICAO
		FROM
			TABELA_AUX BASE
		WHERE
            BASE.TIPO_RUBRICA = 'BASE'
		GROUP BY
			BASE.ORGAO,
			BASE.CODIGO_SEFAZ,
			BASE.ID_FUNCIONARIO,
			BASE.MATRICULA,
			BASE.CPF,
			BASE.COD_GRUPO,
			BASE.DESCRICAO_GRUPO,
			BASE.TIPO_RELATORIO
	) BASE ON BASE.ORGAO = BRUTO.ORGAO
            AND BASE.CODIGO_SEFAZ = BRUTO.CODIGO_SEFAZ
            AND BASE.MATRICULA = BRUTO.MATRICULA
            AND BASE.CPF = BRUTO.CPF
            AND BASE.ID_FUNCIONARIO = BRUTO.ID_FUNCIONARIO
            AND BASE.COD_GRUPO = BRUTO.COD_GRUPO
GROUP BY
	BRUTO.ORGAO,
	BRUTO.CODIGO_SEFAZ,
	BRUTO.COD_GRUPO,
	BRUTO.DESCRICAO_GRUPO,
	BRUTO.TIPO_RELATORIO,
    BASE.IND_CONTRIBUICAO,
    FUNDO.IND_CONTRIBUICAO,
    PATRONAL.IND_CONTRIBUICAO
ORDER BY
	BRUTO.ORGAO,
	BRUTO.CODIGO_SEFAZ,
	BRUTO.COD_GRUPO,
	BRUTO.DESCRICAO_GRUPO,
	BRUTO.TIPO_RELATORIO;


-- RELAT�RIO LOTA��ES MENSAL

WITH TABELA_AUX AS (
	SELECT
		X.ORGAO,
		X.CODIGO_SEFAZ,
		X.ID_FUNCIONARIO,
		X.ID_FOLHA_FUNCIONARIO,
		X.MATRICULA,
		X.CPF,
		X.COD_LOTACAO,
		X.NOME_LOTACAO,
		CASE
            WHEN X.COD_RUBRICA IN (714100, 714110) THEN 'BASE'
            WHEN X.COD_RUBRICA_LEGADO IN ('901') THEN 'FUNDO'
            WHEN X.COD_RUBRICA IN (714400, 714405, 714410, 714420, 714430, 714403) THEN 'PATRONAL'
            WHEN X.COD_RUBRICA IN (999997) THEN 'BRUTO'
		END AS TIPO_RUBRICA,
		X.VALOR_CALCULADO
	FROM
		(
			SELECT
				FF.ID_FOLHA_FUNCIONARIO,
				F.ID_FUNCIONARIO,
				REGEXP_REPLACE(NVL(FF.MATR_DEPENDENTE, PV.COD_INSTITUCIONAL), '[^0-9A-Za-z]', '')    AS MATRICULA,
				PDC.CPF_PESSOA                                              AS CPF,
				E.ORGAO_SIAFI                                               AS ORGAO,
				CS.CODIGO_SEFAZ,
				FR.COD_RUBRICA,
				FR.COD_RUBRICA_LEGADO,
				FFR.VALOR_CALCULADO,
				FO.MES,
				FO.ANO,
				FO.ID_TIPO_FOLHA,
				FF.COD_LOTACAO,
			    FF.NOME_LOTACAO 
			FROM
				SW_PUBLICO.PESSOA P
				JOIN SW_PUBLICO.PESSOA_DOC_CPF PDC ON PDC.ID_PESSOA = P.ID_PESSOA AND PDC.DATA_BAIXA IS NULL
				JOIN SW_PUBLICO.EMPRESA E ON E.SIGLA = 'FUNPREV'
				JOIN SW_FUNPREV.PESSOA_VINCULO PV ON PV.ID_PESSOA = P.ID_PESSOA
				JOIN SW_FUNPREV.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
				JOIN SW_FUNPREV.FOLHA_FUNC FF ON FF.ID_FUNCIONARIO = F.ID_FUNCIONARIO
				JOIN SW_FUNPREV.FOLHA FO ON FO.ID_FOLHA = FF.ID_FOLHA
				JOIN SW_FUNPREV.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
				JOIN SW_PUBLICO.FOLHA_RUBRICA FR ON FR.ID_RUBRICA = FFR.ID_RUBRICA
                LEFT JOIN SW_FUNPREV.FOLHA_CODIGO_SEFAZ CS ON CS.ID_CODIGO_SEFAZ = FO.ID_CODIGO_SEFAZ
			WHERE
				FO.ID_TIPO_FOLHA = 1000000
				AND FO.MES = 7
				AND FO.ANO = 2026
				AND ( FR.COD_RUBRICA IN (714100, 714110)
					OR FR.COD_RUBRICA_LEGADO IN ( '901' )
					OR FR.COD_RUBRICA IN (714400, 714405, 714410, 714420, 714430, 714403)
					OR FR.COD_RUBRICA IN (999997) )
                AND NOT EXISTS (
                    SELECT
                        1
                    FROM
                        SW_FUNPREV.FOLHA_FICHA_FINANCEIRA
                    WHERE  
                        ID_RUBRICA IN (1000347, 1555749)
                        AND ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
                )
		) X
)
SELECT
	BRUTO.ORGAO                                                                 AS "Codigo empresa",
    CASE
        WHEN
            BASE.IND_CONTRIBUICAO = 'S'
            OR FUNDO.IND_CONTRIBUICAO = 'S'
            OR PATRONAL.IND_CONTRIBUICAO = 'S'
        THEN 'S'
        ELSE 'N'
    END                                                                         AS IND_CONTRIBUICAO,
	BRUTO.CODIGO_SEFAZ,
	COUNT(DISTINCT BRUTO.MATRICULA)                                             AS "Contracheques",
	COUNT(DISTINCT BRUTO.CPF)                                                   AS "CPFs",
	BRUTO.COD_LOTACAO                                                           AS "Codigo Lotacao",
	BRUTO.NOME_LOTACAO                                                          AS "Lotacao",
	NVL(SUM(BASE.VALOR_CALCULADO), 0)                                           AS "Valor base",
	NVL(SUM(FUNDO.VALOR_CALCULADO), 0)                                          AS "Valor fundo",
	NVL(SUM(PATRONAL.VALOR_CALCULADO), 0)                                       AS "Valor 28%",
	NVL(SUM(FUNDO.VALOR_CALCULADO), 0) + NVL(SUM(PATRONAL.VALOR_CALCULADO), 0)  AS "Repasse",
	NVL(SUM(BRUTO.VALOR_CALCULADO), 0)                                          AS "Valor Bruto"
FROM
	(
		SELECT
			BRUTO.ORGAO,
			BRUTO.CODIGO_SEFAZ,
			BRUTO.ID_FUNCIONARIO,
			BRUTO.MATRICULA,
			BRUTO.CPF,
			BRUTO.COD_LOTACAO,
			BRUTO.NOME_LOTACAO,
			SUM(BRUTO.VALOR_CALCULADO) AS VALOR_CALCULADO
		FROM
			TABELA_AUX BRUTO
		WHERE
			BRUTO.TIPO_RUBRICA = 'BRUTO'
		GROUP BY
			BRUTO.ORGAO,
			BRUTO.CODIGO_SEFAZ,
			BRUTO.ID_FUNCIONARIO,
			BRUTO.MATRICULA,
			BRUTO.CPF,
			BRUTO.COD_LOTACAO,
			BRUTO.NOME_LOTACAO
	) BRUTO
	LEFT JOIN (
		SELECT
			FUNDO.ORGAO,
			FUNDO.CODIGO_SEFAZ,
			FUNDO.ID_FUNCIONARIO,
			FUNDO.MATRICULA,
			FUNDO.CPF,
			FUNDO.COD_LOTACAO,
			FUNDO.NOME_LOTACAO,
			SUM(FUNDO.VALOR_CALCULADO) AS VALOR_CALCULADO,
            CASE
                WHEN SUM(FUNDO.VALOR_CALCULADO) = 0 THEN 'N'
                ELSE 'S'
            END AS IND_CONTRIBUICAO
		FROM
			TABELA_AUX FUNDO
		WHERE
			FUNDO.TIPO_RUBRICA = 'FUNDO'
		GROUP BY
			FUNDO.ORGAO,
			FUNDO.CODIGO_SEFAZ,
			FUNDO.ID_FUNCIONARIO,
			FUNDO.MATRICULA,
			FUNDO.CPF,
			FUNDO.COD_LOTACAO,
			FUNDO.NOME_LOTACAO
	) FUNDO ON FUNDO.ORGAO = BRUTO.ORGAO
            AND FUNDO.CODIGO_SEFAZ = BRUTO.CODIGO_SEFAZ
            AND FUNDO.MATRICULA = BRUTO.MATRICULA
            AND FUNDO.CPF = BRUTO.CPF
            AND FUNDO.ID_FUNCIONARIO = BRUTO.ID_FUNCIONARIO
            AND FUNDO.COD_LOTACAO = BRUTO.COD_LOTACAO
            AND FUNDO.NOME_LOTACAO = BRUTO.NOME_LOTACAO
	LEFT JOIN (
		SELECT
			PATRONAL.ORGAO,
			PATRONAL.CODIGO_SEFAZ,
			PATRONAL.ID_FUNCIONARIO,
			PATRONAL.MATRICULA,
			PATRONAL.CPF,
			PATRONAL.COD_LOTACAO,
			PATRONAL.NOME_LOTACAO,
			SUM(PATRONAL.VALOR_CALCULADO) AS VALOR_CALCULADO,
            CASE
                WHEN SUM(PATRONAL.VALOR_CALCULADO) = 0 THEN 'N'
                ELSE 'S'
            END AS IND_CONTRIBUICAO
		FROM
			TABELA_AUX PATRONAL
		WHERE
			PATRONAL.TIPO_RUBRICA = 'PATRONAL'
		GROUP BY
			PATRONAL.ORGAO,
			PATRONAL.CODIGO_SEFAZ,
			PATRONAL.ID_FUNCIONARIO,
			PATRONAL.MATRICULA,
			PATRONAL.CPF,
			PATRONAL.COD_LOTACAO,
			PATRONAL.NOME_LOTACAO
	) PATRONAL ON PATRONAL.ORGAO = BRUTO.ORGAO
            AND PATRONAL.CODIGO_SEFAZ = BRUTO.CODIGO_SEFAZ
            AND PATRONAL.MATRICULA = BRUTO.MATRICULA
            AND PATRONAL.CPF = BRUTO.CPF
            AND PATRONAL.ID_FUNCIONARIO = BRUTO.ID_FUNCIONARIO
            AND PATRONAL.COD_LOTACAO = BRUTO.COD_LOTACAO
            AND PATRONAL.NOME_LOTACAO = BRUTO.NOME_LOTACAO
	LEFT JOIN (
		SELECT
			BASE.ORGAO,
			BASE.CODIGO_SEFAZ,
			BASE.ID_FUNCIONARIO,
			BASE.MATRICULA,
			BASE.CPF,
			BASE.COD_LOTACAO,
			BASE.NOME_LOTACAO,
			SUM(BASE.VALOR_CALCULADO) AS VALOR_CALCULADO,
            CASE
                WHEN SUM(BASE.VALOR_CALCULADO) = 0 THEN 'N'
                ELSE 'S'
            END AS IND_CONTRIBUICAO
		FROM
			TABELA_AUX BASE
		WHERE
			BASE.TIPO_RUBRICA = 'BASE'
		GROUP BY
			BASE.ORGAO,
			BASE.CODIGO_SEFAZ,
			BASE.ID_FUNCIONARIO,
			BASE.MATRICULA,
			BASE.CPF,
			BASE.COD_LOTACAO,
			BASE.NOME_LOTACAO
	) BASE ON BASE.ORGAO = BRUTO.ORGAO
            AND BASE.CODIGO_SEFAZ = BRUTO.CODIGO_SEFAZ
            AND BASE.MATRICULA = BRUTO.MATRICULA
            AND BASE.CPF = BRUTO.CPF
            AND BASE.ID_FUNCIONARIO = BRUTO.ID_FUNCIONARIO
            AND BASE.COD_LOTACAO = BRUTO.COD_LOTACAO
            AND BASE.NOME_LOTACAO = BRUTO.NOME_LOTACAO
GROUP BY
	BRUTO.ORGAO,
	BRUTO.CODIGO_SEFAZ,
	BRUTO.COD_LOTACAO,
	BRUTO.NOME_LOTACAO,
    BASE.IND_CONTRIBUICAO,
    FUNDO.IND_CONTRIBUICAO,
    PATRONAL.IND_CONTRIBUICAO
ORDER BY
	BRUTO.ORGAO,
	BRUTO.CODIGO_SEFAZ,
	BRUTO.COD_LOTACAO,
	BRUTO.NOME_LOTACAO;


-- RELAT�RIO LOTA��ES NATAL

WITH TABELA_AUX AS (
	SELECT
		X.ORGAO,
		X.CODIGO_SEFAZ,
		X.ID_FUNCIONARIO,
		X.ID_FOLHA_FUNCIONARIO,
		X.MATRICULA,
		X.CPF,
		X.COD_LOTACAO,
		X.NOME_LOTACAO,
		CASE
            WHEN X.COD_RUBRICA IN (714250) THEN 'BASE' 
            WHEN X.COD_RUBRICA_LEGADO IN ('900') THEN 'FUNDO'
            WHEN X.COD_RUBRICA IN (714450, 714455, 714460, 714435, 714440) THEN 'PATRONAL'
            WHEN X.COD_RUBRICA IN (999997) THEN 'BRUTO'
		END AS TIPO_RUBRICA,
		X.VALOR_CALCULADO
	FROM
		(
			SELECT
                FF.ID_FOLHA_FUNCIONARIO,
                F.ID_FUNCIONARIO,
                REGEXP_REPLACE(NVL(FF.MATR_DEPENDENTE, PV.COD_INSTITUCIONAL), '[^0-9A-Za-z]', '')   AS MATRICULA,
                PDC.CPF_PESSOA                                                                      AS CPF,
                E.ORGAO_SIAFI                                                                       AS ORGAO,
                CS.CODIGO_SEFAZ,
                FR.COD_RUBRICA,
                FR.COD_RUBRICA_LEGADO,
                FFR.VALOR_CALCULADO,
                FO.MES,
                FO.ANO,
                FO.ID_TIPO_FOLHA,
                FF.COD_LOTACAO,
                FF.NOME_LOTACAO 
			FROM
                SW_PUBLICO.PESSOA P
                JOIN SW_PUBLICO.PESSOA_DOC_CPF PDC ON PDC.ID_PESSOA = P.ID_PESSOA AND PDC.DATA_BAIXA IS NULL
                JOIN SW_PUBLICO.EMPRESA E ON E.SIGLA = 'FUNPREV'
                JOIN SW_FUNPREV.PESSOA_VINCULO PV ON PV.ID_PESSOA = P.ID_PESSOA
                JOIN SW_FUNPREV.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
                JOIN SW_FUNPREV.FOLHA_FUNC FF ON FF.ID_FUNCIONARIO = F.ID_FUNCIONARIO
                JOIN SW_FUNPREV.FOLHA FO ON FO.ID_FOLHA = FF.ID_FOLHA
                JOIN SW_FUNPREV.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
                JOIN SW_PUBLICO.FOLHA_RUBRICA FR ON FR.ID_RUBRICA = FFR.ID_RUBRICA
                LEFT JOIN SW_FUNPREV.FOLHA_CODIGO_SEFAZ CS ON CS.ID_CODIGO_SEFAZ = FO.ID_CODIGO_SEFAZ
			WHERE
                FO.ID_TIPO_FOLHA = 1000000
                AND FO.MES = 7
                AND FO.ANO = 2026
                AND ( FR.COD_RUBRICA IN (714250)
                    OR (FR.COD_RUBRICA_LEGADO IN ('900') AND FR.COD_RUBRICA <> 620050)
                    OR FR.COD_RUBRICA IN (714450, 714455, 714460, 714435, 714440)
                    OR FR.COD_RUBRICA IN (999997) )
                AND NOT EXISTS (
                    SELECT
                        1
                    FROM
                        SW_FUNPREV.FOLHA_FICHA_FINANCEIRA
                    WHERE  
                        ID_RUBRICA IN (1000347, 1555749)
                        AND ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
                )
		) X
)
SELECT
	BRUTO.ORGAO                                                                 AS "Codigo empresa",
    CASE
        WHEN
            BASE.IND_CONTRIBUICAO = 'S'
            OR FUNDO.IND_CONTRIBUICAO = 'S'
            OR PATRONAL.IND_CONTRIBUICAO = 'S'
        THEN 'S'
        ELSE 'N'
    END                                                                         AS IND_CONTRIBUICAO,
	BRUTO.CODIGO_SEFAZ,
	COUNT(DISTINCT BRUTO.MATRICULA)                                             AS "Contracheques",
	COUNT(DISTINCT BRUTO.CPF)                                                   AS "CPFs",
	BRUTO.COD_LOTACAO                                                           AS "Codigo Lotacao",
	BRUTO.NOME_LOTACAO                                                          AS "Lotacao",
	NVL(SUM(BASE.VALOR_CALCULADO), 0)                                           AS "Valor base",
	NVL(SUM(FUNDO.VALOR_CALCULADO), 0)                                          AS "Valor fundo",
	NVL(SUM(PATRONAL.VALOR_CALCULADO), 0)                                       AS "Valor 28%",
	NVL(SUM(FUNDO.VALOR_CALCULADO), 0) + NVL(SUM(PATRONAL.VALOR_CALCULADO), 0)  AS "Repasse",
	NVL(SUM(BRUTO.VALOR_CALCULADO), 0)                                          AS "Valor Bruto"
FROM
	(
		SELECT
			BRUTO.ORGAO,
			BRUTO.CODIGO_SEFAZ,
			BRUTO.ID_FUNCIONARIO,
			BRUTO.MATRICULA,
			BRUTO.CPF,
			BRUTO.COD_LOTACAO,
			BRUTO.NOME_LOTACAO,
			SUM(BRUTO.VALOR_CALCULADO) AS VALOR_CALCULADO
		FROM
			TABELA_AUX BRUTO
		WHERE
			BRUTO.TIPO_RUBRICA = 'BRUTO'
		GROUP BY
			BRUTO.ORGAO,
			BRUTO.CODIGO_SEFAZ,
			BRUTO.ID_FUNCIONARIO,
			BRUTO.MATRICULA,
			BRUTO.CPF,
			BRUTO.COD_LOTACAO,
			BRUTO.NOME_LOTACAO
	) BRUTO
	LEFT JOIN (
		SELECT
			FUNDO.ORGAO,
			FUNDO.CODIGO_SEFAZ,
			FUNDO.ID_FUNCIONARIO,
			FUNDO.MATRICULA,
			FUNDO.CPF,
			FUNDO.COD_LOTACAO,
			FUNDO.NOME_LOTACAO,
			SUM(FUNDO.VALOR_CALCULADO) AS VALOR_CALCULADO,
            CASE
                WHEN SUM(FUNDO.VALOR_CALCULADO) = 0 THEN 'N'
                ELSE 'S'
            END AS IND_CONTRIBUICAO
		FROM
			TABELA_AUX FUNDO
		WHERE
			FUNDO.TIPO_RUBRICA = 'FUNDO'
		GROUP BY
			FUNDO.ORGAO,
			FUNDO.CODIGO_SEFAZ,
			FUNDO.ID_FUNCIONARIO,
			FUNDO.MATRICULA,
			FUNDO.CPF,
			FUNDO.COD_LOTACAO,
			FUNDO.NOME_LOTACAO
	) FUNDO ON FUNDO.ORGAO = BRUTO.ORGAO
            AND FUNDO.CODIGO_SEFAZ = BRUTO.CODIGO_SEFAZ
            AND FUNDO.MATRICULA = BRUTO.MATRICULA
            AND FUNDO.CPF = BRUTO.CPF
            AND FUNDO.ID_FUNCIONARIO = BRUTO.ID_FUNCIONARIO
            AND FUNDO.COD_LOTACAO = BRUTO.COD_LOTACAO
            AND FUNDO.NOME_LOTACAO = BRUTO.NOME_LOTACAO
	LEFT JOIN (
		SELECT
			PATRONAL.ORGAO,
			PATRONAL.CODIGO_SEFAZ,
			PATRONAL.ID_FUNCIONARIO,
			PATRONAL.MATRICULA,
			PATRONAL.CPF,
			PATRONAL.COD_LOTACAO,
			PATRONAL.NOME_LOTACAO,
			SUM(PATRONAL.VALOR_CALCULADO) AS VALOR_CALCULADO,
            CASE
                WHEN SUM(PATRONAL.VALOR_CALCULADO) = 0 THEN 'N'
                ELSE 'S'
            END AS IND_CONTRIBUICAO
		FROM
			TABELA_AUX PATRONAL
		WHERE
			PATRONAL.TIPO_RUBRICA = 'PATRONAL'
		GROUP BY
			PATRONAL.ORGAO,
			PATRONAL.CODIGO_SEFAZ,
			PATRONAL.ID_FUNCIONARIO,
			PATRONAL.MATRICULA,
			PATRONAL.CPF,
			PATRONAL.COD_LOTACAO,
			PATRONAL.NOME_LOTACAO
	) PATRONAL ON PATRONAL.ORGAO = BRUTO.ORGAO
            AND PATRONAL.CODIGO_SEFAZ = BRUTO.CODIGO_SEFAZ
            AND PATRONAL.MATRICULA = BRUTO.MATRICULA
            AND PATRONAL.CPF = BRUTO.CPF
            AND PATRONAL.ID_FUNCIONARIO = BRUTO.ID_FUNCIONARIO
            AND PATRONAL.COD_LOTACAO = BRUTO.COD_LOTACAO
            AND PATRONAL.NOME_LOTACAO = BRUTO.NOME_LOTACAO
	LEFT JOIN (
		SELECT
			BASE.ORGAO,
			BASE.CODIGO_SEFAZ,
			BASE.ID_FUNCIONARIO,
			BASE.MATRICULA,
			BASE.CPF,
			BASE.COD_LOTACAO,
			BASE.NOME_LOTACAO,
			SUM(BASE.VALOR_CALCULADO) AS VALOR_CALCULADO,
            CASE
                WHEN SUM(BASE.VALOR_CALCULADO) = 0 THEN 'N'
                ELSE 'S'
            END AS IND_CONTRIBUICAO
		FROM
			TABELA_AUX BASE
		WHERE
			BASE.TIPO_RUBRICA = 'BASE'
		GROUP BY
			BASE.ORGAO,
			BASE.CODIGO_SEFAZ,
			BASE.ID_FUNCIONARIO,
			BASE.MATRICULA,
			BASE.CPF,
			BASE.COD_LOTACAO,
			BASE.NOME_LOTACAO
	) BASE ON BASE.ORGAO = BRUTO.ORGAO
            AND BASE.CODIGO_SEFAZ = BRUTO.CODIGO_SEFAZ
            AND BASE.MATRICULA = BRUTO.MATRICULA
            AND BASE.CPF = BRUTO.CPF
            AND BASE.ID_FUNCIONARIO = BRUTO.ID_FUNCIONARIO
            AND BASE.COD_LOTACAO = BRUTO.COD_LOTACAO
            AND BASE.NOME_LOTACAO = BRUTO.NOME_LOTACAO
GROUP BY
	BRUTO.ORGAO,
	BRUTO.CODIGO_SEFAZ,
	BRUTO.COD_LOTACAO,
	BRUTO.NOME_LOTACAO,
    BASE.IND_CONTRIBUICAO,
    FUNDO.IND_CONTRIBUICAO,
    PATRONAL.IND_CONTRIBUICAO
ORDER BY
	BRUTO.ORGAO,
	BRUTO.CODIGO_SEFAZ,
	BRUTO.COD_LOTACAO,
	BRUTO.NOME_LOTACAO;


-- RELATORIO POR FAIXA MENSAL
WITH TABELA_AUX AS (
    SELECT
        X.ORGAO,
        X.ID_FUNCIONARIO,
        X.MATRICULA,
        X.CPF,
        X.CODIGO_SEFAZ,
        X.DESCRICAO_SEFAZ,
        X.TIPO_BENEFICIO,
        CASE
            WHEN X.COD_RUBRICA IN (714100, 714110) THEN 'BASE'
            WHEN X.COD_RUBRICA_LEGADO IN ('901') THEN 'FUNDO'
            WHEN X.COD_RUBRICA IN (714400, 714405, 714410, 714420, 714430, 714403) THEN  'PATRONAL'
            WHEN X.COD_RUBRICA IN (999997) THEN 'BRUTO'
        END TIPO_RUBRICA,
        X.VALOR_CALCULADO
    FROM
        (
        SELECT
            NVL(FC.ID_FUNCIONARIO, PC.ID_FUNCIONARIO) ID_FUNCIONARIO,
            REGEXP_REPLACE(FC.COD_INSTITUCIONAL, '[^0-9A-Za-z]', '') MATRICULA,
            PDC.CPF_PESSOA CPF,
            E.ORGAO_SIAFI ORGAO,
            R.COD_RUBRICA,
            R.COD_RUBRICA_LEGADO,
            FF.VALOR_CALCULADO,
            CS.CODIGO_SEFAZ,
            CS.DESCRICAO_SEFAZ,
            CASE FO.TIPO_FOLHA_SEFAZ
                WHEN 'C1' THEN 'Padrão'
                WHEN 'C2' THEN 'Reintegrados'
                WHEN 'C3' THEN 'Temporário'
                WHEN 'C4' THEN 'Prestador'
                WHEN 'C5' THEN 'Bolsistas'
                WHEN 'C6' THEN 'Inativos'
                WHEN 'C7' THEN 'Pensionistas'
                WHEN 'C8' THEN 'RGPS'
                WHEN 'C9' THEN 'RPPS'
            END TIPO_BENEFICIO
        FROM
            SW_FUNPREV.FOLHA FO
            JOIN SW_FUNPREV.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
            JOIN SW_FUNPREV.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
            JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
            JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FC.ID_PESSOA
            JOIN SW_PUBLICO.PESSOA_DOC_CPF PDC ON PDC.ID_PESSOA = P.ID_PESSOA AND PDC.DATA_BAIXA IS NULL
            JOIN SW_PUBLICO.EMPRESA E ON E.SIGLA = 'FUNPREV'
            LEFT JOIN SW_FUNPREV.FOLHA_CODIGO_SEFAZ CS ON CS.ID_CODIGO_SEFAZ = FO.ID_CODIGO_SEFAZ
            LEFT JOIN SW_FUNPREV.FUNC_PENSAO_CIVIL PC ON PC.ID_PENSIONISTA = FC.ID_PENSIONISTA
            JOIN SW_FUNPREV.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = NVL(FC.ID_FUNCIONARIO, PC.ID_FUNCIONARIO)
        WHERE
            FO.ID_TIPO_FOLHA = 1000000
            AND FO.MES = 7
            AND FO.ANO = 2026
            AND FI.ID_REGIME NOT IN (1000003, 9)
            AND (
                R.COD_RUBRICA IN (714100, 714110)
                OR R.COD_RUBRICA_LEGADO IN ('901')
                OR R.COD_RUBRICA IN (714400, 714405, 714410, 714420, 714430, 714403)
                OR R.COD_RUBRICA IN (999997)
            )
            AND NOT EXISTS (
                SELECT
                    1
                FROM
                    SW_FUNPREV.FOLHA_FICHA_FINANCEIRA
                WHERE  
                    ID_RUBRICA IN (1000347, 1555749)
                    AND ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
            )
        ) X
)
SELECT
    BRUTO.ORGAO "CODIGO EMPRESA",
    COUNT(BRUTO.MATRICULA) CONTRACHEQUES,
    SUM(CASE
        WHEN NVL(BASE.VALOR_CALCULADO, 0) > FAIXA.VALOR_FINAL THEN 0
        ELSE 1
    END) CONTRACHEQUES_FAIXA,
    BRUTO.CODIGO_SEFAZ,
    BRUTO.DESCRICAO_SEFAZ,
    BRUTO.TIPO_BENEFICIO,
    FAIXA.FAIXA,
    SUM(CASE
        WHEN NVL(BASE.VALOR_CALCULADO, 0) > FAIXA.VALOR_FINAL THEN FAIXA.VALOR_FINAL - FAIXA.VALOR_1
        ELSE NVL(BASE.VALOR_CALCULADO, 0) - FAIXA.VALOR_1
    END) "VALOR BASE FAIXA",
    SUM(CASE
        WHEN FAIXA.FAIXA = 1 THEN 0
        WHEN NVL(BASE.VALOR_CALCULADO, 0) > FAIXA.VALOR_FINAL THEN FAIXA.VALOR_FINAL - FAIXA.VALOR_1
        ELSE NVL(BASE.VALOR_CALCULADO, 0) - FAIXA.VALOR_1
    END) * 28/100 "VALOR PATRONAL",
    SUM(CASE
        WHEN NVL(BASE.VALOR_CALCULADO, 0) > FAIXA.VALOR_FINAL THEN FAIXA.VALOR_FINAL - FAIXA.VALOR_1
        ELSE NVL(BASE.VALOR_CALCULADO, 0) - FAIXA.VALOR_1
    END) * (FAIXA.PERCENTUAL / 100) "VALOR FUNDO",
    (SUM(CASE
        WHEN FAIXA.FAIXA = 1 THEN 0
        WHEN NVL(BASE.VALOR_CALCULADO, 0) > FAIXA.VALOR_FINAL THEN FAIXA.VALOR_FINAL - FAIXA.VALOR_1
        ELSE NVL(BASE.VALOR_CALCULADO, 0) - FAIXA.VALOR_1
    END) * 28/100) + (SUM(CASE
        WHEN NVL(BASE.VALOR_CALCULADO, 0) > FAIXA.VALOR_FINAL THEN FAIXA.VALOR_FINAL - FAIXA.VALOR_1
        ELSE NVL(BASE.VALOR_CALCULADO, 0) - FAIXA.VALOR_1
    END) * (FAIXA.PERCENTUAL / 100)) "REPASSE",
    CASE
        WHEN FAIXA.FAIXA = 1 THEN NVL(SUM(BRUTO.VALOR_CALCULADO), 0)
    END "VALOR BRUTO"
FROM
    (
    SELECT
        BRUTO.ORGAO,
        BRUTO.ID_FUNCIONARIO,
        BRUTO.MATRICULA,
        BRUTO.CPF,
        BRUTO.CODIGO_SEFAZ,
        BRUTO.DESCRICAO_SEFAZ,
        BRUTO.TIPO_BENEFICIO,
        SUM(BRUTO.VALOR_CALCULADO) VALOR_CALCULADO
    FROM
        TABELA_AUX BRUTO
    WHERE
        BRUTO.TIPO_RUBRICA = 'BRUTO'
    GROUP BY
        BRUTO.ORGAO,
        BRUTO.ID_FUNCIONARIO,
        BRUTO.MATRICULA,
        BRUTO.CPF,
        BRUTO.CODIGO_SEFAZ,
        BRUTO.DESCRICAO_SEFAZ,
        BRUTO.TIPO_BENEFICIO
    ) BRUTO
    JOIN (
        SELECT
            BASE.ORGAO,
            BASE.ID_FUNCIONARIO,
            BASE.MATRICULA,
            BASE.CPF,
            BASE.CODIGO_SEFAZ,
            BASE.DESCRICAO_SEFAZ,
            BASE.TIPO_BENEFICIO,
            SUM(BASE.VALOR_CALCULADO) VALOR_CALCULADO
        FROM
            TABELA_AUX BASE
        WHERE
            BASE.TIPO_RUBRICA = 'BASE'
        GROUP BY
            BASE.ORGAO,
            BASE.ID_FUNCIONARIO,
            BASE.MATRICULA,
            BASE.CPF,
            BASE.CODIGO_SEFAZ,
            BASE.DESCRICAO_SEFAZ,
            BASE.TIPO_BENEFICIO
    ) BASE ON BASE.ORGAO = BRUTO.ORGAO
            AND BASE.CODIGO_SEFAZ = BRUTO.CODIGO_SEFAZ
            AND BASE.MATRICULA = BRUTO.MATRICULA
            AND BASE.CPF = BRUTO.CPF
            AND BASE.ID_FUNCIONARIO = BRUTO.ID_FUNCIONARIO
            AND BASE.TIPO_BENEFICIO = BRUTO.TIPO_BENEFICIO
    JOIN (
        SELECT
            VT.FAIXA,
            VT.VALOR_INICIAL,
            VT.VALOR_FINAL,
            VT.VALOR_1,
            VT.PERCENTUAL
        FROM
            SW_FUNPREV.FOLHA FO
            JOIN SW_FUNPREV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA AND VT.ID_TABELA = 1000280
        WHERE
            SUBSTR(FO.CHAVE_FOLHA, 9) = 300 AND FO.MES = 7 AND FO.ANO = 2026 AND FO.ID_TIPO_FOLHA = 1000000
    ) FAIXA ON FAIXA.VALOR_1 < BASE.VALOR_CALCULADO
GROUP BY
    BRUTO.ORGAO,
    BRUTO.CODIGO_SEFAZ,
    BRUTO.DESCRICAO_SEFAZ,
    BRUTO.TIPO_BENEFICIO,
    FAIXA.FAIXA,
    FAIXA.PERCENTUAL
ORDER BY
    BRUTO.ORGAO,
    BRUTO.CODIGO_SEFAZ,
    FAIXA.FAIXA;

-- RELATORIO POR FAIXA NATAL
WITH TABELA_AUX AS (
    SELECT
        X.ORGAO,
        X.ID_FUNCIONARIO,
        X.MATRICULA,
        X.CPF,
        X.CODIGO_SEFAZ,
        X.DESCRICAO_SEFAZ,
        X.TIPO_BENEFICIO,
        CASE
            WHEN X.COD_RUBRICA IN (714250) THEN 'BASE'
            WHEN X.COD_RUBRICA_LEGADO IN ('900') THEN 'FUNDO'
            WHEN X.COD_RUBRICA IN (714450, 714455, 714460, 714435, 714440, 714436) THEN  'PATRONAL'
            WHEN X.COD_RUBRICA IN (999997) THEN 'BRUTO'
        END TIPO_RUBRICA,
        X.VALOR_CALCULADO
    FROM
        (
        SELECT
            NVL(FC.ID_FUNCIONARIO, PC.ID_FUNCIONARIO) ID_FUNCIONARIO,
            REGEXP_REPLACE(FC.COD_INSTITUCIONAL, '[^0-9A-Za-z]', '') MATRICULA,
            PDC.CPF_PESSOA CPF,
            E.ORGAO_SIAFI ORGAO,
            R.COD_RUBRICA,
            R.COD_RUBRICA_LEGADO,
            FF.VALOR_CALCULADO,
            CS.CODIGO_SEFAZ,
            CS.DESCRICAO_SEFAZ,
            CASE FO.TIPO_FOLHA_SEFAZ
                WHEN 'C1' THEN 'Padrão'
                WHEN 'C2' THEN 'Reintegrados'
                WHEN 'C3' THEN 'Temporário'
                WHEN 'C4' THEN 'Prestador'
                WHEN 'C5' THEN 'Bolsistas'
                WHEN 'C6' THEN 'Inativos'
                WHEN 'C7' THEN 'Pensionistas'
                WHEN 'C8' THEN 'RGPS'
                WHEN 'C9' THEN 'RPPS'
            END TIPO_BENEFICIO
        FROM
            SW_FUNPREV.FOLHA FO
            JOIN SW_FUNPREV.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
            JOIN SW_FUNPREV.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
            JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
            JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FC.ID_PESSOA
            JOIN SW_PUBLICO.PESSOA_DOC_CPF PDC ON PDC.ID_PESSOA = P.ID_PESSOA AND PDC.DATA_BAIXA IS NULL
            JOIN SW_PUBLICO.EMPRESA E ON E.SIGLA = 'FUNPREV'
            LEFT JOIN SW_FUNPREV.FOLHA_CODIGO_SEFAZ CS ON CS.ID_CODIGO_SEFAZ = FO.ID_CODIGO_SEFAZ
            LEFT JOIN SW_FUNPREV.FUNC_PENSAO_CIVIL PC ON PC.ID_PENSIONISTA = FC.ID_PENSIONISTA
            JOIN SW_FUNPREV.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = NVL(FC.ID_FUNCIONARIO, PC.ID_FUNCIONARIO)
        WHERE
            FO.ID_TIPO_FOLHA = 1000000
            AND FO.MES = 7
            AND FO.ANO = 2026
            AND FI.ID_REGIME NOT IN (1000003, 9)
            AND (
                R.COD_RUBRICA IN (714250)
                OR R.COD_RUBRICA_LEGADO IN ('900')
                OR R.COD_RUBRICA IN (714450, 714455, 714460, 714435, 714440, 714436)
                OR R.COD_RUBRICA IN (999997)
            )
            AND NOT EXISTS (
                SELECT
                    1
                FROM
                    SW_FUNPREV.FOLHA_FICHA_FINANCEIRA
                WHERE  
                    ID_RUBRICA IN (1000347, 1555749)
                    AND ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
            )
        ) X
)
SELECT
    BRUTO.ORGAO "CODIGO EMPRESA",
    COUNT(BRUTO.MATRICULA) CONTRACHEQUES,
    SUM(CASE
        WHEN NVL(BASE.VALOR_CALCULADO, 0) > FAIXA.VALOR_FINAL THEN 0
        ELSE 1
    END) CONTRACHEQUES_FAIXA,
    BRUTO.CODIGO_SEFAZ,
    BRUTO.DESCRICAO_SEFAZ,
    BRUTO.TIPO_BENEFICIO,
    FAIXA.FAIXA,
    SUM(CASE
        WHEN NVL(BASE.VALOR_CALCULADO, 0) > FAIXA.VALOR_FINAL THEN FAIXA.VALOR_FINAL - FAIXA.VALOR_1
        ELSE NVL(BASE.VALOR_CALCULADO, 0) - FAIXA.VALOR_1
    END) "VALOR BASE FAIXA",
    SUM(CASE
        WHEN FAIXA.FAIXA = 1 THEN 0
        WHEN NVL(BASE.VALOR_CALCULADO, 0) > FAIXA.VALOR_FINAL THEN FAIXA.VALOR_FINAL - FAIXA.VALOR_1
        ELSE NVL(BASE.VALOR_CALCULADO, 0) - FAIXA.VALOR_1
    END) * 28/100 "VALOR PATRONAL",
    SUM(CASE
        WHEN NVL(BASE.VALOR_CALCULADO, 0) > FAIXA.VALOR_FINAL THEN FAIXA.VALOR_FINAL - FAIXA.VALOR_1
        ELSE NVL(BASE.VALOR_CALCULADO, 0) - FAIXA.VALOR_1
    END) * (FAIXA.PERCENTUAL / 100) "VALOR FUNDO",
    (SUM(CASE
        WHEN FAIXA.FAIXA = 1 THEN 0
        WHEN NVL(BASE.VALOR_CALCULADO, 0) > FAIXA.VALOR_FINAL THEN FAIXA.VALOR_FINAL - FAIXA.VALOR_1
        ELSE NVL(BASE.VALOR_CALCULADO, 0) - FAIXA.VALOR_1
    END) * 28/100) + (SUM(CASE
        WHEN NVL(BASE.VALOR_CALCULADO, 0) > FAIXA.VALOR_FINAL THEN FAIXA.VALOR_FINAL - FAIXA.VALOR_1
        ELSE NVL(BASE.VALOR_CALCULADO, 0) - FAIXA.VALOR_1
    END) * (FAIXA.PERCENTUAL / 100)) "REPASSE",
    CASE
        WHEN FAIXA.FAIXA = 1 THEN NVL(SUM(BRUTO.VALOR_CALCULADO), 0)
    END "VALOR BRUTO"
FROM
    (
    SELECT
        BRUTO.ORGAO,
        BRUTO.ID_FUNCIONARIO,
        BRUTO.MATRICULA,
        BRUTO.CPF,
        BRUTO.CODIGO_SEFAZ,
        BRUTO.DESCRICAO_SEFAZ,
        BRUTO.TIPO_BENEFICIO,
        SUM(BRUTO.VALOR_CALCULADO) VALOR_CALCULADO
    FROM
        TABELA_AUX BRUTO
    WHERE
        BRUTO.TIPO_RUBRICA = 'BRUTO'
    GROUP BY
        BRUTO.ORGAO,
        BRUTO.ID_FUNCIONARIO,
        BRUTO.MATRICULA,
        BRUTO.CPF,
        BRUTO.CODIGO_SEFAZ,
        BRUTO.DESCRICAO_SEFAZ,
        BRUTO.TIPO_BENEFICIO
    ) BRUTO
    JOIN (
        SELECT
            BASE.ORGAO,
            BASE.ID_FUNCIONARIO,
            BASE.MATRICULA,
            BASE.CPF,
            BASE.CODIGO_SEFAZ,
            BASE.DESCRICAO_SEFAZ,
            BASE.TIPO_BENEFICIO,
            SUM(BASE.VALOR_CALCULADO) VALOR_CALCULADO
        FROM
            TABELA_AUX BASE
        WHERE
            BASE.TIPO_RUBRICA = 'BASE'
        GROUP BY
            BASE.ORGAO,
            BASE.ID_FUNCIONARIO,
            BASE.MATRICULA,
            BASE.CPF,
            BASE.CODIGO_SEFAZ,
            BASE.DESCRICAO_SEFAZ,
            BASE.TIPO_BENEFICIO
    ) BASE ON BASE.ORGAO = BRUTO.ORGAO
            AND BASE.CODIGO_SEFAZ = BRUTO.CODIGO_SEFAZ
            AND BASE.MATRICULA = BRUTO.MATRICULA
            AND BASE.CPF = BRUTO.CPF
            AND BASE.ID_FUNCIONARIO = BRUTO.ID_FUNCIONARIO
            AND BASE.TIPO_BENEFICIO = BRUTO.TIPO_BENEFICIO
    JOIN (
        SELECT
            VT.FAIXA,
            VT.VALOR_INICIAL,
            VT.VALOR_FINAL,
            VT.VALOR_1,
            VT.PERCENTUAL
        FROM
            SW_FUNPREV.FOLHA FO
            JOIN SW_FUNPREV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA AND VT.ID_TABELA = 1000280
        WHERE
            SUBSTR(FO.CHAVE_FOLHA, 9) = 300 AND FO.MES = 7 AND FO.ANO = 2026 AND FO.ID_TIPO_FOLHA = 1000000
    ) FAIXA ON FAIXA.VALOR_1 < BASE.VALOR_CALCULADO
GROUP BY
    BRUTO.ORGAO,
    BRUTO.CODIGO_SEFAZ,
    BRUTO.DESCRICAO_SEFAZ,
    BRUTO.TIPO_BENEFICIO,
    FAIXA.FAIXA,
    FAIXA.PERCENTUAL
ORDER BY
    BRUTO.ORGAO,
    BRUTO.CODIGO_SEFAZ,
    FAIXA.FAIXA;