WITH DADOS_COMBINADOS AS (
SELECT 
    'AGESPISA' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_AGESPISA.FOLHA FO
    JOIN SW_AGESPISA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_AGESPISA.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_AGESPISA.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_AGESPISA.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'CAPSI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_CAPSI.FOLHA FO
    JOIN SW_CAPSI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CAPSI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_CAPSI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_CAPSI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'CBMPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_CBMPI.FOLHA FO
    JOIN SW_CBMPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CBMPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_CBMPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_CBMPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'CENDFOL' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_CENDFOL.FOLHA FO
    JOIN SW_CENDFOL.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CENDFOL.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_CENDFOL.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_CENDFOL.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'CRS_I' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_CRS_I.FOLHA FO
    JOIN SW_CRS_I.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CRS_I.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_CRS_I.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_CRS_I.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'CRS_III' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_CRS_III.FOLHA FO
    JOIN SW_CRS_III.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CRS_III.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_CRS_III.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_CRS_III.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'CRS_IV' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_CRS_IV.FOLHA FO
    JOIN SW_CRS_IV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CRS_IV.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_CRS_IV.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_CRS_IV.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'CRS_IX' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_CRS_IX.FOLHA FO
    JOIN SW_CRS_IX.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CRS_IX.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_CRS_IX.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_CRS_IX.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'CRS_V' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_CRS_V.FOLHA FO
    JOIN SW_CRS_V.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CRS_V.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_CRS_V.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_CRS_V.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'CRS_VII' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_CRS_VII.FOLHA FO
    JOIN SW_CRS_VII.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CRS_VII.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_CRS_VII.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_CRS_VII.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'CRS_VIII' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_CRS_VIII.FOLHA FO
    JOIN SW_CRS_VIII.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CRS_VIII.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_CRS_VIII.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_CRS_VIII.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'CRS_X' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_CRS_X.FOLHA FO
    JOIN SW_CRS_X.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CRS_X.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_CRS_X.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_CRS_X.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'CRS_XII' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_CRS_XII.FOLHA FO
    JOIN SW_CRS_XII.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CRS_XII.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_CRS_XII.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_CRS_XII.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'CRS_XIII' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_CRS_XIII.FOLHA FO
    JOIN SW_CRS_XIII.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CRS_XIII.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_CRS_XIII.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_CRS_XIII.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'CRS_XV' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_CRS_XV.FOLHA FO
    JOIN SW_CRS_XV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CRS_XV.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_CRS_XV.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_CRS_XV.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'DEFCIVIL' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_DEFCIVIL.FOLHA FO
    JOIN SW_DEFCIVIL.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_DEFCIVIL.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_DEFCIVIL.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_DEFCIVIL.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'DGPCPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_DGPCPI.FOLHA FO
    JOIN SW_DGPCPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_DGPCPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_DGPCPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_DGPCPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'FAPEPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_FAPEPI.FOLHA FO
    JOIN SW_FAPEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FAPEPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_FAPEPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_FAPEPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'FESPPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_FESPPI.FOLHA FO
    JOIN SW_FESPPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FESPPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_FESPPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_FESPPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'FUESPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_FUESPI.FOLHA FO
    JOIN SW_FUESPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUESPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_FUESPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_FUESPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'FUNAP' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_FUNAP.FOLHA FO
    JOIN SW_FUNAP.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUNAP.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_FUNAP.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_FUNAP.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'FUNPESPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_FUNPESPI.FOLHA FO
    JOIN SW_FUNPESPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUNPESPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_FUNPESPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_FUNPESPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'FUNSAUDE' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_FUNSAUDE.FOLHA FO
    JOIN SW_FUNSAUDE.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUNSAUDE.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_FUNSAUDE.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_FUNSAUDE.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'GAMIL' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_GAMIL.FOLHA FO
    JOIN SW_GAMIL.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_GAMIL.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_GAMIL.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_GAMIL.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'HAA' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_HAA.FOLHA FO
    JOIN SW_HAA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_HAA.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_HAA.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_HAA.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'HCC' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_HCC.FOLHA FO
    JOIN SW_HCC.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_HCC.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_HCC.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_HCC.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'HEDA' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_HEDA.FOLHA FO
    JOIN SW_HEDA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_HEDA.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_HEDA.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_HEDA.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'HEJBC' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_HEJBC.FOLHA FO
    JOIN SW_HEJBC.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_HEJBC.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_HEJBC.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_HEJBC.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'HEJFM' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_HEJFM.FOLHA FO
    JOIN SW_HEJFM.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_HEJFM.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_HEJFM.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_HEJFM.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'HEJH' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_HEJH.FOLHA FO
    JOIN SW_HEJH.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_HEJH.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_HEJH.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_HEJH.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'HEJLM' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_HEJLM.FOLHA FO
    JOIN SW_HEJLM.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_HEJLM.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_HEJLM.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_HEJLM.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'HEMOPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_HEMOPI.FOLHA FO
    JOIN SW_HEMOPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_HEMOPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_HEMOPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_HEMOPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'HENM' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_HENM.FOLHA FO
    JOIN SW_HENM.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_HENM.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_HENM.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_HENM.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'HGV' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_HGV.FOLHA FO
    JOIN SW_HGV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_HGV.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_HGV.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_HGV.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'HILP' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_HILP.FOLHA FO
    JOIN SW_HILP.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_HILP.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_HILP.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_HILP.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'HLDC' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_HLDC.FOLHA FO
    JOIN SW_HLDC.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_HLDC.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_HLDC.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_HLDC.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'HLGCB' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_HLGCB.FOLHA FO
    JOIN SW_HLGCB.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_HLGCB.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_HLGCB.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_HLGCB.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'HLJMF' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_HLJMF.FOLHA FO
    JOIN SW_HLJMF.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_HLJMF.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_HLJMF.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_HLJMF.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'HPM' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_HPM.FOLHA FO
    JOIN SW_HPM.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_HPM.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_HPM.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_HPM.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'HRCF' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_HRCF.FOLHA FO
    JOIN SW_HRCF.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_HRCF.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_HRCF.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_HRCF.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'HRCM' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_HRCM.FOLHA FO
    JOIN SW_HRCM.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_HRCM.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_HRCM.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_HRCM.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'HRCR' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_HRCR.FOLHA FO
    JOIN SW_HRCR.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_HRCR.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_HRCR.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_HRCR.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'HRDA' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_HRDA.FOLHA FO
    JOIN SW_HRDA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_HRDA.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_HRDA.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_HRDA.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'HRDC' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_HRDC.FOLHA FO
    JOIN SW_HRDC.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_HRDC.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_HRDC.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_HRDC.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'HREP' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_HREP.FOLHA FO
    JOIN SW_HREP.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_HREP.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_HREP.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_HREP.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'HRFAC' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_HRFAC.FOLHA FO
    JOIN SW_HRFAC.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_HRFAC.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_HRFAC.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_HRFAC.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'HRJL' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_HRJL.FOLHA FO
    JOIN SW_HRJL.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_HRJL.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_HRJL.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_HRJL.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'HRJPC' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_HRJPC.FOLHA FO
    JOIN SW_HRJPC.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_HRJPC.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_HRJPC.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_HRJPC.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'HRLM' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_HRLM.FOLHA FO
    JOIN SW_HRLM.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_HRLM.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_HRLM.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_HRLM.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'HRP' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_HRP.FOLHA FO
    JOIN SW_HRP.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_HRP.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_HRP.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_HRP.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'HRTN' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_HRTN.FOLHA FO
    JOIN SW_HRTN.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_HRTN.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_HRTN.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_HRTN.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'HRTNB' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_HRTNB.FOLHA FO
    JOIN SW_HRTNB.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_HRTNB.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_HRTNB.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_HRTNB.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'IASPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_IASPI.FOLHA FO
    JOIN SW_IASPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_IASPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_IASPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_IASPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'IDTNP' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_IDTNP.FOLHA FO
    JOIN SW_IDTNP.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_IDTNP.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_IDTNP.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_IDTNP.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'INTERPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_INTERPI.FOLHA FO
    JOIN SW_INTERPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_INTERPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_INTERPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_INTERPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'LACEN' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_LACEN.FOLHA FO
    JOIN SW_LACEN.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_LACEN.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_LACEN.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_LACEN.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'MDER' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_MDER.FOLHA FO
    JOIN SW_MDER.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_MDER.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_MDER.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_MDER.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'METRO' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_METRO.FOLHA FO
    JOIN SW_METRO.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_METRO.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_METRO.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_METRO.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'PMPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_PMPI.FOLHA FO
    JOIN SW_PMPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PMPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_PMPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_PMPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'PRODSUS' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_PRODSUS.FOLHA FO
    JOIN SW_PRODSUS.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PRODSUS.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_PRODSUS.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_PRODSUS.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'RMSS' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_RMSS.FOLHA FO
    JOIN SW_RMSS.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_RMSS.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_RMSS.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_RMSS.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'SAF' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_SAF.FOLHA FO
    JOIN SW_SAF.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SAF.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SAF.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_SAF.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'SASC' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_SASC.FOLHA FO
    JOIN SW_SASC.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SASC.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SASC.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_SASC.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'SEADPREVPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_SEADPREVPI.FOLHA FO
    JOIN SW_SEADPREVPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEADPREVPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEADPREVPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_SEADPREVPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'SECEPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_SECEPI.FOLHA FO
    JOIN SW_SECEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SECEPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SECEPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_SECEPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'SECULT' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_SECULT.FOLHA FO
    JOIN SW_SECULT.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SECULT.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SECULT.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_SECULT.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'SEDUC' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_SEDUC.FOLHA FO
    JOIN SW_SEDUC.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEDUC.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEDUC.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_SEDUC.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'SEDUC_ALFA' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_SEDUC_ALFA.FOLHA FO
    JOIN SW_SEDUC_ALFA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEDUC_ALFA.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEDUC_ALFA.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_SEDUC_ALFA.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'SEDUC_EDIT' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_SEDUC_EDIT.FOLHA FO
    JOIN SW_SEDUC_EDIT.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEDUC_EDIT.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEDUC_EDIT.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_SEDUC_EDIT.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'SEDUC_EJA' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_SEDUC_EJA.FOLHA FO
    JOIN SW_SEDUC_EJA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEDUC_EJA.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEDUC_EJA.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_SEDUC_EJA.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'SEDUC_PTEC' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_SEDUC_PTEC.FOLHA FO
    JOIN SW_SEDUC_PTEC.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEDUC_PTEC.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEDUC_PTEC.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_SEDUC_PTEC.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'SEFAZ' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_SEFAZ.FOLHA FO
    JOIN SW_SEFAZ.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEFAZ.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEFAZ.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_SEFAZ.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'SEJUSPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_SEJUSPI.FOLHA FO
    JOIN SW_SEJUSPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEJUSPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEJUSPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_SEJUSPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'SEMARH' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_SEMARH.FOLHA FO
    JOIN SW_SEMARH.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEMARH.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEMARH.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_SEMARH.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'SEPLAN' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_SEPLAN.FOLHA FO
    JOIN SW_SEPLAN.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEPLAN.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEPLAN.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_SEPLAN.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'SETRE' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_SETRE.FOLHA FO
    JOIN SW_SETRE.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SETRE.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SETRE.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_SETRE.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'SSPPI' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_SSPPI.FOLHA FO
    JOIN SW_SSPPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SSPPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SSPPI.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_SSPPI.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'TFD' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_TFD.FOLHA FO
    JOIN SW_TFD.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_TFD.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_TFD.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_TFD.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'UIS' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_UIS.FOLHA FO
    JOIN SW_UIS.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_UIS.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_UIS.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_UIS.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'UMS_AVLN' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_UMS_AVLN.FOLHA FO
    JOIN SW_UMS_AVLN.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_UMS_AVLN.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_UMS_AVLN.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_UMS_AVLN.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'UMSBOC' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_UMSBOC.FOLHA FO
    JOIN SW_UMSBOC.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_UMSBOC.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_UMSBOC.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_UMSBOC.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'UMS_FILO' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_UMS_FILO.FOLHA FO
    JOIN SW_UMS_FILO.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_UMS_FILO.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_UMS_FILO.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_UMS_FILO.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'UMS_FRANC' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_UMS_FRANC.FOLHA FO
    JOIN SW_UMS_FRANC.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_UMS_FRANC.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_UMS_FRANC.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_UMS_FRANC.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'UMS_ITAIN' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_UMS_ITAIN.FOLHA FO
    JOIN SW_UMS_ITAIN.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_UMS_ITAIN.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_UMS_ITAIN.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_UMS_ITAIN.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000

UNION ALL

SELECT 
    'UMS_PAES' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PD.NOME_DIVISAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    FR.VALOR_MULTIPLICADOR
FROM
    SW_UMS_PAES.FOLHA FO
    JOIN SW_UMS_PAES.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_UMS_PAES.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_UMS_PAES.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    JOIN SW_UMS_PAES.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PC.DATA_BAIXA IS NULL
WHERE 
    R.COD_RUBRICA = 111260
    AND FO.MES = 8
    AND FO.ANO = 2026
    --AND FR.VALOR_MULTIPLICADOR > 3000
)
SELECT * FROM (
    SELECT 
        ORGAO,
        NOME,
        CPF,
        NOME_DIVISAO,
        LISTAGG(DISTINCT CHAVE_FOLHA, ' ; ') WITHIN GROUP (ORDER BY CHAVE_FOLHA) AS CHAVE_FOLHA,
        COD_RUBRICA,
        VALOR_MULTIPLICADOR,
        SUM(VALOR_MULTIPLICADOR) OVER (PARTITION BY CPF) AS TOTAL_VALOR_MULTIPLICADOR_GERAL
    FROM DADOS_COMBINADOS
    GROUP BY 
        ORGAO, NOME, CPF, NOME_DIVISAO, COD_RUBRICA, VALOR_MULTIPLICADOR
)
WHERE TOTAL_VALOR_MULTIPLICADOR_GERAL > 3000;