SELECT 
    'DEFENSORIA Pública do Estado do Piauí' AS "nomeUnidGestOuEntidade",
    '350101' AS "codigoUnidGestSiafOuEquivalente",
    REPLACE(REPLACE(REPLACE(E.CNPJ, '.', ''), '/', ''), '-', '') AS "cnpjPagador",
    FC.NOME AS "nomeServidor",
    REPLACE(REPLACE(FC.CPF_PESSOA, '.', ''), '-', '') AS "cpf",
    TO_CHAR(TO_DATE(FC.DATA_NASCIMENTO, 'DD/MM/YYYY'), 'YYYY-MM-DD') AS "dataNascimento",
    FC.COD_LOTACAO AS "codigoLotaFolha",
    FC.NOME_LOTACAO AS "descricaoLotacao",
    FC.COD_INSTITUCIONAL AS "matricula",
    CM.COD_MUNICIPIO_IBGE AS "codigoIbgeMunicipio",
    LPAD(COALESCE(FC.COD_FUNCAO, FC.COD_CARGO, FC.COD_ESPECIALIDADE), 10, '0') AS "codigoCargFolha",
    COALESCE(FC.FUNCAO, FC.CARGO, FC.ESPECIALIDADE) AS "descricaoCargFolha",
    TO_CHAR(TO_DATE(FC.DATA_ADMISSAO, 'DD/MM/YYYY'), 'YYYY-MM-DD') AS "dataAdmissao",
    CASE 
        WHEN PD.ID_DIVISAO = 1000001 THEN 2
        WHEN PD.ID_DIVISAO = 1000000 THEN 5
        WHEN PD.ID_DIVISAO = 1000020 THEN 1
    END AS "vinculo",
    FC.MES AS "mesReferencia",
    FC.ANO AS "anoReferencia",
    LPAD(R.COD_RUBRICA, 10, '0') AS "codigoRubrFolha",
    R.NOME_RUBRICA AS "descricaoRubrFolha",
    CASE
        WHEN R.TIPO = 'R' THEN 1
        WHEN R.TIPO = 'D' THEN 2
    END AS "rubricaFolha",
    REPLACE(SUM(FF.VALOR_CALCULADO), ',', '.') AS "valor",
    FC.COD_BANCO AS "codigoBanco",
    LPAD(REPLACE(FC.COD_AGENCIA, '-', ''), 4, '0') AS "codigoAgencia",
    LPAD(CASE
        WHEN INSTR(FC.CONTA_CORRENTE, '-') > 0 
        THEN SUBSTR(FC.CONTA_CORRENTE, 1, INSTR(FC.CONTA_CORRENTE, '-') - 1)
        ELSE SUBSTR(FC.CONTA_CORRENTE, 1, LENGTH(FC.CONTA_CORRENTE) - 1)
    END, 25, '0') AS "numeroContBancaria",
    SUBSTR(FC.CONTA_CORRENTE, -1) AS "digitoVerificador"
FROM 
    SW_DEFENSORIA.FOLHA_CONTRACHEQUE FC
    JOIN SW_DEFENSORIA.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
    JOIN SW_DEFENSORIA.RHB_LOTACAO L ON L.COD_LOTACAO = FC.COD_LOTACAO
    LEFT JOIN SW_PUBLICO.RHB_CEP_MUNICIPIO_IBGE CM ON CM.ID_MUNICIPIO = L.ID_MUNICIPIO
    JOIN SW_PUBLICO.EMPRESA E ON E.SIGLA = 'DEFENSORIA'
    LEFT JOIN SW_DEFENSORIA.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FC.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    LEFT JOIN SW_DEFENSORIA.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    LEFT JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
WHERE 
    FC.MES = 7
    AND FC.ANO = 2026
    AND R.TIPO IN ('R', 'D')
    AND FC.ID_PENSIONISTA_PA IS NULL
    AND FC.ID_ESTAGIARIO IS NULL
GROUP BY
    'DEFENSORIA Pública do Estado do Piauí',
    '350101',
    E.CNPJ,
    FC.NOME,
    FC.CPF_PESSOA,
    FC.DATA_NASCIMENTO,
    FC.COD_LOTACAO,
    FC.NOME_LOTACAO,
    FC.COD_INSTITUCIONAL,
    CM.COD_MUNICIPIO_IBGE,
    FC.COD_FUNCAO, FC.COD_CARGO, FC.COD_ESPECIALIDADE,
    FC.FUNCAO, FC.CARGO, FC.ESPECIALIDADE,
    FC.DATA_ADMISSAO,
    PD.ID_DIVISAO,
    FC.MES,
    FC.ANO,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    R.TIPO,
    FC.COD_BANCO,
    FC.COD_AGENCIA,
    FC.CONTA_CORRENTE,
    FC.CONTA_CORRENTE
UNION ALL
SELECT 
    'Defensoria Pública do Estado do Piauí' AS "nomeUnidGestOuEntidade",
    '350101' AS "codigoUnidGestSiafOuEquivalente",
    REPLACE(REPLACE(REPLACE(E.CNPJ, '.', ''), '/', ''), '-', '') AS "cnpjPagador",
    FC.NOME AS "nomeServidor",
    REPLACE(REPLACE(FC.CPF_PESSOA, '.', ''), '-', '') AS "cpf",
    TO_CHAR(TO_DATE(FC.DATA_NASCIMENTO, 'DD/MM/YYYY'), 'YYYY-MM-DD') AS "dataNascimento",
    FC.COD_LOTACAO AS "codigoLotaFolha",
    FC.NOME_LOTACAO AS "descricaoLotacao",
    FC.COD_INSTITUCIONAL AS "matricula",
    CM.COD_MUNICIPIO_IBGE AS "codigoIbgeMunicipio",
    LPAD(COALESCE(FC.COD_FUNCAO, FC.COD_CARGO, FC.COD_ESPECIALIDADE), 10, '0') AS "codigoCargFolha",
    COALESCE(FC.FUNCAO, FC.CARGO, FC.ESPECIALIDADE) AS "descricaoCargFolha",
    TO_CHAR(TO_DATE(FC.DATA_ADMISSAO, 'DD/MM/YYYY'), 'YYYY-MM-DD') AS "dataAdmissao",
    13 AS "vinculo",
    FC.MES AS "mesReferencia",
    FC.ANO AS "anoReferencia",
    LPAD(R.COD_RUBRICA, 10, '0') AS "codigoRubrFolha",
    R.NOME_RUBRICA AS "descricaoRubrFolha",
    CASE
        WHEN R.TIPO = 'R' THEN 1
        WHEN R.TIPO = 'D' THEN 2
    END AS "rubricaFolha",
    REPLACE(SUM(FFE.VALOR), ',', '.') AS "valor",
    FC.COD_BANCO AS "codigoBanco",
    LPAD(REPLACE(FC.COD_AGENCIA, '-', ''), 4, '0') AS "codigoAgencia",
    LPAD(CASE 
        WHEN INSTR(FC.CONTA_CORRENTE, '-') > 0 
        THEN SUBSTR(FC.CONTA_CORRENTE, 1, INSTR(FC.CONTA_CORRENTE, '-') - 1)
        ELSE SUBSTR(FC.CONTA_CORRENTE, 1, LENGTH(FC.CONTA_CORRENTE) - 1)
    END, 25, '0') AS "numeroContBancaria",
    SUBSTR(FC.CONTA_CORRENTE, -1) AS "digitoVerificador"
FROM 
    SW_DEFENSORIA.FOLHA_CONTRACHEQUE FC
    JOIN SW_DEFENSORIA.ESTAG_PAGAMENTO_RUBRICA_FICHAF FFE ON FFE.ID_FOLHA_ESTAGIARIO = FC.ID_ESTAGIARIO_PAGAMENTO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FFE.ID_RUBRICA
    JOIN SW_DEFENSORIA.RHB_LOTACAO L ON L.COD_LOTACAO = FC.COD_LOTACAO
    LEFT JOIN SW_PUBLICO.RHB_CEP_MUNICIPIO_IBGE CM ON CM.ID_MUNICIPIO = L.ID_MUNICIPIO
    JOIN SW_PUBLICO.EMPRESA E ON E.SIGLA = 'DEFENSORIA'
WHERE 
    FC.MES = 7
    AND FC.ANO = 2026
    AND R.TIPO IN ('R', 'D')
    AND FC.ID_ESTAGIARIO IS NOT NULL
    AND FC.ID_PENSIONISTA_PA IS NULL
GROUP BY
    'DEFENSORIA Pública do Estado do Piauí',
    '350101',
    E.CNPJ,
    FC.NOME,
    FC.CPF_PESSOA,
    FC.DATA_NASCIMENTO,
    FC.COD_LOTACAO,
    FC.NOME_LOTACAO,
    FC.COD_INSTITUCIONAL,
    CM.COD_MUNICIPIO_IBGE,
    FC.COD_FUNCAO, FC.COD_CARGO, FC.COD_ESPECIALIDADE,
    FC.FUNCAO, FC.CARGO, FC.ESPECIALIDADE,
    FC.DATA_ADMISSAO,
    15,
    FC.MES,
    FC.ANO,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    R.TIPO,
    FC.COD_BANCO,
    FC.COD_AGENCIA,
    FC.CONTA_CORRENTE,
    FC.CONTA_CORRENTE
;
/*
UNION ALL
SELECT 
    'Defensoria Pública do Estado do Piauí' AS "nomeUnidGestOuEntidade",
    '350101' AS "codigoUnidGestSiafOuEquivalente",
    REPLACE(REPLACE(REPLACE(E.CNPJ, '.', ''), '/', ''), '-', '') AS "cnpjPagador",
    FC.NOME AS "nomeServidor",
    REPLACE(REPLACE(FC.CPF_PESSOA, '.', ''), '-', '') AS "cpf",
    TO_CHAR(TO_DATE(FC.DATA_NASCIMENTO, 'DD/MM/YYYY'), 'YYYY-MM-DD') AS "dataNascimento",
    FC.COD_LOTACAO AS "codigoLotaFolha",
    FC.NOME_LOTACAO AS "descricaoLotacao",
    FC.COD_INSTITUCIONAL AS "matricula",
    CM.COD_MUNICIPIO_IBGE AS "codigoIbgeMunicipio",
    LPAD(COALESCE(FC.COD_FUNCAO, FC.COD_CARGO, FC.COD_ESPECIALIDADE), 10, '0') AS "codigoCargFolha",
    COALESCE(FC.FUNCAO, FC.CARGO, FC.ESPECIALIDADE) AS "descricaoCargFolha",
    TO_CHAR(TO_DATE(FC.DATA_ADMISSAO, 'DD/MM/YYYY'), 'YYYY-MM-DD') AS "dataAdmissao",
    15 AS "vinculo",
    FC.MES AS "mesReferencia",
    FC.ANO AS "anoReferencia",
    LPAD(R.COD_RUBRICA, 10, '0') AS "codigoRubrFolha",
    R.NOME_RUBRICA AS "descricaoRubrFolha",
    CASE
        WHEN R.TIPO = 'R' THEN 1
        WHEN R.TIPO = 'D' THEN 2
    END AS "rubricaFolha",
    REPLACE(SUM(FF.VALOR_CALCULADO), ',', '.') AS "valor",
    FC.COD_BANCO AS "codigoBanco",
    LPAD(REPLACE(FC.COD_AGENCIA, '-', ''), 4, '0') AS "codigoAgencia",
    LPAD(CASE 
        WHEN INSTR(FC.CONTA_CORRENTE, '-') > 0 
        THEN SUBSTR(FC.CONTA_CORRENTE, 1, INSTR(FC.CONTA_CORRENTE, '-') - 1)
        ELSE SUBSTR(FC.CONTA_CORRENTE, 1, LENGTH(FC.CONTA_CORRENTE) - 1)
    END, 25, '0') AS "numeroContBancaria",
    SUBSTR(FC.CONTA_CORRENTE, -1) AS "digitoVerificador"
FROM 
    SW_DEFENSORIA.FOLHA_CONTRACHEQUE FC
    JOIN SW_DEFENSORIA.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_PENSIONISTA_PA = FC.ID_PENSIONISTA_PA AND FF.MES_REFERENCIA = FC.MES AND FF.ANO_REFERENCIA = FC.ANO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
    JOIN SW_DEFENSORIA.RHB_LOTACAO L ON L.COD_LOTACAO = FC.COD_LOTACAO
    LEFT JOIN SW_PUBLICO.RHB_CEP_MUNICIPIO_IBGE CM ON CM.ID_MUNICIPIO = L.ID_MUNICIPIO
    JOIN SW_PUBLICO.EMPRESA E ON E.SIGLA = 'DEFENSORIA'
    LEFT JOIN SW_DEFENSORIA.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = FC.ID_FUNCIONARIO AND FP.DATA_FIM IS NULL
    LEFT JOIN SW_DEFENSORIA.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    LEFT JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
WHERE 
    FC.MES = 7
    AND FC.ANO = 2026
    AND R.TIPO IN ('R', 'D')
    AND FC.ID_PENSIONISTA_PA IS NOT NULL
GROUP BY
    'DEFENSORIA Pública do Estado do Piauí',
    '350101',
    E.CNPJ,
    FC.NOME,
    FC.CPF_PESSOA,
    FC.DATA_NASCIMENTO,
    FC.COD_LOTACAO,
    FC.NOME_LOTACAO,
    FC.COD_INSTITUCIONAL,
    CM.COD_MUNICIPIO_IBGE,
    FC.COD_FUNCAO, FC.COD_CARGO, FC.COD_ESPECIALIDADE,
    FC.FUNCAO, FC.CARGO, FC.ESPECIALIDADE,
    FC.DATA_ADMISSAO,
    15,
    FC.MES,
    FC.ANO,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    R.TIPO,
    FC.COD_BANCO,
    FC.COD_AGENCIA,
    FC.CONTA_CORRENTE,
    FC.CONTA_CORRENTE
;
*/