SELECT 
    E.SIGLA ORGAO,
    HN.NOME,
    PV.COD_INSTITUCIONAL MATRICULA,
    P.NOME_MAE,
    P.NOME_PAI,
    P.DATA_NASCIMENTO,
    CASE 
        WHEN FS.ID_SEXO = 1 THEN 'M'
        ELSE 'F'
    END SEXO,
    E.ORGAO_SIAFI,
    E.NOME_FANTASIA,
    CFF.NOME_CATEGORIA_FUNCIONAL,
    CFF.DESCRICAO_CATEGORIA_FUNCIONAL,
    CASE 
        WHEN FIG.IND_ESOCIAL_REG_PREV = 'V1' THEN 'Regime Geral da Previdência Social - RGPS'
        WHEN FIG.IND_ESOCIAL_REG_PREV = 'V2' THEN 'Regime Próprio de Previdência Social - RPPS'
        WHEN FIG.IND_ESOCIAL_REG_PREV = 'V3' THEN 'Regime de Previdência Social no Exterior'
    END REGIME_PREVIDENCIARIO,
    IR.NOME_REGIME
FROM   
    SW_SEADPREVPI.PESSOA_VINCULO PV 
    JOIN SW_SEADPREVPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SEADPREVPI.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SEADPREVPI.RHB_CARREIRA_CATEG_FUNCIONAL CFF ON CFF.ID_CATEGORIA_FUNCIONAL = FI.ID_CATEGORIA_FUNCIONAL
    JOIN SW_SEADPREVPI.FUNCIONARIO_INF_GOVERNO FIG ON FIG.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SEADPREVPI.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO 
    JOIN SW_PUBLICO.RHB_INGRESSO_REGIME_TRABALHO IR ON IR.ID_REGIME = FI.ID_REGIME
    JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.RHB_CARACT_FISICA_SEXO FS ON FS.ID_SEXO = P.ID_SEXO
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.EMPRESA E ON E.SIGLA = 'SEADPREVPI'
    