SELECT
    'AGESPISA02' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_AGESPISA02.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_AGESPISA02.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_AGESPISA02.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_DETRAN.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1004606
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_AGESPISA02.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    );
    
INSERT INTO SW_AGESPISA02.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_AGESPISA02.SQ_PK_EVENTO_MENSAL.NEXTVAL, 1000181, 1550988, 0);