SELECT
    'SW_ADH' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_ADH.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_ADH.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_ADH.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_ADH.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_AGESPISA' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_AGESPISA.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_AGESPISA.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_AGESPISA.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_AGESPISA.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_AGESPISA02' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_AGESPISA02.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_AGESPISA02.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_AGESPISA02.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_AGESPISA02.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_AGRESP' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_AGRESP.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_AGRESP.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_AGRESP.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_AGRESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_BEP' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_BEP.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_BEP.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_BEP.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_BEP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_CBMPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_CBMPI.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_CBMPI.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_CBMPI.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_CBMPI.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_CCOM' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_CCOM.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_CCOM.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_CCOM.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_CCOM.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_CDTER' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_CDTER.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_CDTER.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_CDTER.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_CDTER.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_CENDROGAS' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_CENDROGAS.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_CENDROGAS.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_CENDROGAS.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_CENDROGAS.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_COFIR' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_COFIR.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_COFIR.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_COFIR.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_COFIR.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_COJUV' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_COJUV.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_COJUV.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_COJUV.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_COJUV.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_DEFCIVIL' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_DEFCIVIL.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_DEFCIVIL.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_DEFCIVIL.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_DEFCIVIL.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_DER' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_DER.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_DER.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_DER.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_DER.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_DETRAN' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_DETRAN.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_DETRAN.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_DETRAN.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_DETRAN.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_EMGERPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_EMGERPI.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_EMGERPI.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_EMGERPI.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_EMGERPI.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_EMGERPI_CEASA' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_EMGERPI_CEASA.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_EMGERPI_CEASA.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_EMGERPI_CEASA.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_EMGERPI_CEASA.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_EMGERPI_CIDAPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_EMGERPI_CIDAPI.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_EMGERPI_CIDAPI.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_EMGERPI_CIDAPI.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_EMGERPI_CIDAPI.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_EMGERPI_CODIPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_EMGERPI_CODIPI.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_EMGERPI_CODIPI.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_EMGERPI_CODIPI.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_EMGERPI_CODIPI.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_EMGERPI_COHAB' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_EMGERPI_COHAB.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_EMGERPI_COHAB.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_EMGERPI_COHAB.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_EMGERPI_COHAB.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_EMGERPI_COMDEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_EMGERPI_COMDEPI.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_EMGERPI_COMDEPI.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_EMGERPI_COMDEPI.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_EMGERPI_COMDEPI.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_EMGERPI_COMEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_EMGERPI_COMEPI.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_EMGERPI_COMEPI.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_EMGERPI_COMEPI.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_EMGERPI_COMEPI.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_EMGERPI_CORESA' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_EMGERPI_CORESA.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_EMGERPI_CORESA.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_EMGERPI_CORESA.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_EMGERPI_CORESA.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_EMGERPI_EMATER' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_EMGERPI_EMATER.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_EMGERPI_EMATER.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_EMGERPI_EMATER.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_EMGERPI_EMATER.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_EMGERPI_ETELPI_FUNART' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_EMGERPI_ETELPI_FUNART.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_EMGERPI_ETELPI_FUNART.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_EMGERPI_ETELPI_FUNART.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_EMGERPI_ETELPI_FUNART.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_EMGERPI_PIEMTUR' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_EMGERPI_PIEMTUR.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_EMGERPI_PIEMTUR.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_EMGERPI_PIEMTUR.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_EMGERPI_PIEMTUR.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_EMGERPI_PRODEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_EMGERPI_PRODEPI.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_EMGERPI_PRODEPI.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_EMGERPI_PRODEPI.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_EMGERPI_PRODEPI.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_FAPEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_FAPEPI.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_FAPEPI.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_FAPEPI.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_FAPEPI.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_FESPPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_FESPPI.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_FESPPI.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_FESPPI.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_FESPPI.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_FUESPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_FUESPI.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_FUESPI.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_FUESPI.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_FUESPI.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_FUNPREV' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_FUNPREV.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_FUNPREV.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_FUNPREV.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_FUNPREV.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_FUPIP' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_FUPIP.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_FUPIP.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_FUPIP.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_FUPIP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_GMG' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_GMG.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_GMG.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_GMG.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_GMG.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_IASPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_IASPI.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_IASPI.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_IASPI.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_IASPI.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_IDEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_IDEPI.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_IDEPI.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_IDEPI.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_IDEPI.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_IMEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_IMEPI.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_IMEPI.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_IMEPI.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_IMEPI.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_IMEPIPROD' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_IMEPIPROD.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_IMEPIPROD.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_IMEPIPROD.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_IMEPIPROD.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_INTERPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_INTERPI.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_INTERPI.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_INTERPI.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_INTERPI.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_JUCEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_JUCEPI.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_JUCEPI.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_JUCEPI.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_JUCEPI.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_METRO' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_METRO.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_METRO.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_METRO.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_METRO.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_PGEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_PGEPI.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_PGEPI.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_PGEPI.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_PGEPI.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_PMPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_PMPI.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_PMPI.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_PMPI.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_PMPI.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_SADA' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_SADA.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_SADA.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_SADA.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SADA.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_SAF' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_SAF.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_SAF.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_SAF.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SAF.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_SASC' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_SASC.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_SASC.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_SASC.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SASC.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_SEADPREVPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_SEADPREVPI.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_SEADPREVPI.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_SEADPREVPI.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEADPREVPI.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_SEAGRO' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_SEAGRO.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_SEAGRO.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_SEAGRO.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEAGRO.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_SECESP' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_SECESP.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_SECESP.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_SECESP.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_SECID' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_SECID.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_SECID.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_SECID.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SECID.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_SECMULHERES' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_SECMULHERES.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_SECMULHERES.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_SECMULHERES.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SECMULHERES.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_SECULT' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_SECULT.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_SECULT.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_SECULT.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SECULT.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_SEDET' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_SEDET.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_SEDET.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_SEDET.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEDET.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_SEDUC' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_SEDUC.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_SEDUC.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_SEDUC.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEDUC.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_SEFAZPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_SEFAZPI.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_SEFAZPI.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_SEFAZPI.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEFAZPI.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_SEGOV' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_SEGOV.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_SEGOV.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_SEGOV.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEGOV.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_SEID' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_SEID.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_SEID.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_SEID.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEID.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_SEINFRA' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_SEINFRA.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_SEINFRA.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_SEINFRA.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEINFRA.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_SEJUSPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_SEJUSPI.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_SEJUSPI.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_SEJUSPI.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEJUSPI.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_SEMAR' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_SEMAR.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_SEMAR.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_SEMAR.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEMAR.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_SEMINPER' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_SEMINPER.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_SEMINPER.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_SEMINPER.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEMINPER.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_SEPLAN' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_SEPLAN.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_SEPLAN.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_SEPLAN.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEPLAN.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_SERES' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_SERES.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_SERES.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_SERES.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SERES.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_SESAPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_SESAPI.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_SESAPI.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_SESAPI.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SESAPI.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_SETRANS' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_SETRANS.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_SETRANS.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_SETRANS.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SETRANS.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_SETRE' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_SETRE.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_SETRE.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_SETRE.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SETRE.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_SETUR' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_SETUR.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_SETUR.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_SETUR.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SETUR.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_SIA' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_SIA.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_SIA.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_SIA.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SIA.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_SSPPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_SSPPI.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_SSPPI.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_SSPPI.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SSPPI.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_SURPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_SURPI.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_SURPI.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_SURPI.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SURPI.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_TVANTARES' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_TVANTARES.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_TVANTARES.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_TVANTARES.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_TVANTARES.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    


UNION ALL

SELECT
    'SW_VICEGOV' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    EV.ID_EVENTO,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_VICEGOV.FOLHA_EVENTO_MENSAL (ID_EVENTO_MENSAL, ID_FOLHA, ID_EVENTO, ID_PROCEDIMENTO) VALUES (SW_VICEGOV.SQ_PK_EVENTO_MENSAL.NEXTVAL, ' || FO.ID_FOLHA || ', ' || EV.ID_EVENTO || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_VICEGOV.FOLHA FO
    JOIN (
        SELECT
            EM.ID_EVENTO,
            EM.ID_PROCEDIMENTO
        FROM
            SW_SECESP.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_EVENTO_MENSAL = 1556484
    ) EV ON EV.ID_EVENTO IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_VICEGOV.FOLHA_EVENTO_MENSAL EM
        WHERE
            EM.ID_FOLHA = FO.ID_FOLHA
            AND EM.ID_EVENTO = EV.ID_EVENTO
            AND EM.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )
    