SELECT
    'AGESPISA02' ORGAO,
    FO.CHAVE_FOLHA,
    FO.TIPO_FOLHA_SEFAZ,
    FO.DESCRICAO,
    E.NOME_EVENTO EVENTO,
    EV.ID_RUBRICA,
    EV.ID_PROCEDIMENTO,
    'INSERT INTO SW_AGESPISA02.FOLHA_EVENTO_MENSAL_RUBRICA (ID_EVENTO_MENSAL_RUBRICA, ID_EVENTO_MENSAL, ID_RUBRICA, ID_PROCEDIMENTO) VALUES (SW_AGESPISA02.SQ_PK_EVENTO_MENSAL_RUBRICA.NEXTVAL, ' || EM.ID_EVENTO_MENSAL || ', ' || EV.ID_RUBRICA || ', ' || EV.ID_PROCEDIMENTO || ');' INSERT_
FROM
    SW_AGESPISA02.FOLHA FO
    JOIN SW_AGESPISA02.FOLHA_EVENTO_MENSAL EM ON EM.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_EVENTO E ON E.ID_EVENTO = EM.ID_EVENTO
    JOIN (
        SELECT
            MR.ID_RUBRICA,
            MR.ID_PROCEDIMENTO
        FROM
            SW_DETRAN.FOLHA_EVENTO_MENSAL EM2
            JOIN SW_DETRAN.FOLHA_EVENTO_MENSAL_RUBRICA MR ON MR.ID_EVENTO_MENSAL = EM2.ID_EVENTO_MENSAL
        WHERE
            EM2.ID_EVENTO_MENSAL = 1004606
    ) EV ON EV.ID_RUBRICA IS NOT NULL
WHERE
    FO.MES = 9
    AND FO.ANO = 2026
    AND EM.ID_EVENTO = 1550988
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_AGESPISA02.FOLHA_EVENTO_MENSAL EM2
            JOIN SW_AGESPISA02.FOLHA_EVENTO_MENSAL_RUBRICA MR ON MR.ID_EVENTO_MENSAL = EM2.ID_EVENTO_MENSAL
        WHERE
            EM2.ID_EVENTO_MENSAL = EM.ID_EVENTO_MENSAL
            AND MR.ID_RUBRICA = EV.ID_RUBRICA
            AND MR.ID_PROCEDIMENTO = EV.ID_PROCEDIMENTO
    )