SELECT 
    'ADAPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_ADAPI.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'ADH' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_ADH.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'AGESPISA' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_AGESPISA.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'AGESPISA02' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_AGESPISA02.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'AGRESP' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_AGRESP.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'ATIPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_ATIPI.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'BEP' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_BEP.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'CBMPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_CBMPI.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'CCOM' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_CCOM.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'CDTER' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_CDTER.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'CENDROGAS' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_CENDROGAS.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'CEPM' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_CEPM.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'CGEPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_CGEPI.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'COFIR' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_COFIR.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'COJUV' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_COJUV.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'CPVCI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_CPVCI.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'DEFCIVIL' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_DEFCIVIL.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'DEFENSORIA' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_DEFENSORIA.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'DER' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_DER.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'DETRAN' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_DETRAN.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'EMATER' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_EMATER.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'EMATERPROD' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_EMATERPROD.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'EMGERPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_EMGERPI.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'EMGERPI_CEASA' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_EMGERPI_CEASA.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'EMGERPI_CIDAPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_EMGERPI_CIDAPI.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'EMGERPI_CODIPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_EMGERPI_CODIPI.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'EMGERPI_COHAB' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_EMGERPI_COHAB.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'EMGERPI_COMDEPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_EMGERPI_COMDEPI.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'EMGERPI_COMEPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_EMGERPI_COMEPI.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'EMGERPI_CORESA' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_EMGERPI_CORESA.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'EMGERPI_EMATER' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_EMGERPI_EMATER.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'EMGERPI_ETELPI_FUNART' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_EMGERPI_ETELPI_FUNART.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'EMGERPI_PIEMTUR' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_EMGERPI_PIEMTUR.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'EMGERPI_PRODEPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_EMGERPI_PRODEPI.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'EMPRESA' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_EMPRESA.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'FAPEPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_FAPEPI.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'FESPPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_FESPPI.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'FUESPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_FUESPI.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'FUNDESPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_FUNDESPI.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'FUNPREV' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_FUNPREV.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'FUPIP' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_FUPIP.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'GMG' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_GMG.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'IASPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_IASPI.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'IDEPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_IDEPI.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'IMEPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_IMEPI.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'IMEPIPROD' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_IMEPIPROD.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'INATIVOS_PENSIONISTAS' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_INATIVOS_PENSIONISTAS.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'INATIVOS_SEDUC' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_INATIVOS_SEDUC.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'INATIVOS_TCE' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_INATIVOS_TCE.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'INTERPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_INTERPI.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'JUCEPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_JUCEPI.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'METRO' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_METRO.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'PENSIONISTAS' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_PENSIONISTAS.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'PGEPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_PGEPI.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'PIAUIPREV' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_PIAUIPREV.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'PMPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_PMPI.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'REENVIO' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_REENVIO.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'SADA' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_SADA.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'SAF' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_SAF.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'SASC' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_SASC.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'SEADPREVPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_SEADPREVPI.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'SEAGRO' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_SEAGRO.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'SECESP' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_SECESP.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'SECID' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_SECID.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'SECMULHERES' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_SECMULHERES.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'SECULT' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_SECULT.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'SEDET' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_SEDET.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'SEDUC' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_SEDUC.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'SEDUC_PRECATORIO' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_SEDUC_PRECATORIO.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'SEFAZPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_SEFAZPI.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'SEGOV' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_SEGOV.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'SEID' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_SEID.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'SEINFRA' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_SEINFRA.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'SEJUSPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_SEJUSPI.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'SEMAR' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_SEMAR.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'SEMINPER' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_SEMINPER.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'SEPLAN' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_SEPLAN.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'SERES' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_SERES.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'SESAPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_SESAPI.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'SETRANS' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_SETRANS.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'SETRE' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_SETRE.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'SETUR' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_SETUR.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'SIA' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_SIA.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'SSPPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_SSPPI.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'SURPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_SURPI.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'TVANTARES' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_TVANTARES.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
UNION ALL
SELECT 
    'VICEGOV' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.ID_PESSOA,
    PV.COD_INSTITUCIONAL
FROM
    SW_VICEGOV.PESSOA_VINCULO PV 
WHERE 
    PV.ID_PESSOA = 1039966
;