-- RELATÓRIO LOTAÇÕES NATAL
WITH TABELA_AUX AS (
    SELECT
        X.ORGAO,
        X.ID_FUNCIONARIO,
        X.ID_FOLHA_FUNCIONARIO,
        X.MATRICULA,
        X.CPF,
        X.COD_LOTACAO,
        X.NOME_LOTACAO,
        CASE
            WHEN X.COD_RUBRICA IN (714250) THEN 'BASE'
            WHEN X.COD_RUBRICA_LEGADO IN ('900') THEN 'FUNDO'
            WHEN X.COD_RUBRICA IN (714450, 714455, 714460) THEN 'PATRONAL'
            WHEN X.COD_RUBRICA IN (999997) THEN 'BRUTO'
        END TIPO_RUBRICA,
        X.VALOR_CALCULADO
    FROM
        (
        SELECT
            FF.ID_FOLHA_FUNCIONARIO,
            F.ID_FUNCIONARIO,
            REGEXP_REPLACE(PV.COD_INSTITUCIONAL, '[^0-9A-Za-z]', '') MATRICULA,
            PDC.CPF_PESSOA CPF,
            E.ORGAO_SIAFI ORGAO,
            R.COD_RUBRICA,
            R.COD_RUBRICA_LEGADO,
            FR.VALOR_CALCULADO,
            FO.MES,
            FO.ANO,
            FO.ID_TIPO_FOLHA,
            FF.COD_LOTACAO,
            FF.NOME_LOTACAO
        FROM
            SW_PUBLICO.PESSOA P
            JOIN SW_PUBLICO.PESSOA_DOC_CPF PDC ON PDC.ID_PESSOA = P.ID_PESSOA AND PDC.DATA_BAIXA IS NULL
            JOIN SW_PUBLICO.EMPRESA E ON E.SIGLA = 'DEFENSORIA'
            JOIN SW_DEFENSORIA.PESSOA_VINCULO PV ON PV.ID_PESSOA = P.ID_PESSOA
            JOIN SW_DEFENSORIA.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
            JOIN SW_DEFENSORIA.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = F.ID_FUNCIONARIO
            JOIN SW_DEFENSORIA.FOLHA_FUNC FF ON FF.ID_FUNCIONARIO = F.ID_FUNCIONARIO
            JOIN SW_DEFENSORIA.FOLHA FO ON FO.ID_FOLHA = FF.ID_FOLHA
            JOIN SW_DEFENSORIA.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
            JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
        WHERE
            FO.ID_TIPO_FOLHA IN (1000000, 1000003)
            AND FO.MES = 8
            AND FO.ANO = 2026
            AND (
                R.COD_RUBRICA IN (714250)
                OR R.COD_RUBRICA_LEGADO IN ('900')
                OR R.COD_RUBRICA IN (714450, 714455, 714460)
                OR R.COD_RUBRICA IN (999997)
            )
        ) X
)
SELECT
    BRUTO.ORGAO "CODIGO EMPRESA",
    COUNT(DISTINCT BRUTO.MATRICULA) "CONTRACHEQUES",
    COUNT(DISTINCT BRUTO.CPF) "CPFs",
    BRUTO.COD_LOTACAO "CODIGO LOTACAO",
    BRUTO.NOME_LOTACAO "LOTACAO",
    NVL(SUM(BASE.VALOR_CALCULADO), 0) "VALOR BASE",
    NVL(SUM(FUNDO.VALOR_CALCULADO), 0) "VALOR FUNDO",
    NVL(SUM(PATRONAL.VALOR_CALCULADO), 0) "PATRONAL",
    NVL(SUM(FUNDO.VALOR_CALCULADO), 0) + NVL(SUM(PATRONAL.VALOR_CALCULADO), 0) "REPASSE",
    NVL(SUM(BRUTO.VALOR_CALCULADO), 0) "VALOR BRUTO"
FROM
    (
    SELECT
        BRUTO.ORGAO,
        BRUTO.ID_FUNCIONARIO,
        BRUTO.MATRICULA,
        BRUTO.CPF,
        BRUTO.COD_LOTACAO,
        BRUTO.NOME_LOTACAO,
    SUM(BRUTO.VALOR_CALCULADO) VALOR_CALCULADO
    FROM
        TABELA_AUX BRUTO
    WHERE
        BRUTO.TIPO_RUBRICA = 'BRUTO'
    GROUP BY
        BRUTO.ORGAO,
        BRUTO.ID_FUNCIONARIO,
        BRUTO.MATRICULA,
        BRUTO.CPF,
        BRUTO.COD_LOTACAO,
        BRUTO.NOME_LOTACAO
    ) BRUTO
    LEFT JOIN (
        SELECT
            FUNDO.ORGAO,
            FUNDO.ID_FUNCIONARIO,
            FUNDO.MATRICULA,
            FUNDO.CPF,
            FUNDO.COD_LOTACAO,
            FUNDO.NOME_LOTACAO,
            SUM(FUNDO.VALOR_CALCULADO) VALOR_CALCULADO,
            CASE
                WHEN SUM(FUNDO.VALOR_CALCULADO) = 0 THEN 'N'
                ELSE 'S'
            END IND_CONTRIBUICAO
        FROM
            TABELA_AUX FUNDO
        WHERE
            FUNDO.TIPO_RUBRICA = 'FUNDO'
        GROUP BY
            FUNDO.ORGAO,
            FUNDO.ID_FUNCIONARIO,
            FUNDO.MATRICULA,
            FUNDO.CPF,
            FUNDO.COD_LOTACAO,
            FUNDO.NOME_LOTACAO
    ) FUNDO ON FUNDO.ORGAO = BRUTO.ORGAO
            AND FUNDO.MATRICULA = BRUTO.MATRICULA
            AND FUNDO.CPF = BRUTO.CPF
            AND FUNDO.ID_FUNCIONARIO = BRUTO.ID_FUNCIONARIO
            AND FUNDO.COD_LOTACAO = BRUTO.COD_LOTACAO
            AND FUNDO.NOME_LOTACAO = BRUTO.NOME_LOTACAO
    LEFT JOIN (
        SELECT
            PATRONAL.ORGAO,
            PATRONAL.ID_FUNCIONARIO,
            PATRONAL.MATRICULA,
            PATRONAL.CPF,
            PATRONAL.COD_LOTACAO,
            PATRONAL.NOME_LOTACAO,
            SUM(PATRONAL.VALOR_CALCULADO) VALOR_CALCULADO,
            CASE
                WHEN SUM(PATRONAL.VALOR_CALCULADO) = 0 THEN 'N'
                ELSE 'S'
            END IND_CONTRIBUICAO
        FROM
            TABELA_AUX PATRONAL
        WHERE
            PATRONAL.TIPO_RUBRICA = 'PATRONAL'
        GROUP BY
            PATRONAL.ORGAO,
            PATRONAL.ID_FUNCIONARIO,
            PATRONAL.MATRICULA,
            PATRONAL.CPF,
            PATRONAL.COD_LOTACAO,
            PATRONAL.NOME_LOTACAO
    ) PATRONAL ON PATRONAL.ORGAO = BRUTO.ORGAO
            AND PATRONAL.MATRICULA = BRUTO.MATRICULA
            AND PATRONAL.CPF = BRUTO.CPF
            AND PATRONAL.ID_FUNCIONARIO = BRUTO.ID_FUNCIONARIO
            AND PATRONAL.COD_LOTACAO = BRUTO.COD_LOTACAO
            AND PATRONAL.NOME_LOTACAO = BRUTO.NOME_LOTACAO
    LEFT JOIN (
        SELECT
            BASE.ORGAO,
            BASE.ID_FUNCIONARIO,
            BASE.MATRICULA,
            BASE.CPF,
            BASE.COD_LOTACAO,
            BASE.NOME_LOTACAO,
            SUM(BASE.VALOR_CALCULADO) VALOR_CALCULADO,
            CASE
                WHEN SUM(BASE.VALOR_CALCULADO) = 0 THEN 'N'
                ELSE 'S'
            END IND_CONTRIBUICAO
        FROM
            TABELA_AUX BASE
        WHERE
            BASE.TIPO_RUBRICA = 'BASE'
        GROUP BY
            BASE.ORGAO,
            BASE.ID_FUNCIONARIO,
            BASE.MATRICULA,
            BASE.CPF,
            BASE.COD_LOTACAO,
            BASE.NOME_LOTACAO
    ) BASE ON BASE.ORGAO = BRUTO.ORGAO
            AND BASE.MATRICULA = BRUTO.MATRICULA
            AND BASE.CPF = BRUTO.CPF
            AND BASE.ID_FUNCIONARIO = BRUTO.ID_FUNCIONARIO
            AND BASE.COD_LOTACAO = BRUTO.COD_LOTACAO
            AND BASE.NOME_LOTACAO = BRUTO.NOME_LOTACAO
GROUP BY
    BRUTO.ORGAO,
    BRUTO.COD_LOTACAO,
    BRUTO.NOME_LOTACAO,
    BASE.IND_CONTRIBUICAO,
    FUNDO.IND_CONTRIBUICAO,
    PATRONAL.IND_CONTRIBUICAO
ORDER BY
    BRUTO.ORGAO,
    BRUTO.COD_LOTACAO,
    BRUTO.NOME_LOTACAO;