-- RELATÓRIO POR FAIXA MENSAL
WITH TABELA_AUX AS (
    SELECT
        X.ORGAO,
        X.ID_FUNCIONARIO,
        X.ID_FOLHA_FUNCIONARIO,
        X.MATRICULA,
        X.CPF,
        X.COD_GRUPO,
        X.DESCRICAO_GRUPO,
        X.TIPO_RELATORIO,
        CASE
			WHEN X.COD_RUBRICA IN (714100, 714110) THEN 'BASE'
			WHEN X.COD_RUBRICA_LEGADO IN ('901') THEN 'FUNDO'
			WHEN X.COD_RUBRICA IN (714400, 714405, 714410, 714420) THEN 'PATRONAL'
			WHEN X.COD_RUBRICA IN (999997) THEN 'BRUTO'
		END TIPO_RUBRICA,
        X.VALOR_CALCULADO
    FROM
        (
        SELECT
            FF.ID_FOLHA_FUNCIONARIO,
            F.ID_FUNCIONARIO,
            REGEXP_REPLACE(PV.COD_INSTITUCIONAL, '[^0-9A-Za-z]', '') MATRICULA,
            PDC.CPF_PESSOA CPF,
            E.ORGAO_SIAFI ORGAO,
            R.COD_RUBRICA,
            R.COD_RUBRICA_LEGADO,
            FR.VALOR_CALCULADO,
            FO.MES,
            FO.ANO,
            FO.ID_TIPO_FOLHA,
            NVL(GRUP_REL.CODIGO, 'SEM GRUPO') COD_GRUPO,
            NVL(GRUP_REL.DESCRICAO, 'SEM GRUPO') DESCRICAO_GRUPO,
            GRUP_REL.TIPO_RELATORIO TIPO_RELATORIO
        FROM
            SW_PUBLICO.PESSOA P
            JOIN SW_PUBLICO.PESSOA_DOC_CPF PDC ON PDC.ID_PESSOA = P.ID_PESSOA AND PDC.DATA_BAIXA IS NULL
            JOIN SW_PUBLICO.EMPRESA E ON E.SIGLA = 'DEFENSORIA'
            JOIN SW_DEFENSORIA.PESSOA_VINCULO PV ON PV.ID_PESSOA = P.ID_PESSOA
            JOIN SW_DEFENSORIA.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
            JOIN SW_DEFENSORIA.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = F.ID_FUNCIONARIO
            JOIN SW_DEFENSORIA.FOLHA_FUNC FF ON FF.ID_FUNCIONARIO = F.ID_FUNCIONARIO
            LEFT JOIN SW_DEFENSORIA.RHB_LOTACAO LOT ON LOT.COD_LOTACAO = FF.COD_LOTACAO
            LEFT JOIN SW_DEFENSORIA.RHB_LOTACAO_GRUPO LOT_GRUP ON LOT_GRUP.ID_LOTACAO = LOT.ID_LOTACAO
            LEFT JOIN SW_DEFENSORIA.RHB_LOTA_GRUPO_RELATORIO GRUP_REL ON GRUP_REL.ID_LOTA_GRUPO_RELATORIO = COALESCE(LOT_GRUP.ID_LOTA_GRUPO_RELATORIO,(
                SELECT
                    X.ID_LOTA_GRUPO_RELATORIO
                FROM
                    SW_DEFENSORIA.RHB_LOTA_GRUPO_RELATORIO X
                WHERE
                    X.CODIGO = E.ORGAO_SIAFI
            ))
            JOIN SW_DEFENSORIA.FOLHA FO ON FO.ID_FOLHA = FF.ID_FOLHA
            JOIN SW_DEFENSORIA.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
            JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA
        WHERE
            FO.ID_TIPO_FOLHA = 1000000
            AND FO.MES = 6
            AND FO.ANO = 2026
            AND (
                R.COD_RUBRICA IN (714100, 714110)
                OR R.COD_RUBRICA_LEGADO IN ('901')
                OR R.COD_RUBRICA IN (714400, 714405, 714410, 714420)
                OR R.COD_RUBRICA IN (999997)
            )
        ) X
)
SELECT
    BRUTO.ORGAO "CODIGO EMPRESA",
    COUNT(DISTINCT BRUTO.MATRICULA) "CONTRACHEQUES",
    COUNT(DISTINCT BRUTO.CPF) "CPFs",
    BRUTO.COD_GRUPO "CODIGO GRUPO",
    BRUTO.DESCRICAO_GRUPO "GRUPO",
    CASE BRUTO.TIPO_RELATORIO
        WHEN 'E' THEN 'EXECUTIVO'
        ELSE 'OUTROS PODERES'
    END "TIPO DE RELATORIO",
    NVL(BASE.FAIXA, 1) "FAIXA",
    NVL(SUM(BASE.VALOR_CALCULADO), 0) "VALOR BASE",
    NVL(SUM(FUNDO.VALOR_CALCULADO), 0) "VALOR FUNDO",
    NVL(SUM(PATRONAL.VALOR_CALCULADO), 0) "PATRONAL",
    NVL(SUM(FUNDO.VALOR_CALCULADO), 0) + NVL(SUM(PATRONAL.VALOR_CALCULADO), 0) "REPASSE",
    NVL(SUM(BRUTO.VALOR_CALCULADO), 0) "VALOR BRUTO"
FROM
    (
    SELECT
        BRUTO.ORGAO,
        BRUTO.ID_FUNCIONARIO,
        BRUTO.MATRICULA,
        BRUTO.CPF,
        BRUTO.COD_GRUPO,
        BRUTO.DESCRICAO_GRUPO,
        BRUTO.TIPO_RELATORIO,
        SUM(BRUTO.VALOR_CALCULADO) VALOR_CALCULADO
    FROM
        TABELA_AUX BRUTO
    WHERE
        BRUTO.TIPO_RUBRICA = 'BRUTO'
    GROUP BY
        BRUTO.ORGAO,
        BRUTO.ID_FUNCIONARIO,
        BRUTO.MATRICULA,
        BRUTO.CPF,
        BRUTO.COD_GRUPO,
        BRUTO.DESCRICAO_GRUPO,
        BRUTO.TIPO_RELATORIO
    ) BRUTO
    LEFT JOIN (
        SELECT
            FUNDO.ORGAO,
            FUNDO.ID_FUNCIONARIO,
            FUNDO.MATRICULA,
            FUNDO.CPF,
            FUNDO.COD_GRUPO,
            FUNDO.DESCRICAO_GRUPO,
            FUNDO.TIPO_RELATORIO,
            SUM(FUNDO.VALOR_CALCULADO) VALOR_CALCULADO,
            CASE
                WHEN SUM(FUNDO.VALOR_CALCULADO) = 0 THEN 'N'
                ELSE 'S'
            END IND_CONTRIBUICAO
        FROM
            TABELA_AUX FUNDO
        WHERE
            FUNDO.TIPO_RUBRICA = 'FUNDO'
        GROUP BY
            FUNDO.ORGAO,
            FUNDO.ID_FUNCIONARIO,
            FUNDO.MATRICULA,
            FUNDO.CPF,
            FUNDO.COD_GRUPO,
            FUNDO.DESCRICAO_GRUPO,
            FUNDO.TIPO_RELATORIO
    ) FUNDO ON FUNDO.ORGAO = BRUTO.ORGAO
            AND FUNDO.MATRICULA = BRUTO.MATRICULA
            AND FUNDO.CPF = BRUTO.CPF
            AND FUNDO.ID_FUNCIONARIO = BRUTO.ID_FUNCIONARIO
            AND FUNDO.COD_GRUPO = BRUTO.COD_GRUPO
    LEFT JOIN (
        SELECT
            PATRONAL.ORGAO,
            PATRONAL.ID_FUNCIONARIO,
            PATRONAL.MATRICULA,
            PATRONAL.CPF,
            PATRONAL.COD_GRUPO,
            PATRONAL.DESCRICAO_GRUPO,
            PATRONAL.TIPO_RELATORIO,
            SUM(PATRONAL.VALOR_CALCULADO) VALOR_CALCULADO,
            CASE
                WHEN SUM(PATRONAL.VALOR_CALCULADO) = 0 THEN 'N'
                ELSE 'S'
            END IND_CONTRIBUICAO
        FROM
            TABELA_AUX PATRONAL
        WHERE
            PATRONAL.TIPO_RUBRICA = 'PATRONAL'
        GROUP BY
            PATRONAL.ORGAO,
            PATRONAL.ID_FUNCIONARIO,
            PATRONAL.MATRICULA,
            PATRONAL.CPF,
            PATRONAL.COD_GRUPO,
            PATRONAL.DESCRICAO_GRUPO,
            PATRONAL.TIPO_RELATORIO
    ) PATRONAL ON PATRONAL.ORGAO = BRUTO.ORGAO
            AND PATRONAL.MATRICULA = BRUTO.MATRICULA
            AND PATRONAL.CPF = BRUTO.CPF
            AND PATRONAL.ID_FUNCIONARIO = BRUTO.ID_FUNCIONARIO
            AND PATRONAL.COD_GRUPO = BRUTO.COD_GRUPO
    LEFT JOIN (
        SELECT
            BASE.ORGAO,
            BASE.ID_FUNCIONARIO,
            BASE.MATRICULA,
            BASE.CPF,
            BASE.COD_GRUPO,
            BASE.DESCRICAO_GRUPO,
            BASE.TIPO_RELATORIO,
            SUM(BASE.VALOR_CALCULADO) VALOR_CALCULADO,
            CASE
                WHEN SUM(BASE.VALOR_CALCULADO) = 0 THEN 'N'
                ELSE 'S'
            END IND_CONTRIBUICAO,
            CASE
                WHEN SUM(BASE.VALOR_CALCULADO) BETWEEN VT1.VALOR_INICIAL AND VT1.VALOR_FINAL THEN 1
                WHEN SUM(BASE.VALOR_CALCULADO) BETWEEN VT2.VALOR_INICIAL AND VT2.VALOR_FINAL THEN 2
                WHEN SUM(BASE.VALOR_CALCULADO) BETWEEN VT3.VALOR_INICIAL AND VT3.VALOR_FINAL THEN 3
                WHEN SUM(BASE.VALOR_CALCULADO) BETWEEN VT4.VALOR_INICIAL AND VT4.VALOR_FINAL THEN 4
                ELSE - 1
            END FAIXA
        FROM
            TABELA_AUX BASE
            JOIN SW_DEFENSORIA.FOLHA FO ON SUBSTR(FO.CHAVE_FOLHA, 9) = 100 AND FO.MES = 1 AND FO.ANO = 2026
            JOIN SW_DEFENSORIA.FOLHA_VALOR_TABELA VT1 ON VT1.ID_FOLHA = FO.ID_FOLHA AND VT1.ID_TABELA = 1000280 AND VT1.FAIXA = 1
            JOIN SW_DEFENSORIA.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO.ID_FOLHA AND VT2.ID_TABELA = 1000280 AND VT2.FAIXA = 2
            JOIN SW_DEFENSORIA.FOLHA_VALOR_TABELA VT3 ON VT3.ID_FOLHA = FO.ID_FOLHA AND VT3.ID_TABELA = 1000280 AND VT3.FAIXA = 3
            JOIN SW_DEFENSORIA.FOLHA_VALOR_TABELA VT4 ON VT4.ID_FOLHA = FO.ID_FOLHA AND VT4.ID_TABELA = 1000280 AND VT4.FAIXA = 4
        WHERE
            BASE.TIPO_RUBRICA = 'BASE'
        GROUP BY
            BASE.ORGAO,
            BASE.ID_FUNCIONARIO,
            BASE.MATRICULA,
            BASE.CPF,
            BASE.COD_GRUPO,
            BASE.DESCRICAO_GRUPO,
            BASE.TIPO_RELATORIO,
            VT1.VALOR_INICIAL,
            VT1.VALOR_FINAL,
            VT2.VALOR_INICIAL,
            VT2.VALOR_FINAL,
            VT3.VALOR_INICIAL,
            VT3.VALOR_FINAL,
            VT4.VALOR_INICIAL,
            VT4.VALOR_FINAL
    ) BASE ON BASE.ORGAO = BRUTO.ORGAO
            AND BASE.MATRICULA = BRUTO.MATRICULA
            AND BASE.CPF = BRUTO.CPF
            AND BASE.ID_FUNCIONARIO = BRUTO.ID_FUNCIONARIO
            AND BASE.COD_GRUPO = BRUTO.COD_GRUPO
GROUP BY
    BRUTO.ORGAO,
    BRUTO.COD_GRUPO,
    BRUTO.DESCRICAO_GRUPO,
    BRUTO.TIPO_RELATORIO,
    NVL(BASE.FAIXA, 1),
    BASE.IND_CONTRIBUICAO,
    FUNDO.IND_CONTRIBUICAO,
    PATRONAL.IND_CONTRIBUICAO
ORDER BY
    BRUTO.ORGAO,
    BRUTO.COD_GRUPO,
    BRUTO.DESCRICAO_GRUPO,
    BRUTO.TIPO_RELATORIO,
    NVL(BASE.FAIXA, 1);