DELETE FROM SP_OPERACAO.CONSULTAS_CPF WHERE ID_CONSULTA_CPF IN (
SELECT DISTINCT
    CC.ID_CONSULTA_CPF
FROM
    SP_OPERACAO.CONSULTAS_CPF CC
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PDC ON PDC.CPF_PESSOA = CC.CPF_COMPLETO AND PDC.DATA_BAIXA IS NULL
    JOIN SW_PUBLICO.PESSOA_CERTIDAO_OBITO CO ON CO.ID_PESSOA = PDC.ID_PESSOA
);