SELECT DISTINCT
    CC.*
FROM
    SW_FUNPREV.FOLHA FO
    JOIN SW_FUNPREV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PDC ON PDC.ID_PESSOA = NVL(FF.ID_PESSOA_DEPENDENTE, FF.ID_PESSOA_FUNCIONARIO) AND PDC.DATA_BAIXA IS NULL
    JOIN SP_OPERACAO.CONSULTAS_CPF CC ON CC.CPF_COMPLETO = PDC.CPF_PESSOA
    LEFT JOIN SW_PUBLICO.PESSOA_CERTIDAO_OBITO CO ON CO.ID_PESSOA = NVL(FF.ID_PESSOA_DEPENDENTE, FF.ID_PESSOA_FUNCIONARIO)
WHERE
    FO.MES = 10
    AND FO.ANO = 2026
    AND FO.ID_TIPO_FOLHA = 1000000
    AND FF.IND_REMUNERACAO = 'S'
    AND CO.ID_CERTIDAO_OBITO IS NULL
ORDER BY
    CC.ID_CONSULTA_CPF