SELECT
    CC.CHAVE_FOLHA,
    LISTAGG(FO.CHAVE_FOLHA, ' ; ') WITHIN GROUP (ORDER BY FO.CHAVE_FOLHA) CHAVE_FOLHA,
    REPLACE(REPLACE(PDC.CPF_PESSOA, '.', ''), '-', '') CPF,
    PDC.CPF_PESSOA CPF_COMPLETO,
    HN.NOME,
    LISTAGG(NVL(FF.MATR_DEPENDENTE, FF.COD_INSTITUCIONAL), ' ; ') WITHIN GROUP (ORDER BY NVL(FF.MATR_DEPENDENTE, FF.COD_INSTITUCIONAL)) MATRICULAS,
    'UPDATE SP_OPERACAO.CONSULTAS_CPF SET CHAVE_FOLHA = ''' || LISTAGG(FO.CHAVE_FOLHA, ' ; ') WITHIN GROUP (ORDER BY FO.CHAVE_FOLHA) || ''', MATRICULAS = ''' || LISTAGG(NVL(FF.MATR_DEPENDENTE, FF.COD_INSTITUCIONAL), ' ; ') WITHIN GROUP (ORDER BY NVL(FF.MATR_DEPENDENTE, FF.COD_INSTITUCIONAL)) || ''' WHERE ID_CONSULTA_CPF = ' || CC.ID_CONSULTA_CPF || ';' UPDATE_
FROM
    SW_FUNPREV.FOLHA FO
    JOIN SW_FUNPREV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PDC ON PDC.ID_PESSOA = NVL(FF.ID_PESSOA_DEPENDENTE, FF.ID_PESSOA_FUNCIONARIO) AND PDC.DATA_BAIXA IS NULL
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = NVL(FF.ID_PESSOA_DEPENDENTE, FF.ID_PESSOA_FUNCIONARIO) AND HN.DATA_FIM IS NULL
    JOIN SP_OPERACAO.CONSULTAS_CPF CC ON CC.CPF_COMPLETO = PDC.CPF_PESSOA
WHERE
    FO.MES = 10
    AND FO.ANO = 2026
    AND FO.ID_TIPO_FOLHA = 1000000
    AND FF.IND_REMUNERACAO = 'S'
GROUP BY
    CC.CHAVE_FOLHA,
    PDC.CPF_PESSOA,
    HN.NOME,
    CC.ID_CONSULTA_CPF