SELECT 
    'ADAPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_ADAPI.FOLHA_CONTRACHEQUE FC
    JOIN SW_ADAPI.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_ADAPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_ADAPI.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'ADH' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_ADH.FOLHA_CONTRACHEQUE FC
    JOIN SW_ADH.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_ADH.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_ADH.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'AGESPISA' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_AGESPISA.FOLHA_CONTRACHEQUE FC
    JOIN SW_AGESPISA.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_AGESPISA.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_AGESPISA.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'AGESPISA02' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_AGESPISA02.FOLHA_CONTRACHEQUE FC
    JOIN SW_AGESPISA02.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_AGESPISA02.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_AGESPISA02.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'AGRESP' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_AGRESP.FOLHA_CONTRACHEQUE FC
    JOIN SW_AGRESP.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_AGRESP.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_AGRESP.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'BEP' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_BEP.FOLHA_CONTRACHEQUE FC
    JOIN SW_BEP.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_BEP.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_BEP.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'CBMPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_CBMPI.FOLHA_CONTRACHEQUE FC
    JOIN SW_CBMPI.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_CBMPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_CBMPI.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'CCOM' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_CCOM.FOLHA_CONTRACHEQUE FC
    JOIN SW_CCOM.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_CCOM.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_CCOM.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'CDTER' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_CDTER.FOLHA_CONTRACHEQUE FC
    JOIN SW_CDTER.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_CDTER.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_CDTER.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'CENDROGAS' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_CENDROGAS.FOLHA_CONTRACHEQUE FC
    JOIN SW_CENDROGAS.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_CENDROGAS.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_CENDROGAS.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'COFIR' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_COFIR.FOLHA_CONTRACHEQUE FC
    JOIN SW_COFIR.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_COFIR.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_COFIR.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'COJUV' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_COJUV.FOLHA_CONTRACHEQUE FC
    JOIN SW_COJUV.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_COJUV.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_COJUV.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'DEFCIVIL' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_DEFCIVIL.FOLHA_CONTRACHEQUE FC
    JOIN SW_DEFCIVIL.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_DEFCIVIL.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_DEFCIVIL.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'DER' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_DER.FOLHA_CONTRACHEQUE FC
    JOIN SW_DER.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_DER.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_DER.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'DETRAN' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_DETRAN.FOLHA_CONTRACHEQUE FC
    JOIN SW_DETRAN.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_DETRAN.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_DETRAN.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'EMGERPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_EMGERPI.FOLHA_CONTRACHEQUE FC
    JOIN SW_EMGERPI.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_EMGERPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_EMGERPI.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'EMGERPI_CEASA' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_EMGERPI_CEASA.FOLHA_CONTRACHEQUE FC
    JOIN SW_EMGERPI_CEASA.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_EMGERPI_CEASA.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_EMGERPI_CEASA.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'EMGERPI_CIDAPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_EMGERPI_CIDAPI.FOLHA_CONTRACHEQUE FC
    JOIN SW_EMGERPI_CIDAPI.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_EMGERPI_CIDAPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_EMGERPI_CIDAPI.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'EMGERPI_CODIPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_EMGERPI_CODIPI.FOLHA_CONTRACHEQUE FC
    JOIN SW_EMGERPI_CODIPI.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_EMGERPI_CODIPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_EMGERPI_CODIPI.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'EMGERPI_COHAB' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_EMGERPI_COHAB.FOLHA_CONTRACHEQUE FC
    JOIN SW_EMGERPI_COHAB.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_EMGERPI_COHAB.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_EMGERPI_COHAB.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'EMGERPI_COMDEPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_EMGERPI_COMDEPI.FOLHA_CONTRACHEQUE FC
    JOIN SW_EMGERPI_COMDEPI.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_EMGERPI_COMDEPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_EMGERPI_COMDEPI.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'EMGERPI_COMEPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_EMGERPI_COMEPI.FOLHA_CONTRACHEQUE FC
    JOIN SW_EMGERPI_COMEPI.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_EMGERPI_COMEPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_EMGERPI_COMEPI.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'EMGERPI_CORESA' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_EMGERPI_CORESA.FOLHA_CONTRACHEQUE FC
    JOIN SW_EMGERPI_CORESA.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_EMGERPI_CORESA.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_EMGERPI_CORESA.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'EMGERPI_EMATER' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_EMGERPI_EMATER.FOLHA_CONTRACHEQUE FC
    JOIN SW_EMGERPI_EMATER.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_EMGERPI_EMATER.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_EMGERPI_EMATER.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'EMGERPI_ETELPI_FUNART' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_EMGERPI_ETELPI_FUNART.FOLHA_CONTRACHEQUE FC
    JOIN SW_EMGERPI_ETELPI_FUNART.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_EMGERPI_ETELPI_FUNART.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_EMGERPI_ETELPI_FUNART.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'EMGERPI_PIEMTUR' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_EMGERPI_PIEMTUR.FOLHA_CONTRACHEQUE FC
    JOIN SW_EMGERPI_PIEMTUR.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_EMGERPI_PIEMTUR.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_EMGERPI_PIEMTUR.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'EMGERPI_PRODEPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_EMGERPI_PRODEPI.FOLHA_CONTRACHEQUE FC
    JOIN SW_EMGERPI_PRODEPI.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_EMGERPI_PRODEPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_EMGERPI_PRODEPI.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'FAPEPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_FAPEPI.FOLHA_CONTRACHEQUE FC
    JOIN SW_FAPEPI.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_FAPEPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_FAPEPI.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'FESPPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_FESPPI.FOLHA_CONTRACHEQUE FC
    JOIN SW_FESPPI.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_FESPPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_FESPPI.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'FUESPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_FUESPI.FOLHA_CONTRACHEQUE FC
    JOIN SW_FUESPI.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_FUESPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_FUESPI.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'FUNPREV' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_FUNPREV.FOLHA_CONTRACHEQUE FC
    JOIN SW_FUNPREV.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_FUNPREV.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_FUNPREV.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'FUPIP' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_FUPIP.FOLHA_CONTRACHEQUE FC
    JOIN SW_FUPIP.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_FUPIP.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_FUPIP.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'GMG' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_GMG.FOLHA_CONTRACHEQUE FC
    JOIN SW_GMG.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_GMG.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_GMG.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'IASPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_IASPI.FOLHA_CONTRACHEQUE FC
    JOIN SW_IASPI.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_IASPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_IASPI.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'IDEPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_IDEPI.FOLHA_CONTRACHEQUE FC
    JOIN SW_IDEPI.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_IDEPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_IDEPI.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'IMEPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_IMEPI.FOLHA_CONTRACHEQUE FC
    JOIN SW_IMEPI.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_IMEPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_IMEPI.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'IMEPIPROD' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_IMEPIPROD.FOLHA_CONTRACHEQUE FC
    JOIN SW_IMEPIPROD.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_IMEPIPROD.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_IMEPIPROD.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'INTERPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_INTERPI.FOLHA_CONTRACHEQUE FC
    JOIN SW_INTERPI.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_INTERPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_INTERPI.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'JUCEPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_JUCEPI.FOLHA_CONTRACHEQUE FC
    JOIN SW_JUCEPI.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_JUCEPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_JUCEPI.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'METRO' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_METRO.FOLHA_CONTRACHEQUE FC
    JOIN SW_METRO.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_METRO.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_METRO.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'PGEPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_PGEPI.FOLHA_CONTRACHEQUE FC
    JOIN SW_PGEPI.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_PGEPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PGEPI.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'PMPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_PMPI.FOLHA_CONTRACHEQUE FC
    JOIN SW_PMPI.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_PMPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PMPI.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SADA' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_SADA.FOLHA_CONTRACHEQUE FC
    JOIN SW_SADA.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_SADA.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_SADA.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SAF' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_SAF.FOLHA_CONTRACHEQUE FC
    JOIN SW_SAF.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_SAF.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_SAF.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SASC' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_SASC.FOLHA_CONTRACHEQUE FC
    JOIN SW_SASC.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_SASC.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_SASC.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SEADPREVPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_SEADPREVPI.FOLHA_CONTRACHEQUE FC
    JOIN SW_SEADPREVPI.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_SEADPREVPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEADPREVPI.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SEAGRO' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_SEAGRO.FOLHA_CONTRACHEQUE FC
    JOIN SW_SEAGRO.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_SEAGRO.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEAGRO.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SECESP' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_SECESP.FOLHA_CONTRACHEQUE FC
    JOIN SW_SECESP.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_SECESP.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_SECESP.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SECID' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_SECID.FOLHA_CONTRACHEQUE FC
    JOIN SW_SECID.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_SECID.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_SECID.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SECMULHERES' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_SECMULHERES.FOLHA_CONTRACHEQUE FC
    JOIN SW_SECMULHERES.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_SECMULHERES.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_SECMULHERES.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SECULT' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_SECULT.FOLHA_CONTRACHEQUE FC
    JOIN SW_SECULT.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_SECULT.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_SECULT.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SEDET' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_SEDET.FOLHA_CONTRACHEQUE FC
    JOIN SW_SEDET.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_SEDET.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEDET.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SEDUC' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_SEDUC.FOLHA_CONTRACHEQUE FC
    JOIN SW_SEDUC.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_SEDUC.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEDUC.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SEFAZPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_SEFAZPI.FOLHA_CONTRACHEQUE FC
    JOIN SW_SEFAZPI.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_SEFAZPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEFAZPI.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SEGOV' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_SEGOV.FOLHA_CONTRACHEQUE FC
    JOIN SW_SEGOV.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_SEGOV.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEGOV.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SEID' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_SEID.FOLHA_CONTRACHEQUE FC
    JOIN SW_SEID.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_SEID.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEID.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SEINFRA' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_SEINFRA.FOLHA_CONTRACHEQUE FC
    JOIN SW_SEINFRA.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_SEINFRA.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEINFRA.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SEJUSPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_SEJUSPI.FOLHA_CONTRACHEQUE FC
    JOIN SW_SEJUSPI.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_SEJUSPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEJUSPI.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SEMAR' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_SEMAR.FOLHA_CONTRACHEQUE FC
    JOIN SW_SEMAR.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_SEMAR.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEMAR.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SEMINPER' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_SEMINPER.FOLHA_CONTRACHEQUE FC
    JOIN SW_SEMINPER.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_SEMINPER.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEMINPER.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SEPLAN' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_SEPLAN.FOLHA_CONTRACHEQUE FC
    JOIN SW_SEPLAN.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_SEPLAN.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEPLAN.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SERES' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_SERES.FOLHA_CONTRACHEQUE FC
    JOIN SW_SERES.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_SERES.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_SERES.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SESAPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_SESAPI.FOLHA_CONTRACHEQUE FC
    JOIN SW_SESAPI.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_SESAPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_SESAPI.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SETRANS' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_SETRANS.FOLHA_CONTRACHEQUE FC
    JOIN SW_SETRANS.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_SETRANS.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_SETRANS.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SETRE' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_SETRE.FOLHA_CONTRACHEQUE FC
    JOIN SW_SETRE.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_SETRE.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_SETRE.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SETUR' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_SETUR.FOLHA_CONTRACHEQUE FC
    JOIN SW_SETUR.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_SETUR.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_SETUR.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SIA' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_SIA.FOLHA_CONTRACHEQUE FC
    JOIN SW_SIA.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_SIA.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_SIA.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SSPPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_SSPPI.FOLHA_CONTRACHEQUE FC
    JOIN SW_SSPPI.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_SSPPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_SSPPI.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'SURPI' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_SURPI.FOLHA_CONTRACHEQUE FC
    JOIN SW_SURPI.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_SURPI.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_SURPI.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'TVANTARES' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_TVANTARES.FOLHA_CONTRACHEQUE FC
    JOIN SW_TVANTARES.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_TVANTARES.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_TVANTARES.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026

UNION ALL

SELECT 
    'VICEGOV' ORGAO,
    FO.CHAVE_FOLHA,
    HN.NOME,
    FC.COD_INSTITUCIONAL MATRICULA,
    R.NOME_RUBRICA RUBRICA,
    FR.VALOR_CALCULADO VALOR_RUBRICA_119100,
    R2.NOME_RUBRICA RUBRICA,
    FR2.VALOR_CALCULADO VALOR_RUBRICA_620205
FROM
    SW_VICEGOV.FOLHA_CONTRACHEQUE FC
    JOIN SW_VICEGOV.FOLHA FO ON FO.ID_FOLHA = FC.ID_FOLHA
    JOIN SW_VICEGOV.FOLHA_FUNC_RUBRICA FR ON FR.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_VICEGOV.FOLHA_FUNC_RUBRICA FR2 ON FR2.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FR.ID_RUBRICA AND R.COD_RUBRICA = 119100
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.ID_RUBRICA = FR2.ID_RUBRICA AND R2.COD_RUBRICA = 620205
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FC.ID_PESSOA AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 7
    AND FO.ANO = 2026