SELECT 
    'SEADPREVPI' ORGAO,
    PC.CPF_PESSOA,
    HN.NOME,
    P.ID_PESSOA,
    'DELETE FROM SW_PUBLICO.PESSOA_ENDERECO WHERE ID_PESSOA = ' ||P.ID_PESSOA || ';' UPDATE_1,
    'DELETE FROM SW_PUBLICO.PESSOA_CARACTERISTICA_FISICA WHERE ID_PESSOA = ' ||P.ID_PESSOA || ';' UPDATE_2,
    'DELETE FROM SW_PUBLICO.PESSOA_ESTADO_CIVIL WHERE ID_PESSOA = ' ||P.ID_PESSOA || ';' UPDATE_3,
    'DELETE FROM SW_PUBLICO.PESSOA_DOC_CPF WHERE ID_PESSOA = ' ||P.ID_PESSOA || ';' UPDATE_4,
    'DELETE FROM SW_PUBLICO.PESSOA_HISTORICO_NOMES WHERE ID_PESSOA = ' ||P.ID_PESSOA || ';' UPDATE_5,
    'DELETE FROM SW_PUBLICO.PESSOA WHERE ID_PESSOA = ' ||P.ID_PESSOA || ';' UPDATE_6
FROM 
    SW_PUBLICO.PESSOA P 
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = P.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = P.ID_PESSOA
WHERE 
    --PC.CPF_PESSOA = '075.035.953-61'
    P.ID_PESSOA = 1445955;
