CLEAR SCREEN;

DECLARE
    MES                       VARCHAR2(7) := 9;
    ANO                       VARCHAR2(7) := 2026;
    QRY                       VARCHAR2(32767);
    QRY_DIV                   VARCHAR2(32767);
    IDS_DIVISAO_DESCONSIDERAR VARCHAR2(32767);
    TIPOS_FOLHA               VARCHAR2(100) := '1000000';
BEGIN
    DBMS_OUTPUT.ENABLE(BUFFER_SIZE => NULL);
    QRY_DIV := 'SELECT VALOR FROM SW_PUBLICO.CONFIG_SISTEMA WHERE NOME = ''IDS_DIVISAO_DESCONSIDERAR''';
    EXECUTE IMMEDIATE QRY_DIV
    INTO IDS_DIVISAO_DESCONSIDERAR;
    
--    qry := 'SELECT A.COD_INSTITUCIONAL, A.ORGAO_ORIGEM, A.QNTD_CONSIGNACOES, A.ID_FUNCIONARIO_ORIGEM, B.ORGAO_PAGAMENTO, B.QNTD_CONSIG_LANCADAS, B.ID_FUNCIONARIO_PAGAMENTO, A.QNTD_CONSIGNACOES - B.QNTD_CONSIG_LANCADAS AS DIFERENCA, ''SELECT '''''' || SUBSTR( B.ORGAO_PAGAMENTO , 4) || '''''' AS ORGAO, PV.COD_INSTITUCIONAL, R.COD_RUBRICA, R.NOME_RUBRICA, C.VALOR FROM SW_PUBLICO.FOLHA_RUBRICA R JOIN '' || A.ORGAO_ORIGEM || ''.FUNCIONARIO F ON F.ID_FUNCIONARIO = '' || A.ID_FUNCIONARIO_ORIGEM || '' JOIN '' || A.ORGAO_ORIGEM || ''.PESSOA_VINCULO PV ON PV.ID_PESSOA_VINCULO = F.ID_PESSOA_VINCULO JOIN ( SELECT '' || B.ID_FUNCIONARIO_PAGAMENTO || '' AS ID_FUNCIONARIO, ID_CONSIGNATARIO, ID_RUBRICA, DATA_INICIO, DATA_INICIO, DATA_FIM, DATA_CANCELAMENTO, VALOR, IND_PARAMETRO, ORDEM, OBSERVACAO, COD_CHAVE, IND_BASE, CODIGO_SISTEMA, REMESSA_ARQUIVO, CODIGO_LANCAMENTO, NOME_SERVIDOR, QTD_REGISTROS, TOTAL_LANCAMENTOS, TIPO_REGISTRO, CONTRATO, PRESTACAO, PRIORIDADE, FINANCEIRO_1, ORGAO, QUANTIDADE_PARCELAS, PARCELA_ATUAL, SISTEMA, FINANCEIRO_2, INFORMACAO_RESERVADA, ORGAO_ANTERIOR, FINANCEIRO_ANTERIOR, DATA_PROCESSAMENTO, STATUS_PROCESSAMENTO, NOME_ARQUIVO FROM '' || A.ORGAO_ORIGEM || ''.FOLHA_CONSIG_CONSIGNADO WHERE ID_FUNCIONARIO = '' || A.ID_FUNCIONARIO_ORIGEM || '' AND EXTRACT(MONTH FROM DATA_INICIO) = '' || ' || mes || ' || '' AND EXTRACT(YEAR FROM DATA_INICIO) = '' || ' || ano || ' || '' ) C ON C.ID_RUBRICA = R.ID_RUBRICA UNION ALL '' AS QUERY FROM (';                                                                                                                                       
    DBMS_OUTPUT.PUT_LINE('SELECT A.COD_INSTITUCIONAL, A.ORGAO_ORIGEM, A.QNTD_CONSIGNACOES, A.ID_FUNCIONARIO_ORIGEM, B.ORGAO_PAGAMENTO, B.QNTD_CONSIG_LANCADAS, B.ID_FUNCIONARIO_PAGAMENTO, A.QNTD_CONSIGNACOES - B.QNTD_CONSIG_LANCADAS AS DIFERENCA, ''INSERT INTO '' || B.ORGAO_PAGAMENTO || ''.FOLHA_CONSIG_CONSIGNADO (ID_FUNCIONARIO, ID_PENSIONISTA, ID_CONSIGNATARIO, ID_RUBRICA, DATA_CADASTRO, DATA_INICIO, DATA_FIM, DATA_CANCELAMENTO, VALOR, IND_PARAMETRO, ORDEM, OBSERVACAO, COD_CHAVE, IND_BASE, CODIGO_SISTEMA, REMESSA_ARQUIVO, CODIGO_LANCAMENTO, NOME_SERVIDOR, QTD_REGISTROS, TOTAL_LANCAMENTOS, TIPO_REGISTRO, CONTRATO, PRESTACAO, PRIORIDADE, FINANCEIRO_1, ORGAO, QUANTIDADE_PARCELAS, PARCELA_ATUAL, SISTEMA, FINANCEIRO_2, INFORMACAO_RESERVADA, ORGAO_ANTERIOR, FINANCEIRO_ANTERIOR, DATA_PROCESSAMENTO, STATUS_PROCESSAMENTO, NOME_ARQUIVO) SELECT '' || B.ID_FUNCIONARIO_PAGAMENTO || '' AS ID_FUNCIONARIO, '' || B.ID_PENSIONISTA ||'' AS ID_PENSIONISTA, ID_CONSIGNATARIO, ID_RUBRICA, DATA_CADASTRO, DATA_INICIO, DATA_FIM, DATA_CANCELAMENTO, VALOR, IND_PARAMETRO, ORDEM, OBSERVACAO, COD_CHAVE, IND_BASE, CODIGO_SISTEMA, REMESSA_ARQUIVO, CODIGO_LANCAMENTO, NOME_SERVIDOR, QTD_REGISTROS, TOTAL_LANCAMENTOS, TIPO_REGISTRO, CONTRATO, PRESTACAO, PRIORIDADE, FINANCEIRO_1, ORGAO, QUANTIDADE_PARCELAS, PARCELA_ATUAL, SISTEMA, FINANCEIRO_2, INFORMACAO_RESERVADA, ORGAO_ANTERIOR, FINANCEIRO_ANTERIOR, DATA_PROCESSAMENTO, STATUS_PROCESSAMENTO, NOME_ARQUIVO FROM '' || A.ORGAO_ORIGEM || ''.FOLHA_CONSIG_CONSIGNADO WHERE ID_FUNCIONARIO = '' || A.ID_FUNCIONARIO_ORIGEM || '' AND EXTRACT(MONTH FROM DATA_INICIO) = '' || '
                         || MES
                         || ' || '' AND EXTRACT(YEAR FROM DATA_INICIO) = '' || '
                         || ANO
                         || ' AS QUERY_1, CASE WHEN B.RUBRICAS IS NULL THEN '';'' ELSE  '' AND ID_RUBRICA NOT IN ('' || B.RUBRICAS || '') ;'' END AS QUERY_2 FROM ('
                         );

    DBMS_OUTPUT.PUT_LINE('SELECT Q.COD_INSTITUCIONAL, Q.ORGAO AS ORGAO_ORIGEM, Q.ID_FUNCIONARIO AS ID_FUNCIONARIO_ORIGEM, Q.ID_PESSOA, COUNT(Q.ID_CONSIGNADO) AS QNTD_CONSIGNACOES FROM ('
    );
    FOR R IN (
        SELECT
            'SW_' || SIGLA AS ESQUEMA
        FROM
            SW_PUBLICO.EMPRESA
        WHERE
            DATA_EXTINCAO IS NULL
            AND SIGLA NOT IN ('REENVIO','SEDUC_PRECATORIO')
    ) LOOP
        IF QRY IS NOT NULL THEN
            DBMS_OUTPUT.PUT_LINE(' UNION ALL ');
        END IF;
        QRY := 'SELECT '''
               || R.ESQUEMA
               || ''' AS ORGAO, PV.COD_INSTITUCIONAL, F.ID_FUNCIONARIO, FC.ID_CONSIGNADO, FC.DATA_INICIO, PV.ID_VINCULO, PV.ID_PESSOA FROM '
               || R.ESQUEMA
               || '.FOLHA_CONSIG_CONSIGNADO FC JOIN '
               || R.ESQUEMA
               || '.FUNCIONARIO F ON F.ID_FUNCIONARIO = FC.ID_FUNCIONARIO JOIN '
               || R.ESQUEMA
               || '.PESSOA_VINCULO PV ON PV.ID_PESSOA_VINCULO = F.ID_PESSOA_VINCULO';

        DBMS_OUTPUT.PUT_LINE(QRY);
    END LOOP;

    DBMS_OUTPUT.PUT_LINE(') Q WHERE EXTRACT(MONTH FROM Q.DATA_INICIO) = '
                         || MES
                         || ' AND EXTRACT(YEAR FROM Q.DATA_INICIO) = '
                         || ANO
                         || ' AND Q.ID_VINCULO = 2 GROUP BY Q.ORGAO, Q.COD_INSTITUCIONAL, Q.ID_FUNCIONARIO, Q.ID_PESSOA');

    DBMS_OUTPUT.PUT_LINE(') A LEFT JOIN (');
    DBMS_OUTPUT.PUT_LINE('SELECT Q.COD_INSTITUCIONAL, Q.ORGAO AS ORGAO_PAGAMENTO, Q.ID_FUNCIONARIO AS ID_FUNCIONARIO_PAGAMENTO, Q.ID_PENSIONISTA, Q.ID_PESSOA, COUNT(Q.ID_CONSIGNADO) AS QNTD_CONSIG_LANCADAS, LISTAGG(Q.ID_RUBRICA,'', '') WITHIN GROUP ( ORDER BY Q.ID_RUBRICA ) RUBRICAS FROM ('
    );
    QRY := NULL;
    FOR R IN (
        SELECT
            'SW_' || SIGLA AS ESQUEMA
        FROM
            SW_PUBLICO.EMPRESA
        WHERE
            DATA_EXTINCAO IS NULL
    ) LOOP
        IF QRY IS NOT NULL THEN
            DBMS_OUTPUT.PUT_LINE(' UNION ALL ');
        END IF;
        QRY := 'SELECT DISTINCT '''
               || R.ESQUEMA
               || ''' AS ORGAO, CASE WHEN FF.ID_PENSIONISTA IS NULL THEN FF.COD_INSTITUCIONAL ELSE FF.MATR_DEPENDENTE END AS COD_INSTITUCIONAL, FF.ID_FUNCIONARIO, CASE WHEN FF.ID_PENSIONISTA IS NULL THEN ''NULL'' ELSE TO_CHAR(FF.ID_PENSIONISTA) END AS ID_PENSIONISTA, FO.MES, FO.ANO, FC.ID_CONSIGNADO, FC.ID_RUBRICA, CASE WHEN FF.ID_PENSIONISTA IS NULL THEN FF.ID_PESSOA_FUNCIONARIO ELSE FF.ID_PESSOA_DEPENDENTE END AS ID_PESSOA FROM '
               || R.ESQUEMA
               || '.FOLHA_FUNC FF JOIN '
               || R.ESQUEMA
               || '.FOLHA FO ON FO.ID_FOLHA = FF.ID_FOLHA JOIN '
               || R.ESQUEMA
               || '.FUNCIONARIO F ON F.ID_FUNCIONARIO = FF.ID_FUNCIONARIO JOIN '
               || R.ESQUEMA
               || '.PESSOA_VINCULO PV ON PV.ID_PESSOA_VINCULO = F.ID_PESSOA_VINCULO LEFT JOIN '
               || R.ESQUEMA
               || '.FOLHA_FUNC_PERFIL FP ON FP.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO JOIN '
               || R.ESQUEMA
               || '.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL LEFT JOIN '
               || R.ESQUEMA
               || '.FOLHA_CONSIG_CONSIGNADO FC ON (FC.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND (FC.ID_PENSIONISTA = FF.ID_PENSIONISTA OR FC.ID_PENSIONISTA IS NULL) AND TO_CHAR(FC.DATA_INICIO, ''YYYYMM'') = FO.ANO || LPAD(FO.MES, 2, ''0'') ) WHERE FO.MES = '
               || MES
               || ' AND FO.ANO = '
               || ANO
               || ' AND FO.IND_LANCAR_CONSIGNACOES = ''S'' AND FF.IND_REMUNERACAO = ''S'' AND P.ID_DIVISAO NOT IN ('
               || IDS_DIVISAO_DESCONSIDERAR
               || ')';

        DBMS_OUTPUT.PUT_LINE(QRY);
    END LOOP;

    DBMS_OUTPUT.PUT_LINE(') Q GROUP BY Q.ORGAO, Q.COD_INSTITUCIONAL, Q.ID_FUNCIONARIO, Q.ID_PENSIONISTA, Q.ID_PESSOA');
    DBMS_OUTPUT.PUT_LINE(') B ON B.COD_INSTITUCIONAL = A.COD_INSTITUCIONAL WHERE A.QNTD_CONSIGNACOES - B.QNTD_CONSIG_LANCADAS > 0 AND ( A.ORGAO_ORIGEM <> B.ORGAO_PAGAMENTO OR ( A.ORGAO_ORIGEM = B.ORGAO_PAGAMENTO AND A.ID_FUNCIONARIO_ORIGEM <> B.ID_FUNCIONARIO_PAGAMENTO ) AND A.ID_PESSOA = B.ID_PESSOA) ORDER BY B.ORGAO_PAGAMENTO'
    );
END;