SELECT 
    'FUNPREV' ORGAO,
    FO.CHAVE_FOLHA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA,
    NJ.CODIGO,
    NJ.NOME_NATUREZA NATUREZA_RUBRICA
FROM 
    SW_FUNPREV.FOLHA FO 
    JOIN SW_FUNPREV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUNPREV.FOLHA_FUNC_RUBRICA_IMPORTADA FRI ON FRI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO 
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FRI.ID_RUBRICA
    JOIN SW_PUBLICO.ESB_NATU_RUBRICA_FOLHA_PAG NJ ON NJ.ID_ESB_SOC_NAT_RUB_FOL_PAG = R.ID_ESB_SOC_NAT_RUB_FOL_PAG
WHERE 
    R.ID_ESB_SOC_NAT_RUB_FOL_PAG IN (105,106,1000571)
    AND FO.ANO = 2026
    AND FO.MES = 8