SELECT 
    'CBMPI' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_CBMPI.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_CBMPI.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_CBMPI.FOLHA FO
    JOIN SW_CBMPI.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_CBMPI.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'PGEPI' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_PGEPI.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_PGEPI.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_PGEPI.FOLHA FO
    JOIN SW_PGEPI.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_PGEPI.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'CGEPI' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_CGEPI.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_CGEPI.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_CGEPI.FOLHA FO
    JOIN SW_CGEPI.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_CGEPI.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'SSPPI' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_SSPPI.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_SSPPI.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_SSPPI.FOLHA FO
    JOIN SW_SSPPI.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SSPPI.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'COJUV' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_COJUV.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_COJUV.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_COJUV.FOLHA FO
    JOIN SW_COJUV.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_COJUV.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'ATIPI' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_ATIPI.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_ATIPI.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_ATIPI.FOLHA FO
    JOIN SW_ATIPI.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_ATIPI.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'FAPEPI' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_FAPEPI.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_FAPEPI.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_FAPEPI.FOLHA FO
    JOIN SW_FAPEPI.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_FAPEPI.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'DEFCIVIL' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_DEFCIVIL.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_DEFCIVIL.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_DEFCIVIL.FOLHA FO
    JOIN SW_DEFCIVIL.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_DEFCIVIL.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'ADH' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_ADH.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_ADH.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_ADH.FOLHA FO
    JOIN SW_ADH.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_ADH.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'SEAGRO' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_SEAGRO.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_SEAGRO.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_SEAGRO.FOLHA FO
    JOIN SW_SEAGRO.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEAGRO.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'IDEPI' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_IDEPI.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_IDEPI.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_IDEPI.FOLHA FO
    JOIN SW_IDEPI.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_IDEPI.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'SURPI' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_SURPI.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_SURPI.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_SURPI.FOLHA FO
    JOIN SW_SURPI.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SURPI.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'SEID' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_SEID.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_SEID.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_SEID.FOLHA FO
    JOIN SW_SEID.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEID.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'SECID' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_SECID.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_SECID.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_SECID.FOLHA FO
    JOIN SW_SECID.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SECID.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'FUPIP' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_FUPIP.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_FUPIP.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_FUPIP.FOLHA FO
    JOIN SW_FUPIP.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_FUPIP.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'SETUR' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_SETUR.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_SETUR.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_SETUR.FOLHA FO
    JOIN SW_SETUR.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SETUR.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL       
SELECT 
    'SETRANS' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_SETRANS.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_SETRANS.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_SETRANS.FOLHA FO
    JOIN SW_SETRANS.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SETRANS.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'TVANTARES' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_TVANTARES.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_TVANTARES.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_TVANTARES.FOLHA FO
    JOIN SW_TVANTARES.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_TVANTARES.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'VICEGOV' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_VICEGOV.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_VICEGOV.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_VICEGOV.FOLHA FO
    JOIN SW_VICEGOV.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_VICEGOV.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'SEINFRA' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_SEINFRA.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_SEINFRA.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_SEINFRA.FOLHA FO
    JOIN SW_SEINFRA.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEINFRA.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'CCOM' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_CCOM.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_CCOM.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_CCOM.FOLHA FO
    JOIN SW_CCOM.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_CCOM.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'FUNDESPI' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_FUNDESPI.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_FUNDESPI.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_FUNDESPI.FOLHA FO
    JOIN SW_FUNDESPI.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_FUNDESPI.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'SEDET' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_SEDET.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_SEDET.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_SEDET.FOLHA FO
    JOIN SW_SEDET.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEDET.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'INTERPI' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_INTERPI.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_INTERPI.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_INTERPI.FOLHA FO
    JOIN SW_INTERPI.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_INTERPI.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'JUCEPI' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_JUCEPI.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_JUCEPI.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_JUCEPI.FOLHA FO
    JOIN SW_JUCEPI.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_JUCEPI.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'SEMAR' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_SEMAR.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_SEMAR.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_SEMAR.FOLHA FO
    JOIN SW_SEMAR.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEMAR.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'GMG' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_GMG.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_GMG.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_GMG.FOLHA FO
    JOIN SW_GMG.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_GMG.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'SEPLAN' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_SEPLAN.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_SEPLAN.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_SEPLAN.FOLHA FO
    JOIN SW_SEPLAN.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEPLAN.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'SAF' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_SAF.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_SAF.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_SAF.FOLHA FO
    JOIN SW_SAF.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SAF.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'SECULT' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_SECULT.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_SECULT.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_SECULT.FOLHA FO
    JOIN SW_SECULT.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SECULT.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'DER' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_DER.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_DER.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_DER.FOLHA FO
    JOIN SW_DER.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_DER.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'DETRAN' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_DETRAN.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_DETRAN.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_DETRAN.FOLHA FO
    JOIN SW_DETRAN.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_DETRAN.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'IASPI' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_IASPI.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_IASPI.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_IASPI.FOLHA FO
    JOIN SW_IASPI.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_IASPI.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'ADAPI' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_ADAPI.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_ADAPI.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_ADAPI.FOLHA FO
    JOIN SW_ADAPI.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_ADAPI.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'IMEPIPROD' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_IMEPIPROD.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_IMEPIPROD.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_IMEPIPROD.FOLHA FO
    JOIN SW_IMEPIPROD.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_IMEPIPROD.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'CPVCI' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_CPVCI.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_CPVCI.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_CPVCI.FOLHA FO
    JOIN SW_CPVCI.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_CPVCI.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'CENDROGAS' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_CENDROGAS.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_CENDROGAS.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_CENDROGAS.FOLHA FO
    JOIN SW_CENDROGAS.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_CENDROGAS.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'COFIR' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_COFIR.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_COFIR.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_COFIR.FOLHA FO
    JOIN SW_COFIR.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_COFIR.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'SEMINPER' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_SEMINPER.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_SEMINPER.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_SEMINPER.FOLHA FO
    JOIN SW_SEMINPER.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEMINPER.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'AGRESP' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_AGRESP.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_AGRESP.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_AGRESP.FOLHA FO
    JOIN SW_AGRESP.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_AGRESP.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'CEPM' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_CEPM.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_CEPM.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_CEPM.FOLHA FO
    JOIN SW_CEPM.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_CEPM.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'EMATER' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_EMATER.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_EMATER.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_EMATER.FOLHA FO
    JOIN SW_EMATER.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_EMATER.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'FUESPI' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_FUESPI.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_FUESPI.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_FUESPI.FOLHA FO
    JOIN SW_FUESPI.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_FUESPI.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'EMATERPROD' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_EMATERPROD.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_EMATERPROD.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_EMATERPROD.FOLHA FO
    JOIN SW_EMATERPROD.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_EMATERPROD.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL        
SELECT 
    'CDTER' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_CDTER.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_CDTER.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_CDTER.FOLHA FO
    JOIN SW_CDTER.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_CDTER.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'SERES' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_SERES.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_SERES.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_SERES.FOLHA FO
    JOIN SW_SERES.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SERES.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'SECESP' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_SECESP.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_SECESP.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_SECESP.FOLHA FO
    JOIN SW_SECESP.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SECESP.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL     
SELECT 
    'EMGERPI_CORESA' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_EMGERPI_CORESA.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_EMGERPI_CORESA.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_EMGERPI_CORESA.FOLHA FO
    JOIN SW_EMGERPI_CORESA.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_EMGERPI_CORESA.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'FUNPREV' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_FUNPREV.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_FUNPREV.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_FUNPREV.FOLHA FO
    JOIN SW_FUNPREV.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_FUNPREV.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'FESPPI' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_FESPPI.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_FESPPI.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_FESPPI.FOLHA FO
    JOIN SW_FESPPI.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_FESPPI.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'SIA' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_SIA.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_SIA.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_SIA.FOLHA FO
    JOIN SW_SIA.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SIA.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'SETRE' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_SETRE.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_SETRE.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_SETRE.FOLHA FO
    JOIN SW_SETRE.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SETRE.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'AGESPISA' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_AGESPISA.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_AGESPISA.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_AGESPISA.FOLHA FO
    JOIN SW_AGESPISA.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_AGESPISA.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'SEGOV' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_SEGOV.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_SEGOV.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEGOV.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'SASC' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_SASC.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_SASC.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_SASC.FOLHA FO
    JOIN SW_SASC.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SASC.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'METRO' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_METRO.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_METRO.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_METRO.FOLHA FO
    JOIN SW_METRO.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_METRO.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL            
SELECT 
    'SADA' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_SADA.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_SADA.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_SADA.FOLHA FO
    JOIN SW_SADA.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SADA.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'SECMULHERES' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_SECMULHERES.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_SECMULHERES.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_SECMULHERES.FOLHA FO
    JOIN SW_SECMULHERES.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SECMULHERES.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'EMGERPI_EMATER' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_EMGERPI_EMATER.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_EMGERPI_EMATER.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_EMGERPI_EMATER.FOLHA FO
    JOIN SW_EMGERPI_EMATER.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_EMGERPI_EMATER.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL      
SELECT 
    'SESAPI' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_SESAPI.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_SESAPI.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_SESAPI.FOLHA FO
    JOIN SW_SESAPI.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SESAPI.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'PMPI' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_PMPI.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_PMPI.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_PMPI.FOLHA FO
    JOIN SW_PMPI.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_PMPI.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'SEJUSPI' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_SEJUSPI.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_SEJUSPI.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_SEJUSPI.FOLHA FO
    JOIN SW_SEJUSPI.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEJUSPI.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'SEFAZPI' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_SEFAZPI.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_SEFAZPI.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_SEFAZPI.FOLHA FO
    JOIN SW_SEFAZPI.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEFAZPI.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'SEADPREVPI' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_SEADPREVPI.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_SEADPREVPI.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_SEADPREVPI.FOLHA FO
    JOIN SW_SEADPREVPI.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEADPREVPI.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'IMEPI' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_IMEPI.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_IMEPI.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_IMEPI.FOLHA FO
    JOIN SW_IMEPI.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_IMEPI.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'BEP' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_BEP.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_BEP.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_BEP.FOLHA FO
    JOIN SW_BEP.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_BEP.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'EMGERPI_COMEPI' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_EMGERPI_COMEPI.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_EMGERPI_COMEPI.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_EMGERPI_COMEPI.FOLHA FO
    JOIN SW_EMGERPI_COMEPI.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_EMGERPI_COMEPI.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'EMGERPI_COMDEPI' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_EMGERPI_COMDEPI.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_EMGERPI_COMDEPI.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_EMGERPI_COMDEPI.FOLHA FO
    JOIN SW_EMGERPI_COMDEPI.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_EMGERPI_COMDEPI.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'EMGERPI_COHAB' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_EMGERPI_COHAB.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_EMGERPI_COHAB.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_EMGERPI_COHAB.FOLHA FO
    JOIN SW_EMGERPI_COHAB.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_EMGERPI_COHAB.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'EMGERPI_PRODEPI' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_EMGERPI_PRODEPI.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_EMGERPI_PRODEPI.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_EMGERPI_PRODEPI.FOLHA FO
    JOIN SW_EMGERPI_PRODEPI.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_EMGERPI_PRODEPI.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'EMGERPI_CEASA' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_EMGERPI_CEASA.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_EMGERPI_CEASA.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_EMGERPI_CEASA.FOLHA FO
    JOIN SW_EMGERPI_CEASA.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_EMGERPI_CEASA.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'EMGERPI_PIEMTUR' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_EMGERPI_PIEMTUR.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_EMGERPI_PIEMTUR.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_EMGERPI_PIEMTUR.FOLHA FO
    JOIN SW_EMGERPI_PIEMTUR.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_EMGERPI_PIEMTUR.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'EMGERPI_ETELPI_FUNART' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_EMGERPI_ETELPI_FUNART.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_EMGERPI_ETELPI_FUNART.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_EMGERPI_ETELPI_FUNART.FOLHA FO
    JOIN SW_EMGERPI_ETELPI_FUNART.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_EMGERPI_ETELPI_FUNART.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'EMGERPI_CIDAPI' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_EMGERPI_CIDAPI.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_EMGERPI_CIDAPI.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_EMGERPI_CIDAPI.FOLHA FO
    JOIN SW_EMGERPI_CIDAPI.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_EMGERPI_CIDAPI.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'SEDUC' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_SEDUC.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_SEDUC.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_SEDUC.FOLHA FO
    JOIN SW_SEDUC.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_SEDUC.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'EMGERPI' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_EMGERPI.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_EMGERPI.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_EMGERPI.FOLHA FO
    JOIN SW_EMGERPI.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_EMGERPI.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    )
UNION ALL    
SELECT 
    'EMGERPI_CODIPI' ORGAO,
    FO.CHAVE_FOLHA,
    RF.ID_RUBRICA_FORMULA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    R2.COD_RUBRICA COD_INCIDENCIA,
    R2.NOME_RUBRICA INCIDENCIA,
    'INSERT INTO SW_EMGERPI_CODIPI.FOLHA_RUBRICA_INCIDENCIA (ID_INCIDENCIA_RUBRICA, ID_RUBRICA_FORMULA, DATA_CADASTRO, ID_INCIDENCIA) VALUES (SW_EMGERPI_CODIPI.SQ_PK_INCIDENCIA.NEXTVAL, ' || RF.ID_RUBRICA_FORMULA || ', ''' || SYSDATE || ''', ' || R2.ID_RUBRICA || ');' INSERT_
FROM
    SW_EMGERPI_CODIPI.FOLHA FO
    JOIN SW_EMGERPI_CODIPI.FOLHA_RUBRICA_FORMULA RF ON RF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RF.ID_RUBRICA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R2 ON R2.COD_RUBRICA IN (111036)
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN (111051, 111053, 111054, 719500, 720000, 715100, 116003, 126003, 136003, 146003, 156003)
    AND NOT EXISTS (
        SELECT
            1
        FROM
            SW_EMGERPI_CODIPI.FOLHA_RUBRICA_INCIDENCIA RI
        WHERE
            RI.ID_RUBRICA_FORMULA = RF.ID_RUBRICA_FORMULA
            AND RI.ID_INCIDENCIA = R2.ID_RUBRICA
    );