DELETE FROM SW_TVANTARES.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_TVANTARES.FOLHA FO
    JOIN SW_TVANTARES.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_TVANTARES.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_CBMPI.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_CBMPI.FOLHA FO
    JOIN SW_CBMPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CBMPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_PGEPI.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_PGEPI.FOLHA FO
    JOIN SW_PGEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PGEPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_SSPPI.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_SSPPI.FOLHA FO
    JOIN SW_SSPPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SSPPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_FAPEPI.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_FAPEPI.FOLHA FO
    JOIN SW_FAPEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FAPEPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_DEFCIVIL.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_DEFCIVIL.FOLHA FO
    JOIN SW_DEFCIVIL.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_DEFCIVIL.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_ADH.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_ADH.FOLHA FO
    JOIN SW_ADH.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_ADH.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_SEAGRO.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_SEAGRO.FOLHA FO
    JOIN SW_SEAGRO.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEAGRO.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_IDEPI.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_IDEPI.FOLHA FO
    JOIN SW_IDEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_IDEPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_SURPI.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_SURPI.FOLHA FO
    JOIN SW_SURPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SURPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_SEID.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_SEID.FOLHA FO
    JOIN SW_SEID.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEID.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_SECID.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_SECID.FOLHA FO
    JOIN SW_SECID.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SECID.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_FUPIP.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_FUPIP.FOLHA FO
    JOIN SW_FUPIP.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUPIP.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_SETUR.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_SETUR.FOLHA FO
    JOIN SW_SETUR.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SETUR.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_SETRANS.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_SETRANS.FOLHA FO
    JOIN SW_SETRANS.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SETRANS.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_TVANTARES.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_TVANTARES.FOLHA FO
    JOIN SW_TVANTARES.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_TVANTARES.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_VICEGOV.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_VICEGOV.FOLHA FO
    JOIN SW_VICEGOV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_VICEGOV.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_SEINFRA.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_SEINFRA.FOLHA FO
    JOIN SW_SEINFRA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEINFRA.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_CCOM.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_CCOM.FOLHA FO
    JOIN SW_CCOM.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CCOM.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_SEDET.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_SEDET.FOLHA FO
    JOIN SW_SEDET.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEDET.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_INTERPI.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_INTERPI.FOLHA FO
    JOIN SW_INTERPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_INTERPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_JUCEPI.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_JUCEPI.FOLHA FO
    JOIN SW_JUCEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_JUCEPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_SEMAR.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_SEMAR.FOLHA FO
    JOIN SW_SEMAR.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEMAR.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_GMG.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_GMG.FOLHA FO
    JOIN SW_GMG.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_GMG.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_SEPLAN.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_SEPLAN.FOLHA FO
    JOIN SW_SEPLAN.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEPLAN.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_SAF.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_SAF.FOLHA FO
    JOIN SW_SAF.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SAF.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_SECULT.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_SECULT.FOLHA FO
    JOIN SW_SECULT.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SECULT.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_DER.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_DER.FOLHA FO
    JOIN SW_DER.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_DER.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_DETRAN.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_DETRAN.FOLHA FO
    JOIN SW_DETRAN.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_DETRAN.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_IASPI.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_IASPI.FOLHA FO
    JOIN SW_IASPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_IASPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_ADAPI.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_ADAPI.FOLHA FO
    JOIN SW_ADAPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_ADAPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_CENDROGAS.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_CENDROGAS.FOLHA FO
    JOIN SW_CENDROGAS.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CENDROGAS.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_COFIR.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_COFIR.FOLHA FO
    JOIN SW_COFIR.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_COFIR.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_SEMINPER.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_SEMINPER.FOLHA FO
    JOIN SW_SEMINPER.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEMINPER.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_AGRESP.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_AGRESP.FOLHA FO
    JOIN SW_AGRESP.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_AGRESP.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_FUESPI.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_FUESPI.FOLHA FO
    JOIN SW_FUESPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUESPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_SERES.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_SERES.FOLHA FO
    JOIN SW_SERES.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SERES.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_SECESP.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_SECESP.FOLHA FO
    JOIN SW_SECESP.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SECESP.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_FUNPREV.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_FUNPREV.FOLHA FO
    JOIN SW_FUNPREV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUNPREV.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-312','03/2026-310','03/2026-300','03/2026-320','03/2026-380','03/2026-350','03/2026-370','03/2026-441','03/2026-420','03/2026-400','03/2026-440','03/2026-340','03/2026-360','03/2026-390','03/2026-330') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_SEGOV.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEGOV.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_SASC.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_SASC.FOLHA FO
    JOIN SW_SASC.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SASC.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_METRO.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_METRO.FOLHA FO
    JOIN SW_METRO.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_METRO.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_SADA.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_SADA.FOLHA FO
    JOIN SW_SADA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SADA.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_SECMULHERES.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_SECMULHERES.FOLHA FO
    JOIN SW_SECMULHERES.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SECMULHERES.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_EMGERPI_EMATER.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_EMGERPI_EMATER.FOLHA FO
    JOIN SW_EMGERPI_EMATER.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_EMATER.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_SESAPI.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_SESAPI.FOLHA FO
    JOIN SW_SESAPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SESAPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100','03/2026-250') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_PMPI.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_PMPI.FOLHA FO
    JOIN SW_PMPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PMPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_SEJUSPI.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_SEJUSPI.FOLHA FO
    JOIN SW_SEJUSPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEJUSPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_SEFAZPI.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_SEFAZPI.FOLHA FO
    JOIN SW_SEFAZPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEFAZPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_SEADPREVPI.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_SEADPREVPI.FOLHA FO
    JOIN SW_SEADPREVPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEADPREVPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100','03/2026-360','03/2026-370') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_IMEPI.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_IMEPI.FOLHA FO
    JOIN SW_IMEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_IMEPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_BEP.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_BEP.FOLHA FO
    JOIN SW_BEP.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_BEP.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-300') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_EMGERPI_COMEPI.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_EMGERPI_COMEPI.FOLHA FO
    JOIN SW_EMGERPI_COMEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_COMEPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_EMGERPI_COMDEPI.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_EMGERPI_COMDEPI.FOLHA FO
    JOIN SW_EMGERPI_COMDEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_COMDEPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_EMGERPI_COHAB.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_EMGERPI_COHAB.FOLHA FO
    JOIN SW_EMGERPI_COHAB.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_COHAB.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_EMGERPI_PRODEPI.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_EMGERPI_PRODEPI.FOLHA FO
    JOIN SW_EMGERPI_PRODEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_PRODEPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_EMGERPI_PIEMTUR.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_EMGERPI_PIEMTUR.FOLHA FO
    JOIN SW_EMGERPI_PIEMTUR.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_PIEMTUR.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);

DELETE FROM SW_SEDUC.FOLHA_FUNC_RUBRICA_IMPORTADA WHERE ID_RUBRICA_IMPORTADA IN (
SELECT RI.ID_RUBRICA_IMPORTADA FROM SW_SEDUC.FOLHA FO
    JOIN SW_SEDUC.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEDUC.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
WHERE FO.CHAVE_FOLHA IN ('03/2026-100','03/2026-110','03/2026-120','03/2026-250','03/2026-280') AND FO.DATA_FECHAMENTO IS NULL AND RI.ID_CONSIGNADO IS NOT NULL);