DELETE FROM SW_SESAPI.ESOCIAL_TRANSMISSAO 
WHERE ID_ESOCIAL_EVENTO IN (
    SELECT EE.ID_ESOCIAL_EVENTO 
    FROM SW_SESAPI.ESOCIAL_EVENTO EE
    JOIN SW_PUBLICO.ESB_TIPO_ARQUIVO_ESOCIAL TA ON TA.ID_ESB_TIPO_ARQUIVO_ESOCIAL = EE.ID_ESOCIAL_TIPO_ARQUIVO
    WHERE TA.CODIGO IN ('S-3000')
    AND EE.STATUS_VOBYS IN ('P')
    );

DELETE FROM SW_SESAPI.ESOCIAL_EVENTO_OCORRENCIA 
WHERE ID_ESOCIAL_EVENTO IN (
    SELECT EE.ID_ESOCIAL_EVENTO 
    FROM SW_SESAPI.ESOCIAL_EVENTO EE
    JOIN SW_PUBLICO.ESB_TIPO_ARQUIVO_ESOCIAL TA ON TA.ID_ESB_TIPO_ARQUIVO_ESOCIAL = EE.ID_ESOCIAL_TIPO_ARQUIVO
    WHERE TA.CODIGO IN ('S-3000')
    AND EE.STATUS_VOBYS IN ('P')
    );

DELETE FROM SW_SESAPI.ESOCIAL_EVENTO_ATRIBUTO 
WHERE ID_ESOCIAL_EVENTO IN (
    SELECT EE.ID_ESOCIAL_EVENTO 
    FROM SW_SESAPI.ESOCIAL_EVENTO EE
    JOIN SW_PUBLICO.ESB_TIPO_ARQUIVO_ESOCIAL TA ON TA.ID_ESB_TIPO_ARQUIVO_ESOCIAL = EE.ID_ESOCIAL_TIPO_ARQUIVO
    WHERE TA.CODIGO IN ('S-3000')
    AND EE.STATUS_VOBYS IN ('P')
    );

DELETE FROM SW_SESAPI.ESOCIAL_EVENTO 
WHERE ID_ESOCIAL_EVENTO IN (
    SELECT EE.ID_ESOCIAL_EVENTO 
    FROM SW_SESAPI.ESOCIAL_EVENTO EE
    JOIN SW_PUBLICO.ESB_TIPO_ARQUIVO_ESOCIAL TA ON TA.ID_ESB_TIPO_ARQUIVO_ESOCIAL = EE.ID_ESOCIAL_TIPO_ARQUIVO
    WHERE TA.CODIGO IN ('S-3000')
    AND EE.STATUS_VOBYS IN ('P')
    );
