DELETE FROM SW_EMPRESA.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMPRESA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMPRESA.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMPRESA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMPRESA.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMPRESA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMPRESA.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMPRESA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_EMPRESA.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMPRESA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_CBMPI.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CBMPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_CBMPI.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CBMPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_CBMPI.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CBMPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_CBMPI.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CBMPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_CBMPI.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CBMPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_PGEPI.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_PGEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_PGEPI.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_PGEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_PGEPI.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_PGEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_PGEPI.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_PGEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_PGEPI.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_PGEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_CGEPI.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CGEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_CGEPI.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CGEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_CGEPI.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CGEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_CGEPI.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CGEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_CGEPI.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CGEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_SSPPI.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SSPPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SSPPI.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SSPPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SSPPI.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SSPPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SSPPI.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SSPPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_SSPPI.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SSPPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_COJUV.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_COJUV.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_COJUV.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_COJUV.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_COJUV.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_COJUV.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_COJUV.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_COJUV.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_COJUV.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_COJUV.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_ATIPI.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_ATIPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_ATIPI.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_ATIPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_ATIPI.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_ATIPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_ATIPI.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_ATIPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_ATIPI.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_ATIPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_FAPEPI.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_FAPEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_FAPEPI.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_FAPEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_FAPEPI.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_FAPEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_FAPEPI.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_FAPEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_FAPEPI.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_FAPEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_DEFCIVIL.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_DEFCIVIL.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_DEFCIVIL.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_DEFCIVIL.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_DEFCIVIL.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_DEFCIVIL.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_DEFCIVIL.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_DEFCIVIL.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_DEFCIVIL.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_DEFCIVIL.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_ADH.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_ADH.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_ADH.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_ADH.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_ADH.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_ADH.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_ADH.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_ADH.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_ADH.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_ADH.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_SEAGRO.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEAGRO.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEAGRO.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEAGRO.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEAGRO.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEAGRO.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEAGRO.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEAGRO.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_SEAGRO.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEAGRO.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_IDEPI.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_IDEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_IDEPI.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_IDEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_IDEPI.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_IDEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_IDEPI.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_IDEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_IDEPI.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_IDEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_SURPI.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SURPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SURPI.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SURPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SURPI.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SURPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SURPI.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SURPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_SURPI.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SURPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_SEID.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEID.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEID.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEID.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEID.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEID.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEID.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEID.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_SEID.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEID.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_SECID.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SECID.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SECID.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SECID.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SECID.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SECID.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SECID.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SECID.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_SECID.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SECID.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_FUPIP.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_FUPIP.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_FUPIP.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_FUPIP.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_FUPIP.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_FUPIP.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_FUPIP.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_FUPIP.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_FUPIP.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_FUPIP.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_SETUR.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SETUR.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SETUR.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SETUR.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SETUR.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SETUR.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SETUR.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SETUR.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_SETUR.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SETUR.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_AGESPISA.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_AGESPISA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_AGESPISA.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_AGESPISA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_AGESPISA.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_AGESPISA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_AGESPISA.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_AGESPISA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_AGESPISA.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_AGESPISA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_SETRANS.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SETRANS.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SETRANS.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SETRANS.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SETRANS.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SETRANS.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SETRANS.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SETRANS.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_SETRANS.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SETRANS.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_TVANTARES.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_TVANTARES.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_TVANTARES.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_TVANTARES.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_TVANTARES.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_TVANTARES.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_TVANTARES.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_TVANTARES.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_TVANTARES.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_TVANTARES.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_VICEGOV.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_VICEGOV.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_VICEGOV.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_VICEGOV.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_VICEGOV.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_VICEGOV.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_VICEGOV.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_VICEGOV.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_VICEGOV.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_VICEGOV.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_SEINFRA.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEINFRA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEINFRA.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEINFRA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEINFRA.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEINFRA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEINFRA.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEINFRA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_SEINFRA.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEINFRA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_CCOM.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CCOM.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_CCOM.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CCOM.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_CCOM.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CCOM.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_CCOM.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CCOM.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_CCOM.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CCOM.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_FUNDESPI.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_FUNDESPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_FUNDESPI.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_FUNDESPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_FUNDESPI.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_FUNDESPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_FUNDESPI.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_FUNDESPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_FUNDESPI.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_FUNDESPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_SEDET.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEDET.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEDET.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEDET.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEDET.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEDET.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEDET.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEDET.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_SEDET.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEDET.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_INTERPI.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_INTERPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_INTERPI.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_INTERPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_INTERPI.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_INTERPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_INTERPI.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_INTERPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_INTERPI.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_INTERPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_JUCEPI.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_JUCEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_JUCEPI.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_JUCEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_JUCEPI.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_JUCEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_JUCEPI.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_JUCEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_JUCEPI.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_JUCEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_SEMAR.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEMAR.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEMAR.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEMAR.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEMAR.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEMAR.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEMAR.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEMAR.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_SEMAR.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEMAR.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_GMG.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_GMG.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_GMG.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_GMG.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_GMG.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_GMG.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_GMG.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_GMG.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_GMG.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_GMG.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_SEPLAN.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEPLAN.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEPLAN.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEPLAN.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEPLAN.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEPLAN.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEPLAN.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEPLAN.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_SEPLAN.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEPLAN.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_SAF.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SAF.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SAF.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SAF.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SAF.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SAF.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SAF.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SAF.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_SAF.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SAF.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_SECULT.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SECULT.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SECULT.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SECULT.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SECULT.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SECULT.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SECULT.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SECULT.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_SECULT.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SECULT.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_DER.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_DER.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_DER.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_DER.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_DER.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_DER.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_DER.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_DER.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_DER.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_DER.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_DETRAN.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_DETRAN.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_DETRAN.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_DETRAN.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_DETRAN.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_DETRAN.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_DETRAN.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_DETRAN.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_DETRAN.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_DETRAN.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_IASPI.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_IASPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_IASPI.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_IASPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_IASPI.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_IASPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_IASPI.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_IASPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_IASPI.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_IASPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_ADAPI.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_ADAPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_ADAPI.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_ADAPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_ADAPI.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_ADAPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_ADAPI.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_ADAPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_ADAPI.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_ADAPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_IMEPIPROD.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_IMEPIPROD.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_IMEPIPROD.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_IMEPIPROD.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_IMEPIPROD.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_IMEPIPROD.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_IMEPIPROD.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_IMEPIPROD.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_IMEPIPROD.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_IMEPIPROD.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_CPVCI.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CPVCI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_CPVCI.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CPVCI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_CPVCI.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CPVCI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_CPVCI.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CPVCI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_CPVCI.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CPVCI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_CENDROGAS.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CENDROGAS.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_CENDROGAS.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CENDROGAS.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_CENDROGAS.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CENDROGAS.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_CENDROGAS.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CENDROGAS.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_CENDROGAS.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CENDROGAS.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_COFIR.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_COFIR.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_COFIR.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_COFIR.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_COFIR.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_COFIR.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_COFIR.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_COFIR.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_COFIR.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_COFIR.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_SEMINPER.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEMINPER.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEMINPER.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEMINPER.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEMINPER.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEMINPER.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEMINPER.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEMINPER.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_SEMINPER.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEMINPER.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_AGRESP.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_AGRESP.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_AGRESP.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_AGRESP.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_AGRESP.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_AGRESP.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_AGRESP.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_AGRESP.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_AGRESP.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_AGRESP.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_CEPM.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CEPM.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_CEPM.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CEPM.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_CEPM.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CEPM.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_CEPM.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CEPM.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_CEPM.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CEPM.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_EMATER.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMATER.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMATER.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMATER.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMATER.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMATER.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMATER.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMATER.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_EMATER.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMATER.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_FUESPI.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_FUESPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_FUESPI.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_FUESPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_FUESPI.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_FUESPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_FUESPI.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_FUESPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_FUESPI.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_FUESPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_EMATERPROD.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMATERPROD.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMATERPROD.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMATERPROD.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMATERPROD.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMATERPROD.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMATERPROD.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMATERPROD.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_EMATERPROD.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMATERPROD.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_DEFENSORIA.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_DEFENSORIA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_DEFENSORIA.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_DEFENSORIA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_DEFENSORIA.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_DEFENSORIA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_DEFENSORIA.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_DEFENSORIA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_DEFENSORIA.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_DEFENSORIA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_PENSIONISTAS.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_PENSIONISTAS.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_PENSIONISTAS.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_PENSIONISTAS.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_PENSIONISTAS.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_PENSIONISTAS.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_PENSIONISTAS.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_PENSIONISTAS.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_PENSIONISTAS.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_PENSIONISTAS.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_CDTER.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CDTER.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_CDTER.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CDTER.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_CDTER.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CDTER.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_CDTER.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CDTER.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_CDTER.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_CDTER.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_SERES.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SERES.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SERES.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SERES.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SERES.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SERES.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SERES.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SERES.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_SERES.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SERES.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_SECESP.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SECESP.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SECESP.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SECESP.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SECESP.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SECESP.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SECESP.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SECESP.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_SECESP.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SECESP.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_INATIVOS_PENSIONISTAS.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_INATIVOS_PENSIONISTAS.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_INATIVOS_PENSIONISTAS.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_INATIVOS_PENSIONISTAS.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_INATIVOS_PENSIONISTAS.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_INATIVOS_PENSIONISTAS.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_INATIVOS_PENSIONISTAS.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_INATIVOS_PENSIONISTAS.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_INATIVOS_PENSIONISTAS.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_INATIVOS_PENSIONISTAS.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_SEDUC_PRECATORIO.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEDUC_PRECATORIO.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEDUC_PRECATORIO.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEDUC_PRECATORIO.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEDUC_PRECATORIO.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEDUC_PRECATORIO.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEDUC_PRECATORIO.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEDUC_PRECATORIO.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_SEDUC_PRECATORIO.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEDUC_PRECATORIO.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_EMGERPI_CORESA.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_CORESA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_CORESA.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_CORESA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_CORESA.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_CORESA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_CORESA.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_CORESA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_EMGERPI_CORESA.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_CORESA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_FUNPREV.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_FUNPREV.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_FUNPREV.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_FUNPREV.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_FUNPREV.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_FUNPREV.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_FUNPREV.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_FUNPREV.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_FUNPREV.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_FUNPREV.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_FESPPI.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_FESPPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_FESPPI.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_FESPPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_FESPPI.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_FESPPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_FESPPI.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_FESPPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_FESPPI.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_FESPPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_SIA.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SIA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SIA.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SIA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SIA.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SIA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SIA.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SIA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_SIA.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SIA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_SETRE.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SETRE.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SETRE.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SETRE.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SETRE.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SETRE.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SETRE.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SETRE.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_SETRE.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SETRE.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_SEGOV.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEGOV.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEGOV.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEGOV.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEGOV.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEGOV.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEGOV.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEGOV.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_SEGOV.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEGOV.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_SASC.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SASC.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SASC.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SASC.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SASC.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SASC.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SASC.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SASC.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_SASC.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SASC.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_METRO.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_METRO.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_METRO.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_METRO.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_METRO.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_METRO.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_METRO.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_METRO.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_METRO.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_METRO.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_PIAUIPREV.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_PIAUIPREV.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_PIAUIPREV.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_PIAUIPREV.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_PIAUIPREV.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_PIAUIPREV.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_PIAUIPREV.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_PIAUIPREV.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_PIAUIPREV.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_PIAUIPREV.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_INATIVOS_SEDUC.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_INATIVOS_SEDUC.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_INATIVOS_SEDUC.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_INATIVOS_SEDUC.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_INATIVOS_SEDUC.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_INATIVOS_SEDUC.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_INATIVOS_SEDUC.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_INATIVOS_SEDUC.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_INATIVOS_SEDUC.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_INATIVOS_SEDUC.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_INATIVOS_TCE.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_INATIVOS_TCE.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_INATIVOS_TCE.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_INATIVOS_TCE.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_INATIVOS_TCE.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_INATIVOS_TCE.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_INATIVOS_TCE.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_INATIVOS_TCE.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_INATIVOS_TCE.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_INATIVOS_TCE.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_SADA.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SADA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SADA.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SADA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SADA.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SADA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SADA.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SADA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_SADA.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SADA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_SECMULHERES.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SECMULHERES.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SECMULHERES.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SECMULHERES.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SECMULHERES.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SECMULHERES.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SECMULHERES.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SECMULHERES.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_SECMULHERES.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SECMULHERES.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_EMGERPI_EMATER.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_EMATER.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_EMATER.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_EMATER.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_EMATER.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_EMATER.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_EMATER.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_EMATER.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_EMGERPI_EMATER.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_EMATER.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_REENVIO.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_REENVIO.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_REENVIO.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_REENVIO.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_REENVIO.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_REENVIO.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_REENVIO.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_REENVIO.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_REENVIO.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_REENVIO.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_SESAPI.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SESAPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SESAPI.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SESAPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SESAPI.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SESAPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SESAPI.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SESAPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_SESAPI.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SESAPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_PMPI.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_PMPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_PMPI.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_PMPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_PMPI.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_PMPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_PMPI.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_PMPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_PMPI.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_PMPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_SEJUSPI.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEJUSPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEJUSPI.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEJUSPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEJUSPI.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEJUSPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEJUSPI.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEJUSPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_SEJUSPI.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEJUSPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_SEFAZPI.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEFAZPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEFAZPI.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEFAZPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEFAZPI.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEFAZPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEFAZPI.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEFAZPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_SEFAZPI.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEFAZPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_SEADPREVPI.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEADPREVPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEADPREVPI.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEADPREVPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEADPREVPI.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEADPREVPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEADPREVPI.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEADPREVPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_SEADPREVPI.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEADPREVPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_IMEPI.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_IMEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_IMEPI.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_IMEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_IMEPI.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_IMEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_IMEPI.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_IMEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_IMEPI.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_IMEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_BEP.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_BEP.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_BEP.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_BEP.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_BEP.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_BEP.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_BEP.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_BEP.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_BEP.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_BEP.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_EMGERPI_COMEPI.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_COMEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_COMEPI.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_COMEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_COMEPI.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_COMEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_COMEPI.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_COMEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_EMGERPI_COMEPI.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_COMEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_EMGERPI_COMDEPI.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_COMDEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_COMDEPI.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_COMDEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_COMDEPI.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_COMDEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_COMDEPI.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_COMDEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_EMGERPI_COMDEPI.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_COMDEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_EMGERPI_COHAB.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_COHAB.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_COHAB.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_COHAB.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_COHAB.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_COHAB.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_COHAB.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_COHAB.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_EMGERPI_COHAB.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_COHAB.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_EMGERPI_PRODEPI.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_PRODEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_PRODEPI.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_PRODEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_PRODEPI.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_PRODEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_PRODEPI.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_PRODEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_EMGERPI_PRODEPI.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_PRODEPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_EMGERPI_CEASA.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_CEASA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_CEASA.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_CEASA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_CEASA.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_CEASA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_CEASA.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_CEASA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_EMGERPI_CEASA.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_CEASA.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_EMGERPI_PIEMTUR.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_PIEMTUR.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_PIEMTUR.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_PIEMTUR.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_PIEMTUR.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_PIEMTUR.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_PIEMTUR.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_PIEMTUR.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_EMGERPI_PIEMTUR.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_PIEMTUR.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_EMGERPI_ETELPI_FUNART.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_ETELPI_FUNART.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_ETELPI_FUNART.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_ETELPI_FUNART.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_ETELPI_FUNART.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_ETELPI_FUNART.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_ETELPI_FUNART.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_ETELPI_FUNART.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_EMGERPI_ETELPI_FUNART.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_ETELPI_FUNART.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_EMGERPI_CIDAPI.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_CIDAPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_CIDAPI.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_CIDAPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_CIDAPI.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_CIDAPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_CIDAPI.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_CIDAPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_EMGERPI_CIDAPI.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_CIDAPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_SEDUC.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEDUC.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEDUC.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEDUC.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEDUC.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEDUC.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_SEDUC.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEDUC.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_SEDUC.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_SEDUC.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_EMGERPI.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_EMGERPI.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');

DELETE FROM SW_EMGERPI_CODIPI.FOLHA_CONTRACHEQUE WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_CODIPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_CODIPI.FOLHA_FICHA_FINANCEIRA WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_CODIPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_CODIPI.FOLHA_ARQUIVO_CRED_BANCARIO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_CODIPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
DELETE FROM SW_EMGERPI_CODIPI.FOLHA_FECHAMENTO_IMG_CREDITO WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_CODIPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
UPDATE SW_EMGERPI_CODIPI.FOLHA SET DATA_FECHAMENTO = NULL WHERE ID_FOLHA IN (SELECT ID_FOLHA FROM SW_EMGERPI_CODIPI.FOLHA WHERE CHAVE_FOLHA = '03/2026-100');
