-- Excluir Perfis Incorretos #6166
SELECT 
    'SEDUC' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PTM.NOME_MOVIMENTACAO,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM,
    TI.NOME_TIPO_INCIDENCIA,
    IR.NOME_REMUNERACAO,
    'DELETE FROM SW_SEDUC.FUNCIONARIO_PERFIL WHERE ID_FUNCIONARIO_PERFIL = ' || FP.ID_FUNCIONARIO_PERFIL || ';' AS DELETE_
FROM
    SW_SEDUC.PESSOA_VINCULO PV
    JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SEDUC.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SEDUC.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.RHB_PERFIL_TIPO_FUNCIONARIO PTF ON PTF.ID_TIPO_FUNCIONARIO = FP.ID_TIPO_FUNCIONARIO
    JOIN SW_PUBLICO.RHB_PERFIL_TIPO_MOVIMENTACAO PTM ON PTM.ID_MOVIMENTACAO = FP.ID_MOVIMENTACAO
    JOIN SW_PUBLICO.RHB_INGRESSO_REMUNERACAO IR ON IR.ID_REMUNERACAO = FP.ID_REMUNERACAO
    JOIN SW_PUBLICO.FOLHA_TAB_TIPO_INCIDENCIA TI ON TI.ID_TIPO_INCIDENCIA = FP.ID_TIPO_INCIDENCIA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE 
    FP.ID_FUNCIONARIO_PERFIL IN (1213908, 1213894);
    
SELECT 
    'SEDUC' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    FP.ID_FUNCIONARIO_PERFIL,
    PTM.NOME_MOVIMENTACAO,
    PD.NOME_DIVISAO,
    PS.NOME_SITUACAO,
    FP.DATA_INICIO,
    FP.DATA_FIM,
    TI.NOME_TIPO_INCIDENCIA,
    IR.NOME_REMUNERACAO,
    'UPDATE SW_SEDUC.FUNCIONARIO_PERFIL SET DATA_FIM = NULL WHERE ID_FUNCIONARIO_PERFIL = ' || FP.ID_FUNCIONARIO_PERFIL || ';' AS UPDATE_
FROM
    SW_SEDUC.PESSOA_VINCULO PV
    JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SEDUC.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SEDUC.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
    JOIN SW_PUBLICO.RHB_PERFIL_SITUACAO PS ON PS.ID_SITUACAO = P.ID_SITUACAO
    JOIN SW_PUBLICO.RHB_PERFIL_TIPO_FUNCIONARIO PTF ON PTF.ID_TIPO_FUNCIONARIO = FP.ID_TIPO_FUNCIONARIO
    JOIN SW_PUBLICO.RHB_PERFIL_TIPO_MOVIMENTACAO PTM ON PTM.ID_MOVIMENTACAO = FP.ID_MOVIMENTACAO
    JOIN SW_PUBLICO.RHB_INGRESSO_REMUNERACAO IR ON IR.ID_REMUNERACAO = FP.ID_REMUNERACAO
    JOIN SW_PUBLICO.FOLHA_TAB_TIPO_INCIDENCIA TI ON TI.ID_TIPO_INCIDENCIA = FP.ID_TIPO_INCIDENCIA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA
WHERE 
    FP.ID_FUNCIONARIO_PERFIL =  1206601;
    
SELECT
    *
FROM
    ALL_CONSTRAINTS
WHERE
    CONSTRAINT_NAME = 'FK_FOLHA_FUNC_PERFIL_RH'
    AND OWNER = 'SW_SEDUC';

-- Baixa de CPF #6128

SELECT 
    'SEDUC' ORGAO,
    HN.NOME,
    PC.CPF_PESSOA,
    PC.DATA_BAIXA,
    PC.ID_CPF,
    'UPDATE SW_PUBLICO.PESSOA_DOC_CPF SET DATA_BAIXA = ''30/03/2026'' WHERE PC.ID_CPF = ' || PC.ID_CPF || ';' AS UPDATE_
FROM 
    SW_PUBLICO.PESSOA_DOC_CPF PC 
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PC.ID_PESSOA
WHERE 
    PC.ID_CPF = '1236742';
    


    
       
    