-- PROFESSORES 40H

SELECT 
    'SEDUC' AS ORGAO,
    FO.MES,
    FO.ANO,
    SUBSTR(FO.CHAVE_FOLHA, 9) COD_FOLHA,
    FO.DESCRICAO AS DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA AS REFERENCIA,
    CC.NOME_CLASSE AS CLASSE,
    CP.NOME_PADRAO AS PADRAO,
    CN.NOME_NIVEL AS NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA,
    NR_MAR.VALOR_REFERENCIA AS VALOR_REFERENCIA_MARCO,
    FFR.VALOR_CALCULADO,
    FFR_MAR.VALOR_CALCULADO AS VALOR_CALCULADO_MARCO

FROM
    SW_SEDUC.FOLHA FO
    
    JOIN SW_SEDUC.FOLHA_FUNC FF
    ON FF.ID_FOLHA = FO.ID_FOLHA

    JOIN SW_SEDUC.FOLHA_FUNC_RUBRICA FFR 
        ON FFR.ID_FOLHA = FO.ID_FOLHA
        
    JOIN SW_SEDUC.FOLHA_VALOR_NIVEL_REFERENCIA NR 
        ON NR.ID_FOLHA = FO.ID_FOLHA
        
    JOIN SW_SEDUC.RHB_CARREIRA_REFERENCIA CR 
        ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
        
    LEFT JOIN SW_SEDUC.RHB_CARREIRA_PADRAO CP 
        ON CP.ID_PADRAO = CR.ID_PADRAO
        
    LEFT JOIN SW_SEDUC.RHB_CARREIRA_CLASSE CC 
        ON CC.ID_CLASSE = CR.ID_CLASSE
        
    LEFT JOIN SW_SEDUC.RHB_CARREIRA_NIVEL CN 
        ON CN.ID_NIVEL = CR.ID_NIVEL
        
    LEFT JOIN (
        SELECT 
            FFR.ID_FUNCIONARIO,
            FFR.ID_RUBRICA,
            FFR.VALOR_CALCULADO
        FROM SW_SEDUC.FOLHA FO
        JOIN SW_SEDUC.FOLHA_FUNC_RUBRICA FFR 
            ON FFR.ID_FOLHA = FO.ID_FOLHA
        WHERE 
            FO.ID_TIPO_FOLHA = 1000000
            AND FO.MES = 3
            AND FO.ANO = 2026
    ) FFR_MAR
        ON FFR_MAR.ID_FUNCIONARIO = FFR.ID_FUNCIONARIO
        AND FFR_MAR.ID_RUBRICA = FFR.ID_RUBRICA  
    LEFT JOIN (
        SELECT 
            NR.ID_REFERENCIA,
            NR.VALOR_REFERENCIA
        FROM SW_SEDUC.FOLHA FO
        JOIN SW_SEDUC.FOLHA_VALOR_NIVEL_REFERENCIA NR 
            ON NR.ID_FOLHA = FO.ID_FOLHA
        WHERE 
            FO.ID_TIPO_FOLHA = 1000000
            AND FO.MES = 3
            AND FO.ANO = 2026
    ) NR_MAR
        ON NR_MAR.ID_REFERENCIA = NR.ID_REFERENCIA 

WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 4
    AND FO.ANO = 2026
    AND CR.ID_REFERENCIA IN (45, 49, 50, 51, 52, 1, 2, 3, 4, 5, 6, 7, 8, 13, 17, 18, 19, 20, 29, 33, 34, 35, 36, 61, 65, 66, 67, 68);

-- UPDATE PROFESSORES 40H
UPDATE SW_SEDUC.FOLHA_VALOR_NIVEL_REFERENCIA NR
SET NR.VALOR_REFERENCIA = CASE 
    -- CLASSE A e B (I ao IV)
    WHEN CC.NOME_CLASSE = 'A' AND CP.NOME_PADRAO = 'I'   THEN 5226.25
    WHEN CC.NOME_CLASSE = 'A' AND CP.NOME_PADRAO = 'II'  THEN 5226.25
    WHEN CC.NOME_CLASSE = 'A' AND CP.NOME_PADRAO = 'III' THEN 5226.25
    WHEN CC.NOME_CLASSE = 'A' AND CP.NOME_PADRAO = 'IV'  THEN 5226.25
    WHEN CC.NOME_CLASSE = 'B' AND CP.NOME_PADRAO = 'I'   THEN 5226.25
    WHEN CC.NOME_CLASSE = 'B' AND CP.NOME_PADRAO = 'II'  THEN 5226.25
    WHEN CC.NOME_CLASSE = 'B' AND CP.NOME_PADRAO = 'III' THEN 5226.25
    WHEN CC.NOME_CLASSE = 'B' AND CP.NOME_PADRAO = 'IV'  THEN 5226.25
    -- CLASSE SL (I ao IV)
    WHEN CC.NOME_CLASSE = 'SL' AND CP.NOME_PADRAO = 'I'   THEN 5288.21
    WHEN CC.NOME_CLASSE = 'SL' AND CP.NOME_PADRAO = 'II'  THEN 5350.66
    WHEN CC.NOME_CLASSE = 'SL' AND CP.NOME_PADRAO = 'III' THEN 5413.55
    WHEN CC.NOME_CLASSE = 'SL' AND CP.NOME_PADRAO = 'IV'  THEN 5476.94
    -- CLASSE SE (I ao IV)
    WHEN CC.NOME_CLASSE = 'SE' AND CP.NOME_PADRAO = 'I'  THEN 5540.79
    WHEN CC.NOME_CLASSE = 'SE' AND CP.NOME_PADRAO = 'II' THEN 5624.68
    WHEN CC.NOME_CLASSE = 'SE' AND CP.NOME_PADRAO = 'III' THEN 5808.36
    WHEN CC.NOME_CLASSE = 'SE' AND CP.NOME_PADRAO = 'IV' THEN 5994.67
    -- CLASSE SM (I ao IV)
    WHEN CC.NOME_CLASSE = 'SM' AND CP.NOME_PADRAO = 'I'  THEN 6066.83
    WHEN CC.NOME_CLASSE = 'SM' AND CP.NOME_PADRAO = 'II' THEN 6343.25
    WHEN CC.NOME_CLASSE = 'SM' AND CP.NOME_PADRAO = 'III' THEN 6622.02
    WHEN CC.NOME_CLASSE = 'SM' AND CP.NOME_PADRAO = 'IV' THEN 6902.99
    -- CLASSE SD (I ao IV)
    WHEN CC.NOME_CLASSE = 'SD' AND CP.NOME_PADRAO = 'I'  THEN 7513.47
    WHEN CC.NOME_CLASSE = 'SD' AND CP.NOME_PADRAO = 'II' THEN 8137.36
    WHEN CC.NOME_CLASSE = 'SD' AND CP.NOME_PADRAO = 'III' THEN 8867.00
    WHEN CC.NOME_CLASSE = 'SD' AND CP.NOME_PADRAO = 'IV' THEN 9509.50
END
FROM SW_SEDUC.FOLHA_VALOR_NIVEL_REFERENCIA NR
JOIN SW_SEDUC.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
LEFT JOIN SW_SEDUC.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
LEFT JOIN SW_SEDUC.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
WHERE NR.ID_FOLHA IN (
    SELECT FO.ID_FOLHA
    FROM SW_SEDUC.FOLHA FO
    WHERE FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 4
    AND FO.ANO = 2026
)
AND NR.ID_REFERENCIA IN (45, 49, 50, 51, 52, 1, 2, 3, 4, 5, 6, 7, 8, 13, 17, 18, 19, 20, 29, 33, 34, 35, 36, 61, 65, 66, 67, 68);

-- PROFESSORES 20H 
SELECT 
    'SEDUC' AS ORGAO,
    FO.MES,
    FO.ANO,
    SUBSTR(FO.CHAVE_FOLHA, 9) COD_FOLHA,
    FO.DESCRICAO AS DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA AS REFERENCIA,
    CC.NOME_CLASSE AS CLASSE,
    CP.NOME_PADRAO AS PADRAO,
    CN.NOME_NIVEL AS NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA,
    NR_MAR.VALOR_REFERENCIA AS VALOR_REFERENCIA_MARCO,
    FFR.VALOR_CALCULADO,
    FFR_MAR.VALOR_CALCULADO AS VALOR_CALCULADO_MARCO
FROM
    SW_SEDUC.FOLHA FO
    
    JOIN SW_SEDUC.FOLHA_FUNC FF
    ON FF.ID_FOLHA = FO.ID_FOLHA

    JOIN SW_SEDUC.FOLHA_FUNC_RUBRICA FFR 
        ON FFR.ID_FOLHA = FO.ID_FOLHA
        
    JOIN SW_SEDUC.FOLHA_VALOR_NIVEL_REFERENCIA NR 
        ON NR.ID_FOLHA = FO.ID_FOLHA
        
    JOIN SW_SEDUC.RHB_CARREIRA_REFERENCIA CR 
        ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
        
    LEFT JOIN SW_SEDUC.RHB_CARREIRA_PADRAO CP 
        ON CP.ID_PADRAO = CR.ID_PADRAO
        
    LEFT JOIN SW_SEDUC.RHB_CARREIRA_CLASSE CC 
        ON CC.ID_CLASSE = CR.ID_CLASSE
        
    LEFT JOIN SW_SEDUC.RHB_CARREIRA_NIVEL CN 
        ON CN.ID_NIVEL = CR.ID_NIVEL
        
    LEFT JOIN (
        SELECT 
            FFR.ID_FUNCIONARIO,
            FFR.ID_RUBRICA,
            FFR.VALOR_CALCULADO
        FROM SW_SEDUC.FOLHA FO
        JOIN SW_SEDUC.FOLHA_FUNC_RUBRICA FFR 
            ON FFR.ID_FOLHA = FO.ID_FOLHA
        WHERE 
            FO.ID_TIPO_FOLHA = 1000000
            AND FO.MES = 3
            AND FO.ANO = 2026
    ) FFR_MAR
        ON FFR_MAR.ID_FUNCIONARIO = FFR.ID_FUNCIONARIO
        AND FFR_MAR.ID_RUBRICA = FFR.ID_RUBRICA  
    LEFT JOIN (
        SELECT 
            NR.ID_REFERENCIA,
            NR.VALOR_REFERENCIA
        FROM SW_SEDUC.FOLHA FO
        JOIN SW_SEDUC.FOLHA_VALOR_NIVEL_REFERENCIA NR 
            ON NR.ID_FOLHA = FO.ID_FOLHA
        WHERE 
            FO.ID_TIPO_FOLHA = 1000000
            AND FO.MES = 3
            AND FO.ANO = 2026
    ) NR_MAR
        ON NR_MAR.ID_REFERENCIA = NR.ID_REFERENCIA   
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 4
    AND FO.ANO = 2026
    AND CR.ID_REFERENCIA IN (117, 121, 122, 123, 124, 73, 74, 75, 76, 77, 78, 79, 80, 85, 89, 90, 91, 92, 101, 105, 106, 107, 108, 133, 137, 138, 139, 140);

-- UPDATE PROFESSORES 20H
UPDATE SW_SEDUC.FOLHA_VALOR_NIVEL_REFERENCIA NR
SET NR.VALOR_REFERENCIA = CASE 
    -- CLASSE A e B (I ao IV)
    WHEN CC.NOME_CLASSE = 'A' AND CP.NOME_PADRAO = 'I'   THEN 2613.13
    WHEN CC.NOME_CLASSE = 'A' AND CP.NOME_PADRAO = 'II'  THEN 2613.13
    WHEN CC.NOME_CLASSE = 'A' AND CP.NOME_PADRAO = 'III' THEN 2613.13
    WHEN CC.NOME_CLASSE = 'A' AND CP.NOME_PADRAO = 'IV'  THEN 2613.13
    WHEN CC.NOME_CLASSE = 'B' AND CP.NOME_PADRAO = 'I'   THEN 2613.13
    WHEN CC.NOME_CLASSE = 'B' AND CP.NOME_PADRAO = 'II'  THEN 2613.13
    WHEN CC.NOME_CLASSE = 'B' AND CP.NOME_PADRAO = 'III' THEN 2613.13
    WHEN CC.NOME_CLASSE = 'B' AND CP.NOME_PADRAO = 'IV'  THEN 2613.13
    -- CLASSE SL (I ao IV)
    WHEN CC.NOME_CLASSE = 'SL' AND CP.NOME_PADRAO = 'I'   THEN 2644.11
    WHEN CC.NOME_CLASSE = 'SL' AND CP.NOME_PADRAO = 'II'  THEN 2675.33
    WHEN CC.NOME_CLASSE = 'SL' AND CP.NOME_PADRAO = 'III' THEN 2706.78
    WHEN CC.NOME_CLASSE = 'SL' AND CP.NOME_PADRAO = 'IV'  THEN 2738.47
    -- CLASSE SE (I ao IV)
    WHEN CC.NOME_CLASSE = 'SE' AND CP.NOME_PADRAO = 'I'  THEN 2770.40
    WHEN CC.NOME_CLASSE = 'SE' AND CP.NOME_PADRAO = 'II' THEN 2812.34
    WHEN CC.NOME_CLASSE = 'SE' AND CP.NOME_PADRAO = 'III' THEN 2904.18
    WHEN CC.NOME_CLASSE = 'SE' AND CP.NOME_PADRAO = 'IV' THEN 2997.34
    -- CLASSE SM (I ao IV)
    WHEN CC.NOME_CLASSE = 'SM' AND CP.NOME_PADRAO = 'I'  THEN 3033.42
    WHEN CC.NOME_CLASSE = 'SM' AND CP.NOME_PADRAO = 'II' THEN 3171.63
    WHEN CC.NOME_CLASSE = 'SM' AND CP.NOME_PADRAO = 'III' THEN 3311.01
    WHEN CC.NOME_CLASSE = 'SM' AND CP.NOME_PADRAO = 'IV' THEN 3451.50
    -- CLASSE SD (I ao IV)
    WHEN CC.NOME_CLASSE = 'SD' AND CP.NOME_PADRAO = 'I'  THEN 3756.74
    WHEN CC.NOME_CLASSE = 'SD' AND CP.NOME_PADRAO = 'II' THEN 4093.69
    WHEN CC.NOME_CLASSE = 'SD' AND CP.NOME_PADRAO = 'III' THEN 4433.50
    WHEN CC.NOME_CLASSE = 'SD' AND CP.NOME_PADRAO = 'IV' THEN 4754.75
END
FROM SW_SEDUC.FOLHA_VALOR_NIVEL_REFERENCIA NR
JOIN SW_SEDUC.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
LEFT JOIN SW_SEDUC.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
LEFT JOIN SW_SEDUC.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
WHERE NR.ID_FOLHA IN (
    SELECT FO.ID_FOLHA
    FROM SW_SEDUC.FOLHA FO
    WHERE FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 4
    AND FO.ANO = 2026
)
AND NR.ID_REFERENCIA IN (117, 121, 122, 123, 124, 73, 74, 75, 76, 77, 78, 79, 80, 85, 89, 90, 91, 92, 101, 105, 106, 107, 108, 133, 137, 138, 139, 140);
