SELECT 
    'SEJUSPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_SEJUSPI.FOLHA FO
    JOIN SW_SEJUSPI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEJUSPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_SEJUSPI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_SEJUSPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_SEJUSPI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 4
    AND FO.ANO = 2026
    AND FO.CHAVE_FOLHA = '04/2026-100';
    
SELECT 
    'SSPPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_SSPPI.FOLHA FO
    JOIN SW_SSPPI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SSPPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_SSPPI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_SSPPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_SSPPI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 4
    AND FO.ANO = 2026
    AND FO.CHAVE_FOLHA = '04/2026-100';
    
SELECT 
    'PMPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_PMPI.FOLHA FO
    JOIN SW_PMPI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PMPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_PMPI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_PMPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_PMPI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 4
    AND FO.ANO = 2026
    AND FO.CHAVE_FOLHA = '04/2026-100';

SELECT 
    'CBMPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_CBMPI.FOLHA FO
    JOIN SW_CBMPI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CBMPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_CBMPI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_CBMPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_CBMPI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 4
    AND FO.ANO = 2026
    AND FO.CHAVE_FOLHA = '04/2026-100';
    
SELECT DISTINCT
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA,
    FO.CHAVE_FOLHA,
    CC.NOME_CLASSE,
    CP.NOME_PADRAO,
    CN.NOME_NIVEL,
    NR.VALOR_REFERENCIA
FROM
    SW_SSPPI.FOLHA FO
    JOIN SW_SSPPI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SSPPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_SSPPI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_SSPPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_SSPPI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 4
    AND FO.ANO = 2026
    --AND CR.NOME_REFERENCIA = 'NF-Ag.Penit'
ORDER BY CC.NOME_CLASSE, CP.NOME_PADRAO;

