SELECT 
    'SEDUC' ORGAO,
    TA.CODIGO,
    HN.NOME,
    PC.CPF_PESSOA CPF,
    PV.COD_INSTITUCIONAL MATRICULA,
    EE.ID_ESOCIAL_EVENTO,
    EE.CHAVE_VOBYS,
    CASE
        WHEN EE.STATUS_VOBYS = 'P' THEN 'Pendente'
        WHEN EE.STATUS_VOBYS = 'A' THEN 'Assinado'
        WHEN EE.STATUS_VOBYS = 'T' THEN 'Transmitido'
        WHEN EE.STATUS_VOBYS = 'E' THEN 'Erro'
        WHEN EE.STATUS_VOBYS = 'R' THEN 'Aprovado'
        WHEN EE.STATUS_VOBYS = 'G' THEN 'Aguardando Processamento'
        WHEN EE.STATUS_VOBYS = 'M' THEN 'Em preenchimento'
        WHEN EE.STATUS_VOBYS = 'X' THEN 'Excluido'
    END STATUS,
    /*

    'https://siape.sead.pi.gov.br/org/pmpi/esocial/envio/eventos/evento/' || EE.ID_ESOCIAL_EVENTO LINK,
    'DELETE FROM SW_SEDUC.ESOCIAL_TRANSMISSAO WHERE ID_ESOCIAL_EVENTO IN (SELECT ID_ESOCIAL_EVENTO FROM SW_SEDUC.ESOCIAL_EVENTO WHERE ID_ESOCIAL_EVENTO = ' || EE.ID_ESOCIAL_EVENTO || ');' AS DELETE_1,
    'DELETE FROM SW_SEDUC.ESOCIAL_EVENTO_OCORRENCIA WHERE ID_ESOCIAL_EVENTO IN (SELECT ID_ESOCIAL_EVENTO FROM SW_SEDUC.ESOCIAL_EVENTO WHERE ID_ESOCIAL_EVENTO = ' || EE.ID_ESOCIAL_EVENTO || ');' AS DELETE_2,
    'DELETE FROM SW_SEDUC.ESOCIAL_EVENTO_ATRIBUTO WHERE ID_ESOCIAL_EVENTO IN (SELECT ID_ESOCIAL_EVENTO FROM SW_SEDUC.ESOCIAL_EVENTO WHERE ID_ESOCIAL_EVENTO = ' || EE.ID_ESOCIAL_EVENTO || ');' AS DELETE_3,
    'DELETE FROM SW_SEDUC.ESOCIAL_EVENTO WHERE ID_ESOCIAL_EVENTO IN (SELECT ID_ESOCIAL_EVENTO FROM SW_SEDUC.ESOCIAL_EVENTO WHERE ID_ESOCIAL_EVENTO = ' || EE.ID_ESOCIAL_EVENTO || ');' AS DELETE_4,

    */
    FD.DATA_DESLIGAMENTO,
    PA.DATA_APOSENTADORIA 
FROM
    SW_SEDUC.ESOCIAL_EVENTO EE 
    JOIN SW_SEDUC.PESSOA_VINCULO PV ON PV.ID_PESSOA_VINCULO = EE.CHAVE_VOBYS
    JOIN SW_FUNPREV.PESSOA_VINCULO PV2 ON PV2.COD_INSTITUCIONAL = PV.COD_INSTITUCIONAL
    JOIN SW_SEDUC.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    LEFT JOIN SW_SEDUC.FUNC_DESLIGAMENTO FD ON FD.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    LEFT JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT PA ON PA.ID_PESSOA = PV.ID_PESSOA AND PA.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    --JOIN SW_PUBLICO.PREV_PROP_ORGAO_ORIGEM PO ON PO.ID_PREV_ORIGEM =  PA.ID_PREV_ORIGEM
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = PV.ID_PESSOA AND HN.DATA_FIM IS NULL
    JOIN SW_PUBLICO.PESSOA_DOC_CPF PC ON PC.ID_PESSOA = PV.ID_PESSOA AND PC.DATA_BAIXA IS NULL
    JOIN SW_PUBLICO.ESB_TIPO_ARQUIVO_ESOCIAL TA ON TA.ID_ESB_TIPO_ARQUIVO_ESOCIAL = EE.ID_ESOCIAL_TIPO_ARQUIVO
WHERE
    TA.CODIGO IN ('S-2200')
    AND EE.STATUS_VOBYS IN ('P', 'E')
    --AND FD.DATA_DESLIGAMENTO <= TO_DATE('21/11/2021', 'DD/MM/YYYY')
    --AND PA.DATA_APOSENTADORIA <= TO_DATE('21/11/2021', 'DD/MM/YYYY')
    --AND PO.ID_EMPRESA = 58
    ;