SELECT 
    'EMPRESA' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_EMPRESA.FOLHA FO
    JOIN SW_EMPRESA.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMPRESA.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_EMPRESA.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_EMPRESA.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_EMPRESA.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'CBMPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_CBMPI.FOLHA FO
    JOIN SW_CBMPI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CBMPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_CBMPI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_CBMPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_CBMPI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'PGEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_PGEPI.FOLHA FO
    JOIN SW_PGEPI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PGEPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_PGEPI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_PGEPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_PGEPI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'CGEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_CGEPI.FOLHA FO
    JOIN SW_CGEPI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CGEPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_CGEPI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_CGEPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_CGEPI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'SSPPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_SSPPI.FOLHA FO
    JOIN SW_SSPPI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SSPPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_SSPPI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_SSPPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_SSPPI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'COJUV' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_COJUV.FOLHA FO
    JOIN SW_COJUV.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_COJUV.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_COJUV.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_COJUV.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_COJUV.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'ATIPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_ATIPI.FOLHA FO
    JOIN SW_ATIPI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_ATIPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_ATIPI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_ATIPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_ATIPI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'FAPEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_FAPEPI.FOLHA FO
    JOIN SW_FAPEPI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FAPEPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_FAPEPI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_FAPEPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_FAPEPI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'DEFCIVIL' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_DEFCIVIL.FOLHA FO
    JOIN SW_DEFCIVIL.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_DEFCIVIL.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_DEFCIVIL.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_DEFCIVIL.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_DEFCIVIL.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'ADH' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_ADH.FOLHA FO
    JOIN SW_ADH.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_ADH.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_ADH.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_ADH.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_ADH.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'SEAGRO' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_SEAGRO.FOLHA FO
    JOIN SW_SEAGRO.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEAGRO.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_SEAGRO.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_SEAGRO.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_SEAGRO.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'IDEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_IDEPI.FOLHA FO
    JOIN SW_IDEPI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_IDEPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_IDEPI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_IDEPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_IDEPI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'SURPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_SURPI.FOLHA FO
    JOIN SW_SURPI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SURPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_SURPI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_SURPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_SURPI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'SEID' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_SEID.FOLHA FO
    JOIN SW_SEID.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEID.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_SEID.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_SEID.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_SEID.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'SECID' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_SECID.FOLHA FO
    JOIN SW_SECID.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SECID.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_SECID.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_SECID.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_SECID.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'FUPIP' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_FUPIP.FOLHA FO
    JOIN SW_FUPIP.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUPIP.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_FUPIP.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_FUPIP.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_FUPIP.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'SETUR' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_SETUR.FOLHA FO
    JOIN SW_SETUR.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SETUR.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_SETUR.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_SETUR.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_SETUR.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'AGESPISA' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_AGESPISA.FOLHA FO
    JOIN SW_AGESPISA.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_AGESPISA.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_AGESPISA.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_AGESPISA.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_AGESPISA.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'SETRANS' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_SETRANS.FOLHA FO
    JOIN SW_SETRANS.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SETRANS.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_SETRANS.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_SETRANS.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_SETRANS.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'TVANTARES' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_TVANTARES.FOLHA FO
    JOIN SW_TVANTARES.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_TVANTARES.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_TVANTARES.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_TVANTARES.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_TVANTARES.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'VICEGOV' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_VICEGOV.FOLHA FO
    JOIN SW_VICEGOV.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_VICEGOV.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_VICEGOV.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_VICEGOV.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_VICEGOV.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'SEINFRA' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_SEINFRA.FOLHA FO
    JOIN SW_SEINFRA.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEINFRA.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_SEINFRA.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_SEINFRA.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_SEINFRA.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'CCOM' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_CCOM.FOLHA FO
    JOIN SW_CCOM.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CCOM.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_CCOM.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_CCOM.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_CCOM.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'FUNDESPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_FUNDESPI.FOLHA FO
    JOIN SW_FUNDESPI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUNDESPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_FUNDESPI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_FUNDESPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_FUNDESPI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'SEDET' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_SEDET.FOLHA FO
    JOIN SW_SEDET.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEDET.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_SEDET.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_SEDET.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_SEDET.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'INTERPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_INTERPI.FOLHA FO
    JOIN SW_INTERPI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_INTERPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_INTERPI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_INTERPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_INTERPI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'JUCEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_JUCEPI.FOLHA FO
    JOIN SW_JUCEPI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_JUCEPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_JUCEPI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_JUCEPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_JUCEPI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'SEMAR' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_SEMAR.FOLHA FO
    JOIN SW_SEMAR.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEMAR.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_SEMAR.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_SEMAR.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_SEMAR.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'GMG' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_GMG.FOLHA FO
    JOIN SW_GMG.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_GMG.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_GMG.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_GMG.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_GMG.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'SEPLAN' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_SEPLAN.FOLHA FO
    JOIN SW_SEPLAN.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEPLAN.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_SEPLAN.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_SEPLAN.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_SEPLAN.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'SAF' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_SAF.FOLHA FO
    JOIN SW_SAF.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SAF.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_SAF.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_SAF.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_SAF.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'SECULT' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_SECULT.FOLHA FO
    JOIN SW_SECULT.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SECULT.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_SECULT.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_SECULT.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_SECULT.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'DER' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_DER.FOLHA FO
    JOIN SW_DER.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_DER.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_DER.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_DER.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_DER.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'DETRAN' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_DETRAN.FOLHA FO
    JOIN SW_DETRAN.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_DETRAN.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_DETRAN.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_DETRAN.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_DETRAN.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'IASPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_IASPI.FOLHA FO
    JOIN SW_IASPI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_IASPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_IASPI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_IASPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_IASPI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'ADAPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_ADAPI.FOLHA FO
    JOIN SW_ADAPI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_ADAPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_ADAPI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_ADAPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_ADAPI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'IMEPIPROD' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_IMEPIPROD.FOLHA FO
    JOIN SW_IMEPIPROD.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_IMEPIPROD.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_IMEPIPROD.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_IMEPIPROD.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_IMEPIPROD.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'CPVCI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_CPVCI.FOLHA FO
    JOIN SW_CPVCI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CPVCI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_CPVCI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_CPVCI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_CPVCI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'CENDROGAS' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_CENDROGAS.FOLHA FO
    JOIN SW_CENDROGAS.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CENDROGAS.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_CENDROGAS.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_CENDROGAS.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_CENDROGAS.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'COFIR' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_COFIR.FOLHA FO
    JOIN SW_COFIR.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_COFIR.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_COFIR.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_COFIR.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_COFIR.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'SEMINPER' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_SEMINPER.FOLHA FO
    JOIN SW_SEMINPER.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEMINPER.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_SEMINPER.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_SEMINPER.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_SEMINPER.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'AGRESP' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_AGRESP.FOLHA FO
    JOIN SW_AGRESP.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_AGRESP.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_AGRESP.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_AGRESP.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_AGRESP.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'CEPM' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_CEPM.FOLHA FO
    JOIN SW_CEPM.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CEPM.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_CEPM.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_CEPM.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_CEPM.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'EMATER' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_EMATER.FOLHA FO
    JOIN SW_EMATER.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMATER.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_EMATER.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_EMATER.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_EMATER.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'FUESPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_FUESPI.FOLHA FO
    JOIN SW_FUESPI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUESPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_FUESPI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_FUESPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_FUESPI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
    AND CR.ID_REFERENCIA NOT IN (100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175)
UNION ALL        
SELECT 
    'EMATERPROD' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_EMATERPROD.FOLHA FO
    JOIN SW_EMATERPROD.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMATERPROD.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_EMATERPROD.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_EMATERPROD.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_EMATERPROD.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'DEFENSORIA' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_DEFENSORIA.FOLHA FO
    JOIN SW_DEFENSORIA.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_DEFENSORIA.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_DEFENSORIA.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_DEFENSORIA.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_DEFENSORIA.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'PENSIONISTAS' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_PENSIONISTAS.FOLHA FO
    JOIN SW_PENSIONISTAS.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PENSIONISTAS.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_PENSIONISTAS.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_PENSIONISTAS.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_PENSIONISTAS.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'CDTER' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_CDTER.FOLHA FO
    JOIN SW_CDTER.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CDTER.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_CDTER.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_CDTER.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_CDTER.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'SERES' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_SERES.FOLHA FO
    JOIN SW_SERES.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SERES.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_SERES.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_SERES.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_SERES.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'SECESP' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_SECESP.FOLHA FO
    JOIN SW_SECESP.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SECESP.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_SECESP.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_SECESP.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_SECESP.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'INATIVOS_PENSIONISTAS' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_INATIVOS_PENSIONISTAS.FOLHA FO
    JOIN SW_INATIVOS_PENSIONISTAS.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_INATIVOS_PENSIONISTAS.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_INATIVOS_PENSIONISTAS.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_INATIVOS_PENSIONISTAS.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_INATIVOS_PENSIONISTAS.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'SEDUC_PRECATORIO' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_SEDUC_PRECATORIO.FOLHA FO
    JOIN SW_SEDUC_PRECATORIO.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEDUC_PRECATORIO.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_SEDUC_PRECATORIO.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_SEDUC_PRECATORIO.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_SEDUC_PRECATORIO.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'EMGERPI_CORESA' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_EMGERPI_CORESA.FOLHA FO
    JOIN SW_EMGERPI_CORESA.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_CORESA.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_EMGERPI_CORESA.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_EMGERPI_CORESA.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_EMGERPI_CORESA.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'FUNPREV' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_FUNPREV.FOLHA FO
    JOIN SW_FUNPREV.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUNPREV.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_FUNPREV.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_FUNPREV.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_FUNPREV.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'FESPPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_FESPPI.FOLHA FO
    JOIN SW_FESPPI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FESPPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_FESPPI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_FESPPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_FESPPI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'SIA' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_SIA.FOLHA FO
    JOIN SW_SIA.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SIA.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_SIA.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_SIA.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_SIA.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'SETRE' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_SETRE.FOLHA FO
    JOIN SW_SETRE.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SETRE.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_SETRE.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_SETRE.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_SETRE.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'SEGOV' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEGOV.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_SEGOV.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_SEGOV.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_SEGOV.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'SASC' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_SASC.FOLHA FO
    JOIN SW_SASC.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SASC.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_SASC.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_SASC.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_SASC.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'METRO' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_METRO.FOLHA FO
    JOIN SW_METRO.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_METRO.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_METRO.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_METRO.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_METRO.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'PIAUIPREV' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_PIAUIPREV.FOLHA FO
    JOIN SW_PIAUIPREV.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PIAUIPREV.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_PIAUIPREV.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_PIAUIPREV.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_PIAUIPREV.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'INATIVOS_SEDUC' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_INATIVOS_SEDUC.FOLHA FO
    JOIN SW_INATIVOS_SEDUC.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_INATIVOS_SEDUC.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_INATIVOS_SEDUC.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_INATIVOS_SEDUC.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_INATIVOS_SEDUC.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'INATIVOS_TCE' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_INATIVOS_TCE.FOLHA FO
    JOIN SW_INATIVOS_TCE.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_INATIVOS_TCE.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_INATIVOS_TCE.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_INATIVOS_TCE.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_INATIVOS_TCE.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'SADA' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_SADA.FOLHA FO
    JOIN SW_SADA.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SADA.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_SADA.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_SADA.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_SADA.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'SECMULHERES' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_SECMULHERES.FOLHA FO
    JOIN SW_SECMULHERES.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SECMULHERES.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_SECMULHERES.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_SECMULHERES.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_SECMULHERES.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'EMGERPI_EMATER' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_EMGERPI_EMATER.FOLHA FO
    JOIN SW_EMGERPI_EMATER.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_EMATER.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_EMGERPI_EMATER.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_EMGERPI_EMATER.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_EMGERPI_EMATER.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'REENVIO' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_REENVIO.FOLHA FO
    JOIN SW_REENVIO.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_REENVIO.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_REENVIO.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_REENVIO.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_REENVIO.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'SESAPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_SESAPI.FOLHA FO
    JOIN SW_SESAPI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SESAPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_SESAPI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_SESAPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_SESAPI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'PMPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_PMPI.FOLHA FO
    JOIN SW_PMPI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PMPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_PMPI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_PMPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_PMPI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'SEJUSPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_SEJUSPI.FOLHA FO
    JOIN SW_SEJUSPI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEJUSPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_SEJUSPI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_SEJUSPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_SEJUSPI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'SEFAZPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_SEFAZPI.FOLHA FO
    JOIN SW_SEFAZPI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEFAZPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_SEFAZPI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_SEFAZPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_SEFAZPI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'SEADPREVPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_SEADPREVPI.FOLHA FO
    JOIN SW_SEADPREVPI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEADPREVPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_SEADPREVPI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_SEADPREVPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_SEADPREVPI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'IMEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_IMEPI.FOLHA FO
    JOIN SW_IMEPI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_IMEPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_IMEPI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_IMEPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_IMEPI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'BEP' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_BEP.FOLHA FO
    JOIN SW_BEP.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_BEP.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_BEP.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_BEP.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_BEP.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'EMGERPI_COMEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_EMGERPI_COMEPI.FOLHA FO
    JOIN SW_EMGERPI_COMEPI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_COMEPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_EMGERPI_COMEPI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_EMGERPI_COMEPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_EMGERPI_COMEPI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'EMGERPI_COMDEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_EMGERPI_COMDEPI.FOLHA FO
    JOIN SW_EMGERPI_COMDEPI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_COMDEPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_EMGERPI_COMDEPI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_EMGERPI_COMDEPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_EMGERPI_COMDEPI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'EMGERPI_COHAB' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_EMGERPI_COHAB.FOLHA FO
    JOIN SW_EMGERPI_COHAB.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_COHAB.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_EMGERPI_COHAB.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_EMGERPI_COHAB.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_EMGERPI_COHAB.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'EMGERPI_PRODEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_EMGERPI_PRODEPI.FOLHA FO
    JOIN SW_EMGERPI_PRODEPI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_PRODEPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_EMGERPI_PRODEPI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_EMGERPI_PRODEPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_EMGERPI_PRODEPI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'EMGERPI_CEASA' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_EMGERPI_CEASA.FOLHA FO
    JOIN SW_EMGERPI_CEASA.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_CEASA.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_EMGERPI_CEASA.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_EMGERPI_CEASA.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_EMGERPI_CEASA.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'EMGERPI_PIEMTUR' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_EMGERPI_PIEMTUR.FOLHA FO
    JOIN SW_EMGERPI_PIEMTUR.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_PIEMTUR.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_EMGERPI_PIEMTUR.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_EMGERPI_PIEMTUR.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_EMGERPI_PIEMTUR.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'EMGERPI_ETELPI_FUNART' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_EMGERPI_ETELPI_FUNART.FOLHA FO
    JOIN SW_EMGERPI_ETELPI_FUNART.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_ETELPI_FUNART.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_EMGERPI_ETELPI_FUNART.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_EMGERPI_ETELPI_FUNART.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_EMGERPI_ETELPI_FUNART.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'EMGERPI_CIDAPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_EMGERPI_CIDAPI.FOLHA FO
    JOIN SW_EMGERPI_CIDAPI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_CIDAPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_EMGERPI_CIDAPI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_EMGERPI_CIDAPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_EMGERPI_CIDAPI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'SEDUC' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_SEDUC.FOLHA FO
    JOIN SW_SEDUC.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEDUC.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_SEDUC.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_SEDUC.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_SEDUC.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
    AND CR.ID_REFERENCIA NOT IN (45, 49, 50, 51, 52, 1, 2, 3, 4, 5, 6, 7, 8, 13, 17, 18, 19, 20, 29, 33, 34, 35, 36, 61, 65, 66, 67, 68, 117, 121, 122, 123, 124, 73, 74, 75, 76, 77, 78, 79, 80, 85, 89, 90, 91, 92, 101, 105, 106, 107, 108, 133, 137, 138, 139, 140)
UNION ALL        
SELECT 
    'EMGERPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_EMGERPI.FOLHA FO
    JOIN SW_EMGERPI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_EMGERPI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_EMGERPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_EMGERPI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026
UNION ALL        
SELECT 
    'EMGERPI_CODIPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    CR.ID_REFERENCIA,
    CR.NOME_REFERENCIA REFERENCIA,
    CC.NOME_CLASSE CLASSE,
    CP.NOME_PADRAO PADRAO,
    CN.NOME_NIVEL NIVEL,
    NR.ID_NIVEL_REFERENCIA_FOLHA,
    NR.VALOR_REFERENCIA
FROM
    SW_EMGERPI_CODIPI.FOLHA FO
    JOIN SW_EMGERPI_CODIPI.FOLHA_VALOR_NIVEL_REFERENCIA NR ON NR.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_CODIPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = NR.ID_REFERENCIA
    JOIN SW_EMGERPI_CODIPI.RHB_CARREIRA_PADRAO CP ON CP.ID_PADRAO = CR.ID_PADRAO
    JOIN SW_EMGERPI_CODIPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
    JOIN SW_EMGERPI_CODIPI.RHB_CARREIRA_NIVEL CN ON CN.ID_NIVEL = CR.ID_NIVEL
WHERE 
    FO.ID_TIPO_FOLHA = 1000000
    AND FO.MES = 3
    AND FO.ANO = 2026;