SELECT 
    'FUNPREV' ORGAO,
    HN.NOME NOME_INSTITUIDOR,
    FF.COD_INSTITUCIONAL MATRICULA_INSTITUIDOR,
    HN2.NOME NOME_DEPENDENTE,
    FF.MATR_DEPENDENTE MATRICULA_DEPENDENTE,
    FC.DATA_FIM,
    FO.CHAVE_FOLHA,
    RI.ID_RUBRICA_IMPORTADA,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    ROUND(RI.VALOR_MULTIPLICADOR * 1.0390 ,2)NOVO_VALOR,
    'UPDATE SW_FUNPREV.FOLHA_FUNC_RUBRICA_IMPORTADA SET VALOR_MULTIPLICADOR = VALOR_MULTIPLICADOR * 1.0390 WHERE ID_RUBRICA_IMPORTADA = ' || RI.ID_RUBRICA_IMPORTADA || ';' AS COMANDO_UPDATE
FROM
    SW_FUNPREV.FOLHA FO
    JOIN SW_FUNPREV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUNPREV.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    LEFT JOIN SW_FUNPREV.FUNC_PENSAO_CIVIL FC ON FC.ID_PENSIONISTA = FF.ID_PENSIONISTA
    LEFT JOIN SW_FUNPREV.FUNCIONARIO F ON F.ID_FUNCIONARIO = FC.ID_FUNCIONARIO
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN2 ON HN2.ID_PESSOA = FF.ID_PESSOA_DEPENDENTE AND HN2.DATA_FIM IS NULL
WHERE
    FO.MES = 5
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('141001', '151001')