SELECT 
    'Defensoria Pública do Estado do Piauí' nomeUnidGestOuEntidade,
    '350101' codigoUnidGestSiafOuEquivalente,
    E.CNPJ cnpjPagador,
    FC.NOME nomeServidor,
    FC.CPF_PESSOA cpf,
    FC.DATA_NASCIMENTO dataNascimento,
    FC.COD_LOTACAO codigoLotaFolha,
    FC.NOME_LOTACAO descricaoLotacao,
    FC.COD_INSTITUCIONAL matricula,
    CM.COD_MUNICIPIO_IBGE codigoIbgeMunicipio,
    FC.COD_CARGO codigoCargFolha,
    FC.CARGO descricaoCargFolha,
    FC.DATA_ADMISSAO dataAdmissao,
    CASE 
        WHEN FC.ID_ESTAGIARIO IS NOT NULL THEN 13
        WHEN PD.ID_DIVISAO = 1000001 THEN 2
        WHEN PD.ID_DIVISAO = 1000000 THEN 5
        WHEN PD.ID_DIVISAO = 1000020 THEN 1
    END vinculo,
    FF.MES_REFERENCIA mesReferencia,
    FF.ANO_REFERENCIA anoReferencia,
    R.COD_RUBRICA codigoRubrFolha,
    R.NOME_RUBRICA descricaoRubrFolha,
    CASE
        WHEN R.TIPO = 'R' THEN 1
        WHEN R.TIPO = 'D' THEN 2
    END rubricaFolha,
    FF.VALOR_CALCULADO valor,
    CASE 
        WHEN INSTR(FC.COD_BANCO, '-') > 0 
        THEN SUBSTR(FC.COD_BANCO, 1, INSTR(FC.COD_BANCO, '-') - 1)
        ELSE SUBSTR(FC.COD_BANCO, 1, LENGTH(FC.COD_BANCO) - 1)
    END codigoBanco,
    FC.COD_AGENCIA codigoAgencia,
    FC.CONTA_CORRENTE numeroContBancaria,
    SUBSTR(FC.CONTA_CORRENTE, -1) digitoVerificador
FROM 
    SW_DEFENSORIA.FOLHA FO
    JOIN SW_DEFENSORIA.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_DEFENSORIA.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
    JOIN SW_PUBLICO.RHB_CEP_MUNICIPIO_IBGE CM ON CM.ID_MUNICIPIO = FC.ID_MUNICIPIO
    JOIN SW_PUBLICO.EMPRESA E ON E.SIGLA = 'DEFENSORIA'
    LEFT JOIN SW_DEFENSORIA.FUNCIONARIO F ON F.ID_FUNCIONARIO = FC.ID_FUNCIONARIO
    LEFT JOIN SW_DEFENSORIA.FUNCIONARIO_PERFIL FP ON FP.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    LEFT JOIN SW_DEFENSORIA.RHB_PERFIL P ON P.ID_PERFIL = FP.ID_PERFIL
    LEFT JOIN SW_PUBLICO.RHB_PERFIL_DIVISAO PD ON PD.ID_DIVISAO = P.ID_DIVISAO
WHERE 
    FO.MES = 2
    AND FO.ANO = 2026;