SELECT 
    'FUNPREV' ORGAO,
    TA.CODIGO,
    EE.ID_ESOCIAL_EVENTO,
    EE.CHAVE_VOBYS,
    SUBSTR(EE.CHAVE_VOBYS, 1, LENGTH(EE.CHAVE_VOBYS) - 1) AS ID_CHAVE_VOBYS,
    PC.ID_PENSIONISTA,
    CASE
        WHEN EE.STATUS_VOBYS = 'P' THEN 'Pendente'
        WHEN EE.STATUS_VOBYS = 'A' THEN 'Assinado'
        WHEN EE.STATUS_VOBYS = 'T' THEN 'Transmitido'
        WHEN EE.STATUS_VOBYS = 'E' THEN 'Erro'
        WHEN EE.STATUS_VOBYS = 'R' THEN 'Aprovado'
        WHEN EE.STATUS_VOBYS = 'G' THEN 'Aguardando Processamento'
        WHEN EE.STATUS_VOBYS = 'M' THEN 'Em preenchimento'
        WHEN EE.STATUS_VOBYS = 'X' THEN 'Excluido'
    END STATUS,
    EE.RECIBO,
    EA.VALOR_ATRIBUTO NR_BENEFICIO_EVENTO,
    PC.NR_BENEFICIO NR_BENEFICIO_PENSAL_CIVIL,
    'UPDATE SW_FUNPREV.FUNC_PENSAO_CIVIL SET NR_BENEFICIO = '''|| EA.VALOR_ATRIBUTO || ''' WHERE ID_PENSIONISTA = ' || PC.ID_PENSIONISTA || ';' UPDATE_
    --EO.DESCRICAO DESCRICAO_OCORRENCIA, 
    --'https://siape.sead.pi.gov.br/org/funprev/esocial/envio/eventos/evento/' || EE.ID_ESOCIAL_EVENTO LINK
FROM
    SW_FUNPREV.ESOCIAL_EVENTO EE
    JOIN SW_FUNPREV.ESOCIAL_EVENTO_ATRIBUTO EA ON EA.ID_ESOCIAL_EVENTO = EE.ID_ESOCIAL_EVENTO AND EA.NOME_ATRIBUTO = 'nrBeneficio'
    JOIN SW_FUNPREV.FUNC_PENSAO_CIVIL PC ON PC.ID_PENSIONISTA = TO_NUMBER(SUBSTR(EE.CHAVE_VOBYS, 1, LENGTH(EE.CHAVE_VOBYS) - 1))
    JOIN SW_PUBLICO.ESB_TIPO_ARQUIVO_ESOCIAL TA ON TA.ID_ESB_TIPO_ARQUIVO_ESOCIAL = EE.ID_ESOCIAL_TIPO_ARQUIVO
WHERE
    TA.CODIGO = 'S-2410'
    AND EE.STATUS_VOBYS = 'R'
    AND EE.ID_ESOCIAL_EVENTO IN (5609813,5609814)
    -- EE.ID_ESOCIAL_EVENTO IN (488359,481593,486016,483997,485478,488111,492580,488587,478381,487422,490780,5748272,487734,477176,2124512,2085527,485959)
    AND EE.CHAVE_VOBYS LIKE '%P';