-- RELATÓRIO LOTAÇÕES MENSAL

WITH TABELA_AUX AS (
	SELECT
		X.ORGAO,
		X.CODIGO_SEFAZ,
		X.ID_FUNCIONARIO,
		X.ID_FOLHA_FUNCIONARIO,
		X.MATRICULA,
		X.CPF,
		X.COD_LOTACAO,
		X.NOME_LOTACAO,
		CASE
            WHEN X.COD_RUBRICA IN (714100, 714110) THEN 'BASE'
            WHEN X.COD_RUBRICA_LEGADO IN ('901') THEN 'FUNDO'
            WHEN X.COD_RUBRICA IN (714400, 714405, 714410, 714420, 714430, 714403) THEN 'PATRONAL'
            WHEN X.COD_RUBRICA IN (999997) THEN 'BRUTO'
		END AS TIPO_RUBRICA,
		X.VALOR_CALCULADO
	FROM
		(
			SELECT
				FF.ID_FOLHA_FUNCIONARIO,
				F.ID_FUNCIONARIO,
				REGEXP_REPLACE(NVL(FF.MATR_DEPENDENTE, PV.COD_INSTITUCIONAL), '[^0-9A-Za-z]', '')    AS MATRICULA,
				PDC.CPF_PESSOA                                              AS CPF,
				E.ORGAO_SIAFI                                               AS ORGAO,
				CS.CODIGO_SEFAZ,
				FR.COD_RUBRICA,
				FR.COD_RUBRICA_LEGADO,
				FFR.VALOR_CALCULADO,
				FO.MES,
				FO.ANO,
				FO.ID_TIPO_FOLHA,
				FF.COD_LOTACAO,
			    FF.NOME_LOTACAO 
			FROM
				SW_PUBLICO.PESSOA P
				JOIN SW_PUBLICO.PESSOA_DOC_CPF PDC ON PDC.ID_PESSOA = P.ID_PESSOA AND PDC.DATA_BAIXA IS NULL
				JOIN SW_PUBLICO.EMPRESA E ON E.SIGLA = 'FUNPREV'
				JOIN SW_FUNPREV.PESSOA_VINCULO PV ON PV.ID_PESSOA = P.ID_PESSOA
				JOIN SW_FUNPREV.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
				JOIN SW_FUNPREV.FOLHA_FUNC FF ON FF.ID_FUNCIONARIO = F.ID_FUNCIONARIO
				JOIN SW_FUNPREV.FOLHA FO ON FO.ID_FOLHA = FF.ID_FOLHA
				JOIN SW_FUNPREV.FOLHA_FUNC_RUBRICA FFR ON FFR.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
				JOIN SW_PUBLICO.FOLHA_RUBRICA FR ON FR.ID_RUBRICA = FFR.ID_RUBRICA
                LEFT JOIN SW_FUNPREV.FOLHA_CODIGO_SEFAZ CS ON CS.ID_CODIGO_SEFAZ = FO.ID_CODIGO_SEFAZ
			WHERE
				FO.ID_TIPO_FOLHA = 1000000
				AND FO.MES = 12
				AND FO.ANO = 2025
				AND ( FR.COD_RUBRICA IN (714100, 714110)
					OR FR.COD_RUBRICA_LEGADO IN ( '901' )
					OR FR.COD_RUBRICA IN (714400, 714405, 714410, 714420, 714430, 714403)
					OR FR.COD_RUBRICA IN (999997) )
                AND NOT EXISTS (
                    SELECT
                        1
                    FROM
                        SW_FUNPREV.FOLHA_FICHA_FINANCEIRA
                    WHERE  
                        ID_RUBRICA IN (1000347, 1555749)
                        AND ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
                )
                AND FF.COD_LOTACAO IN ('000303', '090303', '091303')
		) X
)
SELECT
	BRUTO.ORGAO                                                                 AS "Codigo empresa",
    CASE
        WHEN
            BASE.IND_CONTRIBUICAO = 'S'
            OR FUNDO.IND_CONTRIBUICAO = 'S'
            OR PATRONAL.IND_CONTRIBUICAO = 'S'
        THEN 'S'
        ELSE 'N'
    END                                                                         AS IND_CONTRIBUICAO,
	BRUTO.CODIGO_SEFAZ,
	COUNT(DISTINCT BRUTO.MATRICULA)                                             AS "Contracheques",
	COUNT(DISTINCT BRUTO.CPF)                                                   AS "CPFs",
	BRUTO.COD_LOTACAO                                                           AS "Codigo Lotacao",
	BRUTO.NOME_LOTACAO                                                          AS "Lotacao",
	NVL(SUM(BASE.VALOR_CALCULADO), 0)                                           AS "Valor base",
	NVL(SUM(FUNDO.VALOR_CALCULADO), 0)                                          AS "Valor fundo",
	NVL(SUM(PATRONAL.VALOR_CALCULADO), 0)                                       AS "Valor 28%",
	NVL(SUM(FUNDO.VALOR_CALCULADO), 0) + NVL(SUM(PATRONAL.VALOR_CALCULADO), 0)  AS "Repasse",
	NVL(SUM(BRUTO.VALOR_CALCULADO), 0)                                          AS "Valor Bruto"
FROM
	(
		SELECT
			BRUTO.ORGAO,
			BRUTO.CODIGO_SEFAZ,
			BRUTO.ID_FUNCIONARIO,
			BRUTO.MATRICULA,
			BRUTO.CPF,
			BRUTO.COD_LOTACAO,
			BRUTO.NOME_LOTACAO,
			SUM(BRUTO.VALOR_CALCULADO) AS VALOR_CALCULADO
		FROM
			TABELA_AUX BRUTO
		WHERE
			BRUTO.TIPO_RUBRICA = 'BRUTO'
		GROUP BY
			BRUTO.ORGAO,
			BRUTO.CODIGO_SEFAZ,
			BRUTO.ID_FUNCIONARIO,
			BRUTO.MATRICULA,
			BRUTO.CPF,
			BRUTO.COD_LOTACAO,
			BRUTO.NOME_LOTACAO
	) BRUTO
	LEFT JOIN (
		SELECT
			FUNDO.ORGAO,
			FUNDO.CODIGO_SEFAZ,
			FUNDO.ID_FUNCIONARIO,
			FUNDO.MATRICULA,
			FUNDO.CPF,
			FUNDO.COD_LOTACAO,
			FUNDO.NOME_LOTACAO,
			SUM(FUNDO.VALOR_CALCULADO) AS VALOR_CALCULADO,
            CASE
                WHEN SUM(FUNDO.VALOR_CALCULADO) = 0 THEN 'N'
                ELSE 'S'
            END AS IND_CONTRIBUICAO
		FROM
			TABELA_AUX FUNDO
		WHERE
			FUNDO.TIPO_RUBRICA = 'FUNDO'
		GROUP BY
			FUNDO.ORGAO,
			FUNDO.CODIGO_SEFAZ,
			FUNDO.ID_FUNCIONARIO,
			FUNDO.MATRICULA,
			FUNDO.CPF,
			FUNDO.COD_LOTACAO,
			FUNDO.NOME_LOTACAO
	) FUNDO ON FUNDO.ORGAO = BRUTO.ORGAO
            AND FUNDO.CODIGO_SEFAZ = BRUTO.CODIGO_SEFAZ
            AND FUNDO.MATRICULA = BRUTO.MATRICULA
            AND FUNDO.CPF = BRUTO.CPF
            AND FUNDO.ID_FUNCIONARIO = BRUTO.ID_FUNCIONARIO
            AND FUNDO.COD_LOTACAO = BRUTO.COD_LOTACAO
            AND FUNDO.NOME_LOTACAO = BRUTO.NOME_LOTACAO
	LEFT JOIN (
		SELECT
			PATRONAL.ORGAO,
			PATRONAL.CODIGO_SEFAZ,
			PATRONAL.ID_FUNCIONARIO,
			PATRONAL.MATRICULA,
			PATRONAL.CPF,
			PATRONAL.COD_LOTACAO,
			PATRONAL.NOME_LOTACAO,
			SUM(PATRONAL.VALOR_CALCULADO) AS VALOR_CALCULADO,
            CASE
                WHEN SUM(PATRONAL.VALOR_CALCULADO) = 0 THEN 'N'
                ELSE 'S'
            END AS IND_CONTRIBUICAO
		FROM
			TABELA_AUX PATRONAL
		WHERE
			PATRONAL.TIPO_RUBRICA = 'PATRONAL'
		GROUP BY
			PATRONAL.ORGAO,
			PATRONAL.CODIGO_SEFAZ,
			PATRONAL.ID_FUNCIONARIO,
			PATRONAL.MATRICULA,
			PATRONAL.CPF,
			PATRONAL.COD_LOTACAO,
			PATRONAL.NOME_LOTACAO
	) PATRONAL ON PATRONAL.ORGAO = BRUTO.ORGAO
            AND PATRONAL.CODIGO_SEFAZ = BRUTO.CODIGO_SEFAZ
            AND PATRONAL.MATRICULA = BRUTO.MATRICULA
            AND PATRONAL.CPF = BRUTO.CPF
            AND PATRONAL.ID_FUNCIONARIO = BRUTO.ID_FUNCIONARIO
            AND PATRONAL.COD_LOTACAO = BRUTO.COD_LOTACAO
            AND PATRONAL.NOME_LOTACAO = BRUTO.NOME_LOTACAO
	LEFT JOIN (
		SELECT
			BASE.ORGAO,
			BASE.CODIGO_SEFAZ,
			BASE.ID_FUNCIONARIO,
			BASE.MATRICULA,
			BASE.CPF,
			BASE.COD_LOTACAO,
			BASE.NOME_LOTACAO,
			SUM(BASE.VALOR_CALCULADO) AS VALOR_CALCULADO,
            CASE
                WHEN SUM(BASE.VALOR_CALCULADO) = 0 THEN 'N'
                ELSE 'S'
            END AS IND_CONTRIBUICAO
		FROM
			TABELA_AUX BASE
		WHERE
			BASE.TIPO_RUBRICA = 'BASE'
		GROUP BY
			BASE.ORGAO,
			BASE.CODIGO_SEFAZ,
			BASE.ID_FUNCIONARIO,
			BASE.MATRICULA,
			BASE.CPF,
			BASE.COD_LOTACAO,
			BASE.NOME_LOTACAO
	) BASE ON BASE.ORGAO = BRUTO.ORGAO
            AND BASE.CODIGO_SEFAZ = BRUTO.CODIGO_SEFAZ
            AND BASE.MATRICULA = BRUTO.MATRICULA
            AND BASE.CPF = BRUTO.CPF
            AND BASE.ID_FUNCIONARIO = BRUTO.ID_FUNCIONARIO
            AND BASE.COD_LOTACAO = BRUTO.COD_LOTACAO
            AND BASE.NOME_LOTACAO = BRUTO.NOME_LOTACAO
GROUP BY
	BRUTO.ORGAO,
	BRUTO.CODIGO_SEFAZ,
	BRUTO.COD_LOTACAO,
	BRUTO.NOME_LOTACAO,
    BASE.IND_CONTRIBUICAO,
    FUNDO.IND_CONTRIBUICAO,
    PATRONAL.IND_CONTRIBUICAO;