SELECT 
    'EMPRESA' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_EMPRESA.FOLHA FO
    JOIN SW_EMPRESA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMPRESA.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_EMPRESA.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_EMPRESA.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'CBMPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_CBMPI.FOLHA FO
    JOIN SW_CBMPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CBMPI.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_CBMPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_CBMPI.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'PGEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_PGEPI.FOLHA FO
    JOIN SW_PGEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PGEPI.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_PGEPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_PGEPI.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'CGEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_CGEPI.FOLHA FO
    JOIN SW_CGEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CGEPI.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_CGEPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_CGEPI.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'SSPPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_SSPPI.FOLHA FO
    JOIN SW_SSPPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SSPPI.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_SSPPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SSPPI.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'COJUV' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_COJUV.FOLHA FO
    JOIN SW_COJUV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_COJUV.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_COJUV.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_COJUV.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'ATIPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_ATIPI.FOLHA FO
    JOIN SW_ATIPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_ATIPI.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_ATIPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_ATIPI.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'FAPEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_FAPEPI.FOLHA FO
    JOIN SW_FAPEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FAPEPI.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_FAPEPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_FAPEPI.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'DEFCIVIL' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_DEFCIVIL.FOLHA FO
    JOIN SW_DEFCIVIL.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_DEFCIVIL.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_DEFCIVIL.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_DEFCIVIL.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'ADH' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_ADH.FOLHA FO
    JOIN SW_ADH.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_ADH.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_ADH.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_ADH.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'SEAGRO' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_SEAGRO.FOLHA FO
    JOIN SW_SEAGRO.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEAGRO.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_SEAGRO.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEAGRO.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'IDEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_IDEPI.FOLHA FO
    JOIN SW_IDEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_IDEPI.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_IDEPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_IDEPI.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'SURPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_SURPI.FOLHA FO
    JOIN SW_SURPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SURPI.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_SURPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SURPI.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'SEID' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_SEID.FOLHA FO
    JOIN SW_SEID.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEID.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_SEID.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEID.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'SECID' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_SECID.FOLHA FO
    JOIN SW_SECID.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SECID.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_SECID.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SECID.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'FUPIP' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_FUPIP.FOLHA FO
    JOIN SW_FUPIP.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUPIP.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_FUPIP.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_FUPIP.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'SETUR' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_SETUR.FOLHA FO
    JOIN SW_SETUR.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SETUR.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_SETUR.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SETUR.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'AGESPISA' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_AGESPISA.FOLHA FO
    JOIN SW_AGESPISA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_AGESPISA.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_AGESPISA.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_AGESPISA.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'SETRANS' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_SETRANS.FOLHA FO
    JOIN SW_SETRANS.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SETRANS.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_SETRANS.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SETRANS.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'TVANTARES' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_TVANTARES.FOLHA FO
    JOIN SW_TVANTARES.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_TVANTARES.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_TVANTARES.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_TVANTARES.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'VICEGOV' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_VICEGOV.FOLHA FO
    JOIN SW_VICEGOV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_VICEGOV.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_VICEGOV.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_VICEGOV.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'SEINFRA' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_SEINFRA.FOLHA FO
    JOIN SW_SEINFRA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEINFRA.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_SEINFRA.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEINFRA.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'CCOM' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_CCOM.FOLHA FO
    JOIN SW_CCOM.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CCOM.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_CCOM.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_CCOM.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'FUNDESPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_FUNDESPI.FOLHA FO
    JOIN SW_FUNDESPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUNDESPI.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_FUNDESPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_FUNDESPI.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'SEDET' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_SEDET.FOLHA FO
    JOIN SW_SEDET.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEDET.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_SEDET.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEDET.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'INTERPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_INTERPI.FOLHA FO
    JOIN SW_INTERPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_INTERPI.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_INTERPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_INTERPI.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'JUCEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_JUCEPI.FOLHA FO
    JOIN SW_JUCEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_JUCEPI.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_JUCEPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_JUCEPI.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'SEMAR' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_SEMAR.FOLHA FO
    JOIN SW_SEMAR.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEMAR.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_SEMAR.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEMAR.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'GMG' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_GMG.FOLHA FO
    JOIN SW_GMG.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_GMG.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_GMG.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_GMG.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'SEPLAN' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_SEPLAN.FOLHA FO
    JOIN SW_SEPLAN.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEPLAN.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_SEPLAN.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEPLAN.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'SAF' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_SAF.FOLHA FO
    JOIN SW_SAF.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SAF.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_SAF.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SAF.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'SECULT' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_SECULT.FOLHA FO
    JOIN SW_SECULT.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SECULT.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_SECULT.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SECULT.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'DER' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_DER.FOLHA FO
    JOIN SW_DER.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_DER.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_DER.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_DER.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'DETRAN' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_DETRAN.FOLHA FO
    JOIN SW_DETRAN.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_DETRAN.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_DETRAN.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_DETRAN.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'IASPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_IASPI.FOLHA FO
    JOIN SW_IASPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_IASPI.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_IASPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_IASPI.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'ADAPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_ADAPI.FOLHA FO
    JOIN SW_ADAPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_ADAPI.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_ADAPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_ADAPI.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'IMEPIPROD' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_IMEPIPROD.FOLHA FO
    JOIN SW_IMEPIPROD.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_IMEPIPROD.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_IMEPIPROD.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_IMEPIPROD.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'CPVCI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_CPVCI.FOLHA FO
    JOIN SW_CPVCI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CPVCI.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_CPVCI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_CPVCI.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'CENDROGAS' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_CENDROGAS.FOLHA FO
    JOIN SW_CENDROGAS.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CENDROGAS.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_CENDROGAS.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_CENDROGAS.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'COFIR' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_COFIR.FOLHA FO
    JOIN SW_COFIR.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_COFIR.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_COFIR.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_COFIR.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'SEMINPER' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_SEMINPER.FOLHA FO
    JOIN SW_SEMINPER.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEMINPER.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_SEMINPER.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEMINPER.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'AGRESP' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_AGRESP.FOLHA FO
    JOIN SW_AGRESP.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_AGRESP.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_AGRESP.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_AGRESP.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'CEPM' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_CEPM.FOLHA FO
    JOIN SW_CEPM.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CEPM.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_CEPM.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_CEPM.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'EMATER' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_EMATER.FOLHA FO
    JOIN SW_EMATER.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMATER.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_EMATER.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_EMATER.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'FUESPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_FUESPI.FOLHA FO
    JOIN SW_FUESPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUESPI.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_FUESPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_FUESPI.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'EMATERPROD' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_EMATERPROD.FOLHA FO
    JOIN SW_EMATERPROD.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMATERPROD.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_EMATERPROD.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_EMATERPROD.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'DEFENSORIA' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_DEFENSORIA.FOLHA FO
    JOIN SW_DEFENSORIA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_DEFENSORIA.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_DEFENSORIA.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_DEFENSORIA.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'PENSIONISTAS' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_PENSIONISTAS.FOLHA FO
    JOIN SW_PENSIONISTAS.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PENSIONISTAS.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_PENSIONISTAS.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_PENSIONISTAS.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'CDTER' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_CDTER.FOLHA FO
    JOIN SW_CDTER.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CDTER.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_CDTER.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_CDTER.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'SERES' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_SERES.FOLHA FO
    JOIN SW_SERES.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SERES.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_SERES.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SERES.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'SECESP' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_SECESP.FOLHA FO
    JOIN SW_SECESP.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SECESP.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_SECESP.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SECESP.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'INATIVOS_PENSIONISTAS' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_INATIVOS_PENSIONISTAS.FOLHA FO
    JOIN SW_INATIVOS_PENSIONISTAS.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_INATIVOS_PENSIONISTAS.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_INATIVOS_PENSIONISTAS.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_INATIVOS_PENSIONISTAS.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'SEDUC_PRECATORIO' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_SEDUC_PRECATORIO.FOLHA FO
    JOIN SW_SEDUC_PRECATORIO.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEDUC_PRECATORIO.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_SEDUC_PRECATORIO.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEDUC_PRECATORIO.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'EMGERPI_CORESA' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_EMGERPI_CORESA.FOLHA FO
    JOIN SW_EMGERPI_CORESA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_CORESA.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_EMGERPI_CORESA.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_EMGERPI_CORESA.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL      
SELECT 
    'FESPPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_FESPPI.FOLHA FO
    JOIN SW_FESPPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FESPPI.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_FESPPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_FESPPI.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'SIA' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_SIA.FOLHA FO
    JOIN SW_SIA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SIA.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_SIA.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SIA.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'SETRE' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_SETRE.FOLHA FO
    JOIN SW_SETRE.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SETRE.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_SETRE.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SETRE.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'SEGOV' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEGOV.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_SEGOV.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEGOV.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'SASC' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_SASC.FOLHA FO
    JOIN SW_SASC.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SASC.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_SASC.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SASC.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'METRO' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_METRO.FOLHA FO
    JOIN SW_METRO.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_METRO.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_METRO.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_METRO.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'PIAUIPREV' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_PIAUIPREV.FOLHA FO
    JOIN SW_PIAUIPREV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PIAUIPREV.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_PIAUIPREV.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_PIAUIPREV.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'INATIVOS_SEDUC' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_INATIVOS_SEDUC.FOLHA FO
    JOIN SW_INATIVOS_SEDUC.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_INATIVOS_SEDUC.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_INATIVOS_SEDUC.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_INATIVOS_SEDUC.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'INATIVOS_TCE' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_INATIVOS_TCE.FOLHA FO
    JOIN SW_INATIVOS_TCE.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_INATIVOS_TCE.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_INATIVOS_TCE.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_INATIVOS_TCE.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'SADA' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_SADA.FOLHA FO
    JOIN SW_SADA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SADA.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_SADA.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SADA.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'SECMULHERES' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_SECMULHERES.FOLHA FO
    JOIN SW_SECMULHERES.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SECMULHERES.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_SECMULHERES.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SECMULHERES.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'EMGERPI_EMATER' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_EMGERPI_EMATER.FOLHA FO
    JOIN SW_EMGERPI_EMATER.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_EMATER.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_EMGERPI_EMATER.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_EMGERPI_EMATER.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'REENVIO' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_REENVIO.FOLHA FO
    JOIN SW_REENVIO.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_REENVIO.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_REENVIO.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_REENVIO.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'SESAPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_SESAPI.FOLHA FO
    JOIN SW_SESAPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SESAPI.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_SESAPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SESAPI.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'PMPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_PMPI.FOLHA FO
    JOIN SW_PMPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PMPI.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_PMPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_PMPI.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'SEJUSPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_SEJUSPI.FOLHA FO
    JOIN SW_SEJUSPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEJUSPI.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_SEJUSPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEJUSPI.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'SEFAZPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_SEFAZPI.FOLHA FO
    JOIN SW_SEFAZPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEFAZPI.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_SEFAZPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEFAZPI.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'SEADPREVPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_SEADPREVPI.FOLHA FO
    JOIN SW_SEADPREVPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEADPREVPI.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_SEADPREVPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEADPREVPI.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'IMEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_IMEPI.FOLHA FO
    JOIN SW_IMEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_IMEPI.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_IMEPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_IMEPI.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'EMGERPI_COMEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_EMGERPI_COMEPI.FOLHA FO
    JOIN SW_EMGERPI_COMEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_COMEPI.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_EMGERPI_COMEPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_EMGERPI_COMEPI.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'EMGERPI_COMDEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_EMGERPI_COMDEPI.FOLHA FO
    JOIN SW_EMGERPI_COMDEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_COMDEPI.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_EMGERPI_COMDEPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_EMGERPI_COMDEPI.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'EMGERPI_COHAB' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_EMGERPI_COHAB.FOLHA FO
    JOIN SW_EMGERPI_COHAB.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_COHAB.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_EMGERPI_COHAB.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_EMGERPI_COHAB.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'EMGERPI_PRODEPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_EMGERPI_PRODEPI.FOLHA FO
    JOIN SW_EMGERPI_PRODEPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_PRODEPI.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_EMGERPI_PRODEPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_EMGERPI_PRODEPI.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'EMGERPI_CEASA' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_EMGERPI_CEASA.FOLHA FO
    JOIN SW_EMGERPI_CEASA.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_CEASA.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_EMGERPI_CEASA.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_EMGERPI_CEASA.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'EMGERPI_PIEMTUR' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_EMGERPI_PIEMTUR.FOLHA FO
    JOIN SW_EMGERPI_PIEMTUR.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_PIEMTUR.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_EMGERPI_PIEMTUR.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_EMGERPI_PIEMTUR.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'EMGERPI_ETELPI_FUNART' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_EMGERPI_ETELPI_FUNART.FOLHA FO
    JOIN SW_EMGERPI_ETELPI_FUNART.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_ETELPI_FUNART.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_EMGERPI_ETELPI_FUNART.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_EMGERPI_ETELPI_FUNART.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'EMGERPI_CIDAPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_EMGERPI_CIDAPI.FOLHA FO
    JOIN SW_EMGERPI_CIDAPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_CIDAPI.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_EMGERPI_CIDAPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_EMGERPI_CIDAPI.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'SEDUC' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_SEDUC.FOLHA FO
    JOIN SW_SEDUC.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEDUC.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_SEDUC.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_SEDUC.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'EMGERPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_EMGERPI.FOLHA FO
    JOIN SW_EMGERPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_EMGERPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_EMGERPI.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
UNION ALL    
SELECT 
    'EMGERPI_CODIPI' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    RI.DATA_CADASTRO
FROM
    SW_EMGERPI_CODIPI.FOLHA FO
    JOIN SW_EMGERPI_CODIPI.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_CODIPI.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_EMGERPI_CODIPI.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_EMGERPI_CODIPI.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', '131002', 
    '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005');