WITH TABELA_AUX AS (
    SELECT
        X.ORGAO,
        X.ID_FUNCIONARIO,
        X.MATRICULA,
        X.CPF,
        X.CODIGO_SEFAZ,
        X.DESCRICAO_SEFAZ,
        X.TIPO_BENEFICIO,
        CASE
            WHEN X.COD_RUBRICA IN (714100, 714110) THEN 'BASE'
            WHEN X.COD_RUBRICA_LEGADO IN ('901') THEN 'FUNDO'
            WHEN X.COD_RUBRICA IN (714400, 714405, 714410, 714420, 714430, 714403) THEN  'PATRONAL'
            WHEN X.COD_RUBRICA IN (999997) THEN 'BRUTO'
        END TIPO_RUBRICA,
        X.VALOR_CALCULADO
    FROM
        (
        SELECT
            NVL(FC.ID_FUNCIONARIO, PC.ID_FUNCIONARIO) ID_FUNCIONARIO,
            REGEXP_REPLACE(FC.COD_INSTITUCIONAL, '[^0-9A-Za-z]', '') MATRICULA,
            PDC.CPF_PESSOA CPF,
            E.ORGAO_SIAFI ORGAO,
            R.COD_RUBRICA,
            R.COD_RUBRICA_LEGADO,
            FF.VALOR_CALCULADO,
            CS.CODIGO_SEFAZ,
            CS.DESCRICAO_SEFAZ,
            CASE FO.TIPO_FOLHA_SEFAZ
                WHEN 'C1' THEN 'Padrão'
                WHEN 'C2' THEN 'Reintegrados'
                WHEN 'C3' THEN 'Temporário'
                WHEN 'C4' THEN 'Prestador'
                WHEN 'C5' THEN 'Bolsistas'
                WHEN 'C6' THEN 'Inativos'
                WHEN 'C7' THEN 'Pensionistas'
                WHEN 'C8' THEN 'RGPS'
                WHEN 'C9' THEN 'RPPS'
            END TIPO_BENEFICIO
        FROM
            SW_FUNPREV.FOLHA FO
            JOIN SW_FUNPREV.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
            JOIN SW_FUNPREV.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
            JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
            JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FC.ID_PESSOA
            JOIN SW_PUBLICO.PESSOA_DOC_CPF PDC ON PDC.ID_PESSOA = P.ID_PESSOA AND PDC.DATA_BAIXA IS NULL
            JOIN SW_PUBLICO.EMPRESA E ON E.SIGLA = 'FUNPREV'
            LEFT JOIN SW_FUNPREV.FOLHA_CODIGO_SEFAZ CS ON CS.ID_CODIGO_SEFAZ = FO.ID_CODIGO_SEFAZ
            LEFT JOIN SW_FUNPREV.FUNC_PENSAO_CIVIL PC ON PC.ID_PENSIONISTA = FC.ID_PENSIONISTA
            JOIN SW_FUNPREV.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = NVL(FC.ID_FUNCIONARIO, PC.ID_FUNCIONARIO)
        WHERE
            FO.ID_TIPO_FOLHA = 1000000
            AND FO.MES = 12
            AND FO.ANO = 2025
            AND FI.ID_REGIME NOT IN (1000003, 9)
            AND (
                R.COD_RUBRICA IN (714100, 714110)
                OR R.COD_RUBRICA_LEGADO IN ('901')
                OR R.COD_RUBRICA IN (714400, 714405, 714410, 714420, 714430, 714403)
                OR R.COD_RUBRICA IN (999997)
            )
            AND NOT EXISTS (
                SELECT
                    1
                FROM
                    SW_FUNPREV.FOLHA_FICHA_FINANCEIRA
                WHERE  
                    ID_RUBRICA IN (1000347, 1555749)
                    AND ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
            )
        ) X
)
SELECT
    BRUTO.ORGAO "CODIGO EMPRESA",
    COUNT(BRUTO.MATRICULA) CONTRACHEQUES,
    SUM(CASE
        WHEN NVL(BASE.VALOR_CALCULADO, 0) > FAIXA.VALOR_FINAL THEN 0
        ELSE 1
    END) CONTRACHEQUES_FAIXA,
    BRUTO.CODIGO_SEFAZ,
    BRUTO.DESCRICAO_SEFAZ,
    BRUTO.TIPO_BENEFICIO,
    FAIXA.FAIXA,
    SUM(CASE
        WHEN NVL(BASE.VALOR_CALCULADO, 0) > FAIXA.VALOR_FINAL THEN FAIXA.VALOR_FINAL - FAIXA.VALOR_1
        ELSE NVL(BASE.VALOR_CALCULADO, 0) - FAIXA.VALOR_1
    END) "VALOR BASE FAIXA",
    SUM(CASE
        WHEN FAIXA.FAIXA = 1 THEN 0
        WHEN NVL(BASE.VALOR_CALCULADO, 0) > FAIXA.VALOR_FINAL THEN FAIXA.VALOR_FINAL - FAIXA.VALOR_1
        ELSE NVL(BASE.VALOR_CALCULADO, 0) - FAIXA.VALOR_1
    END) * 28/100 "VALOR PATRONAL",
    SUM(CASE
        WHEN NVL(BASE.VALOR_CALCULADO, 0) > FAIXA.VALOR_FINAL THEN FAIXA.VALOR_FINAL - FAIXA.VALOR_1
        ELSE NVL(BASE.VALOR_CALCULADO, 0) - FAIXA.VALOR_1
    END) * (FAIXA.PERCENTUAL / 100) "VALOR FUNDO",
    (SUM(CASE
        WHEN FAIXA.FAIXA = 1 THEN 0
        WHEN NVL(BASE.VALOR_CALCULADO, 0) > FAIXA.VALOR_FINAL THEN FAIXA.VALOR_FINAL - FAIXA.VALOR_1
        ELSE NVL(BASE.VALOR_CALCULADO, 0) - FAIXA.VALOR_1
    END) * 28/100) + (SUM(CASE
        WHEN NVL(BASE.VALOR_CALCULADO, 0) > FAIXA.VALOR_FINAL THEN FAIXA.VALOR_FINAL - FAIXA.VALOR_1
        ELSE NVL(BASE.VALOR_CALCULADO, 0) - FAIXA.VALOR_1
    END) * (FAIXA.PERCENTUAL / 100)) "REPASSE",
    CASE
        WHEN FAIXA.FAIXA = 1 THEN NVL(SUM(BRUTO.VALOR_CALCULADO), 0)
    END "VALOR BRUTO"
FROM
    (
    SELECT
        BRUTO.ORGAO,
        BRUTO.ID_FUNCIONARIO,
        BRUTO.MATRICULA,
        BRUTO.CPF,
        BRUTO.CODIGO_SEFAZ,
        BRUTO.DESCRICAO_SEFAZ,
        BRUTO.TIPO_BENEFICIO,
        SUM(BRUTO.VALOR_CALCULADO) VALOR_CALCULADO
    FROM
        TABELA_AUX BRUTO
    WHERE
        BRUTO.TIPO_RUBRICA = 'BRUTO'
    GROUP BY
        BRUTO.ORGAO,
        BRUTO.ID_FUNCIONARIO,
        BRUTO.MATRICULA,
        BRUTO.CPF,
        BRUTO.CODIGO_SEFAZ,
        BRUTO.DESCRICAO_SEFAZ,
        BRUTO.TIPO_BENEFICIO
    ) BRUTO
    JOIN (
        SELECT
            BASE.ORGAO,
            BASE.ID_FUNCIONARIO,
            BASE.MATRICULA,
            BASE.CPF,
            BASE.CODIGO_SEFAZ,
            BASE.DESCRICAO_SEFAZ,
            BASE.TIPO_BENEFICIO,
            SUM(BASE.VALOR_CALCULADO) VALOR_CALCULADO
        FROM
            TABELA_AUX BASE
        WHERE
            BASE.TIPO_RUBRICA = 'BASE'
        GROUP BY
            BASE.ORGAO,
            BASE.ID_FUNCIONARIO,
            BASE.MATRICULA,
            BASE.CPF,
            BASE.CODIGO_SEFAZ,
            BASE.DESCRICAO_SEFAZ,
            BASE.TIPO_BENEFICIO
    ) BASE ON BASE.ORGAO = BRUTO.ORGAO
            AND BASE.CODIGO_SEFAZ = BRUTO.CODIGO_SEFAZ
            AND BASE.MATRICULA = BRUTO.MATRICULA
            AND BASE.CPF = BRUTO.CPF
            AND BASE.ID_FUNCIONARIO = BRUTO.ID_FUNCIONARIO
            AND BASE.TIPO_BENEFICIO = BRUTO.TIPO_BENEFICIO
    JOIN (
        SELECT
            VT.FAIXA,
            VT.VALOR_INICIAL,
            VT.VALOR_FINAL,
            VT.VALOR_1,
            VT.PERCENTUAL
        FROM
            SW_FUNPREV.FOLHA FO
            JOIN SW_FUNPREV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA AND VT.ID_TABELA = 1000280
        WHERE
            SUBSTR(FO.CHAVE_FOLHA, 9) = 300 AND FO.MES = 12 AND FO.ANO = 2025 AND FO.ID_TIPO_FOLHA = 1000000
    ) FAIXA ON FAIXA.VALOR_1 < BASE.VALOR_CALCULADO
GROUP BY
    BRUTO.ORGAO,
    BRUTO.CODIGO_SEFAZ,
    BRUTO.DESCRICAO_SEFAZ,
    BRUTO.TIPO_BENEFICIO,
    FAIXA.FAIXA,
    FAIXA.PERCENTUAL
ORDER BY
    BRUTO.ORGAO,
    BRUTO.CODIGO_SEFAZ,
    FAIXA.FAIXA;


WITH TABELA_AUX AS (
    SELECT
        X.ORGAO,
        X.ID_FUNCIONARIO,
        X.MATRICULA,
        X.CPF,
        X.CODIGO_SEFAZ,
        X.DESCRICAO_SEFAZ,
        X.TIPO_BENEFICIO,
        CASE
            WHEN X.COD_RUBRICA IN (714250) THEN 'BASE'
            WHEN X.COD_RUBRICA_LEGADO IN ('900') THEN 'FUNDO'
            WHEN X.COD_RUBRICA IN (714450, 714455, 714460, 714435, 714440, 714436) THEN  'PATRONAL'
            WHEN X.COD_RUBRICA IN (999997) THEN 'BRUTO'
        END TIPO_RUBRICA,
        X.VALOR_CALCULADO
    FROM
        (
        SELECT
            NVL(FC.ID_FUNCIONARIO, PC.ID_FUNCIONARIO) ID_FUNCIONARIO,
            REGEXP_REPLACE(FC.COD_INSTITUCIONAL, '[^0-9A-Za-z]', '') MATRICULA,
            PDC.CPF_PESSOA CPF,
            E.ORGAO_SIAFI ORGAO,
            R.COD_RUBRICA,
            R.COD_RUBRICA_LEGADO,
            FF.VALOR_CALCULADO,
            CS.CODIGO_SEFAZ,
            CS.DESCRICAO_SEFAZ,
            CASE FO.TIPO_FOLHA_SEFAZ
                WHEN 'C1' THEN 'Padrão'
                WHEN 'C2' THEN 'Reintegrados'
                WHEN 'C3' THEN 'Temporário'
                WHEN 'C4' THEN 'Prestador'
                WHEN 'C5' THEN 'Bolsistas'
                WHEN 'C6' THEN 'Inativos'
                WHEN 'C7' THEN 'Pensionistas'
                WHEN 'C8' THEN 'RGPS'
                WHEN 'C9' THEN 'RPPS'
            END TIPO_BENEFICIO
        FROM
            SW_FUNPREV.FOLHA FO
            JOIN SW_FUNPREV.FOLHA_CONTRACHEQUE FC ON FC.ID_FOLHA = FO.ID_FOLHA
            JOIN SW_FUNPREV.FOLHA_FICHA_FINANCEIRA FF ON FF.ID_FOLHA_FUNCIONARIO = FC.ID_FOLHA_FUNCIONARIO
            JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = FF.ID_RUBRICA
            JOIN SW_PUBLICO.PESSOA P ON P.ID_PESSOA = FC.ID_PESSOA
            JOIN SW_PUBLICO.PESSOA_DOC_CPF PDC ON PDC.ID_PESSOA = P.ID_PESSOA AND PDC.DATA_BAIXA IS NULL
            JOIN SW_PUBLICO.EMPRESA E ON E.SIGLA = 'FUNPREV'
            LEFT JOIN SW_FUNPREV.FOLHA_CODIGO_SEFAZ CS ON CS.ID_CODIGO_SEFAZ = FO.ID_CODIGO_SEFAZ
            LEFT JOIN SW_FUNPREV.FUNC_PENSAO_CIVIL PC ON PC.ID_PENSIONISTA = FC.ID_PENSIONISTA
            JOIN SW_FUNPREV.FUNCIONARIO_INGRESSO FI ON FI.ID_FUNCIONARIO = NVL(FC.ID_FUNCIONARIO, PC.ID_FUNCIONARIO)
        WHERE
            FO.ID_TIPO_FOLHA = 1000003
            AND FO.MES = 12
            AND FO.ANO = 2025
            AND FI.ID_REGIME NOT IN (1000003, 9)
            AND (
                R.COD_RUBRICA IN (714250)
                OR R.COD_RUBRICA_LEGADO IN ('900')
                OR R.COD_RUBRICA IN (714450, 714455, 714460, 714435, 714440, 714436)
                OR R.COD_RUBRICA IN (999997)
            )
            AND NOT EXISTS (
                SELECT
                    1
                FROM
                    SW_FUNPREV.FOLHA_FICHA_FINANCEIRA
                WHERE  
                    ID_RUBRICA IN (1000347, 1555749)
                    AND ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
            )
        ) X
)
SELECT
    BRUTO.ORGAO "CODIGO EMPRESA",
    COUNT(BRUTO.MATRICULA) CONTRACHEQUES,
    SUM(CASE
        WHEN NVL(BASE.VALOR_CALCULADO, 0) > FAIXA.VALOR_FINAL THEN 0
        ELSE 1
    END) CONTRACHEQUES_FAIXA,
    BRUTO.CODIGO_SEFAZ,
    BRUTO.DESCRICAO_SEFAZ,
    BRUTO.TIPO_BENEFICIO,
    FAIXA.FAIXA,
    SUM(CASE
        WHEN NVL(BASE.VALOR_CALCULADO, 0) > FAIXA.VALOR_FINAL THEN FAIXA.VALOR_FINAL - FAIXA.VALOR_1
        ELSE NVL(BASE.VALOR_CALCULADO, 0) - FAIXA.VALOR_1
    END) "VALOR BASE FAIXA",
    SUM(CASE
        WHEN FAIXA.FAIXA = 1 THEN 0
        WHEN NVL(BASE.VALOR_CALCULADO, 0) > FAIXA.VALOR_FINAL THEN FAIXA.VALOR_FINAL - FAIXA.VALOR_1
        ELSE NVL(BASE.VALOR_CALCULADO, 0) - FAIXA.VALOR_1
    END) * 28/100 "VALOR PATRONAL",
    SUM(CASE
        WHEN NVL(BASE.VALOR_CALCULADO, 0) > FAIXA.VALOR_FINAL THEN FAIXA.VALOR_FINAL - FAIXA.VALOR_1
        ELSE NVL(BASE.VALOR_CALCULADO, 0) - FAIXA.VALOR_1
    END) * (FAIXA.PERCENTUAL / 100) "VALOR FUNDO",
    (SUM(CASE
        WHEN FAIXA.FAIXA = 1 THEN 0
        WHEN NVL(BASE.VALOR_CALCULADO, 0) > FAIXA.VALOR_FINAL THEN FAIXA.VALOR_FINAL - FAIXA.VALOR_1
        ELSE NVL(BASE.VALOR_CALCULADO, 0) - FAIXA.VALOR_1
    END) * 28/100) + (SUM(CASE
        WHEN NVL(BASE.VALOR_CALCULADO, 0) > FAIXA.VALOR_FINAL THEN FAIXA.VALOR_FINAL - FAIXA.VALOR_1
        ELSE NVL(BASE.VALOR_CALCULADO, 0) - FAIXA.VALOR_1
    END) * (FAIXA.PERCENTUAL / 100)) "REPASSE",
    CASE
        WHEN FAIXA.FAIXA = 1 THEN NVL(SUM(BRUTO.VALOR_CALCULADO), 0)
    END "VALOR BRUTO"
FROM
    (
    SELECT
        BRUTO.ORGAO,
        BRUTO.ID_FUNCIONARIO,
        BRUTO.MATRICULA,
        BRUTO.CPF,
        BRUTO.CODIGO_SEFAZ,
        BRUTO.DESCRICAO_SEFAZ,
        BRUTO.TIPO_BENEFICIO,
        SUM(BRUTO.VALOR_CALCULADO) VALOR_CALCULADO
    FROM
        TABELA_AUX BRUTO
    WHERE
        BRUTO.TIPO_RUBRICA = 'BRUTO'
    GROUP BY
        BRUTO.ORGAO,
        BRUTO.ID_FUNCIONARIO,
        BRUTO.MATRICULA,
        BRUTO.CPF,
        BRUTO.CODIGO_SEFAZ,
        BRUTO.DESCRICAO_SEFAZ,
        BRUTO.TIPO_BENEFICIO
    ) BRUTO
    JOIN (
        SELECT
            BASE.ORGAO,
            BASE.ID_FUNCIONARIO,
            BASE.MATRICULA,
            BASE.CPF,
            BASE.CODIGO_SEFAZ,
            BASE.DESCRICAO_SEFAZ,
            BASE.TIPO_BENEFICIO,
            SUM(BASE.VALOR_CALCULADO) VALOR_CALCULADO
        FROM
            TABELA_AUX BASE
        WHERE
            BASE.TIPO_RUBRICA = 'BASE'
        GROUP BY
            BASE.ORGAO,
            BASE.ID_FUNCIONARIO,
            BASE.MATRICULA,
            BASE.CPF,
            BASE.CODIGO_SEFAZ,
            BASE.DESCRICAO_SEFAZ,
            BASE.TIPO_BENEFICIO
    ) BASE ON BASE.ORGAO = BRUTO.ORGAO
            AND BASE.CODIGO_SEFAZ = BRUTO.CODIGO_SEFAZ
            AND BASE.MATRICULA = BRUTO.MATRICULA
            AND BASE.CPF = BRUTO.CPF
            AND BASE.ID_FUNCIONARIO = BRUTO.ID_FUNCIONARIO
            AND BASE.TIPO_BENEFICIO = BRUTO.TIPO_BENEFICIO
    JOIN (
        SELECT
            VT.FAIXA,
            VT.VALOR_INICIAL,
            VT.VALOR_FINAL,
            VT.VALOR_1,
            VT.PERCENTUAL
        FROM
            SW_FUNPREV.FOLHA FO
            JOIN SW_FUNPREV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA AND VT.ID_TABELA = 1000280
        WHERE
            SUBSTR(FO.CHAVE_FOLHA, 9) = 300 AND FO.MES = 12 AND FO.ANO = 2025 AND FO.ID_TIPO_FOLHA = 1000003
    ) FAIXA ON FAIXA.VALOR_1 < BASE.VALOR_CALCULADO
GROUP BY
    BRUTO.ORGAO,
    BRUTO.CODIGO_SEFAZ,
    BRUTO.DESCRICAO_SEFAZ,
    BRUTO.TIPO_BENEFICIO,
    FAIXA.FAIXA,
    FAIXA.PERCENTUAL
ORDER BY
    BRUTO.ORGAO,
    BRUTO.CODIGO_SEFAZ,
    FAIXA.FAIXA;