SELECT 
    'FUNPREV' ORGAO,
    FO.CHAVE_FOLHA,
    FO.DESCRICAO DESCRICAO_FOLHA,
    FF.COD_INSTITUCIONAL MATRICULA,
    HN.NOME,
    CCF.NOME_CATEGORIA_FUNCIONAL,
    R.COD_RUBRICA,
    R.NOME_RUBRICA RUBRICA,
    RI.VALOR_MULTIPLICADOR,
    RI.ID_RUBRICA_IMPORTADA,
    NVL(PP.IND_FORMA_REVISAO, PC.IND_FORMA_REVISAO) PARIDADE
FROM
    SW_FUNPREV.FOLHA FO
    JOIN SW_FUNPREV.FOLHA_FUNC FF ON FF.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUNPREV.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = FF.ID_FUNCIONARIO AND FR.DATA_TERMINO IS NULL
    JOIN SW_FUNPREV.FOLHA_FUNC_RUBRICA_IMPORTADA RI ON RI.ID_FOLHA_FUNCIONARIO = FF.ID_FOLHA_FUNCIONARIO
    JOIN SW_FUNPREV.RHB_CARREIRA_CATEG_FUNCIONAL CCF ON CCF.ID_CATEGORIA_FUNCIONAL = FR.ID_CATEGORIA_FUNCIONAL
    LEFT JOIN SW_FUNPREV.FUNC_PENSAO_CIVIL PC ON PC.ID_PENSIONISTA = FF.ID_PENSIONISTA AND PC.DATA_FIM IS NULL
    JOIN SW_PUBLICO.FOLHA_RUBRICA R ON R.ID_RUBRICA = RI.ID_RUBRICA
    JOIN SW_PUBLICO.PESSOA_HISTORICO_NOMES HN ON HN.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND HN.DATA_FIM IS NULL
    LEFT JOIN SW_PUBLICO.PREV_PROP_PLAN_PREV_APOSENT PP ON PP.ID_PESSOA = FF.ID_PESSOA_FUNCIONARIO AND PP.ID_FUNCIONARIO_PAGAMENTO = FF.ID_FUNCIONARIO
WHERE
    FO.MES = 3
    AND FO.ANO = 2026
    AND R.COD_RUBRICA IN ('121003', '131003', '141003', '151003', '111001', '111002', '121002', 
    '131002', '141002', '151002', '121001', '121011', '131001', '131012', '141005', '151005')
    AND PP.IND_FORMA_REVISAO = 'P' OR PC.IND_FORMA_REVISAO = 'P';