SELECT 
    'CBMPI' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_CBMPI.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_CBMPI.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_CBMPI.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CBMPI.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_CBMPI.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE 
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'PGEPI' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_PGEPI.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_PGEPI.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_PGEPI.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PGEPI.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_PGEPI.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'SSPPI' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_SSPPI.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_SSPPI.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_SSPPI.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SSPPI.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_SSPPI.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'FAPEPI' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_FAPEPI.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_FAPEPI.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_FAPEPI.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FAPEPI.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_FAPEPI.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'DEFCIVIL' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_DEFCIVIL.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_DEFCIVIL.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_DEFCIVIL.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_DEFCIVIL.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_DEFCIVIL.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'ADH' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_ADH.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_ADH.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_ADH.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_ADH.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_ADH.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'SEAGRO' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_SEAGRO.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_SEAGRO.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_SEAGRO.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEAGRO.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_SEAGRO.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'IDEPI' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_IDEPI.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_IDEPI.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_IDEPI.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_IDEPI.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_IDEPI.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'SURPI' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_SURPI.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_SURPI.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_SURPI.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SURPI.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_SURPI.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'SEID' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_SEID.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_SEID.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_SEID.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEID.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_SEID.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'SECID' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_SECID.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_SECID.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_SECID.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SECID.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_SECID.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'FUPIP' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_FUPIP.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_FUPIP.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_FUPIP.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUPIP.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_FUPIP.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'SETUR' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_SETUR.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_SETUR.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_SETUR.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SETUR.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_SETUR.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'SETRANS' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_SETRANS.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_SETRANS.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_SETRANS.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SETRANS.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_SETRANS.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'TVANTARES' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_TVANTARES.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_TVANTARES.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_TVANTARES.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_TVANTARES.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_TVANTARES.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'VICEGOV' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_VICEGOV.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_VICEGOV.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_VICEGOV.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_VICEGOV.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_VICEGOV.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'SEINFRA' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_SEINFRA.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_SEINFRA.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_SEINFRA.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEINFRA.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_SEINFRA.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'CCOM' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_CCOM.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_CCOM.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_CCOM.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CCOM.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_CCOM.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'SEDET' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_SEDET.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_SEDET.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_SEDET.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEDET.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_SEDET.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'INTERPI' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_INTERPI.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_INTERPI.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_INTERPI.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_INTERPI.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_INTERPI.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'JUCEPI' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_JUCEPI.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_JUCEPI.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_JUCEPI.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_JUCEPI.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_JUCEPI.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'SEMAR' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_SEMAR.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_SEMAR.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_SEMAR.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEMAR.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_SEMAR.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'GMG' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_GMG.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_GMG.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_GMG.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_GMG.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_GMG.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'SEPLAN' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_SEPLAN.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_SEPLAN.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_SEPLAN.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEPLAN.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_SEPLAN.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'SAF' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_SAF.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_SAF.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_SAF.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SAF.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_SAF.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'SECULT' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_SECULT.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_SECULT.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_SECULT.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SECULT.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_SECULT.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'DER' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_DER.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_DER.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_DER.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_DER.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_DER.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'DETRAN' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_DETRAN.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_DETRAN.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_DETRAN.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_DETRAN.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_DETRAN.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'IASPI' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_IASPI.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_IASPI.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_IASPI.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_IASPI.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_IASPI.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'ADAPI' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_ADAPI.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_ADAPI.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_ADAPI.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_ADAPI.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_ADAPI.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'CENDROGAS' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_CENDROGAS.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_CENDROGAS.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_CENDROGAS.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_CENDROGAS.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_CENDROGAS.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'COFIR' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_COFIR.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_COFIR.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_COFIR.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_COFIR.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_COFIR.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'SEMINPER' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_SEMINPER.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_SEMINPER.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_SEMINPER.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEMINPER.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_SEMINPER.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'AGRESP' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_AGRESP.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_AGRESP.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_AGRESP.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_AGRESP.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_AGRESP.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'FUESPI' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_FUESPI.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_FUESPI.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_FUESPI.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUESPI.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_FUESPI.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'SERES' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_SERES.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_SERES.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_SERES.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SERES.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_SERES.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'SECESP' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_SECESP.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_SECESP.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_SECESP.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SECESP.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_SECESP.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'FUNPREV' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_FUNPREV.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_FUNPREV.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_FUNPREV.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_FUNPREV.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-312','03/2026-310','03/2026-300','03/2026-320','03/2026-380','03/2026-350','03/2026-370','03/2026-441','03/2026-420','03/2026-400','03/2026-440','03/2026-340','03/2026-360','03/2026-390','03/2026-330')
    LEFT JOIN SW_FUNPREV.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'SEGOV' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_SEGOV.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_SEGOV.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_SEGOV.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEGOV.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'SASC' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_SASC.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_SASC.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_SASC.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SASC.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_SASC.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'METRO' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_METRO.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_METRO.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_METRO.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_METRO.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_METRO.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'SADA' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_SADA.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_SADA.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_SADA.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SADA.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_SADA.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'SECMULHERES' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_SECMULHERES.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_SECMULHERES.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_SECMULHERES.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SECMULHERES.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_SECMULHERES.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'EMGERPI_EMATER' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_EMGERPI_EMATER.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_EMGERPI_EMATER.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_EMGERPI_EMATER.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_EMATER.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_EMGERPI_EMATER.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'SESAPI' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_SESAPI.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_SESAPI.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_SESAPI.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SESAPI.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100','03/2026-250')
    LEFT JOIN SW_SESAPI.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'PMPI' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_PMPI.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_PMPI.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_PMPI.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_PMPI.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_PMPI.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'SEJUSPI' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_SEJUSPI.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_SEJUSPI.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_SEJUSPI.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEJUSPI.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_SEJUSPI.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'SEFAZPI' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_SEFAZPI.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_SEFAZPI.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_SEFAZPI.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEFAZPI.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_SEFAZPI.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'SEADPREVPI' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_SEADPREVPI.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_SEADPREVPI.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_SEADPREVPI.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEADPREVPI.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100','03/2026-360','03/2026-370')
    LEFT JOIN SW_SEADPREVPI.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'IMEPI' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_IMEPI.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_IMEPI.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_IMEPI.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_IMEPI.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_IMEPI.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'BEP' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_BEP.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_BEP.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_BEP.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_BEP.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-300')
    LEFT JOIN SW_BEP.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'EMGERPI_COMEPI' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_EMGERPI_COMEPI.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_EMGERPI_COMEPI.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_EMGERPI_COMEPI.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_COMEPI.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_EMGERPI_COMEPI.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'EMGERPI_COMDEPI' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_EMGERPI_COMDEPI.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_EMGERPI_COMDEPI.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_EMGERPI_COMDEPI.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_COMDEPI.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_EMGERPI_COMDEPI.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'EMGERPI_COHAB' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_EMGERPI_COHAB.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_EMGERPI_COHAB.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_EMGERPI_COHAB.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_COHAB.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_EMGERPI_COHAB.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'EMGERPI_PRODEPI' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_EMGERPI_PRODEPI.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_EMGERPI_PRODEPI.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_EMGERPI_PRODEPI.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_EMGERPI_PRODEPI.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-100')
    LEFT JOIN SW_EMGERPI_PRODEPI.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
UNION ALL
SELECT 
    'SEDUC' ORGAO,
    FO2.CHAVE_FOLHA,
    VT2.ID_TABELA,
    VT2.FAIXA,
    VT2.VALOR_INICIAL,
    VT2.VALOR_FINAL,
    VT2.PERCENTUAL,
    VT2.VALOR_1,
    VT2.VALOR_2,
    VT.ID_TABELA,
    VT.FAIXA,
    VT.VALOR_INICIAL,
    VT.VALOR_FINAL,
    VT.PERCENTUAL,
    VT.VALOR_1,
    VT.VALOR_2,
    CASE
        WHEN VT2.ID_VALOR_TABELA IS NOT NULL THEN 'UPDATE SW_SEDUC.FOLHA_VALOR_TABELA SET VALOR_INICIAL = ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', VALOR_FINAL = ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', PERCENTUAL = ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', VALOR_1 = ' || REPLACE(VT.VALOR_1, ',', '.') || ', VALOR_2 = ' || REPLACE(VT.VALOR_2, ',', '.') || ' WHERE ID_VALOR_TABELA = ' || VT2.ID_VALOR_TABELA || ';'
        ELSE 'INSERT INTO SW_SEDUC.FOLHA_VALOR_TABELA(ID_VALOR_TABELA, ID_FOLHA, ID_TABELA, FAIXA, VALOR_INICIAL, VALOR_FINAL, PERCENTUAL, VALOR_1, VALOR_2, VALOR_3, DATA_1, DATA_2) VALUES (SW_SEDUC.SQ_PK_VALOR_FOLHA_TABELA.NEXTVAL, ' || FO2.ID_FOLHA || ', ' || VT.ID_TABELA || ', ' || VT.FAIXA || ', ' || REPLACE(VT.VALOR_INICIAL, ',', '.') || ', ' || REPLACE(VT.VALOR_FINAL, ',', '.') || ', ' || REPLACE(VT.PERCENTUAL, ',', '.') || ', ' || REPLACE(VT.VALOR_1, ',', '.') || ', ' || REPLACE(VT.VALOR_2, ',', '.') || ', ' || NVL(TO_CHAR(VT.VALOR_3), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_1), 'NULL') || ', ' || NVL(TO_CHAR(VT.DATA_2), 'NULL') || ');'
    END UPDATE_
FROM
    SW_SEGOV.FOLHA FO
    JOIN SW_SEGOV.FOLHA_VALOR_TABELA VT ON VT.ID_FOLHA = FO.ID_FOLHA
    JOIN SW_SEDUC.FOLHA FO2 ON FO2.CHAVE_FOLHA IN ('03/2026-110','03/2026-120','03/2026-100','03/2026-250','03/2026-280')
    LEFT JOIN SW_SEDUC.FOLHA_VALOR_TABELA VT2 ON VT2.ID_FOLHA = FO2.ID_FOLHA AND VT2.ID_TABELA = VT.ID_TABELA AND VT2.FAIXA = VT.FAIXA
WHERE
    FO.CHAVE_FOLHA = '04/2026-271'
;