SELECT 
    PV.COD_INSTITUCIONAL AS MATRICULA,
    F.ID_FUNCIONARIO,
    FR.ID_FUNCIONARIO_REFERENCIA,
    CR.NOME_REFERENCIA,
    CC.NOME_CLASSE,
    CASE 
        WHEN FR.ID_REFERENCIA = 1000320 THEN 'UPDATE SW_SSPPI.FUNCIONARIO_REFERENCIA SET ID_ESPECIALIDADE = 1000940 WHERE ID_FUNCIONARIO_REFERENCIA = ' 
        || FR.ID_FUNCIONARIO_REFERENCIA || ';'
        WHEN FR.ID_REFERENCIA = 1000340 THEN 'UPDATE SW_SSPPI.FUNCIONARIO_REFERENCIA SET ID_ESPECIALIDADE = 1000960 WHERE ID_FUNCIONARIO_REFERENCIA = ' 
        || FR.ID_FUNCIONARIO_REFERENCIA || ';'
        WHEN FR.ID_REFERENCIA = 1000321 THEN 'UPDATE SW_SSPPI.FUNCIONARIO_REFERENCIA SET ID_ESPECIALIDADE = 1000941 WHERE ID_FUNCIONARIO_REFERENCIA = ' 
        || FR.ID_FUNCIONARIO_REFERENCIA || ';'
        WHEN FR.ID_REFERENCIA = 1000341 THEN 'UPDATE SW_SSPPI.FUNCIONARIO_REFERENCIA SET ID_ESPECIALIDADE = 1000961 WHERE ID_FUNCIONARIO_REFERENCIA = ' 
        || FR.ID_FUNCIONARIO_REFERENCIA || ';'
        WHEN FR.ID_REFERENCIA = 1000342 THEN 'UPDATE SW_SSPPI.FUNCIONARIO_REFERENCIA SET ID_ESPECIALIDADE = 1000942 WHERE ID_FUNCIONARIO_REFERENCIA = ' 
        || FR.ID_FUNCIONARIO_REFERENCIA || ';'
    END AS COMANDO_UPDATE
FROM 
    SW_SSPPI.PESSOA_VINCULO PV
    JOIN SW_SSPPI.FUNCIONARIO F ON F.ID_PESSOA_VINCULO = PV.ID_PESSOA_VINCULO
    JOIN SW_SSPPI.FUNCIONARIO_REFERENCIA FR ON FR.ID_FUNCIONARIO = F.ID_FUNCIONARIO
    JOIN SW_SSPPI.RHB_CARREIRA_REFERENCIA CR ON CR.ID_REFERENCIA = FR.ID_REFERENCIA
    JOIN SW_SSPPI.RHB_CARREIRA_CLASSE CC ON CC.ID_CLASSE = CR.ID_CLASSE
WHERE 
    CR.ID_REFERENCIA IN (1000320, 1000340, 1000321, 1000341, 1000342);