INSERT INTO SW_CRS_I.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_CRS_I.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_CRS_I.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_CRS_I.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_CRS_I.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_CRS_III.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_CRS_III.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_CRS_III.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_CRS_III.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_CRS_III.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_CRS_IV.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_CRS_IV.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_CRS_IV.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_CRS_IV.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_CRS_IV.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_CRS_V.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_CRS_V.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_CRS_V.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_CRS_V.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_CRS_V.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_CRS_VII.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_CRS_VII.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_CRS_VII.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_CRS_VII.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_CRS_VII.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_CRS_VIII.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_CRS_VIII.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_CRS_VIII.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_CRS_VIII.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_CRS_VIII.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_CRS_IX.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_CRS_IX.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_CRS_IX.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_CRS_IX.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_CRS_IX.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_CRS_X.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_CRS_X.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_CRS_X.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_CRS_X.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_CRS_X.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_CRS_XII.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_CRS_XII.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_CRS_XII.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_CRS_XII.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_CRS_XII.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_CRS_XIII.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_CRS_XIII.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_CRS_XIII.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_CRS_XIII.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_CRS_XIII.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_CRS_XV.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_CRS_XV.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_CRS_XV.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_CRS_XV.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_CRS_XV.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_UIS.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_UIS.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_UIS.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_UIS.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_UIS.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HRFAC.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_HRFAC.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HRFAC.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_HRFAC.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_HRFAC.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HLGCB.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_HLGCB.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HLGCB.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_HLGCB.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_HLGCB.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_PRODSUS.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_PRODSUS.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_PRODSUS.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_PRODSUS.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_PRODSUS.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HEJBC.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_HEJBC.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HEJBC.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_HEJBC.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_HEJBC.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_DGPCPI.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_DGPCPI.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_DGPCPI.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_DGPCPI.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_DGPCPI.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_SEDUC_PTEC.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_SEDUC_PTEC.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_SEDUC_PTEC.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_SEDUC_PTEC.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_SEDUC_PTEC.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';
    
INSERT INTO SW_SEDUC_EJA.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_SEDUC_EJA.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_SEDUC_EJA.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_SEDUC_EJA.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_SEDUC_EJA.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_DEFCIVIL.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_DEFCIVIL.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_DEFCIVIL.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_DEFCIVIL.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_DEFCIVIL.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HRCF.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_HRCF.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HRCF.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_HRCF.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_HRCF.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HRLM.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_HRLM.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HRLM.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_HRLM.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_HRLM.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HRCM.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_HRCM.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HRCM.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_HRCM.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_HRCM.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HRJPC.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_HRJPC.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HRJPC.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_HRJPC.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_HRJPC.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HRDC.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_HRDC.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HRDC.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_HRDC.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_HRDC.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HRCR.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_HRCR.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HRCR.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_HRCR.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_HRCR.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_LACEN.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_LACEN.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_LACEN.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_LACEN.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_LACEN.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HILP.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_HILP.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HILP.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_HILP.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_HILP.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HAA.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_HAA.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HAA.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_HAA.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_HAA.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_MDER.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_MDER.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_MDER.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_MDER.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_MDER.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_IDTNP.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_IDTNP.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_IDTNP.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_IDTNP.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_IDTNP.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HGV.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_HGV.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HGV.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_HGV.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_HGV.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HEMOPI.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_HEMOPI.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HEMOPI.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_HEMOPI.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_HEMOPI.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HEDA.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_HEDA.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HEDA.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_HEDA.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_HEDA.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HEJH.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_HEJH.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HEJH.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_HEJH.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_HEJH.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HLJMF.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_HLJMF.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HLJMF.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_HLJMF.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_HLJMF.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HRTNB.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_HRTNB.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HRTNB.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_HRTNB.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_HRTNB.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HREP.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_HREP.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HREP.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_HREP.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_HREP.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HRDA.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_HRDA.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HRDA.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_HRDA.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_HRDA.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_CBMPI.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_CBMPI.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_CBMPI.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_CBMPI.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_CBMPI.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_SSPPI.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_SSPPI.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_SSPPI.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_SSPPI.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_SSPPI.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';


INSERT INTO SW_METRO.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_METRO.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_METRO.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_METRO.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_METRO.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_UMS_PAES.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_UMS_PAES.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_UMS_PAES.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_UMS_PAES.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_UMS_PAES.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_SASC.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_SASC.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_SASC.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_SASC.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_SASC.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_IASPI.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_IASPI.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_IASPI.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_IASPI.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_IASPI.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_SEFAZ.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_SEFAZ.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_SEFAZ.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_SEFAZ.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_SEFAZ.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HEJLM.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_HEJLM.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HEJLM.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_HEJLM.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_HEJLM.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HEJFM.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_HEJFM.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HEJFM.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_HEJFM.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_HEJFM.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HENM.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_HENM.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HENM.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_HENM.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_HENM.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HPM.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_HPM.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HPM.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_HPM.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_HPM.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_UMS_AVLN.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_UMS_AVLN.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_UMS_AVLN.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_UMS_AVLN.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_UMS_AVLN.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_UMS_FILO.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_UMS_FILO.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_UMS_FILO.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_UMS_FILO.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_UMS_FILO.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_UMS_FRANC.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_UMS_FRANC.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_UMS_FRANC.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_UMS_FRANC.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_UMS_FRANC.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_UMS_ITAIN.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_UMS_ITAIN.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_UMS_ITAIN.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_UMS_ITAIN.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_UMS_ITAIN.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_PMPI.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_PMPI.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_PMPI.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_PMPI.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_PMPI.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_FUESPI.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_FUESPI.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_FUESPI.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_FUESPI.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_FUESPI.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_FAPEPI.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_FAPEPI.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_FAPEPI.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_FAPEPI.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_FAPEPI.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_TFD.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_TFD.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_TFD.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_TFD.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_TFD.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_FUNDESPI.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_FUNDESPI.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_FUNDESPI.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_FUNDESPI.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_FUNDESPI.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_SEDUC_SHOI.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_SEDUC_SHOI.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_SEDUC_SHOI.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_SEDUC_SHOI.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_SEDUC_SHOI.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_SEDUC_EDIT.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_SEDUC_EDIT.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_SEDUC_EDIT.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_SEDUC_EDIT.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_SEDUC_EDIT.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_CENDFOL.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_CENDFOL.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_CENDFOL.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_CENDFOL.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_CENDFOL.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_GAMIL.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_GAMIL.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_GAMIL.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_GAMIL.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_GAMIL.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_SECEPI.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_SECEPI.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_SECEPI.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_SECEPI.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_SECEPI.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_SEMARH.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_SEMARH.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_SEMARH.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_SEMARH.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_SEMARH.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_SEPLAN.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_SEPLAN.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_SEPLAN.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_SEPLAN.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_SEPLAN.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_SAF.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_SAF.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_SAF.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_SAF.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_SAF.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_AGESPISA.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_AGESPISA.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_AGESPISA.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_AGESPISA.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_AGESPISA.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HRP.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_HRP.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HRP.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_HRP.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_HRP.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_UMSBOC.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_UMSBOC.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_UMSBOC.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_UMSBOC.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_UMSBOC.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_FUNSAUDE.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_FUNSAUDE.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_FUNSAUDE.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_FUNSAUDE.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_FUNSAUDE.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_RMSS.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_RMSS.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_RMSS.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_RMSS.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_RMSS.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HRTN.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_HRTN.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HRTN.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_HRTN.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_HRTN.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_SEJUSPI.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_SEJUSPI.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_SEJUSPI.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_SEJUSPI.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_SEJUSPI.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_SECULT.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_SECULT.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_SECULT.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_SECULT.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_SECULT.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_FESPPI.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_FESPPI.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_FESPPI.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_FESPPI.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_FESPPI.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_FUNPESPI.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_FUNPESPI.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_FUNPESPI.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_FUNPESPI.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_FUNPESPI.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_FUNAP.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_FUNAP.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_FUNAP.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_FUNAP.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_FUNAP.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_INTERPI.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_INTERPI.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_INTERPI.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_INTERPI.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_INTERPI.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_SETRE.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_SETRE.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_SETRE.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_SETRE.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_SETRE.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HRJL.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_HRJL.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_HRJL.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_HRJL.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_HRJL.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_SEDUC_ALFA.LEGISLACAO_PARAM_VALIDACAO (ID_VALIDACAO, DESCRICAO_VALIDACAO, DATA_CADASTRO, PROCEDIMENTO, VERBETE, IND_ATIVO, MENSAGEM)
SELECT
    SW_SEDUC_ALFA.SQ_PK_VALIDACAO.NEXTVAL,
    PV.DESCRICAO_VALIDACAO,
    PV.DATA_CADASTRO,
    PV.PROCEDIMENTO,
    PV.VERBETE,
    PV.IND_ATIVO,
    PV.MENSAGEM
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';

INSERT INTO SW_SEDUC_ALFA.LEGISLACAO_PARAM_MODULO_VAL (ID_MODULO_VALIDACAO, ID_VALIDACAO, DATA_CADASTRO, ORDEM, DATA_INICIO, IND_TIPO, ID_OBJ_AUTH, IND_ALTERAR, IND_ADICIONAR, IND_EXCLUIR)
SELECT
    SW_SEDUC_ALFA.SQ_PK_MODULO_VALIDACAO.NEXTVAL,
    (SELECT ID_VALIDACAO FROM SW_SEDUC_ALFA.LEGISLACAO_PARAM_VALIDACAO WHERE VERBETE = PV.VERBETE),
    MV.DATA_CADASTRO,
    MV.ORDEM,
    MV.DATA_INICIO,
    MV.IND_TIPO,
    MV.ID_OBJ_AUTH,
    MV.IND_ALTERAR,
    MV.IND_ADICIONAR,
    MV.IND_EXCLUIR
FROM
    SW_SEDUC.LEGISLACAO_PARAM_VALIDACAO PV
    JOIN SW_SEDUC.LEGISLACAO_PARAM_MODULO_VAL MV ON MV.ID_VALIDACAO = PV.ID_VALIDACAO
WHERE
    PV.VERBETE LIKE '%Campo carreira e cargo efetivo obrigatório%';
