SELECT 
    'ADAPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_ADAPI.PESSOA_VINCULO PV 
    JOIN SW_ADAPI.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'ADH' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_ADH.PESSOA_VINCULO PV 
    JOIN SW_ADH.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'AGESPISA' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_AGESPISA.PESSOA_VINCULO PV 
    JOIN SW_AGESPISA.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'AGESPISA02' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_AGESPISA02.PESSOA_VINCULO PV 
    JOIN SW_AGESPISA02.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'AGRESP' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_AGRESP.PESSOA_VINCULO PV 
    JOIN SW_AGRESP.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'ATIPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_ATIPI.PESSOA_VINCULO PV 
    JOIN SW_ATIPI.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'BEP' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_BEP.PESSOA_VINCULO PV 
    JOIN SW_BEP.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'CBMPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_CBMPI.PESSOA_VINCULO PV 
    JOIN SW_CBMPI.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'CCOM' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_CCOM.PESSOA_VINCULO PV 
    JOIN SW_CCOM.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'CDTER' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_CDTER.PESSOA_VINCULO PV 
    JOIN SW_CDTER.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'CENDROGAS' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_CENDROGAS.PESSOA_VINCULO PV 
    JOIN SW_CENDROGAS.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'CEPM' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_CEPM.PESSOA_VINCULO PV 
    JOIN SW_CEPM.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'CGEPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_CGEPI.PESSOA_VINCULO PV 
    JOIN SW_CGEPI.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'COFIR' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_COFIR.PESSOA_VINCULO PV 
    JOIN SW_COFIR.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'COJUV' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_COJUV.PESSOA_VINCULO PV 
    JOIN SW_COJUV.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'CPVCI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_CPVCI.PESSOA_VINCULO PV 
    JOIN SW_CPVCI.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'DEFCIVIL' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_DEFCIVIL.PESSOA_VINCULO PV 
    JOIN SW_DEFCIVIL.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'DEFENSORIA' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_DEFENSORIA.PESSOA_VINCULO PV 
    JOIN SW_DEFENSORIA.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'DER' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_DER.PESSOA_VINCULO PV 
    JOIN SW_DER.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'DETRAN' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_DETRAN.PESSOA_VINCULO PV 
    JOIN SW_DETRAN.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'EMATER' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_EMATER.PESSOA_VINCULO PV 
    JOIN SW_EMATER.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'EMATERPROD' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_EMATERPROD.PESSOA_VINCULO PV 
    JOIN SW_EMATERPROD.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'EMGERPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_EMGERPI.PESSOA_VINCULO PV 
    JOIN SW_EMGERPI.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'EMGERPI_CEASA' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_EMGERPI_CEASA.PESSOA_VINCULO PV 
    JOIN SW_EMGERPI_CEASA.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'EMGERPI_CIDAPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_EMGERPI_CIDAPI.PESSOA_VINCULO PV 
    JOIN SW_EMGERPI_CIDAPI.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'EMGERPI_CODIPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_EMGERPI_CODIPI.PESSOA_VINCULO PV 
    JOIN SW_EMGERPI_CODIPI.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'EMGERPI_COHAB' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_EMGERPI_COHAB.PESSOA_VINCULO PV 
    JOIN SW_EMGERPI_COHAB.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'EMGERPI_COMDEPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_EMGERPI_COMDEPI.PESSOA_VINCULO PV 
    JOIN SW_EMGERPI_COMDEPI.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'EMGERPI_COMEPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_EMGERPI_COMEPI.PESSOA_VINCULO PV 
    JOIN SW_EMGERPI_COMEPI.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'EMGERPI_CORESA' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_EMGERPI_CORESA.PESSOA_VINCULO PV 
    JOIN SW_EMGERPI_CORESA.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'EMGERPI_EMATER' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_EMGERPI_EMATER.PESSOA_VINCULO PV 
    JOIN SW_EMGERPI_EMATER.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'EMGERPI_ETELPI_FUNART' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_EMGERPI_ETELPI_FUNART.PESSOA_VINCULO PV 
    JOIN SW_EMGERPI_ETELPI_FUNART.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'EMGERPI_PIEMTUR' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_EMGERPI_PIEMTUR.PESSOA_VINCULO PV 
    JOIN SW_EMGERPI_PIEMTUR.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'EMGERPI_PRODEPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_EMGERPI_PRODEPI.PESSOA_VINCULO PV 
    JOIN SW_EMGERPI_PRODEPI.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'EMPRESA' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_EMPRESA.PESSOA_VINCULO PV 
    JOIN SW_EMPRESA.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'FAPEPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_FAPEPI.PESSOA_VINCULO PV 
    JOIN SW_FAPEPI.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'FESPPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_FESPPI.PESSOA_VINCULO PV 
    JOIN SW_FESPPI.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'FUESPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_FUESPI.PESSOA_VINCULO PV 
    JOIN SW_FUESPI.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'FUNDESPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_FUNDESPI.PESSOA_VINCULO PV 
    JOIN SW_FUNDESPI.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'FUNPREV' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_FUNPREV.PESSOA_VINCULO PV 
    JOIN SW_FUNPREV.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'FUPIP' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_FUPIP.PESSOA_VINCULO PV 
    JOIN SW_FUPIP.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'GMG' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_GMG.PESSOA_VINCULO PV 
    JOIN SW_GMG.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'IASPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_IASPI.PESSOA_VINCULO PV 
    JOIN SW_IASPI.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'IDEPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_IDEPI.PESSOA_VINCULO PV 
    JOIN SW_IDEPI.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'IMEPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_IMEPI.PESSOA_VINCULO PV 
    JOIN SW_IMEPI.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'IMEPIPROD' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_IMEPIPROD.PESSOA_VINCULO PV 
    JOIN SW_IMEPIPROD.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'INATIVOS_PENSIONISTAS' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_INATIVOS_PENSIONISTAS.PESSOA_VINCULO PV 
    JOIN SW_INATIVOS_PENSIONISTAS.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'INATIVOS_SEDUC' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_INATIVOS_SEDUC.PESSOA_VINCULO PV 
    JOIN SW_INATIVOS_SEDUC.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'INATIVOS_TCE' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_INATIVOS_TCE.PESSOA_VINCULO PV 
    JOIN SW_INATIVOS_TCE.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'INTERPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_INTERPI.PESSOA_VINCULO PV 
    JOIN SW_INTERPI.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'JUCEPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_JUCEPI.PESSOA_VINCULO PV 
    JOIN SW_JUCEPI.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'METRO' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_METRO.PESSOA_VINCULO PV 
    JOIN SW_METRO.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'PENSIONISTAS' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_PENSIONISTAS.PESSOA_VINCULO PV 
    JOIN SW_PENSIONISTAS.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'PGEPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_PGEPI.PESSOA_VINCULO PV 
    JOIN SW_PGEPI.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'PIAUIPREV' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_PIAUIPREV.PESSOA_VINCULO PV 
    JOIN SW_PIAUIPREV.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'PMPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_PMPI.PESSOA_VINCULO PV 
    JOIN SW_PMPI.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'REENVIO' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_REENVIO.PESSOA_VINCULO PV 
    JOIN SW_REENVIO.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'SADA' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_SADA.PESSOA_VINCULO PV 
    JOIN SW_SADA.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'SAF' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_SAF.PESSOA_VINCULO PV 
    JOIN SW_SAF.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'SASC' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_SASC.PESSOA_VINCULO PV 
    JOIN SW_SASC.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'SEADPREVPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_SEADPREVPI.PESSOA_VINCULO PV 
    JOIN SW_SEADPREVPI.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'SEAGRO' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_SEAGRO.PESSOA_VINCULO PV 
    JOIN SW_SEAGRO.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'SECESP' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_SECESP.PESSOA_VINCULO PV 
    JOIN SW_SECESP.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'SECID' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_SECID.PESSOA_VINCULO PV 
    JOIN SW_SECID.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'SECMULHERES' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_SECMULHERES.PESSOA_VINCULO PV 
    JOIN SW_SECMULHERES.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'SECULT' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_SECULT.PESSOA_VINCULO PV 
    JOIN SW_SECULT.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'SEDET' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_SEDET.PESSOA_VINCULO PV 
    JOIN SW_SEDET.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'SEDUC' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_SEDUC.PESSOA_VINCULO PV 
    JOIN SW_SEDUC.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'SEDUC_PRECATORIO' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_SEDUC_PRECATORIO.PESSOA_VINCULO PV 
    JOIN SW_SEDUC_PRECATORIO.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'SEFAZPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_SEFAZPI.PESSOA_VINCULO PV 
    JOIN SW_SEFAZPI.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'SEGOV' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_SEGOV.PESSOA_VINCULO PV 
    JOIN SW_SEGOV.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'SEID' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_SEID.PESSOA_VINCULO PV 
    JOIN SW_SEID.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'SEINFRA' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_SEINFRA.PESSOA_VINCULO PV 
    JOIN SW_SEINFRA.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'SEJUSPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_SEJUSPI.PESSOA_VINCULO PV 
    JOIN SW_SEJUSPI.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'SEMAR' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_SEMAR.PESSOA_VINCULO PV 
    JOIN SW_SEMAR.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'SEMINPER' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_SEMINPER.PESSOA_VINCULO PV 
    JOIN SW_SEMINPER.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'SEPLAN' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_SEPLAN.PESSOA_VINCULO PV 
    JOIN SW_SEPLAN.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'SERES' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_SERES.PESSOA_VINCULO PV 
    JOIN SW_SERES.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'SESAPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_SESAPI.PESSOA_VINCULO PV 
    JOIN SW_SESAPI.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'SETRANS' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_SETRANS.PESSOA_VINCULO PV 
    JOIN SW_SETRANS.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'SETRE' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_SETRE.PESSOA_VINCULO PV 
    JOIN SW_SETRE.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'SETUR' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_SETUR.PESSOA_VINCULO PV 
    JOIN SW_SETUR.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'SIA' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_SIA.PESSOA_VINCULO PV 
    JOIN SW_SIA.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'SSPPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_SSPPI.PESSOA_VINCULO PV 
    JOIN SW_SSPPI.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'SURPI' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_SURPI.PESSOA_VINCULO PV 
    JOIN SW_SURPI.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'TVANTARES' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_TVANTARES.PESSOA_VINCULO PV 
    JOIN SW_TVANTARES.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
UNION ALL
SELECT 
    'VICEGOV' ORGAO,
    PV.ID_PESSOA_VINCULO,
    PV.COD_INSTITUCIONAL MATRICULA,
    V.DESCRICAO_VINCULO
FROM 
    SW_VICEGOV.PESSOA_VINCULO PV 
    JOIN SW_VICEGOV.RHB_VINCULO V ON V.ID_VINCULO = PV.ID_VINCULO
WHERE 
    V.ID_VINCULO = 1
;